import type { Question } from "@/lib/curriculum";
import { registerQuestions } from "./registry";

const questions: Record<string, Question[]> = {
  "agent-loop": [
    {
      id: "q-agent-kp1-1",
      type: "multiple-choice",
      difficulty: "easy",
      question: "In the canonical LLM agent loop (Weng, 2023), which sequence correctly describes one iteration?",
      options: [
        "Action -> Observation -> Thought",
        "Thought -> Action -> Observation",
        "Observation -> Action -> Thought",
        "Thought -> Observation -> Action",
      ],
      correctAnswer: 1,
      explanation: "The ReAct-style agent loop (Yao et al., 2023) cycles: Thought (the LLM reasons about the current state), Action (the LLM emits a tool call or final answer), Observation (the environment returns the tool result). This Thought->Action->Observation triplet repeats until a stopping condition is met.",
      hints: [
        "Think of the agent as first forming a plan (Thought), then doing something (Action), then seeing what happened (Observation).",
        "The LLM generates the first two; the external environment supplies the third.",
      ],
    },
    {
      id: "q-agent-kp1-2",
      type: "true-false",
      difficulty: "easy",
      question: "An agent loop terminates after a fixed, pre-specified number of steps regardless of whether the task is complete.",
      options: ["True", "False"],
      correctAnswer: "False",
      explanation: "Agent loops use configurable stopping conditions: a task-complete action emitted by the LLM, a max-step safety limit, a human interrupt, or a heuristic (e.g., Reflexion detects repeated identical actions). A hard step count is a guard, not the normal termination criterion.",
      hints: [
        "Reflexion (Shinn & Labash, 2023) adds a heuristic that can reset a stuck trajectory -- not a fixed counter.",
        "Stopping conditions are configurable; the agent signals completion through its action space.",
      ],
    },
    {
      id: "q-agent-kp1-3",
      type: "multiple-choice",
      difficulty: "medium",
      question: "As an agent run grows longer, the context window fills with Thought/Action/Observation triples. Which strategy best manages this finite context budget?",
      options: [
        "Truncate the oldest tokens silently to stay under the limit",
        "Summarize completed sub-task trajectories and replace verbose history with compressed summaries",
        "Increase the model temperature to generate shorter responses",
        "Switch to a smaller model once the context exceeds 50% capacity",
      ],
      correctAnswer: 1,
      explanation: "Memory consolidation via summarization (used in Generative Agents, Park et al. 2023) compresses completed episodes into higher-level summaries, freeing context space while retaining key information. Silent truncation loses critical observations; temperature has no effect on context length.",
      hints: [
        "Generative Agents (Park et al., 2023) store a memory stream and surface condensed reflections rather than raw event logs.",
        "The goal is to keep the most relevant context within the token budget -- summarization preserves semantics, truncation does not.",
      ],
    },
    {
      id: "q-agent-kp1-4",
      type: "multiple-choice",
      difficulty: "easy",
      question: "In the ReAct agent loop, what triggers the agent to stop and return a final answer?",
      options: [
        "A hard-coded maximum step count is always reached",
        "The LLM emits a final answer action or a special termination signal",
        "The user manually stops the process",
        "The context window fills up completely",
      ],
      correctAnswer: 1,
      explanation: "The agent emits a final answer action when it determines the task is complete. A max-step guard exists as a safety limit but is not the normal termination criterion.",
      hints: [
        "The agent signals completion through its action space, not by external timer.",
        "The ReAct paper defines a dedicated Finish action that the model emits when done.",
      ],
    },
    {
      id: "q-agent-kp1-5",
      type: "true-false",
      difficulty: "medium",
      question: "An agent loop running for 50 steps with 200-token observations will consume roughly 10,000 tokens in total context.",
      options: ["True", "False"],
      correctAnswer: "True",
      explanation: "Context accumulates linearly: each step adds Thought + Action + roughly 200-token Observation. Managing this growth is the long-context challenge in agent design.",
      hints: [
        "Context is append-only in a typical agent loop. Each step adds to the total.",
        "50 steps x 200 tokens each = 10,000 tokens, before accounting for Thought/Action tokens.",
      ],
    },
    {
      id: "q-agent-kp1-6",
      type: "multiple-choice",
      difficulty: "medium",
      question: "Which technique allows an agent loop to recover from repeated failed actions?",
      options: [
        "Increasing the model temperature on each retry",
        "Reflexion: self-reflection on failed trajectories to produce corrective plans",
        "Switching to a different LLM model automatically",
        "Resetting the context window to empty",
      ],
      correctAnswer: 1,
      explanation: "Reflexion (Shinn et al., 2023) prompts the agent to reflect on why a trajectory failed and store verbal feedback in memory, then re-attempts with that feedback.",
      hints: [
        "Reflexion = reflect on failure + update memory + retry with updated strategy.",
        "The verbal feedback from self-reflection becomes the corrective signal for the next attempt.",
      ],
    },
    {
      id: "q-agent-kp1-7",
      type: "multiple-choice",
      difficulty: "hard",
      question: "What is the key insight behind scratchpad reasoning in agent frameworks?",
      options: [
        "Scratchpad stores tool call results in a database",
        "Allowing the model to generate intermediate reasoning tokens before the final action improves performance because reasoning is part of the computation",
        "Scratchpad compresses context to save tokens",
        "It is a legacy term for the context window before transformer architectures",
      ],
      correctAnswer: 1,
      explanation: "Chain-of-thought research shows generating intermediate reasoning steps improves accuracy. The Thought step lets the model plan before committing to an action.",
      hints: [
        "Why does writing out math steps help humans? The same principle applies to LLMs.",
        "Intermediate tokens serve as working memory that the model conditions its final output on.",
      ],
    },
    {
      id: "q-agent-kp1-8",
      type: "true-false",
      difficulty: "hard",
      question: "Adding more tools to an agent always improves its task performance.",
      options: ["True", "False"],
      correctAnswer: "False",
      explanation: "Too many tools increase selection complexity and can distract from the correct approach. Tool selection quality degrades with very large tool sets. Careful curation and clear descriptions are essential.",
      hints: [
        "More choices can lead to worse decisions. This applies to LLMs selecting tools too.",
        "Research shows tool-selection accuracy drops as the number of available tools grows.",
      ],
    },
    {
      id: "q-agent-kp1-9",
      type: "multiple-choice",
      difficulty: "hard",
      question: "What is prompt injection in the context of LLM agent security?",
      options: [
        "Injecting model weights with adversarial gradients",
        "Malicious content in tool outputs or web pages that hijacks the agent instructions",
        "Overloading the context window with irrelevant data",
        "Using conflicting system prompts",
      ],
      correctAnswer: 1,
      explanation: "Prompt injection embeds adversarial instructions in data the agent reads (tool outputs, web pages). For example, a web page saying Ignore previous instructions could hijack an unguarded agent.",
      hints: [
        "The attacker puts instructions in data the agent reads, not in the system prompt.",
        "Unlike direct injection, indirect injection hides in environmental data the agent retrieves.",
      ],
    },
  ],

  "tool-use-agents": [
    {
      id: "q-agent-kp2-1",
      type: "multiple-choice",
      difficulty: "easy",
      question: "In API-Bank (Li et al., 2023), tool-use capability is evaluated at three levels. Which level requires the agent to plan sequences of API calls to satisfy an ambiguous user request?",
      options: [
        "Level-1: calling a given API correctly",
        "Level-2: retrieving the right API from documentation",
        "Level-3: planning beyond retrieval and call",
        "Level-0: deciding whether an API call is needed at all",
      ],
      correctAnswer: 2,
      explanation: "API-Bank Level-3 assesses the ability to plan multi-step API sequences for under-specified requests. Level-1 tests correct invocation, Level-2 tests API discovery from docs. Level-3 is the hardest and most agentic.",
      hints: [
        "Booking a trip requires: searching flights, hotels, restaurants -- multiple APIs with dependencies.",
        "The levels are nested: 3 subsumes 2 subsumes 1.",
      ],
    },
    {
      id: "q-agent-kp2-2",
      type: "true-false",
      difficulty: "medium",
      question: "When an LLM emits a parallel tool-call response (multiple tool-call objects in one turn), the host application must execute them sequentially to avoid race conditions.",
      options: ["True", "False"],
      correctAnswer: "False",
      explanation: "Parallel tool calls are specifically designed for concurrent execution. Both OpenAI and Anthropic APIs support multiple tool-call objects per response so the host can execute independent calls simultaneously, collect all results, and return them together -- cutting latency.",
      hints: [
        "If two tools are independent (e.g., get weather in Paris and Tokyo), there is no reason to serialize them.",
        "Race conditions only arise when tool calls have shared mutable state -- the host is responsible for managing that.",
      ],
    },
    {
      id: "q-agent-kp2-3",
      type: "multiple-choice",
      difficulty: "hard",
      question: "In ChemCrow (Bran et al., 2023), human expert evaluation showed ChemCrow outperforms vanilla GPT-4 by a large margin, yet LLM-based self-evaluation shows near-parity. What does this reveal?",
      options: [
        "LLMs are reliable evaluators of domain-expert tasks.",
        "LLM self-evaluation is unreliable for tasks requiring deep expertise it does not have.",
        "ChemCrow tool use is primarily decorative and does not improve chemistry quality.",
        "Human evaluators are systematically biased toward tool-augmented systems.",
      ],
      correctAnswer: 1,
      explanation: "ChemCrow results highlight that LLMs cannot reliably judge the chemical correctness of outputs because they lack the domain knowledge to detect subtle errors. Human experts orient toward actual chemical validity, exposing a fundamental limitation of LLM-as-judge for specialist domains.",
      hints: [
        "If the model cannot solve the task, it also cannot reliably score solutions to the task.",
        "This is a key caution for using LLM evaluation in specialized agent benchmarks.",
      ],
    },
    {
      id: "q-agent-kp2-4",
      type: "multiple-choice",
      difficulty: "easy",
      question: "What is a tool schema in LLM function calling?",
      options: [
        "A database schema for storing tool outputs",
        "A JSON description of a tool name, description, and parameter types the LLM uses to generate correct calls",
        "The source code implementation of the tool",
        "A rate-limiting policy for API calls",
      ],
      correctAnswer: 1,
      explanation: "A tool schema (typically JSON Schema) tells the LLM what a tool does, what parameters it accepts, and their types -- like API documentation provided directly to the model.",
      hints: [
        "Think of it as the tool API documentation provided directly to the model.",
        "Without a schema, the LLM has no structured basis for generating valid tool calls.",
      ],
    },
    {
      id: "q-agent-kp2-5",
      type: "true-false",
      difficulty: "easy",
      question: "The LLM itself executes the tool call and returns the result to itself in function calling.",
      options: ["True", "False"],
      correctAnswer: "False",
      explanation: "The LLM only generates the tool call specification (name + arguments). The host application executes it against the actual tool/API and returns the result to the LLM in the next turn.",
      hints: [
        "LLMs generate text. They cannot run code or call APIs. The host does that.",
        "The LLM outputs a structured message; the application layer interprets and executes it.",
      ],
    },
    {
      id: "q-agent-kp2-6",
      type: "multiple-choice",
      difficulty: "medium",
      question: "Tool call hallucination refers to:",
      options: [
        "The model generating outputs that are too creative",
        "The model invoking tool names or parameters that do not exist in the provided schema",
        "Tool calls executing too slowly",
        "Circular tool calls that never terminate",
      ],
      correctAnswer: 1,
      explanation: "Tool call hallucination occurs when the LLM generates tool calls that reference non-existent tools or invalid parameters. This breaks the agent loop and requires error handling.",
      hints: [
        "The LLM is a text generator, not a validator. It can output any text, including invalid tool calls.",
        "Well-written tool descriptions and few-shot examples reduce hallucination rates.",
      ],
    },
    {
      id: "q-agent-kp2-7",
      type: "multiple-choice",
      difficulty: "medium",
      question: "What is the purpose of the required array in a tool JSON Schema parameter definition?",
      options: [
        "Required fields are validated for security",
        "It instructs the LLM which parameters must always be provided vs. optional ones with defaults",
        "Required fields are cached for performance",
        "They trigger parallel execution of the tool",
      ],
      correctAnswer: 1,
      explanation: "The JSON Schema required array tells the LLM which parameters cannot be omitted. Well-designed schemas reduce malformed tool calls.",
      hints: [
        "Without required markers, the LLM might omit crucial parameters.",
        "Optional parameters with sensible defaults should not be in the required array.",
      ],
    },
    {
      id: "q-agent-kp2-8",
      type: "multiple-choice",
      difficulty: "hard",
      question: "Gorilla LLM (Patil et al., 2023) was trained specifically to improve:",
      options: [
        "Multi-step reasoning without any tools",
        "Accurate API call generation from natural language, including correct API retrieval and parameter filling",
        "Parallel conversation handling across multiple users",
        "Code security vulnerability detection",
      ],
      correctAnswer: 1,
      explanation: "Gorilla fine-tunes LLMs on API documentation to generate accurate API calls with retrieval-aware training, reducing hallucination rates on large API sets.",
      hints: [
        "Gorilla is named for its ability to grab the right API from a large set.",
        "Retrieval-aware training means Gorilla can adapt when the API documentation changes.",
      ],
    },
    {
      id: "q-agent-kp2-9",
      type: "true-false",
      difficulty: "hard",
      question: "Giving an LLM agent a code execution tool that runs Python is inherently more dangerous than a web search tool from a security perspective.",
      options: ["True", "False"],
      correctAnswer: "True",
      explanation: "A code execution tool can perform arbitrary file system access and system calls if not sandboxed. Web search is read-only with no side effects. Code execution requires strict sandboxing.",
      hints: [
        "What can arbitrary Python code do on a system? Compare to what web search can do.",
        "Side effects (file writes, network calls, process spawning) are the key risk dimension.",
      ],
    },
  ],

  "react-pattern": [
    {
      id: "q-agent-kp3-1",
      type: "multiple-choice",
      difficulty: "easy",
      question: "What does ReAct stand for in the context of LLM agents?",
      options: [
        "Recursive Action Transformer",
        "Reasoning and Acting",
        "Retrieval-Augmented Contextual Thinking",
        "React.js integrated with Agents",
      ],
      correctAnswer: 1,
      explanation: "ReAct (Yao et al., 2022) interleaves Reasoning traces (Thought) with Action steps, allowing the model to plan, observe results, and update its reasoning before the next action.",
      hints: [
        "The paper title directly describes what the model does: it reasons, then it acts.",
        "The two words in the acronym are Reasoning and Acting.",
      ],
    },
    {
      id: "q-agent-kp3-2",
      type: "true-false",
      difficulty: "medium",
      question: "In the ReAct pattern, the Observation step is generated by the LLM itself.",
      options: ["True", "False"],
      correctAnswer: "False",
      explanation: "The Observation is the real-world result returned by executing the Action (e.g., tool output, search results). The LLM generates Thought and Action; the environment supplies the Observation.",
      hints: [
        "Consider: if the agent calls a web search tool, who provides the search results?",
        "The loop is Thought -> Action -> Observation, where only the last step comes from outside the model.",
      ],
    },
    {
      id: "q-agent-kp3-3",
      type: "multiple-choice",
      difficulty: "hard",
      question: "Compared to chain-of-thought prompting alone, the primary advantage of ReAct is:",
      options: [
        "It eliminates the need for any tools by reasoning over internal knowledge.",
        "It grounds reasoning steps in real observations, reducing hallucinations from stale internal knowledge.",
        "It runs faster because fewer tokens are generated per step.",
        "It requires no few-shot examples to work reliably.",
      ],
      correctAnswer: 1,
      explanation: "Chain-of-thought generates a reasoning trace entirely from the model distribution with no external grounding. ReAct interleaves thoughts with actions: each thought triggers an action, which produces an observation from the environment. The observation can correct earlier hallucinations before the next thought is generated, creating a grounded feedback loop.",
      hints: [
        "In CoT, if the model says the capital of France is London, subsequent thoughts have no signal to correct this.",
        "In ReAct, a search tool returning Paris corrects the hallucination before the next thought is generated.",
      ],
    },
    {
      id: "q-agent-kp3-4",
      type: "multiple-choice",
      difficulty: "medium",
      question: "In Reflexion (Shinn et al., 2023), what is the role of the self-reflection loop?",
      options: [
        "Generating more diverse action choices via beam search",
        "Producing verbal self-critique of a failed trajectory and storing it as episodic memory for the next attempt",
        "Reducing the number of tool calls by caching results",
        "Switching to a smaller model when the main model fails",
      ],
      correctAnswer: 1,
      explanation: "Reflexion prompts the agent to verbally analyze why its last trajectory failed, then stores that critique as a memory entry. On the next attempt, this memory is prepended to the context so the agent can avoid repeating the same mistakes.",
      hints: [
        "Verbal self-critique stored in memory is the key mechanism -- not just retrying the same prompt.",
        "Think of it as an athlete reviewing game film before the next match.",
      ],
    },
    {
      id: "q-agent-kp3-5",
      type: "true-false",
      difficulty: "medium",
      question: "Tree of Thoughts (Yao et al., 2023) explores multiple reasoning paths in breadth-first or depth-first order, unlike linear chain-of-thought.",
      options: ["True", "False"],
      correctAnswer: "True",
      explanation: "Tree of Thoughts frames problem solving as searching a tree where each node is a partial solution (thought). The algorithm can use BFS (explore all branches at current depth) or DFS (follow one branch to completion), guided by a value function that evaluates promising partial solutions.",
      hints: [
        "Linear CoT is a single path from root to leaf. ToT can backtrack and explore siblings.",
        "The value function (another LLM call) estimates whether a partial thought can lead to a correct final answer.",
      ],
    },
    {
      id: "q-agent-kp3-6",
      type: "multiple-choice",
      difficulty: "easy",
      question: "ALFWorld is used to evaluate ReAct agents in which type of environment?",
      options: [
        "Stock trading simulation",
        "Text-based household task simulation where agents navigate rooms and manipulate objects",
        "Web browsing with real websites",
        "Coding challenges on competitive programming platforms",
      ],
      correctAnswer: 1,
      explanation: "ALFWorld is a text-based interactive simulation of household tasks (e.g., heat a tomato and put it on a counter). ReAct agents must navigate rooms and interact with objects using text actions, grounding their reasoning in the textual observations returned by the environment.",
      hints: [
        "ALF stands for Alfred -- the household robot assistant benchmark it is derived from.",
        "Text-based environments give clean, discrete observations ideal for studying the ReAct loop.",
      ],
    },
    {
      id: "q-agent-kp3-7",
      type: "multiple-choice",
      difficulty: "hard",
      question: "A ReAct agent enters an infinite loop, repeatedly calling the same search tool with the same query. What is the most likely root cause?",
      options: [
        "The tool schema is missing required fields",
        "The model lacks a mechanism to detect and escape repeated observations, causing the same thought to trigger the same action",
        "The context window is too small for the task",
        "Parallel tool calls are not supported by the framework",
      ],
      correctAnswer: 1,
      explanation: "Infinite loops in ReAct occur when the model generates an identical thought-action pair despite receiving the same observation repeatedly. Without an explicit loop-detection heuristic (e.g., Reflexion resets on repeated identical actions) or a step budget, the agent cannot self-escape.",
      hints: [
        "Reflexion explicitly checks for repeated identical actions as a hallucination signal and triggers a reset.",
        "A step budget is a safety guard but does not fix the root cause of repetitive reasoning.",
      ],
    },
    {
      id: "q-agent-kp3-8",
      type: "true-false",
      difficulty: "hard",
      question: "A Thought-only agent (chain-of-thought without actions) can match ReAct performance on tasks that require up-to-date factual information.",
      options: ["True", "False"],
      correctAnswer: "False",
      explanation: "Thought-only agents reason entirely from parametric knowledge frozen at training time. For tasks requiring current facts (news, prices, recent papers), they hallucinate or fail because no retrieval grounds the reasoning in fresh information. ReAct actions provide the grounding mechanism.",
      hints: [
        "What does the model do when asked about an event that happened after its training cutoff?",
        "Grounding = connecting reasoning to real-world data. Thought-only has no grounding mechanism.",
      ],
    },
    {
      id: "q-agent-kp3-9",
      type: "multiple-choice",
      difficulty: "medium",
      question: "In the original ReAct paper, which benchmark demonstrated the strongest improvement of ReAct over chain-of-thought alone?",
      options: [
        "HumanEval code generation",
        "HotpotQA multi-hop question answering with Wikipedia search",
        "GSM8K arithmetic reasoning",
        "MMLU multiple-choice knowledge",
      ],
      correctAnswer: 1,
      explanation: "ReAct showed the largest gains on knowledge-intensive tasks like HotpotQA (multi-hop QA) and FEVER (fact verification) where search tool access directly compensated for the model lacking up-to-date or specialized knowledge.",
      hints: [
        "Multi-hop QA requires chaining multiple facts -- each retrieval step grounds the next reasoning step.",
        "Math benchmarks like GSM8K benefit less from retrieval because the facts are self-contained in the problem.",
      ],
    },
  ],

  "planning-agents": [
    {
      id: "q-agent-kp4-1",
      type: "multiple-choice",
      difficulty: "medium",
      question: "In LLM-based planning, what is the main role of a planner step before execution?",
      options: [
        "To compress the user query into fewer tokens.",
        "To decompose a complex goal into an ordered sequence of sub-tasks or tool calls.",
        "To select which LLM model to use for the task.",
        "To validate that tool schemas are syntactically correct.",
      ],
      correctAnswer: 1,
      explanation: "A planner breaks a high-level goal into sub-tasks with dependencies, enabling the agent to execute steps in the right order and handle failures at the sub-task level rather than restarting from scratch.",
      hints: [
        "Think about how a project manager breaks a large project into tickets before any coding begins.",
        "The plan is produced before any tools are actually called.",
      ],
    },
    {
      id: "q-agent-kp4-2",
      type: "true-false",
      difficulty: "hard",
      question: "Monte Carlo Tree Search (MCTS) can be applied to LLM agent planning by using the LLM to evaluate the value of candidate next actions.",
      options: ["True", "False"],
      correctAnswer: "True",
      explanation: "MCTS operates in four phases: Selection (UCT formula), Expansion (add candidate actions), Simulation (roll out using the LLM as value function), and Backpropagation (update Q-values). Tree of Thoughts and RAP both plug LLM-based value estimates into this MCTS cycle.",
      hints: [
        "Tree of Thoughts (Yao et al., 2023) treats each partial solution as a tree node and uses an LLM to score whether it can lead to a full solution.",
        "RAP (Reasoning with Planning) uses the LLM to estimate success probability for MCTS selection.",
      ],
    },
    {
      id: "q-agent-kp4-3",
      type: "multiple-choice",
      difficulty: "hard",
      question: "What is a key limitation of purely LLM-generated plans for long-horizon tasks?",
      options: [
        "LLMs cannot output structured text like JSON or YAML.",
        "Plans become stale as the world changes mid-execution, requiring re-planning.",
        "LLM planners always produce optimal plans with zero redundant steps.",
        "Planning requires access to a dedicated GPU cluster not available at inference time.",
      ],
      correctAnswer: 1,
      explanation: "A plan is a sequence of actions conditioned on expected observations. In a dynamic world, actual observations may deviate from expectations -- a web search returns unexpected results, an API call fails, or user input changes context. This causes plan degradation: later actions were optimized for expected observations, not actual ones. Adaptive replanning addresses this by continuously updating the plan based on real observations.",
      hints: [
        "A 10-step plan where step 3 fails means steps 4-10 were planned for an incorrect world state.",
        "The ReAct Thought->Action->Observation loop is the minimal replanning mechanism.",
      ],
    },
    {
      id: "q-agent-kp4-4",
      type: "multiple-choice",
      difficulty: "easy",
      question: "What is a DAG (directed acyclic graph) plan in agent systems?",
      options: [
        "A plan where tasks run in random order",
        "A task graph encoding dependencies with no circular dependencies, enabling parallel execution of independent tasks",
        "A neural network architecture for planning",
        "A database query plan",
      ],
      correctAnswer: 1,
      explanation: "DAG plans encode task dependencies. Tasks with no unmet dependencies can run in parallel. More efficient than linear plans for independent sub-tasks.",
      hints: [
        "DAG = no cycles = no deadlocks. Parallel paths = speedup.",
        "Example: downloading two files is independent -- both can run in parallel as separate DAG branches.",
      ],
    },
    {
      id: "q-agent-kp4-5",
      type: "true-false",
      difficulty: "easy",
      question: "LLM planners always produce globally optimal plans for complex tasks.",
      options: ["True", "False"],
      correctAnswer: "False",
      explanation: "LLM planners are heuristic. They generate plausible plans but lack optimality guarantees. Symbolic planners (STRIPS, PDDL) can produce optimal plans but require structured world models.",
      hints: [
        "LLMs generate text probabilistically. They do not run formal optimization algorithms.",
        "Heuristic does not mean bad -- it means no formal optimality guarantee.",
      ],
    },
    {
      id: "q-agent-kp4-6",
      type: "multiple-choice",
      difficulty: "medium",
      question: "In HuggingGPT / TaskMatrix, what is the role of the central LLM?",
      options: [
        "Fine-tuning each specialist model on the task",
        "Acting as controller: interpreting user intent, selecting appropriate AI models as tools, and synthesizing outputs",
        "Storing all specialist model weights in one context window",
        "Generating training data for specialist models",
      ],
      correctAnswer: 1,
      explanation: "HuggingGPT uses ChatGPT as planner/controller that parses user requests, selects specialized models from HuggingFace as tools, executes them, and integrates results.",
      hints: [
        "The central LLM is the manager delegating to specialist workers (other AI models).",
        "The controller does not need to know how each specialist model works internally.",
      ],
    },
    {
      id: "q-agent-kp4-7",
      type: "multiple-choice",
      difficulty: "medium",
      question: "What is plan grounding in agent systems?",
      options: [
        "Connecting abstract plans to real-world executable actions and verifying feasibility given current state",
        "Storing the plan in a graph database",
        "Training the LLM on planning datasets",
        "Converting natural language plans to SQL queries",
      ],
      correctAnswer: 0,
      explanation: "Plan grounding connects abstract plans (e.g., book a hotel) to concrete executable steps (specific API calls, valid parameters), checking feasibility given current world state.",
      hints: [
        "Abstract plan: go to the store. Grounded plan: specific route, transportation, store hours checked.",
        "Grounding fails if the abstract action has no valid concrete realization in the current world state.",
      ],
    },
    {
      id: "q-agent-kp4-8",
      type: "multiple-choice",
      difficulty: "hard",
      question: "The key advantage of online re-planning over purely upfront planning is:",
      options: [
        "It is always faster to generate plans on-the-fly",
        "It adapts to unexpected tool results or environment changes without requiring a complete restart",
        "Online re-planning requires less total computation",
        "It eliminates the need for error handling in individual steps",
      ],
      correctAnswer: 1,
      explanation: "Upfront plans assume a static world. Online re-planning continuously revises remaining steps based on actual observations, handling failures and surprises gracefully.",
      hints: [
        "A GPS that recalculates when you miss a turn is re-planning; a printed map is not.",
        "The cost of re-planning is paid at runtime but avoids executing invalid future steps.",
      ],
    },
    {
      id: "q-agent-kp4-9",
      type: "true-false",
      difficulty: "hard",
      question: "LLM planning quality improves significantly when the prompt includes worked examples of task decomposition for the target domain.",
      options: ["True", "False"],
      correctAnswer: "True",
      explanation: "Few-shot examples of decomposed plans substantially improve LLM planning quality by teaching expected granularity, format, and reasoning style for the domain.",
      hints: [
        "Few-shot prompting helps LLMs imitate demonstrated behavior, including plan structure.",
        "Domain-specific examples teach the model what counts as an atomic vs. composite step in that domain.",
      ],
    },
  ],

  "memory-agents": [
    {
      id: "q-agent-kp5-1",
      type: "multiple-choice",
      difficulty: "easy",
      question: "Which type of agent memory stores information only for the duration of a single conversation session?",
      options: [
        "Long-term memory",
        "Episodic memory",
        "Short-term (in-context) memory",
        "Semantic memory",
      ],
      correctAnswer: 2,
      explanation: "Short-term or in-context memory is the running conversation history held in the LLM context window; it is lost when the session ends.",
      hints: [
        "Think about what the LLM can see at any given moment -- it is bounded by the context window.",
        "This type of memory does not persist to disk or a database.",
      ],
    },
    {
      id: "q-agent-kp5-2",
      type: "true-false",
      difficulty: "medium",
      question: "Episodic memory in agents refers to storing summaries of past agent runs so they can be retrieved in future sessions.",
      options: ["True", "False"],
      correctAnswer: "True",
      explanation: "Episodic memory records specific past experiences (task runs, outcomes, errors) that the agent can retrieve to avoid repeating mistakes or reuse successful strategies in new sessions.",
      hints: [
        "The term comes from cognitive science, where episodic memory is memory of specific events, not general facts.",
        "This contrasts with semantic memory, which stores general knowledge rather than specific past episodes.",
      ],
    },
    {
      id: "q-agent-kp5-3",
      type: "multiple-choice",
      difficulty: "hard",
      question: "The memory consolidation problem in long-running agents refers to:",
      options: [
        "The agent inability to write to a SQL database during runtime.",
        "Deciding what information to compress, summarize, or evict from the context window to stay within token limits.",
        "Converting floating-point weights to integers for efficiency.",
        "Merging two separate agent threads into one.",
      ],
      correctAnswer: 1,
      explanation: "Memory consolidation addresses the fundamental constraint that context windows have finite token capacity. As trajectories grow, the history approaches the limit, leaving no room for new observations. Consolidation strategies (summarization, importance scoring, eviction) decide what to preserve while freeing space.",
      hints: [
        "A context window of 128K tokens sounds large, but a 100-step ReAct loop with verbose tool outputs can exceed it quickly.",
        "Generative Agents (Park et al., 2023) use importance-weighted reflection to decide which memories to surface.",
      ],
    },
    {
      id: "q-agent-kp5-4",
      type: "multiple-choice",
      difficulty: "easy",
      question: "In Generative Agents (Park et al., 2023), what is the memory stream?",
      options: [
        "A continuous audio/video recording of agent actions",
        "A chronological list of all observations, reflections, and plans stored as natural language strings",
        "A neural network that compresses all past experiences",
        "A database of all user messages only",
      ],
      correctAnswer: 1,
      explanation: "Generative Agents maintain a memory stream: time-stamped natural language descriptions of events. Retrieval scores entries based on recency, importance, and relevance to the current context.",
      hints: [
        "Memory stream = event diary. Each entry is a natural language description of what happened.",
        "The three retrieval dimensions are recency (decay function), importance (LLM-rated), and relevance (cosine similarity).",
      ],
    },
    {
      id: "q-agent-kp5-5",
      type: "true-false",
      difficulty: "medium",
      question: "Vector databases enable agents to retrieve semantically relevant memories even when exact words differ from the query.",
      options: ["True", "False"],
      correctAnswer: "True",
      explanation: "Semantic (vector) retrieval finds memories by meaning similarity, not exact keyword match. A query about eating lunch can retrieve memories mentioning having a meal.",
      hints: [
        "Vector similarity captures semantic meaning; keyword search requires exact matches.",
        "The embedding model maps both query and memory to the same vector space for comparison.",
      ],
    },
    {
      id: "q-agent-kp5-6",
      type: "multiple-choice",
      difficulty: "medium",
      question: "What is reflection in Generative Agents?",
      options: [
        "The agent looking at its reflection in a simulated mirror",
        "A higher-level synthesis of recent memories into abstract insights, stored as new memory entries",
        "The agent re-executing a task it failed previously",
        "Compressing context by removing old memories",
      ],
      correctAnswer: 1,
      explanation: "Reflection generates higher-order thoughts by asking the LLM to synthesize recent memories into abstract insights stored as new memory stream entries.",
      hints: [
        "Reflection turns low-level events into high-level understanding. Like journaling to extract lessons.",
        "Reflections are themselves stored in the memory stream and can be retrieved like raw events.",
      ],
    },
    {
      id: "q-agent-kp5-7",
      type: "multiple-choice",
      difficulty: "hard",
      question: "How does MemGPT (Packer et al., 2023) extend agent memory beyond context window limits?",
      options: [
        "By training a larger model with more parameters",
        "By implementing OS-style virtual memory: paging relevant memories into the in-context main memory from external storage on demand",
        "By compressing all history into a single embedding vector",
        "By limiting the agent to answering only from its training data",
      ],
      correctAnswer: 1,
      explanation: "MemGPT mimics OS virtual memory: context window = RAM, external databases = disk. The agent manages paging via function calls, enabling unbounded effective memory.",
      hints: [
        "MemGPT: context window = RAM, external DB = hard disk. Agent decides what to swap in and out.",
        "The agent explicitly calls memory management functions to control what is in context.",
      ],
    },
    {
      id: "q-agent-kp5-8",
      type: "true-false",
      difficulty: "hard",
      question: "Storing all past conversation turns verbatim is more effective than summarization for very long agent sessions.",
      options: ["True", "False"],
      correctAnswer: "False",
      explanation: "Verbatim storage hits context limits and includes irrelevant detail. Hierarchical summarization preserves key information in fewer tokens, enabling longer sessions.",
      hints: [
        "Full verbatim storage has linear token growth. Summarization has sub-linear growth.",
        "Not all conversation turns are equally important -- summarization can selectively preserve what matters.",
      ],
    },
    {
      id: "q-agent-kp5-9",
      type: "multiple-choice",
      difficulty: "hard",
      question: "The importance score in Generative Agents memory retrieval is used to:",
      options: [
        "Determine which API calls to make first",
        "Weight memories by significance when deciding what to surface for the current task",
        "Sort memories by creation timestamp only",
        "Measure cosine similarity between memory embeddings",
      ],
      correctAnswer: 1,
      explanation: "Generative Agents score memories by recency (decay function), importance (LLM-rated 1-10 poignancy), and relevance (cosine similarity). All three contribute to the retrieval score.",
      hints: [
        "Importance distinguishes trivial from pivotal events: I ate breakfast vs. I got promoted.",
        "The importance score is assigned by an LLM at the time the memory is created, not at retrieval time.",
      ],
    },
  ],

  "rag-agents": [
    {
      id: "q-agent-kp6-1",
      type: "multiple-choice",
      difficulty: "easy",
      question: "In a RAG system, what is the purpose of the retrieval step?",
      options: [
        "To fine-tune the LLM on new documents.",
        "To fetch relevant document chunks from a vector store to include in the prompt.",
        "To cache the LLM previous responses for speed.",
        "To validate the LLM output against a ground truth database.",
      ],
      correctAnswer: 1,
      explanation: "Retrieval-Augmented Generation fetches semantically relevant chunks from an external knowledge base and injects them into the prompt, giving the LLM up-to-date context it was not trained on.",
      hints: [
        "The model knowledge is static after training -- RAG provides a way to give it fresh information at inference time.",
        "Vector similarity search is the most common method for finding relevant chunks.",
      ],
    },
    {
      id: "q-agent-kp6-2",
      type: "true-false",
      difficulty: "medium",
      question: "In agentic RAG, the agent can iteratively decide to retrieve more information if the initial retrieval was insufficient.",
      options: ["True", "False"],
      correctAnswer: "True",
      explanation: "Agentic RAG treats retrieval as a tool call the agent can invoke multiple times, refining queries based on what it has already retrieved -- a pattern called iterative or multi-hop retrieval.",
      hints: [
        "Contrast naive RAG (one retrieval call) with an agent that can issue follow-up queries.",
        "Think about how a researcher may search for a topic, read, then search for a related sub-topic.",
      ],
    },
    {
      id: "q-agent-kp6-3",
      type: "multiple-choice",
      difficulty: "hard",
      question: "Which technique improves retrieval precision by having the LLM generate a hypothetical answer document before embedding the query?",
      options: [
        "Re-ranking with a cross-encoder",
        "HyDE (Hypothetical Document Embeddings)",
        "Chunk overlap expansion",
        "BM25 keyword fallback",
      ],
      correctAnswer: 1,
      explanation: "HyDE (Gao et al., 2022) generates a hypothetical answer document from the query, then embeds that document for retrieval. Since the hypothetical document is in the same distribution as real documents, its embedding is closer to relevant chunks than a raw query embedding -- bridging the query-document domain gap.",
      hints: [
        "The query who developed relativity embeds far from physics papers, but a generated passage about Einstein embeds near them.",
        "HyDE adds one LLM call per query but can significantly boost recall on complex or ambiguous queries.",
      ],
    },
    {
      id: "q-agent-kp6-4",
      type: "multiple-choice",
      difficulty: "medium",
      question: "What is the difference between fixed-size chunking and semantic chunking in RAG document preparation?",
      options: [
        "Fixed-size chunking is always better because it produces uniform embeddings",
        "Semantic chunking splits documents at natural boundaries (sentences, paragraphs, topics) to keep coherent units together, while fixed-size splits at token counts regardless of meaning",
        "Fixed-size chunking uses sentence transformers; semantic chunking uses BM25",
        "Semantic chunking requires fine-tuning the embedding model on the document collection",
      ],
      correctAnswer: 1,
      explanation: "Fixed-size chunking splits every N tokens, often cutting mid-sentence or mid-idea, producing incoherent chunks that embed poorly. Semantic chunking respects natural language boundaries, producing chunks that represent coherent units of meaning and embed more accurately.",
      hints: [
        "Would you prefer a retrieved chunk that cuts off mid-sentence, or one that contains a complete thought?",
        "Sentence-level or paragraph-level splits are common semantic chunking strategies.",
      ],
    },
    {
      id: "q-agent-kp6-5",
      type: "true-false",
      difficulty: "medium",
      question: "A cross-encoder re-ranker can improve retrieval quality by scoring each retrieved chunk jointly with the query, rather than independently.",
      options: ["True", "False"],
      correctAnswer: "True",
      explanation: "Bi-encoders (used in dense retrieval) encode query and document independently. Cross-encoders score the query-document pair jointly, capturing interaction signals bi-encoders miss. Re-ranking the top-K bi-encoder results with a cross-encoder improves precision at the cost of extra latency.",
      hints: [
        "Joint encoding allows the model to see how the query and chunk relate to each other, not just their individual representations.",
        "Cross-encoders are too slow for full-corpus search but fast enough to re-rank the top 50-100 candidates.",
      ],
    },
    {
      id: "q-agent-kp6-6",
      type: "multiple-choice",
      difficulty: "hard",
      question: "In multi-hop iterative retrieval, why does the agent issue multiple sequential retrieval calls instead of one?",
      options: [
        "To stay within the per-call token limit of the retrieval API",
        "Because answering complex questions requires chaining evidence: the answer to one retrieval informs what to retrieve next",
        "To increase the total number of tokens in context for accuracy",
        "Because vector databases do not support batch queries",
      ],
      correctAnswer: 1,
      explanation: "Multi-hop questions require reasoning over multiple documents in sequence. For example, finding the birthplace of the CEO of a company requires first retrieving the CEO name, then retrieving biographical information. Each retrieval hop builds on the results of the previous one.",
      hints: [
        "Who is the CEO of company X, and where were they born? This needs two sequential retrieval steps.",
        "The query for the second hop depends on the answer to the first hop -- they cannot be parallelized.",
      ],
    },
    {
      id: "q-agent-kp6-7",
      type: "multiple-choice",
      difficulty: "medium",
      question: "Hybrid retrieval combining BM25 (sparse) and dense vector search typically outperforms either alone because:",
      options: [
        "BM25 is faster and vector search is slower, so combining balances latency",
        "Sparse retrieval excels at exact keyword matching while dense retrieval captures semantic similarity; their signals are complementary",
        "Dense vectors require BM25 as a preprocessing step before embedding",
        "Combining them doubles the number of retrieved documents, increasing recall by volume alone",
      ],
      correctAnswer: 1,
      explanation: "BM25 uses TF-IDF term frequencies and excels when queries share exact vocabulary with documents. Dense retrieval captures paraphrase and semantic relationships but may miss exact matches for rare terms. Reciprocal rank fusion or score interpolation combines both signals, improving overall retrieval quality.",
      hints: [
        "A query using technical acronyms that appear verbatim in documents benefits from BM25.",
        "A query using different vocabulary than the document benefits from dense semantic retrieval.",
      ],
    },
    {
      id: "q-agent-kp6-8",
      type: "true-false",
      difficulty: "hard",
      question: "Long-context LLMs with very large context windows make RAG retrieval unnecessary, because the entire knowledge base can fit in the context.",
      options: ["True", "False"],
      correctAnswer: "False",
      explanation: "Even with million-token context windows, RAG remains valuable: LLMs attend less accurately to middle-of-context information (lost-in-the-middle problem), retrieval selects the most relevant chunks reducing noise, and retrieval is faster and cheaper than processing a full document corpus on every query.",
      hints: [
        "The lost-in-the-middle finding shows LLM recall degrades for information placed in the middle of very long contexts.",
        "Retrieving 5 relevant chunks is cheaper than sending 10,000 documents on every query.",
      ],
    },
    {
      id: "q-agent-kp6-9",
      type: "multiple-choice",
      difficulty: "hard",
      question: "Contextual compression in RAG refers to:",
      options: [
        "Compressing the LLM weights using quantization before inference",
        "Extracting only the query-relevant portions of retrieved chunks rather than returning full chunks",
        "Reducing the embedding dimension to save storage space",
        "Compressing multiple user queries into a single batch request",
      ],
      correctAnswer: 1,
      explanation: "Contextual compression passes each retrieved chunk through a secondary LLM or extraction model that removes irrelevant sentences, keeping only the portion directly relevant to the query. This reduces context noise and token usage without losing precision.",
      hints: [
        "A 500-word chunk retrieved for a narrow query may contain only 50 words relevant to that specific question.",
        "Compression reduces the prompt size, leaving more room for additional retrieved chunks.",
      ],
    },
  ],

  "multi-agent-systems": [
    {
      id: "q-agent-kp7-1",
      type: "multiple-choice",
      difficulty: "easy",
      question: "What is the primary motivation for using multiple agents instead of a single large agent?",
      options: [
        "Multiple agents always produce cheaper API calls.",
        "Tasks can be parallelized, specialized agents can handle subtasks better, and context windows remain focused.",
        "Multi-agent systems do not require any orchestration logic.",
        "A single LLM cannot handle more than one tool at a time.",
      ],
      correctAnswer: 1,
      explanation: "Multi-agent systems exploit parallelism, allow specialization (e.g., a coder agent plus a reviewer agent), and keep each agent context focused on its sub-task rather than a bloated shared context.",
      hints: [
        "Think about why companies have teams of specialists instead of one generalist doing everything.",
        "Parallelism and specialization are the two key wins over a monolithic agent.",
      ],
    },
    {
      id: "q-agent-kp7-2",
      type: "true-false",
      difficulty: "medium",
      question: "In a multi-agent system, all agents must share a single context window to coordinate effectively.",
      options: ["True", "False"],
      correctAnswer: "False",
      explanation: "Agents communicate via message passing, shared memory stores, or explicit handoffs -- not by sharing a single context window. Each agent maintains its own context and exchanges structured outputs.",
      hints: [
        "Consider how microservices communicate via APIs, not shared memory.",
        "What would happen to token limits if every agent shared one enormous context?",
      ],
    },
    {
      id: "q-agent-kp7-3",
      type: "multiple-choice",
      difficulty: "hard",
      question: "Which coordination pattern describes an agent that decomposes a task and delegates sub-tasks to specialist agents, then aggregates their results?",
      options: [
        "Peer-to-peer gossip protocol",
        "Blackboard architecture",
        "Orchestrator-subagent (hierarchical) pattern",
        "Reactive agent swarm",
      ],
      correctAnswer: 2,
      explanation: "The orchestrator-subagent pattern implements hierarchical task decomposition. The orchestrator generates sub-tasks, dispatches each to a specialist sub-agent, and synthesizes the results. This reduces communication complexity from O(N^2) for a fully connected mesh to O(N) for the hierarchy.",
      hints: [
        "A manager knows which team member is best for each sub-task -- analogous to a project manager delegating tickets.",
        "Without hierarchy, N agents require N*(N-1)/2 pairwise communication channels.",
      ],
    },
    {
      id: "q-agent-kp7-4",
      type: "multiple-choice",
      difficulty: "medium",
      question: "In a Blackboard multi-agent architecture, how do agents coordinate?",
      options: [
        "All agents share a single LLM context window and take turns appending to it",
        "Agents read from and write to a shared central data structure (the blackboard), reacting to changes made by other agents",
        "A designated lead agent dictates instructions to all others via direct messaging",
        "Agents vote on each action before any agent executes it",
      ],
      correctAnswer: 1,
      explanation: "The Blackboard architecture has a shared workspace where agents post partial solutions. Other agents detect relevant changes and contribute their expertise. No agent needs to know about the others directly -- they coordinate indirectly through the shared blackboard.",
      hints: [
        "Think of a whiteboard in a war room where different experts write findings for others to build on.",
        "The blackboard acts as a shared memory that decouples agents from knowing about each other.",
      ],
    },
    {
      id: "q-agent-kp7-5",
      type: "true-false",
      difficulty: "medium",
      question: "LLM debate (Du et al., 2023) improves factual accuracy by having multiple models generate answers and then critique each other iteratively.",
      options: ["True", "False"],
      correctAnswer: "True",
      explanation: "LLM debate has multiple independent LLM agents generate answers, then each reads the others responses and updates its own answer. After several rounds, the agents tend to converge on more accurate answers than any single agent alone, reducing overconfidence and hallucination.",
      hints: [
        "The key mechanism is that seeing another model disagree prompts re-evaluation of weak reasoning.",
        "Debate improves calibration: models become less confident in incorrect answers when challenged.",
      ],
    },
    {
      id: "q-agent-kp7-6",
      type: "multiple-choice",
      difficulty: "hard",
      question: "MetaGPT assigns different roles (Product Manager, Engineer, Tester) to different LLM agents. What is the primary benefit of this role specialization?",
      options: [
        "Each role uses a different LLM model optimized for that task",
        "Role-specific system prompts focus each agent on its domain, producing higher-quality specialized outputs and enforcing a software process workflow",
        "Roles allow agents to share tool access without conflicts",
        "Specialization eliminates the need for any inter-agent communication",
      ],
      correctAnswer: 1,
      explanation: "MetaGPT gives each agent a role-specific system prompt that focuses its reasoning on that role domain. A Product Manager agent thinks about requirements; an Engineer agent thinks about implementation. This specialization mimics real software teams and produces higher-quality structured outputs than a single generalist agent.",
      hints: [
        "System prompt engineering is the mechanism -- each role gets a different prompt constraining its behavior.",
        "The software process (requirements -> design -> implementation -> test) provides natural handoff points.",
      ],
    },
    {
      id: "q-agent-kp7-7",
      type: "multiple-choice",
      difficulty: "medium",
      question: "ChatDev simulates a software company with LLM agents. What is the main research finding from this system?",
      options: [
        "LLM agents cannot collaborate to produce functional software without human intervention at each step",
        "Role-playing LLM agents can collaboratively generate, review, and test complete software projects through structured multi-turn dialogue",
        "ChatDev requires specialized fine-tuned models for each role to work effectively",
        "The system only works for toy examples under 100 lines of code",
      ],
      correctAnswer: 1,
      explanation: "ChatDev (Qian et al., 2023) demonstrated that role-playing LLM agents (CEO, CTO, Programmer, Tester) can converse in structured phases to produce functional software end-to-end. The structured dialogue protocol guides agents through requirements, design, coding, and testing phases.",
      hints: [
        "The key insight is that structured conversation phases (not just free-form chat) enable effective collaboration.",
        "ChatDev produced software projects with fewer bugs than single-agent baselines in controlled evaluations.",
      ],
    },
    {
      id: "q-agent-kp7-8",
      type: "true-false",
      difficulty: "hard",
      question: "In multi-agent pipelines, an error in an early agent stage can silently propagate and amplify through subsequent agents without any correction mechanism.",
      options: ["True", "False"],
      correctAnswer: "True",
      explanation: "Multi-agent pipelines have error propagation risk: if Agent A produces an incorrect output and passes it to Agent B, B treats it as ground truth. Without explicit verification checkpoints or critic agents, errors cascade and compound across the pipeline, making debugging difficult.",
      hints: [
        "Unlike a single agent that can self-correct via observation, pipeline errors have no automatic correction mechanism.",
        "Adding a critic or validator agent at stage boundaries is the standard mitigation.",
      ],
    },
    {
      id: "q-agent-kp7-9",
      type: "multiple-choice",
      difficulty: "hard",
      question: "Why is trust verification particularly challenging in multi-agent systems where agents can spawn sub-agents?",
      options: [
        "Sub-agents always have lower API rate limits than the parent agent",
        "A malicious or compromised sub-agent can claim to have completed a task correctly, and the orchestrator has no reliable way to verify without re-executing the task itself",
        "Sub-agents cannot access the same tools as parent agents due to permission inheritance rules",
        "Multi-agent systems require all agents to be running the same LLM model version",
      ],
      correctAnswer: 1,
      explanation: "In hierarchical multi-agent systems, the orchestrator delegates tasks to sub-agents and trusts their reported outputs. A compromised or hallucinating sub-agent can report success for a failed task. Without independent verification or output validation, the orchestrator cannot distinguish truthful from fabricated results.",
      hints: [
        "This is analogous to trusting a contractor who claims a job is done without inspecting the work.",
        "Verification agents, result sampling, and deterministic validation are mitigations for this trust problem.",
      ],
    },
  ],

  "agent-frameworks": [
    {
      id: "q-agent-kp8-1",
      type: "multiple-choice",
      difficulty: "easy",
      question: "LangGraph models agent workflows as:",
      options: [
        "Linear chains of LLM calls only.",
        "Directed graphs (nodes = steps, edges = transitions) with support for cycles.",
        "SQL database query plans.",
        "YAML configuration files parsed at runtime.",
      ],
      correctAnswer: 1,
      explanation: "LangGraph represents agent logic as a stateful directed graph where nodes are processing steps and edges encode conditional transitions, naturally supporting loops, branches, and multi-agent handoffs.",
      hints: [
        "The Graph in LangGraph is literal -- think nodes and edges.",
        "Cycles in the graph enable the agent loop: the model can return to earlier nodes.",
      ],
    },
    {
      id: "q-agent-kp8-2",
      type: "true-false",
      difficulty: "medium",
      question: "AutoGen allows multiple LLM-powered agents to converse with each other to solve tasks collaboratively.",
      options: ["True", "False"],
      correctAnswer: "True",
      explanation: "AutoGen core abstraction is conversational agents that send messages to one another; tasks are solved through this multi-agent dialogue, optionally with human-in-the-loop participants.",
      hints: [
        "The Auto in AutoGen refers to automated multi-agent conversations.",
        "Consider a Coder agent and a Critic agent debating code quality as a concrete example.",
      ],
    },
    {
      id: "q-agent-kp8-3",
      type: "multiple-choice",
      difficulty: "hard",
      question: "What is a primary differentiator of CrewAI compared to LangGraph?",
      options: [
        "CrewAI only supports OpenAI models; LangGraph supports all providers.",
        "CrewAI uses a role-based abstraction (Agents with roles/goals/backstory) and structured crew orchestration rather than explicit graph definitions.",
        "CrewAI does not support tool use, while LangGraph does.",
        "CrewAI stores all state in a relational database by default.",
      ],
      correctAnswer: 1,
      explanation: "CrewAI abstracts agents as crew members with human-readable roles and goals, and crews are orchestrated via task assignments -- a higher-level API than LangGraph explicit graph construction.",
      hints: [
        "Think about the metaphor: a crew has roles like Captain and Navigator -- agents have roles like Researcher and Writer.",
        "LangGraph requires defining nodes and edges; CrewAI asks you to define agents and tasks.",
      ],
    },
    {
      id: "q-agent-kp8-4",
      type: "multiple-choice",
      difficulty: "medium",
      question: "What is a Semantic Kernel plugin in the context of LLM agent frameworks?",
      options: [
        "A kernel module that accelerates GPU inference for LLMs",
        "A collection of functions with natural language descriptions that the LLM can select and invoke as tools",
        "A database plugin for storing semantic embeddings",
        "A Python decorator that converts classes into LLM prompts",
      ],
      correctAnswer: 1,
      explanation: "In Microsoft Semantic Kernel, a plugin is a collection of functions (called skills) with annotated descriptions. The LLM planner reads these descriptions and selects which functions to call to complete a goal -- similar to OpenAI function calling but with a framework-native abstraction.",
      hints: [
        "The descriptions on plugin functions are what the LLM reads to decide which to invoke.",
        "Semantic Kernel originated at Microsoft and is used heavily in enterprise Azure AI deployments.",
      ],
    },
    {
      id: "q-agent-kp8-5",
      type: "true-false",
      difficulty: "medium",
      question: "DSPy compiles prompts by optimizing them based on few-shot examples and a metric, rather than requiring manual prompt engineering.",
      options: ["True", "False"],
      correctAnswer: "True",
      explanation: "DSPy (Khattab et al., 2023) treats prompts and few-shot examples as learnable parameters. Given a task metric and a small dataset, DSPy compilation automatically generates and optimizes prompts through a process analogous to gradient-based optimization but using discrete prompt search.",
      hints: [
        "Compilation in DSPy means automatically finding good prompts -- you define what to do, not how to prompt for it.",
        "This contrasts with manual prompt engineering where humans craft each prompt by hand.",
      ],
    },
    {
      id: "q-agent-kp8-6",
      type: "multiple-choice",
      difficulty: "hard",
      question: "The key architectural difference between LangChain (chains) and LangGraph (graphs) is:",
      options: [
        "LangChain supports more LLM providers than LangGraph",
        "LangChain executes steps linearly without branching or looping, while LangGraph supports arbitrary control flow including cycles and conditional branching",
        "LangGraph requires a dedicated server while LangChain runs locally",
        "LangChain uses LCEL syntax while LangGraph uses YAML",
      ],
      correctAnswer: 1,
      explanation: "LangChain chains are DAGs -- they execute steps in a defined order without cycles. Agent loops require cycles (observe -> decide -> act -> observe). LangGraph adds first-class cycle support via its graph abstraction, making it more suitable for agentic workflows that need to iterate.",
      hints: [
        "A chain cannot loop back to an earlier step; a graph with cycles can.",
        "The agent loop pattern (Thought -> Action -> Observation -> back to Thought) requires a cycle.",
      ],
    },
    {
      id: "q-agent-kp8-7",
      type: "multiple-choice",
      difficulty: "medium",
      question: "What is agent checkpointing in the context of agent frameworks like LangGraph?",
      options: [
        "Saving the LLM model weights at training checkpoints",
        "Persisting the agent state (graph node, memory, pending tasks) to storage so execution can be resumed after interruption",
        "Periodically measuring agent accuracy during a long run",
        "Limiting the agent to a checkpoint budget of N tool calls",
      ],
      correctAnswer: 1,
      explanation: "Checkpointing saves the full agent execution state (current graph node, accumulated memory, pending sub-tasks) to persistent storage. If the process crashes or is interrupted, the agent can resume from the last checkpoint rather than starting over.",
      hints: [
        "Think of it like a game save -- you can restore to a specific point if something goes wrong.",
        "For long-running agents (hours or days), checkpointing is essential for reliability.",
      ],
    },
    {
      id: "q-agent-kp8-8",
      type: "true-false",
      difficulty: "hard",
      question: "The OpenAI Assistants API with built-in tools (code interpreter, file search) provides more customization for tool logic than building a custom agent with the Chat Completions API.",
      options: ["True", "False"],
      correctAnswer: "False",
      explanation: "The Assistants API provides convenience with built-in tools but less customization -- the tool implementations (code interpreter, file search) are fixed by OpenAI. A custom agent via Chat Completions lets developers implement any tool logic, control sandboxing, integrate proprietary systems, and customize every aspect of execution.",
      hints: [
        "Convenience and customization are often in tension: managed services abstract away control.",
        "For enterprise use cases needing custom data sources or business logic, custom agents offer more flexibility.",
      ],
    },
    {
      id: "q-agent-kp8-9",
      type: "multiple-choice",
      difficulty: "hard",
      question: "AgentBench (Liu et al., 2023) evaluates LLM agents across multiple environments. What is a key finding from this benchmark?",
      options: [
        "All LLMs perform equally well across different agent task environments",
        "Strong chat model performance does not guarantee strong agent performance; coding and reasoning ability are more predictive",
        "Smaller models consistently outperform larger models in agentic tasks",
        "Tool use degrades performance compared to pure language generation",
      ],
      correctAnswer: 1,
      explanation: "AgentBench found significant variance across models and environments. Models that perform well on standard chat benchmarks do not necessarily perform well as agents. Coding ability and systematic reasoning showed the strongest correlation with agent performance across diverse environments.",
      hints: [
        "Chat ability measures fluency and instruction following; agent ability measures systematic multi-step problem solving.",
        "The benchmark spans operating system tasks, web navigation, database queries, and more.",
      ],
    },
  ],

  "code-agents": [
    {
      id: "q-agent-kp9-1",
      type: "multiple-choice",
      difficulty: "easy",
      question: "SWE-Bench is a benchmark for evaluating agents on:",
      options: [
        "Writing marketing copy for software products.",
        "Resolving real GitHub issues in open-source Python repositories.",
        "Generating unit tests from docstrings only.",
        "Benchmarking LLM inference speed on code completion.",
      ],
      correctAnswer: 1,
      explanation: "SWE-Bench tasks agents with fixing real bugs from GitHub issues in popular Python repos (e.g., scikit-learn, Django), measured by whether the patch passes the associated test suite.",
      hints: [
        "SWE stands for Software Engineering -- the benchmark is about real engineering tasks, not toy problems.",
        "Success is measured by test suite pass rates, not human evaluation.",
      ],
    },
    {
      id: "q-agent-kp9-2",
      type: "true-false",
      difficulty: "medium",
      question: "Code agents typically execute code in a sandboxed environment to prevent accidental damage to the host system.",
      options: ["True", "False"],
      correctAnswer: "True",
      explanation: "Sandboxing (via Docker containers, E2B, or similar) isolates code execution so agent-generated code cannot access sensitive host resources or cause irreversible side effects.",
      hints: [
        "Would you run unknown code directly on your laptop without any isolation?",
        "Think about how Jupyter notebooks or online code runners use isolated environments.",
      ],
    },
    {
      id: "q-agent-kp9-3",
      type: "multiple-choice",
      difficulty: "hard",
      question: "Which agent architecture has shown the strongest performance on SWE-Bench as of 2024?",
      options: [
        "Single-pass code generation with no tool use.",
        "Agents with file editing tools, test execution, and iterative error correction loops.",
        "Purely retrieval-based agents that find similar past patches.",
        "Agents that only generate diffs without running any code.",
      ],
      correctAnswer: 1,
      explanation: "Top SWE-Bench systems use an iterative agent loop: analyze the issue, edit a file, run tests, observe failures, reflect on errors, and revise. Test execution provides ground-truth binary feedback (pass/fail), enabling precise error correction that single-pass generation cannot achieve.",
      hints: [
        "A failed test gives precise error location and type -- far more actionable than a language critique.",
        "The SWE-agent paper found that file navigation (knowing which file to edit) is the hardest sub-problem.",
      ],
    },
    {
      id: "q-agent-kp9-4",
      type: "multiple-choice",
      difficulty: "medium",
      question: "Devin (Cognition AI) uses which iterative loop for code generation and debugging?",
      options: [
        "Generate code once, then submit for human review",
        "Edit code, run tests or commands, observe output, reflect on errors, repeat until passing",
        "Search for similar code online and adapt it without modification",
        "Generate 10 candidate solutions and select the highest-scoring one",
      ],
      correctAnswer: 1,
      explanation: "Devin operates on an Edit-Test-Reflect loop: it writes or modifies code, executes it in a sandboxed environment, reads the output (compiler errors, test failures, runtime exceptions), reflects on what went wrong, and applies a corrective edit. This continues iteratively until the task is complete.",
      hints: [
        "The loop mirrors how human developers work: write, run, debug, repeat.",
        "The reflection step is crucial -- it transforms raw error output into a corrective plan.",
      ],
    },
    {
      id: "q-agent-kp9-5",
      type: "true-false",
      difficulty: "medium",
      question: "Test-driven development (TDD) is a natural fit for code agents because failing tests provide unambiguous feedback signals for the agent to improve its code.",
      options: ["True", "False"],
      correctAnswer: "True",
      explanation: "TDD defines expected behavior via tests before writing implementation code. For code agents, this means the agent has an objective correctness signal (test pass/fail) rather than relying on subjective evaluation. The agent can iteratively improve its implementation guided purely by test results.",
      hints: [
        "Test output is binary and deterministic: pass or fail, with specific error messages.",
        "Compare this to getting feedback like the code looks mostly right -- much less actionable.",
      ],
    },
    {
      id: "q-agent-kp9-6",
      type: "multiple-choice",
      difficulty: "hard",
      question: "What is the key difference between MBPP and HumanEval as code generation benchmarks?",
      options: [
        "HumanEval uses Python; MBPP uses JavaScript",
        "HumanEval focuses on algorithmic problems with docstring specifications; MBPP contains simpler crowd-sourced programming tasks with test cases",
        "MBPP measures execution speed; HumanEval measures code correctness",
        "HumanEval is a multi-language benchmark; MBPP is Python only",
      ],
      correctAnswer: 1,
      explanation: "HumanEval (Chen et al., 2021) consists of 164 hand-crafted algorithmic problems with docstrings, covering data structures, string manipulation, and math. MBPP (Austin et al., 2021) contains 974 crowd-sourced simpler tasks. HumanEval problems tend to be harder and more algorithmic; MBPP covers broader but simpler programming tasks.",
      hints: [
        "HumanEval was created by OpenAI researchers; MBPP was created by Google Brain.",
        "Both use test-based evaluation (pass@k metric) but differ in problem difficulty and source.",
      ],
    },
    {
      id: "q-agent-kp9-7",
      type: "multiple-choice",
      difficulty: "hard",
      question: "Why is multi-file repository navigation a hard challenge for code agents?",
      options: [
        "Most code repositories are too large to fit in any context window",
        "The agent must identify which of potentially thousands of files is relevant to edit without being able to read all files simultaneously",
        "File system APIs are not available in sandboxed environments",
        "Code repositories use proprietary formats that LLMs cannot parse",
      ],
      correctAnswer: 1,
      explanation: "Real repositories contain thousands of files. The agent cannot read all of them in a single context. It must strategically navigate using file listings, grep-like search, import analysis, and code structure understanding to find which files are relevant to a bug or feature -- all while consuming minimal context budget.",
      hints: [
        "SWE-agent specifically designed shell tools for efficient file navigation: search, read ranges, jump to definitions.",
        "The localization problem (finding the right file) is often harder than the actual editing problem.",
      ],
    },
    {
      id: "q-agent-kp9-8",
      type: "true-false",
      difficulty: "hard",
      question: "PR-Pilot is an example of a code agent that operates directly on GitHub pull requests, reading diffs and repository context to generate automated code changes.",
      options: ["True", "False"],
      correctAnswer: "True",
      explanation: "PR-Pilot integrates with GitHub to read pull request diffs, repository structure, and issue context. It can generate code changes, write comments, and automate development workflows -- demonstrating how code agents can be embedded directly into existing developer toolchains.",
      hints: [
        "GitHub automation via LLM agents brings AI assistance into the existing developer workflow.",
        "Reading PR diffs requires understanding both the existing code and the proposed changes in context.",
      ],
    },
    {
      id: "q-agent-kp9-9",
      type: "multiple-choice",
      difficulty: "medium",
      question: "Which sandboxing approach provides the strongest isolation for running agent-generated code?",
      options: [
        "Running code in the same Python process as the agent with a try-except wrapper",
        "Running code in a separate Docker container or microVM with no host filesystem or network access",
        "Using a virtual environment (venv) to isolate Python packages",
        "Restricting code to a subset of Python builtins using an allowlist",
      ],
      correctAnswer: 1,
      explanation: "Docker containers or microVMs (e.g., Firecracker) provide OS-level isolation: the agent code runs in a separate kernel namespace with no access to host files, processes, or network unless explicitly granted. Virtual environments and allowlists are much weaker and can be bypassed.",
      hints: [
        "A venv isolates packages but shares the host kernel and filesystem -- not true isolation.",
        "E2B and similar sandbox services use microVMs for strong isolation with fast startup times.",
      ],
    },
  ],

  "computer-use-agents": [
    {
      id: "q-agent-kp10-1",
      type: "multiple-choice",
      difficulty: "easy",
      question: "Computer use agents perceive the state of a GUI primarily through:",
      options: [
        "Reading the application source code at runtime.",
        "Screenshots or accessibility tree representations of the screen.",
        "Network packet sniffing of application traffic.",
        "Accessing the application internal database directly.",
      ],
      correctAnswer: 1,
      explanation: "Computer use agents observe the UI via screenshots (pixel-level) or structured accessibility trees (element-level), which are then fed to a vision-capable LLM to decide on the next action.",
      hints: [
        "The agent needs to see the screen -- how does a multimodal model receive visual input?",
        "Accessibility APIs (like those for screen readers) provide structured element descriptions.",
      ],
    },
    {
      id: "q-agent-kp10-2",
      type: "true-false",
      difficulty: "medium",
      question: "Anthropic Claude computer use can directly execute arbitrary shell commands on the host machine without any human confirmation.",
      options: ["True", "False"],
      correctAnswer: "False",
      explanation: "Anthropic computer use tools are sandboxed and designed with safety guardrails; shell access, if exposed, requires explicit tool definitions by the developer, and Anthropic recommends human confirmation for irreversible actions.",
      hints: [
        "Consider what safe by default means for a system that can click buttons and type text.",
        "Tool access is always explicitly granted by the developer hosting the agent.",
      ],
    },
    {
      id: "q-agent-kp10-3",
      type: "multiple-choice",
      difficulty: "hard",
      question: "What is the main challenge of using pixel-based screenshots (vs. accessibility trees) for computer use agents?",
      options: [
        "Screenshots are larger files and cost more to transmit.",
        "Pixel-based observation requires visual grounding: precisely mapping UI elements to pixel coordinates for click/type actions.",
        "Accessibility trees cannot represent dynamic web content.",
        "Screenshot-based agents always require GPU acceleration on the host machine.",
      ],
      correctAnswer: 1,
      explanation: "Pixel grounding -- accurately identifying the (x, y) coordinates of a button or input field from a screenshot -- is a hard vision problem; small errors cause mis-clicks that break the task trajectory.",
      hints: [
        "Clicking requires knowing where exactly to click in pixel space, not just what to click.",
        "Accessibility trees give element positions for free; screenshots require the model to infer them.",
      ],
    },
    {
      id: "q-agent-kp10-4",
      type: "multiple-choice",
      difficulty: "medium",
      question: "WebArena is a benchmark for computer use agents that evaluates:",
      options: [
        "LLM performance on web development coding tasks",
        "Autonomous web navigation agents completing realistic tasks on live or simulated websites",
        "Web scraping speed and accuracy",
        "Browser rendering performance for LLM-generated HTML",
      ],
      correctAnswer: 1,
      explanation: "WebArena (Zhou et al., 2023) is a realistic web navigation benchmark with simulated replicas of websites (e-commerce, forum, code repository, CMS). Agents must complete tasks like searching for products, posting content, or navigating menus using browser actions.",
      hints: [
        "WebArena uses sandboxed copies of real web platforms so agents can act without affecting live sites.",
        "Tasks are evaluated by functional correctness (did the agent accomplish the goal?) not just action similarity.",
      ],
    },
    {
      id: "q-agent-kp10-5",
      type: "true-false",
      difficulty: "medium",
      question: "Mind2Web (Deng et al., 2023) demonstrated that web agents trained on one website generalize well to unseen websites with different layouts.",
      options: ["True", "False"],
      correctAnswer: "False",
      explanation: "Mind2Web revealed a significant generalization challenge: agents trained on specific websites struggle with unseen sites that have different DOM structures, element naming conventions, and visual layouts. Cross-website generalization remains an open research problem.",
      hints: [
        "A button called Submit on one site might be called Confirm or a checkmark icon on another.",
        "DOM structure variability across sites means models cannot memorize element locations.",
      ],
    },
    {
      id: "q-agent-kp10-6",
      type: "multiple-choice",
      difficulty: "hard",
      question: "What are the typical action primitives in a GUI agent action space?",
      options: [
        "Read, Write, Execute, Delete",
        "Click, Type, Scroll, Select, Navigate (back/forward), Screenshot",
        "GET, POST, PUT, DELETE (HTTP methods)",
        "Open, Close, Minimize, Maximize",
      ],
      correctAnswer: 1,
      explanation: "GUI agent action spaces are designed to mirror how humans interact with computers: Click (mouse button at coordinates), Type (keyboard input), Scroll (wheel events), Select (dropdown/option selection), Navigate (browser history), and Screenshot (observe current state). This minimal set covers most GUI interaction patterns.",
      hints: [
        "Think about what actions you take when using a computer -- nearly all reduce to these primitives.",
        "The action space design is a key engineering decision that determines what tasks the agent can complete.",
      ],
    },
    {
      id: "q-agent-kp10-7",
      type: "multiple-choice",
      difficulty: "medium",
      question: "What role do multimodal models like GPT-4V play in computer use agents?",
      options: [
        "They generate the GUI screenshots from text descriptions",
        "They process screenshot images to understand UI layout and element locations, enabling vision-based action selection",
        "They translate accessibility tree XML into natural language descriptions",
        "They fine-tune on screenshot-action pairs to learn mouse movements",
      ],
      correctAnswer: 1,
      explanation: "Multimodal models like GPT-4V can process screenshot images as visual input. In computer use agents, the screenshot is passed as an image token sequence to the model, which then identifies UI elements, understands their spatial relationships, and selects appropriate actions (e.g., click at button coordinates).",
      hints: [
        "Vision capability is what enables screenshot-based agents -- a text-only model cannot interpret pixel data.",
        "GPT-4V and Claude with vision can describe what they see in a screenshot and reason about actions.",
      ],
    },
    {
      id: "q-agent-kp10-8",
      type: "true-false",
      difficulty: "hard",
      question: "A computer use agent that mis-clicks on a wrong button can often recover without restarting the task from scratch.",
      options: ["True", "False"],
      correctAnswer: "True",
      explanation: "Modern computer use agents include error recovery mechanisms: after a mis-click, the agent takes a new screenshot, observes the unexpected state, and can take corrective actions (e.g., click the back button, close a dialog, or navigate to the correct page). Recovery is possible as long as the mis-click did not trigger an irreversible action like deleting data.",
      hints: [
        "The agent observes the screenshot after each action, so it can detect that its action had an unexpected effect.",
        "Irreversible actions (form submissions, file deletions) are the cases where mis-clicks cannot be easily recovered.",
      ],
    },
    {
      id: "q-agent-kp10-9",
      type: "multiple-choice",
      difficulty: "hard",
      question: "What is a key difference between web browser agents and desktop GUI agents?",
      options: [
        "Web agents can only read text; desktop agents can click and type",
        "Web agents operate on structured DOM elements with text identifiers, while desktop agents often face arbitrary pixel layouts with no structured element hierarchy",
        "Desktop agents are always faster because they avoid network latency",
        "Web agents require authentication; desktop agents do not",
      ],
      correctAnswer: 1,
      explanation: "Web browsers expose a Document Object Model (DOM) -- a structured tree of elements with IDs, class names, and text content that agents can query via JavaScript. Desktop applications (native apps, legacy software) often provide no such structure, forcing agents to rely purely on pixel-level visual grounding, which is harder.",
      hints: [
        "Querying the DOM gives you button text and location for free; a native app screenshot requires visual parsing.",
        "Accessibility APIs (MSAA, UI Automation on Windows) partially bridge this gap for desktop apps.",
      ],
    },
  ],
};

registerQuestions(questions);

export default questions;
