import type { Question } from '@/lib/curriculum'
import { registerQuestions } from '@/lib/questions'

const questions: Record<string, Question[]> = {
  // ── TREES ─────────────────────────────────────────────────────────────
  'binary-tree-inorder': [
    {
      id: 'q-bti-1',
      type: 'multiple-choice',
      difficulty: 'easy',
      question: 'Inorder traversal visits nodes in what order?',
      options: ['Root, left, right', 'Left, root, right', 'Left, right, root', 'Right, root, left'],
      correctAnswer: 1,
      explanation: 'Inorder: Left subtree → Root → Right subtree. For a BST, inorder traversal produces nodes in ascending sorted order.',
      hints: ['Remember: in-order = in sorted order for BST.', 'Mnemonic: Left, Root, Right.'],
    },
    {
      id: 'q-bti-2',
      type: 'multiple-choice',
      difficulty: 'easy',
      question: 'Inorder of BST with root=4, left=2, right=5, 2\'s children=1,3 yields:',
      options: ['[1,2,3,4,5]', '[4,2,5,1,3]', '[1,3,2,5,4]', '[5,4,3,2,1]'],
      correctAnswer: 0,
      explanation: 'Inorder of a BST always yields ascending sorted order: 1, 2, 3, 4, 5.',
      hints: ['For a BST, inorder = sorted ascending.'],
    },
    {
      id: 'q-bti-3',
      type: 'multiple-choice',
      difficulty: 'easy',
      question: 'Which traversal order visits Root first, then Left, then Right?',
      options: ['Inorder', 'Preorder', 'Postorder', 'Level order'],
      correctAnswer: 1,
      explanation: 'Preorder: Root → Left → Right. Useful for copying or serializing a tree.',
      hints: ['Pre = before. Root comes before subtrees.'],
    },
    {
      id: 'q-bti-4',
      type: 'multiple-choice',
      difficulty: 'medium',
      question: 'Iterative inorder traversal requires which data structure?',
      options: ['Queue', 'Explicit stack', 'Priority queue', 'Deque'],
      correctAnswer: 1,
      explanation: 'Instead of the implicit call stack, maintain an explicit stack. Push nodes while going left, pop to visit, then move to right child.',
      hints: ['Inorder is DFS. DFS uses a stack.'],
    },
    {
      id: 'q-bti-5',
      type: 'true-false',
      difficulty: 'medium',
      question: 'Inorder traversal of a BST can verify whether the tree is a valid BST.',
      options: ['True', 'False'],
      correctAnswer: 'True',
      explanation: 'If inorder produces a strictly increasing sequence, the tree is a valid BST. Compare each node with the previously visited node during traversal.',
      hints: ['A BST\'s inorder is sorted ascending. Track the previous value and check current > prev.'],
    },
    {
      id: 'q-bti-6',
      type: 'multiple-choice',
      difficulty: 'medium',
      question: 'What is the time complexity of iterative inorder traversal?',
      options: ['O(log n)', 'O(n)', 'O(n log n)', 'O(h) where h is height'],
      correctAnswer: 1,
      explanation: 'Every node is pushed and popped from the stack exactly once: O(n) time. Space: O(h) for the stack.',
      hints: ['Each node is visited exactly once.'],
    },
    {
      id: 'q-bti-7',
      type: 'multiple-choice',
      difficulty: 'hard',
      question: 'Morris inorder traversal achieves what complexities?',
      options: [
        'O(n log n) time, O(1) space',
        'O(n) time, O(1) space',
        'O(n) time, O(n) space',
        'O(n^2) time, O(1) space',
      ],
      correctAnswer: 1,
      explanation: 'Morris traversal threads right pointers temporarily (right pointer of inorder predecessor points to successor). No stack or recursion. O(n) time (each pointer modified at most twice), O(1) extra space.',
      hints: ['Morris traversal modifies the tree temporarily using the threaded binary tree concept.'],
    },
    {
      id: 'q-bti-8',
      type: 'multiple-choice',
      difficulty: 'hard',
      question: 'In Morris inorder traversal, when does the algorithm visit (output) a node?',
      options: [
        'When the node has no left child, or when returning via the threaded right pointer',
        'When both children are null',
        'Only when the node is a leaf',
        'When the right pointer is null',
      ],
      correctAnswer: 0,
      explanation: 'Visit when: (1) no left child — visit and go right, OR (2) the node is reached via the threaded right pointer from its inorder predecessor. In case 2, the thread is removed after visiting.',
      hints: ['The core insight: find the inorder predecessor, thread its right pointer, then detect the return.'],
    },
    {
      id: 'q-bti-9',
      type: 'true-false',
      difficulty: 'hard',
      question: 'Given both inorder and preorder traversal arrays of a binary tree with distinct values, you can uniquely reconstruct the original tree.',
      options: ['True', 'False'],
      correctAnswer: 'True',
      explanation: 'Preorder gives the root (first element). Find root in inorder — left subarray is left subtree, right subarray is right subtree. Recurse. This uniquely reconstructs the tree (LeetCode 105).',
      hints: ['Preorder tells you the root; inorder tells you the split between left and right subtrees.'],
    },
  ],

  'binary-tree-level-order': [
    {
      id: 'q-blo-1',
      type: 'multiple-choice',
      difficulty: 'easy',
      question: 'Level order traversal (BFS on a tree) uses which data structure?',
      options: ['Stack', 'Queue', 'Heap', 'Recursion only'],
      correctAnswer: 1,
      explanation: 'A queue ensures FIFO order so nodes are processed level by level, left to right. Enqueue root, then dequeue a node and enqueue its children repeatedly.',
      hints: ['BFS uses a queue. DFS uses a stack.'],
    },
    {
      id: 'q-blo-2',
      type: 'true-false',
      difficulty: 'easy',
      question: 'Level order traversal produces nodes in the same order as the LeetCode tree array representation.',
      options: ['True', 'False'],
      correctAnswer: 'True',
      explanation: 'The LeetCode array encodes nodes level by level, left to right — exactly the BFS order.',
      hints: ['Input [1,2,3,4,5] means root=1, children=2,3, grandchildren=4,5.'],
    },
    {
      id: 'q-blo-3',
      type: 'multiple-choice',
      difficulty: 'easy',
      question: 'For tree root=1, left=2, right=3, left.left=4, left.right=5 — level order grouped by level is:',
      options: ['[[1],[2,3],[4,5]]', '[[1],[3,2],[5,4]]', '[[4,5],[2,3],[1]]', '[[1,2,3,4,5]]'],
      correctAnswer: 0,
      explanation: 'Level 0: [1]. Level 1: [2,3]. Level 2: [4,5].',
      hints: ['Process level by level: root first, then root\'s children, etc.'],
    },
    {
      id: 'q-blo-4',
      type: 'multiple-choice',
      difficulty: 'medium',
      question: 'To get levels separately, you can:',
      options: ['Use two queues alternating per level', 'Track queue size before processing each level', 'Add a null sentinel after each level in the queue', 'All of the above'],
      correctAnswer: 3,
      explanation: 'All three approaches work. Recording queue size (B) is cleanest: at the start of each level, queue size equals the number of nodes at that level. Null sentinel (C) also works. Two queues (A) is more complex but correct.',
      hints: ['At the start of each level, queue contains exactly all nodes of that level.'],
    },
    {
      id: 'q-blo-5',
      type: 'multiple-choice',
      difficulty: 'medium',
      question: 'Zigzag level order alternates direction each level. What is the simplest implementation?',
      options: [
        'Use two stacks alternating per level',
        'Use deque, add to front vs back based on level parity',
        'Collect normally, then reverse odd-numbered levels',
        'B and C both work; A does not',
      ],
      correctAnswer: 2,
      explanation: 'Collecting left-to-right normally and then reversing odd levels (if level % 2 == 1) is the simplest correct approach.',
      hints: ['Even levels: left→right. Odd levels: right→left. Collect left→right then reverse odd.'],
    },
    {
      id: 'q-blo-6',
      type: 'multiple-choice',
      difficulty: 'medium',
      question: 'Time and space complexity of grouped level-order traversal:',
      options: [
        'O(n) time, O(1) space',
        'O(n) time, O(n) space',
        'O(n log n) time, O(n) space',
        'O(n^2) time, O(n) space',
      ],
      correctAnswer: 1,
      explanation: 'Each node enqueued/dequeued once: O(n) time. Queue holds at most one full level at a time — up to O(n) nodes for a complete binary tree\'s last level. Output also O(n).',
      hints: ['The widest level of a complete binary tree has n/2 nodes.'],
    },
    {
      id: 'q-blo-7',
      type: 'multiple-choice',
      difficulty: 'hard',
      question: 'Right side view of a binary tree using level-order traversal: take which node from each level?',
      options: ['First node', 'Last node', 'Rightmost leaf only', 'Middle node'],
      correctAnswer: 1,
      explanation: 'The last node processed at each level in left-to-right BFS is the rightmost visible node from the right.',
      hints: ['What is the last node you process at each depth in left-to-right BFS?'],
    },
    {
      id: 'q-blo-8',
      type: 'true-false',
      difficulty: 'hard',
      question: 'Level-order traversal grouped by level can be implemented recursively without an explicit queue.',
      options: ['True', 'False'],
      correctAnswer: 'True',
      explanation: 'A recursive DFS implementation passes a level parameter and appends to result[level]. This is DFS order but groups output by depth, producing the same result as BFS.',
      hints: ['Pass depth as a parameter. Append node.val to result[depth]. Pre-order DFS gives same level grouping.'],
    },
    {
      id: 'q-blo-9',
      type: 'multiple-choice',
      difficulty: 'hard',
      question: 'Maximum width of a binary tree (counting null gaps). The key insight for computing it efficiently is:',
      options: [
        'Width = number of non-null nodes in widest level',
        'Assign heap-style indices (left=2i, right=2i+1); width = rightmost_index - leftmost_index + 1',
        'Use two queues with sentinel values',
        'DFS and track column positions with a hash map',
      ],
      correctAnswer: 1,
      explanation: 'Assign indices as in a heap array: root=1, left child of i = 2i, right child = 2i+1. Width of a level = last_index - first_index + 1. Normalize per-level to prevent overflow.',
      hints: ['This maps the tree to a heap-style array. Width includes null gaps between leftmost and rightmost nodes.'],
    },
  ],

  'validate-bst': [
    {
      id: 'q-vbst-1',
      type: 'multiple-choice',
      difficulty: 'easy',
      question: 'Which of the following correctly defines a valid Binary Search Tree?',
      options: [
        'Left child < node and right child > node for each node',
        'All left descendants < node value AND all right descendants > node value',
        'Inorder traversal produces sorted array',
        'All of the above (all equivalent definitions)',
      ],
      correctAnswer: 3,
      explanation: 'All three conditions define BST validity. Inorder being sorted is a consequence of the BST property, not just an immediate-children constraint.',
      hints: ['The naive "left child < root < right child" is insufficient — it must hold for ALL descendants.'],
    },
    {
      id: 'q-vbst-2',
      type: 'multiple-choice',
      difficulty: 'easy',
      question: 'Why does the naive check (left.val < node.val < right.val for each node locally) fail for some trees?',
      options: [
        'It does not handle equal values',
        'A node in the right subtree could have a value smaller than the root even if it is locally valid',
        'The check is too slow',
        'It does not work for trees with height > 3',
      ],
      correctAnswer: 1,
      explanation: 'Example: root=10, left=5, right=15, right.left=3. Each node passes local check but 3 < 10 violates BST. The correct approach propagates min/max bounds.',
      hints: ['A node 3 in the right subtree of root 10 would pass local check but violate the global BST invariant.'],
    },
    {
      id: 'q-vbst-3',
      type: 'true-false',
      difficulty: 'easy',
      question: 'For BST validation, null nodes are considered valid.',
      options: ['True', 'False'],
      correctAnswer: 'True',
      explanation: 'Base case: null is a valid BST (vacuously satisfies all properties). Every recursive BST algorithm returns true for null nodes.',
      hints: ['An empty tree is a valid BST.'],
    },
    {
      id: 'q-vbst-4',
      type: 'multiple-choice',
      difficulty: 'medium',
      question: 'The bounds approach to BST validation passes (min, max) at each node. What is the initial call?',
      options: [
        'isValid(root, -Infinity, Infinity)',
        'isValid(root, 0, root.val)',
        'isValid(root, root.val, root.val)',
        'isValid(root, null, null)',
      ],
      correctAnswer: 0,
      explanation: 'Start with no constraints: any value is valid at the root. Recurse: left child gets (min, node.val), right child gets (node.val, max). At each node, check min < node.val < max.',
      hints: ['The root can be any value. Children get tighter constraints based on the parent.'],
    },
    {
      id: 'q-vbst-5',
      type: 'multiple-choice',
      difficulty: 'medium',
      question: 'When validating a BST using inorder traversal, what do you track?',
      options: [
        'The minimum value seen so far',
        'The previous node value — current must be strictly greater',
        'The tree height',
        'The sum of all node values',
      ],
      correctAnswer: 1,
      explanation: 'During inorder traversal, the sequence must be strictly increasing. Track the previously visited node\'s value (prev). If current.val <= prev, invalid BST.',
      hints: ['Inorder of BST is sorted ascending. Verify each step is strictly greater than the previous.'],
    },
    {
      id: 'q-vbst-6',
      type: 'multiple-choice',
      difficulty: 'medium',
      question: 'Time and space complexity of BST validation using bounds recursion:',
      options: [
        'O(n) time, O(1) space',
        'O(n) time, O(h) space where h is height',
        'O(n log n) time, O(n) space',
        'O(n^2) time, O(1) space',
      ],
      correctAnswer: 1,
      explanation: 'Every node visited once: O(n) time. Recursion stack depth = tree height: O(h) space. For balanced tree h = O(log n); for skewed tree h = O(n).',
      hints: ['You visit each node once. The recursion depth equals tree height.'],
    },
    {
      id: 'q-vbst-7',
      type: 'multiple-choice',
      difficulty: 'hard',
      question: 'BST validation must handle equal values. Typically, BST requires:',
      options: [
        'Duplicates placed in the right subtree (left < node <= right)',
        'No duplicates allowed (strictly less on left, strictly greater on right)',
        'Duplicates can go either left or right',
        'It depends on the problem statement',
      ],
      correctAnswer: 3,
      explanation: 'Standard definitions vary. LeetCode 98 (Validate BST) uses strict inequalities: left < node < right (no duplicates). Some BST definitions allow equal values in a specific subtree. Always read the problem constraints.',
      hints: ['LeetCode 98 uses strict inequalities. Real-world BSTs vary.'],
    },
    {
      id: 'q-vbst-8',
      type: 'true-false',
      difficulty: 'hard',
      question: 'Iterative BST validation using an explicit stack (simulating inorder traversal) uses O(h) space in the worst case.',
      options: ['True', 'False'],
      correctAnswer: 'True',
      explanation: 'The iterative inorder stack holds at most h nodes (the leftmost path from current node). For a balanced BST this is O(log n); for a skewed tree this is O(n) = O(h).',
      hints: ['The stack at any point holds the path from root to current node (going left).'],
    },
    {
      id: 'q-vbst-9',
      type: 'multiple-choice',
      difficulty: 'hard',
      question: 'You are given a sorted array and need to construct a height-balanced BST. The strategy is:',
      options: [
        'Insert elements left to right into an empty BST',
        'Pick the middle element as root, recursively build left from left-half and right from right-half',
        'Use a max-heap and heapify',
        'Pick the first element as root, then insert remaining',
      ],
      correctAnswer: 1,
      explanation: 'Picking the median as root ensures balanced height. Left half becomes left subtree, right half becomes right subtree. This gives height O(log n) and runs in O(n) time.',
      hints: ['The root of a balanced BST from sorted array should be the median.'],
    },
  ],

  'lowest-common-ancestor': [
    {
      id: 'q-lca-1',
      type: 'multiple-choice',
      difficulty: 'easy',
      question: 'The Lowest Common Ancestor (LCA) of two nodes p and q is:',
      options: [
        'The deepest node that is an ancestor of both p and q',
        'The root of the tree',
        'The parent of p',
        'The node immediately above q',
      ],
      correctAnswer: 0,
      explanation: 'The LCA is the deepest node having both p and q as descendants (a node is a descendant of itself).',
      hints: ['All ancestors of p, all ancestors of q — the deepest intersection is LCA.'],
    },
    {
      id: 'q-lca-2',
      type: 'true-false',
      difficulty: 'easy',
      question: 'If p is an ancestor of q, then LCA(p, q) = p.',
      options: ['True', 'False'],
      correctAnswer: 'True',
      explanation: 'If p is on the path from root to q, then p is the deepest common ancestor. A node is a descendant of itself.',
      hints: ['Draw p above q — the deepest common ancestor is p itself.'],
    },
    {
      id: 'q-lca-3',
      type: 'multiple-choice',
      difficulty: 'easy',
      question: 'In a BST, if p.val < root.val and q.val < root.val, where is the LCA?',
      options: ['At root', 'In the left subtree', 'In the right subtree', 'Cannot be determined'],
      correctAnswer: 1,
      explanation: 'Both p and q are less than root, so both are in the left subtree. The LCA must also be there — recurse left.',
      hints: ['BST: values less than root go left. Both p and q go left means LCA is in left subtree.'],
    },
    {
      id: 'q-lca-4',
      type: 'multiple-choice',
      difficulty: 'medium',
      question: 'BST LCA algorithm: when do you return the current node as LCA?',
      options: [
        'When either p or q equals current node',
        'When p is in the left subtree and q is in the right subtree (or vice versa)',
        'Only when current node equals the root',
        'When current node is greater than both p and q',
      ],
      correctAnswer: 1,
      explanation: 'If p.val < current.val < q.val (or the reverse), the two nodes are in different subtrees — current node is the LCA. Also if current.val == p.val or == q.val, that node is the LCA.',
      hints: ['Walk from root: if both values go same direction, recurse that way. If they split, current is LCA.'],
    },
    {
      id: 'q-lca-5',
      type: 'multiple-choice',
      difficulty: 'medium',
      question: 'General binary tree LCA recursive function — when both left and right recursive calls return non-null:',
      options: [
        'Return left result',
        'Return right result',
        'Return current node as LCA',
        'Return null',
      ],
      correctAnswer: 2,
      explanation: 'If left returns non-null (p or q found in left subtree) and right returns non-null (the other found in right subtree), current node is the LCA.',
      hints: ['p is in left subtree, q is in right subtree (or vice versa). Their LCA = current node.'],
    },
    {
      id: 'q-lca-6',
      type: 'multiple-choice',
      difficulty: 'medium',
      question: 'Time and space complexity of general binary tree LCA (recursive, no parent pointers):',
      options: [
        'O(log n) time, O(1) space',
        'O(n) time, O(h) space',
        'O(n) time, O(n) space',
        'O(n log n) time, O(log n) space',
      ],
      correctAnswer: 1,
      explanation: 'Every node visited at most once: O(n) time. Recursion depth = tree height h: O(h) space (O(log n) balanced, O(n) skewed).',
      hints: ['One DFS pass visits all n nodes; stack depth = height.'],
    },
    {
      id: 'q-lca-7',
      type: 'multiple-choice',
      difficulty: 'hard',
      question: 'Time complexity of LCA with parent pointers (hash set approach):',
      options: ['O(1)', 'O(log n)', 'O(h) where h is height', 'O(n^2)'],
      correctAnswer: 2,
      explanation: 'Walk p to root collecting ancestors in O(h). Walk q to root until hitting an ancestor in the set: O(h). Worst case h = n (skewed). Space O(h).',
      hints: ['Height of skewed tree is O(n). Balanced tree: O(log n).'],
    },
    {
      id: 'q-lca-8',
      type: 'multiple-choice',
      difficulty: 'hard',
      question: 'The Euler Tour + Sparse Table approach for LCA achieves:',
      options: [
        'O(n) preprocessing, O(n) query',
        'O(n log n) preprocessing, O(1) query',
        'O(n^2) preprocessing, O(log n) query',
        'O(log n) preprocessing, O(log n) query',
      ],
      correctAnswer: 1,
      explanation: 'Euler Tour flattens tree to 2n-1 nodes. Sparse Table on depths answers Range Minimum Queries in O(1). LCA = minimum-depth node on path between p and q in the Euler Tour.',
      hints: ['LCA = minimum-depth node on the Euler Tour path between two nodes.'],
    },
    {
      id: 'q-lca-9',
      type: 'true-false',
      difficulty: 'hard',
      question: 'The iterative LCA algorithm using two pointers (both start at p and q, advancing to parent, switching to other start when reaching null) works correctly even without computing heights explicitly.',
      options: ['True', 'False'],
      correctAnswer: 'True',
      explanation: 'Two pointers: pa starts at p, pb at q. Each step: advance to parent, or if null switch to the other starting node. They meet at LCA after traversing equal total path lengths (p_to_root + q_to_root). This is analogous to the linked list cycle detection trick.',
      hints: ['Same trick as "intersection of two linked lists" — both pointers travel equal total distance.'],
    },
  ],

  'insert-into-bst': [
    {
      id: 'q-ibst-1',
      type: 'multiple-choice',
      difficulty: 'easy',
      question: 'When inserting a value into a BST, if the value is less than the current node, you go:',
      options: ['Right subtree', 'Left subtree', 'Replace current node', 'Insert at root'],
      correctAnswer: 1,
      explanation: 'BST property: smaller values go left. Recurse left until finding a null position to insert.',
      hints: ['BST invariant: left < node < right.'],
    },
    {
      id: 'q-ibst-2',
      type: 'multiple-choice',
      difficulty: 'easy',
      question: 'Standard BST insertion always places the new node as:',
      options: ['The new root', 'An internal node', 'A leaf node', 'The left child of root'],
      correctAnswer: 2,
      explanation: 'Standard BST insertion traverses down until a null pointer — that null position becomes the new leaf.',
      hints: ['You traverse until you hit null. That null becomes the new leaf.'],
    },
    {
      id: 'q-ibst-3',
      type: 'true-false',
      difficulty: 'easy',
      question: 'Inserting n elements in sorted order (1, 2, 3, ...) into an empty BST produces a balanced tree.',
      options: ['True', 'False'],
      correctAnswer: 'False',
      explanation: 'Sorted insertion produces a skewed chain (degenerates to a linked list). Balanced BSTs require explicit rebalancing (AVL, Red-Black).',
      hints: ['What happens inserting 1, 2, 3, 4, 5 in order? Each becomes a right child.'],
    },
    {
      id: 'q-ibst-4',
      type: 'multiple-choice',
      difficulty: 'medium',
      question: 'Time complexity of BST insertion is:',
      options: ['O(1)', 'O(log n) always', 'O(h) where h is tree height', 'O(n) always'],
      correctAnswer: 2,
      explanation: 'Insertion follows one root-to-leaf path: O(h). Balanced tree: h = O(log n). Skewed tree: h = O(n). Average random data: O(log n).',
      hints: ['You traverse at most one path from root to leaf.'],
    },
    {
      id: 'q-ibst-5',
      type: 'multiple-choice',
      difficulty: 'medium',
      question: 'In a recursive BST insert that returns the (possibly new) root, the base case is:',
      options: [
        'root.val == val → return root',
        'root == null → return new TreeNode(val)',
        'root.left == null → insert left',
        'root.right == null → insert right',
      ],
      correctAnswer: 1,
      explanation: 'When we reach null, create a new TreeNode and return it. The caller links it as left or right child.',
      hints: ['Recursive pattern: root.left = insert(root.left, val) or root.right = insert(root.right, val).'],
    },
    {
      id: 'q-ibst-6',
      type: 'multiple-choice',
      difficulty: 'medium',
      question: 'Iterative BST insertion approach:',
      options: [
        'BFS until null node found, insert there',
        'Walk following BST property; when reaching a null child, set parent.left or parent.right',
        'Find the leftmost null and insert',
        'Always insert at the leftmost available position',
      ],
      correctAnswer: 1,
      explanation: 'Track current node and parent. Go left/right per BST rules. When current is null, set parent.left or parent.right to the new node.',
      hints: ['Track both current and parent. When current becomes null, link to parent.'],
    },
    {
      id: 'q-ibst-7',
      type: 'multiple-choice',
      difficulty: 'hard',
      question: 'BST deletion of a node with two children — what is the standard approach?',
      options: [
        'Remove the node and promote the left child',
        'Remove the node and promote the right child',
        'Replace the node\'s value with its inorder successor value, then delete that successor',
        'Split the tree into two separate BSTs',
      ],
      correctAnswer: 2,
      explanation: 'Find inorder successor (smallest in right subtree). Copy its value to current node. Recursively delete the successor (which has at most one child — it has no left child).',
      hints: ['Inorder successor = leftmost node in right subtree. After copying, delete it (simpler case).'],
    },
    {
      id: 'q-ibst-8',
      type: 'true-false',
      difficulty: 'hard',
      question: 'A balanced BST (AVL or Red-Black) guarantees O(log n) worst-case insertion.',
      options: ['True', 'False'],
      correctAnswer: 'True',
      explanation: 'AVL and Red-Black trees maintain balance through rotations after each insertion. Height is kept O(log n), guaranteeing O(log n) for insert, delete, and search.',
      hints: ['Rotations are O(1). At most O(log n) rotations needed per insert.'],
    },
    {
      id: 'q-ibst-9',
      type: 'multiple-choice',
      difficulty: 'hard',
      question: 'Which insertion sequence creates the most balanced BST from values {1,2,3,4,5,6,7}?',
      options: [
        'Sorted: 1,2,3,4,5,6,7',
        'Reverse sorted: 7,6,5,4,3,2,1',
        'Middle-out: 4,2,6,1,3,5,7',
        'Random order (expected balanced)',
      ],
      correctAnswer: 2,
      explanation: 'Inserting the median (4) first, then medians of each half recursively, creates a perfectly balanced BST of height 3. This is the pre-order of a balanced tree.',
      hints: ['What value should be root of a balanced BST containing 1-7? The median: 4.'],
    },
  ],

  'trie-prefix-tree': [
    {
      id: 'q-trie-1',
      type: 'multiple-choice',
      difficulty: 'easy',
      question: 'A Trie (prefix tree) is primarily optimized for:',
      options: [
        'Sorting numbers efficiently',
        'Storing and searching strings by prefix',
        'Finding shortest paths in graphs',
        'Balancing binary search trees',
      ],
      correctAnswer: 1,
      explanation: 'A Trie stores strings character by character. Common uses: autocomplete, spell-check, prefix search. Every root-to-marked-node path represents a stored word.',
      hints: ['The name "prefix tree" is a direct clue.'],
    },
    {
      id: 'q-trie-2',
      type: 'multiple-choice',
      difficulty: 'easy',
      question: 'In a standard Trie for lowercase English letters, each node\'s children array has how many slots?',
      options: ['10', '26', '52', '128'],
      correctAnswer: 1,
      explanation: 'One slot per letter a-z: 26 total. children[0] = \'a\', ..., children[25] = \'z\'.',
      hints: ['Lowercase English: a through z = 26 characters.'],
    },
    {
      id: 'q-trie-3',
      type: 'true-false',
      difficulty: 'easy',
      question: 'Inserting a word of length L into a Trie takes O(L) time regardless of how many words are already stored.',
      options: ['True', 'False'],
      correctAnswer: 'True',
      explanation: 'Each of L characters creates or traverses one node. Existing words share prefixes but do not slow insertion — we always visit exactly L nodes.',
      hints: ['You touch exactly one node per character: L characters = L nodes.'],
    },
    {
      id: 'q-trie-4',
      type: 'multiple-choice',
      difficulty: 'medium',
      question: 'How does a Trie distinguish a complete word from a prefix stored in the path?',
      options: [
        'Stores word length at the root node',
        'Each node has an isEnd (isWord) boolean flag set true at word endings',
        'Complete words are stored only at leaf nodes',
        'Word boundaries tracked in a separate hash set',
      ],
      correctAnswer: 1,
      explanation: 'isEnd=true on the last character\'s node marks a complete word. "app" and "apple" can both be stored with isEnd=true at their respective terminal nodes.',
      hints: ['"app" is a prefix of "apple" — the node for the second \'p\' must indicate it ends a word.'],
    },
    {
      id: 'q-trie-5',
      type: 'multiple-choice',
      difficulty: 'medium',
      question: 'startsWith("pre") vs. search("pre") in a Trie:',
      options: [
        'startsWith returns true only if "pre" is a stored complete word',
        'startsWith returns true if any stored word begins with "pre"; search requires "pre" to be a complete stored word',
        'They are identical',
        'search is faster because it stops earlier',
      ],
      correctAnswer: 1,
      explanation: 'startsWith("pre") = traverse p→r→e nodes, return true if all exist. search("pre") = same traversal + check isEnd=true at \'e\'.',
      hints: ['Distinguish prefix existence (startsWith) from complete word existence (search).'],
    },
    {
      id: 'q-trie-6',
      type: 'multiple-choice',
      difficulty: 'medium',
      question: 'Worst-case space complexity of a Trie storing n words of average length L with alphabet size A:',
      options: ['O(n)', 'O(n * L)', 'O(n * L * A)', 'O(A^L)'],
      correctAnswer: 2,
      explanation: 'Worst case (no shared prefixes): n * L nodes, each with A child pointers. O(n * L * A). In practice shared prefixes reduce this significantly.',
      hints: ['Each node stores A child pointers. Worst case: n words, each L nodes, no sharing.'],
    },
    {
      id: 'q-trie-7',
      type: 'multiple-choice',
      difficulty: 'hard',
      question: 'A compressed Trie (Patricia Trie / Radix Tree) differs from standard Trie by:',
      options: [
        'Storing only leaf nodes',
        'Merging chains of single-child nodes into one edge with a string label',
        'Using hash maps instead of arrays for children',
        'Only supporting prefix queries',
      ],
      correctAnswer: 1,
      explanation: 'Patricia Trie compresses long single-child chains into one edge labeled with the entire substring. Reduces O(total chars) nodes to O(number of keys) nodes.',
      hints: ['If a node has only one child, why not merge it with the parent edge?'],
    },
    {
      id: 'q-trie-8',
      type: 'true-false',
      difficulty: 'hard',
      question: 'A Trie can sort n strings of max length L in O(n * L) time.',
      options: ['True', 'False'],
      correctAnswer: 'True',
      explanation: 'Insert all strings O(n * L), then DFS pre-order collecting words at isEnd nodes. Children are ordered alphabetically (children[0]=\'a\', ...), so DFS yields lexicographic order.',
      hints: ['DFS on Trie visits characters alphabetically. Collecting isEnd nodes during DFS gives sorted strings.'],
    },
    {
      id: 'q-trie-9',
      type: 'multiple-choice',
      difficulty: 'hard',
      question: 'In Word Search II, using a Trie for the dictionary vs. a hash set allows:',
      options: [
        'Faster individual cell access in the grid',
        'Pruning DFS branches when the current path is not a prefix of any dictionary word',
        'Reducing grid traversal from O(mn) to O(log mn)',
        'Parallel searching from multiple starting cells',
      ],
      correctAnswer: 1,
      explanation: 'Advancing a Trie pointer during grid DFS lets us detect dead-ends early: if no child exists for the next character, no dictionary word can extend this path. Hash set requires full word completion before checking.',
      hints: ['The Trie tells you if the current prefix can lead to any dictionary word — enabling pruning.'],
    },
  ],

  'word-search-ii': [
    {
      id: 'q-ws2-1',
      type: 'multiple-choice',
      difficulty: 'easy',
      question: 'Word Search II (find all dictionary words in a 2D grid) uses which primary algorithm?',
      options: [
        'BFS from every cell',
        'DFS backtracking with a Trie for pruning',
        'Dynamic programming on grid cells',
        'Binary search on sorted words',
      ],
      correctAnswer: 1,
      explanation: 'DFS backtracking explores all paths in the grid. A Trie enables early pruning: if the current prefix is not in the Trie, backtrack immediately.',
      hints: ['Word Search I (single word) = DFS backtracking. Word Search II adds Trie for multiple words.'],
    },
    {
      id: 'q-ws2-2',
      type: 'true-false',
      difficulty: 'easy',
      question: 'In Word Search II, the same cell can be used multiple times within a single word path.',
      options: ['True', 'False'],
      correctAnswer: 'False',
      explanation: 'Each cell is used at most once per word path. Mark board[r][c] = \'#\' before recursing, restore after backtracking.',
      hints: ['You must mark cells visited to avoid using them twice in one path.'],
    },
    {
      id: 'q-ws2-3',
      type: 'multiple-choice',
      difficulty: 'easy',
      question: 'The four directions explored from cell (r, c) in Word Search II are:',
      options: [
        '(r-1,c), (r+1,c), (r,c-1), (r,c+1)',
        '(r-1,c-1), (r-1,c+1), (r+1,c-1), (r+1,c+1)',
        '(r-2,c), (r+2,c), (r,c-2), (r,c+2)',
        '(r-1,c) and (r,c+1) only',
      ],
      correctAnswer: 0,
      explanation: 'Only horizontal and vertical neighbors (up, down, left, right) — not diagonals. Words are formed by sequentially adjacent cells sharing an edge.',
      hints: ['Adjacent = sharing an edge, not a corner.'],
    },
    {
      id: 'q-ws2-4',
      type: 'multiple-choice',
      difficulty: 'medium',
      question: 'After finding a word during DFS, how do you prevent reporting duplicates?',
      options: [
        'Use a separate visited set for found words',
        'Set the Trie node\'s isEnd = false after recording the word',
        'Stop the entire DFS immediately',
        'Filter duplicates at the end with a hash set',
      ],
      correctAnswer: 1,
      explanation: 'Setting isEnd = false prevents finding the same word via a different path. More efficient than post-processing deduplication.',
      hints: ['The Trie marks word boundaries. Clear isEnd once found to skip future re-findings.'],
    },
    {
      id: 'q-ws2-5',
      type: 'multiple-choice',
      difficulty: 'medium',
      question: 'What is the time complexity of the Trie-based Word Search II solution?',
      options: [
        'O(m * n * 4^L) where L = max word length (independent of dictionary size W)',
        'O(W * m * n)',
        'O(m * n * L * W)',
        'O(4^(m*n))',
      ],
      correctAnswer: 0,
      explanation: 'With the Trie, one DFS from each cell branches only where Trie has children. Total: O(m * n * 4^L). Building Trie: O(W * L). Key win: all words searched simultaneously.',
      hints: ['The Trie replaces W independent word searches with one simultaneous search.'],
    },
    {
      id: 'q-ws2-6',
      type: 'multiple-choice',
      difficulty: 'medium',
      question: 'What prevents the DFS from revisiting the same cell within a single word path?',
      options: [
        'A global visited array reset between each starting cell',
        'Temporarily replacing board[r][c] with sentinel \'#\' and restoring after recursion',
        'Only allowing moves right and down',
        'Checking if cell index is in the recursion stack explicitly',
      ],
      correctAnswer: 1,
      explanation: 'Set board[r][c] = \'#\' before recursing (prevents children from revisiting). Restore board[r][c] = originalChar after backtracking. O(1) in-place marking.',
      hints: ['Classic backtracking pattern: modify → recurse → undo.'],
    },
    {
      id: 'q-ws2-7',
      type: 'multiple-choice',
      difficulty: 'hard',
      question: 'Pruning Trie nodes after finding a word (removing empty branches) helps because:',
      options: [
        'It reduces memory usage only',
        'Future DFS calls skip dead Trie branches immediately, reducing work',
        'It improves Trie construction time',
        'It is required for correctness (without it duplicates occur)',
      ],
      correctAnswer: 1,
      explanation: 'Once a word is found and its Trie node has no remaining word endings below it, pruning that branch prevents future DFS calls from traversing into it. This optimization is significant when many words share prefixes.',
      hints: ['Dead branches = nodes with no words left. No reason to traverse them. Pruning prevents it.'],
    },
    {
      id: 'q-ws2-8',
      type: 'true-false',
      difficulty: 'hard',
      question: 'Storing complete word strings in Trie leaf nodes (instead of reconstructing during DFS) is a valid optimization.',
      options: ['True', 'False'],
      correctAnswer: 'True',
      explanation: 'Storing the word string in the Trie node allows O(1) retrieval when found. Without it, you reconstruct the path character by character during DFS backtracking (O(L) per match).',
      hints: ['Reconstruction requires building the string as you backtrack. Storing it at the node avoids this.'],
    },
    {
      id: 'q-ws2-9',
      type: 'multiple-choice',
      difficulty: 'hard',
      question: 'Brute force Word Search II (run Word Search I per dictionary word) has complexity:',
      options: [
        'O(W * m * n * 4^L)',
        'O(m * n * 4^L)',
        'O(W * L * m * n)',
        'O(W * (m * n)^2)',
      ],
      correctAnswer: 0,
      explanation: 'For each of W words: DFS from each of m*n cells, branching up to 4 directions for L steps. Per word: O(m * n * 4^L). Total: O(W * m * n * 4^L). Trie approach eliminates the W multiplier.',
      hints: ['Brute force = Word Search I run W times independently.'],
    },
  ],
}

registerQuestions(questions)
