import type { Question } from '@/lib/curriculum'
import { registerQuestions } from '@/lib/questions'

const questions: Record<string, Question[]> = {
  'climbing-stairs': [
    {
      id: 'q-cs-1',
      type: 'multiple-choice',
      difficulty: 'easy',
      question: 'Climbing 1 or 2 steps at a time, ways to reach step n follows:',
      options: ['Fibonacci', 'Factorial', 'Binary', 'Harmonic'],
      correctAnswer: 0,
      explanation: 'dp[i] = dp[i-1] + dp[i-2]. Same recurrence as Fibonacci. dp[1]=1, dp[2]=2.',
    },
    {
      id: 'q-cs-2',
      type: 'multiple-choice',
      difficulty: 'easy',
      question: 'Ways to climb 4 steps:',
      options: ['4', '5', '6', '7'],
      correctAnswer: 1,
      explanation: 'dp[1]=1, dp[2]=2, dp[3]=3, dp[4]=5. Sequences: (1,1,1,1), (1,1,2), (1,2,1), (2,1,1), (2,2).',
    },
    {
      id: 'q-cs-3',
      type: 'true-false',
      difficulty: 'medium',
      question: 'dp[i] = dp[i-1] + dp[i-2] for i >= 3.',
      correctAnswer: 'true',
      explanation: 'From step i, last move was either 1 step (from i-1) or 2 steps (from i-2). Sum both ways.',
    },
    {
      id: 'q-cs-4',
      type: 'multiple-choice',
      difficulty: 'medium',
      question: 'Time complexity with memoization:',
      options: ['O(1)', 'O(n)', 'O(n²)', 'O(2ⁿ)'],
      correctAnswer: 1,
      explanation: 'Each subproblem dp[i] computed once. n subproblems × O(1) each = O(n) total.',
    },
    {
      id: 'q-cs-5',
      type: 'multiple-choice',
      difficulty: 'hard',
      question: 'If you can climb 1, 2, or 3 steps, dp[4] = ?',
      options: ['5', '6', '7', '8'],
      correctAnswer: 2,
      explanation: 'dp[1]=1, dp[2]=2, dp[3]=4 (1+2+3 or 1+1+2 or 1+1+1+1 or 2+2 or 3+1). dp[4]=dp[3]+dp[2]+dp[1]=4+2+1=7.',
    },
    {
      id: 'q-cs-6',
      type: 'multiple-choice',
      difficulty: 'hard',
      question: 'Space optimization for climbing stairs uses:',
      options: ['O(n) array', 'O(1) two variables', 'O(log n) space', 'O(n log n)'],
      correctAnswer: 1,
      explanation: 'Only need previous two values. Keep prev1 and prev2, update iteratively. O(1) space.',
    },
  ],

  'coin-change': [
    {
      id: 'q-cc-1',
      type: 'multiple-choice',
      difficulty: 'medium',
      question: 'Coin change (minimum coins) recurrence:',
      options: ['dp[i] = min(dp[i], dp[i-coin] + 1)', 'dp[i] = dp[i-coin] + 1', 'dp[i] = max(dp[i], dp[i-coin] + 1)', 'dp[i] = coin count'],
      correctAnswer: 0,
      explanation: 'For each coin, try using it: dp[i] = min(dp[i], dp[i-coin] + 1). Initialize dp[0]=0, others=∞.',
    },
    {
      id: 'q-cc-2',
      type: 'multiple-choice',
      difficulty: 'medium',
      question: 'For coins [1,2,5] and amount=11, minimum coins:',
      options: ['2', '3', '5', '11'],
      correctAnswer: 1,
      explanation: '11 = 5 + 5 + 1 (3 coins). Could also do 2+2+2+2+2+1 = 6 coins. Best is 3.',
    },
    {
      id: 'q-cc-3',
      type: 'true-false',
      difficulty: 'easy',
      question: 'dp[i] represents minimum coins to make amount i.',
      correctAnswer: 'true',
      explanation: 'Tabular DP: dp[j] = min coins for amount j. dp[0] = 0 (base case).',
    },
    {
      id: 'q-cc-4',
      type: 'multiple-choice',
      difficulty: 'hard',
      question: 'If amount cannot be formed, dp[amount] equals:',
      options: ['0', '-1', 'Infinity (represented as amount+1)', 'amount'],
      correctAnswer: 2,
      explanation: 'Use amount+1 as "infinity" sentinel. Final check: if dp[amount] > amount, return -1 (impossible).',
    },
    {
      id: 'q-cc-5',
      type: 'multiple-choice',
      difficulty: 'hard',
      question: 'Unbounded coin change time complexity:',
      options: ['O(amount)', 'O(amount × coins)', 'O(coins)', 'O(2^amount)'],
      correctAnswer: 1,
      explanation: 'Outer loop over amounts (1 to target), inner loop over coins. O(amount × len(coins)).',
    },
  ],

  'house-robber': [
    {
      id: 'q-hr-1',
      type: 'multiple-choice',
      difficulty: 'medium',
      question: 'House Robber recurrence:',
      options: ['dp[i] = max(dp[i-1], dp[i-2] + nums[i])', 'dp[i] = dp[i-1] + nums[i]', 'dp[i] = min(dp[i-1], dp[i-2] + nums[i])', 'dp[i] = nums[i] + nums[i-1]'],
      correctAnswer: 0,
      explanation: 'At house i, either skip (dp[i-1]) or rob (dp[i-2] + nums[i]). Take max.',
    },
    {
      id: 'q-hr-2',
      type: 'multiple-choice',
      difficulty: 'medium',
      question: 'For nums=[2,7,9,3,1], max robbed:',
      options: ['10', '11', '12', '13'],
      correctAnswer: 2,
      explanation: 'Rob houses 0,2,4: 2+9+1=12. Or 1,3: 7+3=10. 12 is optimal.',
    },
    {
      id: 'q-hr-3',
      type: 'true-false',
      difficulty: 'easy',
      question: 'Cannot rob adjacent houses means circular adjacency for House Robber II.',
      correctAnswer: 'true',
      explanation: 'House Robber II: houses form circle. Solution: max(rob[0..n-2], rob[1..n-1]). Exclude first or last house.',
    },
    {
      id: 'q-hr-4',
      type: 'multiple-choice',
      difficulty: 'hard',
      question: 'Space optimized House Robber uses:',
      options: ['O(n) array', 'O(1) two variables', 'O(log n) stack', 'O(1) single variable'],
      correctAnswer: 1,
      explanation: 'Only need prev1 = dp[i-1] and prev2 = dp[i-2]. Update iteratively. O(1) space.',
    },
    {
      id: 'q-hr-5',
      type: 'multiple-choice',
      difficulty: 'hard',
      question: 'Base cases for House Robber:',
      options: ['dp[0]=0', 'dp[1]=nums[0]', 'Both A and B', 'dp[0]=nums[0], dp[1]=max(nums[0],nums[1])'],
      correctAnswer: 3,
      explanation: 'dp[0]=nums[0] (only house 0). dp[1]=max(nums[0], nums[1]) (rob house 0 or house 1, not both).',
    },
  ],

  'longest-increasing-subsequence': [
    {
      id: 'q-lis-1',
      type: 'multiple-choice',
      difficulty: 'medium',
      question: 'LIS binary search approach time complexity:',
      options: ['O(n²)', 'O(n log n)', 'O(n)', 'O(log n)'],
      correctAnswer: 1,
      explanation: 'dp[i] = length of LIS ending at i. Binary search to find position in sorted tails array. O(n log n).',
    },
    {
      id: 'q-lis-2',
      type: 'multiple-choice',
      difficulty: 'medium',
      question: 'For [10,9,2,5,3,7,101,18], LIS length:',
      options: ['3', '4', '5', '6'],
      correctAnswer: 1,
      explanation: 'LIS = [2,3,7,101] or [2,3,7,18]. Length 4.',
    },
    {
      id: 'q-lis-3',
      type: 'true-false',
      difficulty: 'easy',
      question: 'LIS strictly increasing means equal elements do not count.',
      correctAnswer: 'true',
      explanation: 'Strictly increasing subsequence requires each element > previous. Equal elements form non-increasing.',
    },
    {
      id: 'q-lis-4',
      type: 'multiple-choice',
      difficulty: 'hard',
      question: 'Binary search in LIS uses:',
      options: ['Stack', 'Binary indexed tree', 'Sorted array of tails', 'Heap'],
      correctAnswer: 2,
      explanation: 'tails[i] = smallest ending value of LIS of length i+1. Binary search to find position to replace.',
    },
    {
      id: 'q-lis-5',
      type: 'multiple-choice',
      difficulty: 'hard',
      question: 'To reconstruct LIS, you need:',
      options: ['Just tails array', 'Parent tracking array', 'Both tails and predecessor', 'Original array only'],
      correctAnswer: 2,
      explanation: 'Track predecessor index for each element. When updating tails, record prev[i]. Backtrack from last element to reconstruct.',
    },
  ],

  'word-break': [
    {
      id: 'q-wb-1',
      type: 'multiple-choice',
      difficulty: 'medium',
      question: 'Word Break recurrence:',
      options: ['dp[i] = OR(dp[j] AND wordDict contains s[j:i])', 'dp[i] = AND(dp[j] AND wordDict)', 'dp[i] = wordDict.contains(s[0:i])', 'dp[i] = dp[i-1]'],
      correctAnswer: 0,
      explanation: 'dp[i] true if exists j < i where dp[j] true AND substring s[j:i] is in wordDict.',
    },
    {
      id: 'q-wb-2',
      type: 'multiple-choice',
      difficulty: 'medium',
      question: '"leetcode" with wordDict=["leet","code"] is:',
      options: ['True', 'False', 'Depends on order', 'Cannot determine'],
      correctAnswer: 0,
      explanation: '"leet" + "code" = "leetcode". dp[4]=true (leet), dp[8]=dp[4] AND contains(code)=true.',
    },
    {
      id: 'q-wb-3',
      type: 'true-false',
      difficulty: 'medium',
      question: 'Using trie can optimize word break dictionary lookup.',
      correctAnswer: 'true',
      explanation: 'Trie allows O(m) lookup for each substring starting at position j, where m is max word length.',
    },
    {
      id: 'q-wb-4',
      type: 'multiple-choice',
      difficulty: 'hard',
      question: 'DP solution time complexity:',
      options: ['O(n)', 'O(n²)', 'O(n × maxWordLength)', 'O(2ⁿ)'],
      correctAnswer: 2,
      explanation: 'For each i, try up to maxWordLength substrings. O(n × L) where L = max word length.',
    },
    {
      id: 'q-wb-5',
      type: 'multiple-choice',
      difficulty: 'hard',
      question: 'Without DP, recursive approach with memoization solves by:',
      options: ['Top-down from index 0', 'Bottom-up from n to 0', 'Binary search', 'Two pointers'],
      correctAnswer: 0,
      explanation: 'Memoized recursion: from position i, try all possible words starting at i. If any returns true, memoize and return true.',
    },
  ],

}

registerQuestions(questions)
