import type { Question } from '@/lib/curriculum'
import { registerQuestions } from '@/lib/questions'

const questions: Record<string, Question[]> = {
  // ── TREES ─────────────────────────────────────────────────────────────
  'binary-tree-inorder': [
    {
      id: 'q-bti-1',
      type: 'multiple-choice',
      difficulty: 'easy',
      question: 'Inorder traversal visits:',
      options: ['Root, left, right', 'Left, root, right', 'Left, right, root', 'Right, root, left'],
      correctAnswer: 1,
      explanation: 'Inorder: Left subtree → Root → Right subtree. For BST, gives sorted order.',
    },
    {
      id: 'q-bti-2',
      type: 'multiple-choice',
      difficulty: 'easy',
      question: 'Inorder of BST [4,2,5,1,3] yields:',
      options: ['[1,2,3,4,5]', '[4,2,5,1,3]', '[1,3,2,5,4]', '[5,4,3,2,1]'],
      correctAnswer: 0,
      explanation: 'Inorder of BST is ascending sorted order: left → root → right.',
    },
    {
      id: 'q-bti-3',
      type: 'multiple-choice',
      difficulty: 'medium',
      question: 'Recursive inorder uses what kind of traversal?',
      options: ['DFS', 'BFS', 'Level order', 'Spiral'],
      correctAnswer: 0,
      explanation: 'Inorder traversal recursively visits left, root, right. This is depth-first (vs BFS which is level-order).',
    },
    {
      id: 'q-bti-4',
      type: 'true-false',
      difficulty: 'medium',
      question: 'Iterative inorder requires explicit stack.',
      correctAnswer: 'true',
      explanation: 'Instead of call stack, maintain explicit stack. Go left until null, pop, visit, go right.',
    },
    {
      id: 'q-bti-5',
      type: 'multiple-choice',
      difficulty: 'hard',
      question: 'Morris inorder traversal achieves:',
      options: ['O(n log n) time, O(1) space', 'O(n) time, O(1) space', 'O(n) time, O(n) space', 'O(n²) time, O(1) space'],
      correctAnswer: 1,
      explanation: 'Morris threads the tree temporarily to traverse without stack or recursion. O(n) time, O(1) space.',
    },
  ],

  'binary-tree-level-order': [
    {
      id: 'q-blo-1',
      type: 'multiple-choice',
      difficulty: 'easy',
      question: 'Level order traversal uses:',
      options: ['Stack', 'Queue', 'Heap', 'Recursion only'],
      correctAnswer: 1,
      explanation: 'Queue ensures nodes are visited level by level (left to right). BFS pattern.',
    },
    {
      id: 'q-blo-2',
      type: 'multiple-choice',
      difficulty: 'medium',
      question: 'To get levels separately, you can:',
      options: ['Use two queues', 'Track queue size per level', 'Both A and B', 'Use stack'],
      correctAnswer: 2,
      explanation: 'Option 1: swap queues when empty. Option 2: record size before processing each level.',
    },
    {
      id: 'q-blo-3',
      type: 'true-false',
      difficulty: 'easy',
      question: 'Zigzag level order alternates direction each level.',
      correctAnswer: 'true',
      explanation: 'Level 0: left→right, Level 1: right→left, etc. Use deque or simple flag to reverse.',
    },
    {
      id: 'q-blo-4',
      type: 'multiple-choice',
      difficulty: 'medium',
      question: 'For tree with root=1, children 2,3, children of 2 are 4,5, level order is:',
      options: ['[1,2,3,4,5]', '[1,3,2,5,4]', '[4,5,2,3,1]', '[1,2,3,5,4]'],
      correctAnswer: 0,
      explanation: 'Level 0: [1], Level 1: [2,3], Level 2: [4,5]. BFS processes level by level.',
    },
    {
      id: 'q-blo-5',
      type: 'multiple-choice',
      difficulty: 'hard',
      question: 'Time complexity of level order traversal:',
      options: ['O(n²)', 'O(n)', 'O(log n)', 'O(n log n)'],
      correctAnswer: 1,
      explanation: 'Each node visited exactly once. Queue operations are O(1) amortized. Total O(n).',
    },
  ],

  'validate-bst': [
    {
      id: 'q-vbst-1',
      type: 'multiple-choice',
      difficulty: 'medium',
      question: 'Valid BST means:',
      options: ['Left < root < right for each node', 'All left descendants < root, all right descendants > root', 'Inorder produces sorted array', 'All of the above'],
      correctAnswer: 3,
      explanation: 'All conditions define BST validity. Inorder being sorted is a consequence, not the definition.',
    },
    {
      id: 'q-vbst-2',
      type: 'multiple-choice',
      difficulty: 'hard',
      question: 'The naive check (left < node < right) fails for:',
      options: ['[10,5,15,null,null,12,20]', '[5,3,7,1,4,6,8]', '[10,5,15,3,7,12,20] with wrong subtree values', '[1,2,3]'],
      correctAnswer: 2,
      explanation: 'Node 3 is in right subtree of 10 but 3 < 10 violates BST. Naive check only looks at immediate children.',
    },
    {
      id: 'q-vbst-3',
      type: 'multiple-choice',
      difficulty: 'hard',
      question: 'Correct approach uses:',
      options: ['Single bounds [min,max]', 'Inorder traversal', 'Both single bounds and inorder', 'Post-order only'],
      correctAnswer: 2,
      explanation: 'Both work. Bounds: recursively pass (min,max). Inorder: check array is sorted after traversal.',
    },
    {
      id: 'q-vbst-4',
      type: 'true-false',
      difficulty: 'medium',
      question: 'For BST validation, null nodes are valid.',
      correctAnswer: 'true',
      explanation: 'Base case: null is a valid BST (vacuously satisfies properties).',
    },
    {
      id: 'q-vbst-5',
      type: 'multiple-choice',
      difficulty: 'hard',
      question: 'Inorder traversal can detect BST in one pass using:',
      options: ['Previous value comparison', 'Current min check', 'Both A and B', 'Binary search'],
      correctAnswer: 2,
      explanation: 'During inorder, compare current node with previous. If prev >= current, not BST. Track previous node value.',
    },
  ],

  'lowest-common-ancestor': [
    {
      id: 'q-lca-1',
      type: 'multiple-choice',
      difficulty: 'medium',
      question: 'LCA of nodes p and q is:',
      options: ['Deepest node containing both', 'Node that has p and q in different subtrees', 'Both definitions equivalent', 'Node closest to p'],
      correctAnswer: 2,
      explanation: 'Both definitions are equivalent for binary trees. Deepest containing both = node with p and q in separate subtrees.',
    },
    {
      id: 'q-lca-2',
      type: 'true-false',
      difficulty: 'easy',
      question: 'If p is ancestor of q, LCA is p.',
      correctAnswer: 'true',
      explanation: 'p is on path from root to q. p is the deepest node containing both p and q.',
    },
    {
      id: 'q-lca-3',
      type: 'multiple-choice',
      difficulty: 'hard',
      question: 'For BST, LCA of p=3, q=7 in tree root=5, left=3, right=7:',
      options: ['3', '5', '7', '4'],
      correctAnswer: 1,
      explanation: 'BST property: 3 < 5 < 7. 5 is the first node where p and q are in different subtrees.',
    },
    {
      id: 'q-lca-4',
      type: 'multiple-choice',
      difficulty: 'hard',
      question: 'General binary tree LCA without parent pointers uses:',
      options: ['Two passes', 'Single DFS recursion', 'Two DFS recursions', 'Stack only'],
      correctAnswer: 1,
      explanation: 'One traversal: return p if found in left/right, return q if found, return node if both found in different subtrees.',
    },
    {
      id: 'q-lca-5',
      type: 'multiple-choice',
      difficulty: 'hard',
      question: 'Time complexity of LCA with parent pointers (using hash set):',
      options: ['O(1)', 'O(log n)', 'O(n)', 'O(n) with O(n) space'],
      correctAnswer: 3,
      explanation: 'Collect ancestors of p in set O(n), traverse from q upward until finding ancestor in set O(n). Total O(n) time, O(n) space.',
    },
  ],
}

registerQuestions(questions)
