import type { Question } from "@/lib/curriculum";

const questions: Record<string, Question[]> = {
  // ── cv-kp-26: Robustness & Adversarial Examples ───────────────────────────
  "robustness-cv": [
    {
      id: "q-cv-kp26-1",
      type: "multiple-choice",
      difficulty: "easy",
      question: "What is an adversarial example in computer vision?",
      options: [
        "A training image with an incorrect label that misleads the model during training.",
        "An image with carefully crafted, imperceptible perturbations that cause a classifier to predict the wrong class.",
        "An image from a different domain (e.g., sketches) that the model fails to classify correctly.",
        "A synthetic image generated by a GAN that fools a human observer.",
      ],
      correctAnswer: 1,
      explanation:
        "Adversarial examples are inputs with small, often human-imperceptible pixel perturbations intentionally crafted to maximise the model's loss.\n\n**Step 1.** The perturbation is chosen via gradient-based optimisation to specifically fool the model, not just add random noise.\n\n**Step 2.** A classic example: an image of a cat to which an imperceptible adversarial perturbation is added, causing a classifier to confidently predict \"guacamole\" instead of \"cat\".\n\n**Step 3.** This reveals that deep networks are linear in high-dimensional spaces — small input changes (amplified by many layers) can cause large output changes.",
      hints: [
        "The perturbation is chosen to specifically fool the model, not just add random noise.",
        'A human sees a cat; the model confidently predicts "guacamole" — what caused this?',
      ],
    },
    {
      id: "q-cv-kp26-2",
      type: "multiple-choice",
      difficulty: "medium",
      question:
        "What is the key insight of the SRCNN (Super-Resolution CNN) approach for image super-resolution?",
      options: [
        "It uses GAN training to generate photorealistic textures in upscaled images.",
        "It learns an end-to-end mapping from low-resolution to high-resolution images using a CNN with convolutional, non-linear mapping, and reconstruction layers.",
        "It applies a frequency-domain upsampling using learned DCT coefficients.",
        "It retrieves high-frequency patches from a database to augment low-resolution inputs.",
      ],
      correctAnswer: 1,
      explanation:
        "SRCNN (Super-Resolution CNN, Dong et al. 2015) pioneers deep learning for single-image super-resolution.\n\n**Step 1.** The method takes a bicubic-upsampled low-resolution image as input and learns to refine it into a high-resolution output.\n\n**Step 2.** The three-layer CNN performs patch extraction (feature extraction), non-linear mapping (mapping features to HR patches), and reconstruction.\n\n**Step 3.** SRCNN outperformed classical sparse-coding methods while being conceptually simpler — an end-to-end learned mapping rather than a hand-crafted pipeline.",
      hints: [
        "Before deep learning, super-resolution used sparse coding with hand-crafted dictionaries — how does SRCNN differ?",
        "An end-to-end CNN learns the LR-to-HR mapping jointly rather than in separate stages.",
      ],
    },
    {
      id: "q-cv-kp26-3",
      type: "true-false",
      difficulty: "easy",
      question:
        "Channel shuffling in ShuffleNet is a permutation operation that reorders channels across groups, enabling cross-group information exchange at essentially zero computational cost.",
      correctAnswer: 0,
      explanation:
        "ShuffleNet applies grouped convolutions (which keep channels isolated) followed by a channel shuffle operation that reorders channels across groups.\n\n**Step 1.** Grouped convolution partitions C channels into g groups, each operating independently — preventing inter-group information flow.\n\n**Step 2.** Channel shuffle physically reorders the output channels so that features from different groups are interleaved before the next grouped conv.\n\n**Step 3.** Shuffling is a permutation (rearranging indices) — it requires $O(C)$ operations with no MACs (multiply-accumulate operations), making it essentially free while restoring cross-group communication.",
      hints: [
        "Grouped convolutions partition channels into independent groups — preventing inter-group information flow.",
        "Shuffling is a permutation (rearranging indices) — how much compute does that require?",
      ],
    },
  ],

  // ── cv-kp-27: Efficient CV ────────────────────────────────────────────────
  "efficient-cv": [
    {
      id: "q-cv-kp27-1",
      type: "multiple-choice",
      difficulty: "easy",
      question:
        "Depthwise separable convolution replaces a standard $3 \\times 3$ conv on C-channel input with output of C channels. By what factor does it reduce FLOPs compared to the standard conv?",
      options: [
        "C/9 reduction (depends on channel count).",
        "$1/(C + 1/9) \\approx 1/9$ for large $C$ (approximately the inverse of the kernel area).",
        "$1/3$ reduction (depthwise is $1/3$ of standard).",
        "$1/(8C/9 + 1)$ which simplifies to roughly $1/9$ only for $C=1$.",
      ],
      correctAnswer: 1,
      explanation:
        "Standard $3 \\times 3$ conv FLOPs $\\propto 3 \\times 3 \\times C_{\\text{in}} \\times C_{\\text{out}} = 9C^2$.\n\n**Step 1.** Depthwise separable splits into two steps: depthwise ($3 \\times 3 \\times C$ = $9C$ FLOPs, one filter per channel) and pointwise ($1 \\times 1 \\times C \\times C = C^2$ FLOPs).\n\n**Step 2.** Total for depthwise separable: $9C + C^2 = C(9 + C)$. Ratio to standard: $C(9+C)/(9C^2) = (9+C)/(9C) \\approx 1/9$ for large $C$.\n\n**Step 3.** MobileNet uses depthwise separable convolutions to achieve approximately $8$-$9\\times$ fewer FLOPs than a standard conv, enabling mobile deployment.",
      hints: [
        "Standard: $F \\times F \\times C_\\text{in} \\times C_\\text{out}$. Depthwise: $F \\times F \\times C$ (one filter per channel). Pointwise: $1 \\times 1 \\times C \\times C$.",
        "For $3 \\times 3$ filter and $C$ channels: ratio = $(9C + C^2) / (9C^2) = (9+C)/(9C) \\to 1/9$ as $C \\to \\infty$.",
      ],
    },
    {
      id: "q-cv-kp27-2",
      type: "multiple-choice",
      difficulty: "medium",
      question:
        "In knowledge distillation, training with a teacher temperature $\\tau > 1$ \"softens\" the probability distribution. If a teacher produces logits $[4, 1, -2]$ and $\\tau = 4$, what happens to the soft label distribution compared to $\\tau = 1$?",
      options: [
        "At $\\tau = 4$ the distribution becomes more uniform (entropy increases), revealing inter-class similarity structure that hard labels hide.",
        "At $\\tau = 4$ the distribution becomes sharper (entropy decreases), making distillation easier.",
        "Temperature only affects the student network, not the teacher soft labels.",
        "At $\\tau = 4$ the distribution is identical to $\\tau = 1$ since softmax is scale-invariant.",
      ],
      correctAnswer: 0,
      explanation:
        "Soft labels are computed as $\\softmax(z / \\tau)$.\n\n**Step 1.** At $\\tau = 1$:\n\\[\np \\propto [e^4, e^1, e^{-2}] \\approx [0.952, 0.047, 0.001],\n\\]\nwhich is very peaked toward class 1.\n\n**Step 2.** At $\\tau = 4$:\n\\[\np \\propto [e^{4/4}, e^{1/4}, e^{-2/4}] = [e^1, e^{0.25}, e^{-0.5}] \\approx [0.574, 0.282, 0.144],\n\\]\nwhich is much more uniform.\n\n**Step 3.** Higher $\\tau$ reveals that the teacher considers class 2 more plausible than class 3 even when predicting class 1 — transferring structural knowledge beyond the top-1 prediction.",
      hints: [
        "Temperature $\\tau$ divides all logits before softmax. With larger $\\tau$, the logit differences are compressed, producing a more uniform distribution.",
        "As $\\tau \\to \\infty$, soft labels approach a uniform distribution; as $\\tau \\to 0$, they approach a one-hot distribution.",
      ],
    },
    {
      id: "q-cv-kp27-3",
      type: "true-false",
      difficulty: "easy",
      question:
        "ShuffleNet uses channel shuffling to enable information flow between feature channels after grouped convolutions, without incurring the full cost of standard convolutions.",
      correctAnswer: 0,
      explanation:
        "Grouped convolution partitions C channels into g groups, each operating independently — preventing inter-group information flow.\n\n**Step 1.** Channel shuffle physically reorders the output channels so that features from different groups are interleaved before the next grouped conv.\n\n**Step 2.** This is a zero-parameter, $O(1)$ permutation that costs negligible compute while restoring cross-group communication.\n\n**Step 3.** Shuffling enables the network to combine information across feature groups at minimal cost, improving representational capacity without the FLOPs of a full convolution.",
      hints: [
        "Grouped convolutions with g=4 create 4 isolated feature groups — without shuffling, information never crosses group boundaries.",
        "Shuffling is a permutation (rearranging indices) — how much compute does that require?",
      ],
    },
  ],

  // ── cv-kp-28: CV Evaluation Metrics ──────────────────────────────────────
  "cv-evaluation": [
    {
      id: "q-cv-kp28-1",
      type: "multiple-choice",
      difficulty: "easy",
      question:
        "COCO mAP (the standard benchmark) is computed at multiple IoU thresholds. Which statement correctly describes how COCO mAP is averaged?",
      options: [
        "$\\text{mAP} = \\text{AP} \\times \\text{IoU}$ — mAP equals AP multiplied by the single IoU threshold.",
        "$\\text{mAP} = \\text{AP} \\times (\\text{IoU} + 0.5)$ — mAP scales AP by the IoU threshold.",
        "$\\text{mAP} = \\frac{1}{10} \\sum_{i=1}^{10} \\text{AP}_{\\text{IoU}_i}$ — mAP is the mean of AP values at 10 IoU thresholds from 0.50 to 0.95.",
        "$\\text{mAP} = \\text{AP}_{0.50} + \\text{AP}_{0.75}$ — mAP sums AP at 0.5 and 0.75 IoU.",
      ],
      correctAnswer: 2,
      explanation:
        "COCO mAP is the mean of AP values computed at 10 IoU thresholds: $0.50, 0.55, \\ldots, 0.95$.\n\n**Step 1.** Higher IoU thresholds demand tighter localisation between predicted and ground-truth boxes — loose boxes that pass IoU $\\geq 0.5$ may fail at IoU $\\geq 0.75$.\n\n**Step 2.** The formula is:\n\\[\n\\text{mAP} = \\frac{1}{10} \\sum_{i=1}^{10} \\text{AP}_{\\text{IoU}_i}.\n\\]\n\n**Step 3.** Averaging over all 10 thresholds rewards detectors that produce both rough ($\\text{IoU} \\geq 0.5$) and precise ($\\text{IoU} \\geq 0.75$) localisations.",
      hints: [
        "COCO mAP averages AP over multiple IoU thresholds, penalising imprecise boxes more as the threshold increases.",
        "The 10 IoU thresholds are $0.50, 0.55, 0.60, 0.65, 0.70, 0.75, 0.80, 0.85, 0.90, 0.95$.",
      ],
    },
    {
      id: "q-cv-kp28-2",
      type: "multiple-choice",
      difficulty: "medium",
      question:
        "FID (Fréchet Inception Distance) measures the distance between feature distributions of real and generated images. Which formula correctly defines FID?",
      options: [
        "$\\|\\mu_r - \\mu_g\\|^2 + \\text{Tr}\\!\\left(\\Sigma_r + \\Sigma_g - 2(\\Sigma_r \\Sigma_g)^{1/2}\\right)$, where $\\mu$ and $\\Sigma$ are the mean and covariance of Inception-v3 pool3 features for real ($r$) and generated ($g$) images.",
        "$\\text{average pixel-wise MSE}$ between real and generated images divided by Inception classification accuracy.",
        "$D_{\\text{KL}}\\!\\left(\\mathcal{N}(\\mu_r, \\Sigma_r) \\| \\mathcal{N}(\\mu_g, \\Sigma_g)\\right)$, the KL divergence between two Gaussians.",
        "$1 - \\text{cosine\\_similarity}(\\mu_r, \\mu_g)$, using only mean Inception features without covariance.",
      ],
      correctAnswer: 0,
      explanation:
        "FID is the Fréchet (Wasserstein-2) distance between two multivariate Gaussians:\n\\[\n\\text{FID} = \\|\\mu_r - \\mu_g\\|^2 + \\text{Tr}\\!\\left(\\Sigma_r + \\Sigma_g - 2(\\Sigma_r \\Sigma_g)^{1/2}\\right).\n\\]\n\n**Step 1.** $\\mu_r, \\Sigma_r$ are the mean and covariance of Inception-v3 pool3 features for real images; $\\mu_g, \\Sigma_g$ are for generated images.\n\n**Step 2.** The first term ($\\|\\mu_r - \\mu_g\\|^2$) penalises drift in mean feature position (poor image quality).\n\n**Step 3.** The second term penalises covariance mismatch — particularly important for detecting mode collapse (when generated covariance is too narrow).",
      hints: [
        "FID is the Fréchet/Wasserstein-2 distance between two multivariate Gaussians $\\mathcal{N}(\\mu_r, \\Sigma_r)$ and $\\mathcal{N}(\\mu_g, \\Sigma_g)$.",
        "The matrix square-root term $(\\Sigma_r \\Sigma_g)^{1/2}$ penalises when the covariances of real and generated features differ — this catches mode collapse.",
      ],
    },
    {
      id: "q-cv-kp28-4",
      type: "multiple-choice",
      difficulty: "medium",
      question:
        "COCO mAP is reported as the mean of AP values computed across 10 IoU thresholds (0.50, 0.55, …, 0.95). A model achieves $\\text{AP}_{0.5} = 0.72$ and $\\text{AP}_{0.75} = 0.52$ but very low AP at stricter thresholds. Which statement best explains why COCO mAP (AP[.50:.95]) might be around 0.48 while VOC mAP (AP@0.5) is 0.72?",
      options: [
        "COCO mAP is lower because COCO has more object categories than Pascal VOC.",
        "Averaging AP over thresholds 0.50–0.95 penalises imprecise localisation; a model with loose bounding boxes scores well at IoU=0.5 but poorly at IoU=0.75–0.95, dragging the average below AP@0.5.",
        "COCO mAP uses a different P-R interpolation method that always produces lower values than the 11-point VOC interpolation.",
        "COCO mAP subtracts the FID score from AP@0.5, which reduces the reported metric.",
      ],
      correctAnswer: 1,
      explanation:
        "COCO mAP[.50:.95] averages AP over 10 IoU thresholds. A model that localises objects loosely will achieve high AP@0.5 but low AP@0.75 and near-zero AP@0.90–0.95.\n\n**Step 1.** VOC mAP uses a single threshold (0.5) — any detection with IoU $\\geq 0.5$ is a true positive.\n\n**Step 2.** COCO mAP averages across all 10 thresholds, so if most values above IoU=0.6 are near zero, the mean will be much lower than AP@0.5 alone.\n\n**Step 3.** The wide range of thresholds in COCO specifically rewards detectors that produce tight bounding boxes, not just correct classifications.",
      hints: [
        "Higher IoU thresholds demand that the predicted box nearly perfectly overlaps the ground truth — loose boxes fail these stricter thresholds.",
        "mAP[.50:.95] is the unweighted mean of 10 AP values — if most values above IoU=0.6 are near zero, the mean will be much lower than AP@0.5.",
      ],
    },
    {
      id: "q-cv-kp28-3",
      type: "true-false",
      difficulty: "easy",
      question:
        "In Pascal VOC evaluation, a detection is a true positive only if its IoU with a ground truth box exceeds 0.5 AND the same ground truth box has not already been matched by a higher-confidence detection.",
      correctAnswer: 0,
      explanation:
        "VOC AP matching is greedy in confidence order: detections are sorted by score and each is assigned to the highest-IoU unmatched GT (if IoU $\\geq 0.5$).\n\n**Step 1.** Once a GT is matched, all further detections overlapping it are FPs regardless of IoU — preventing a single GT from generating multiple TPs.\n\n**Step 2.** This greedy matching ensures the precision-recall curve reflects genuine detection performance.\n\n**Step 3.** The \"unmatched\" condition is critical: two overlapping high-confidence predictions for one GT yield only one TP, not two.",
      hints: [
        'The "unmatched" condition prevents double-counting: two high-confidence overlapping predictions for one GT yield only one TP.',
        "Greedy matching in confidence order rewards detectors that assign highest scores to correct detections.",
      ],
    },
  ],

  // ── cv-kp-30: Foundation Models for CV ───────────────────────────────────
  "foundation-models-cv": [
    {
      id: "q-cv-kp30-1",
      type: "multiple-choice",
      difficulty: "easy",
      question:
        "SAM (Segment Anything Model) consists of three components: an image encoder, a prompt encoder, and a mask decoder. Which image encoder does SAM use and why?",
      options: [
        "A ResNet-50 backbone pretrained on ImageNet because it is fast and lightweight.",
        "A heavyweight ViT (ViT-H/16 in SAM-1) pretrained with MAE, run once per image to produce a $64 \\times 64$ image embedding that is cached and reused across multiple prompts.",
        "A CLIP vision encoder so that text prompts and image prompts can be processed in the same embedding space.",
        "A U-Net encoder-decoder so that the image embedding retains full spatial resolution for segmentation.",
      ],
      correctAnswer: 1,
      explanation:
        "SAM uses a ViT-H (huge) image encoder with MAE pretraining to produce dense image embeddings at 1/16 scale.\n\n**Step 1.** For a $1024 \\times 1024$ input, the embedding is $64 \\times 64$ — a compact representation of the full image.\n\n**Step 2.** Crucially, the image encoder runs once and the resulting embedding is cached — allowing fast interactive segmentation at < 50ms per prompt using only the lightweight prompt encoder and mask decoder.\n\n**Step 3.** ViT-H has 632M parameters; the prompt encoder and mask decoder together have approximately 4M parameters.",
      hints: [
        "The image encoder is the expensive part — SAM amortises its cost by caching the embedding across prompts.",
        "ViT-H has 632M parameters; the prompt encoder and mask decoder together have ~4M.",
      ],
    },
    {
      id: "q-cv-kp30-2",
      type: "multiple-choice",
      difficulty: "medium",
      question:
        "DINOv2 achieves strong performance across diverse CV tasks without task-specific fine-tuning. How is it pretrained?",
      options: [
        "Supervised pretraining on ImageNet-22k with label smoothing and aggressive augmentation.",
        "Self-supervised learning combining DINO self-distillation (student-teacher with centering/sharpening) and iBOT masked image modelling, trained on a carefully curated LVD-142M dataset.",
        "Contrastive pretraining on image-text pairs from the web (similar to CLIP).",
        "Autoregressive next-patch prediction on a large-scale image dataset.",
      ],
      correctAnswer: 1,
      explanation:
        "DINOv2 combines two self-supervised objectives trained on the curated LVD-142M dataset.\n\n**Step 1.** **DINO self-distillation**: a student ViT matches a momentum-teacher's global CLS token predictions on different augmented views.\n\n**Step 2.** **iBOT masked image modelling**: masked patch tokens are predicted, encouraging local feature quality complementary to the global DINO objective.\n\n**Step 3.** Combining DINO (CLS-level) and iBOT (patch-level) objectives gives both global and local feature quality, enabling frozen features to work across depth estimation, segmentation, and classification without fine-tuning.",
      hints: [
        "DINOv2 is purely self-supervised — it uses no text pairs (unlike CLIP) and no manual labels.",
        "Combining DINO (CLS-level) and iBOT (patch-level) objectives encourages both global and local feature quality.",
      ],
    },
    {
      id: "q-cv-kp30-4",
      type: "multiple-choice",
      difficulty: "medium",
      question:
        "SAM (Segment Anything Model) accepts multiple types of prompts to generate segmentation masks. Which of the following is NOT a supported prompt type in SAM?",
      options: [
        "A point (x, y) with a foreground/background label.",
        "A bounding box ($x_1, y_1, x_2, y_2$) specifying a region of interest.",
        "A free-form text description of the object to segment.",
        "A rough mask from a previous prediction used to refine the segmentation.",
      ],
      correctAnswer: 2,
      explanation:
        "SAM's prompt encoder accepts points, bounding boxes, and low-resolution masks as geometric prompts — it does NOT natively accept free-form text descriptions.\n\n**Step 1.** SAM's three prompt types are: (1) foreground/background point clicks encoded as learned position and type embeddings; (2) bounding boxes; (3) low-resolution mask inputs from a previous prediction.\n\n**Step 2.** Text-prompted segmentation requires an additional text-grounding module (e.g., Grounding DINO + SAM) to first localise text in the image.\n\n**Step 3.** SAM's mask decoder generates up to 3 candidate masks with confidence scores, handling ambiguous prompts gracefully.",
      hints: [
        "SAM's prompt encoder converts sparse (points, boxes) and dense (masks) inputs — which input format is it missing?",
        "Text-to-segmentation requires first grounding the text to image regions, which SAM itself does not do.",
      ],
    },
    {
      id: "q-cv-kp30-5",
      type: "multiple-choice",
      difficulty: "easy",
      question:
        "CLIP is trained with a contrastive (InfoNCE) loss on a batch of $N$ image-text pairs. For a batch of $N = 4$ pairs, how many positive and negative pairs does the loss use?",
      options: [
        "4 positives and 4 negatives (one negative per positive pair).",
        "4 positives and 12 negatives ($N$ positives, $N^2 - N$ negatives).",
        "4 positives and 8 negatives (2 negatives per positive).",
        "4 positives and 16 negatives ($N^2$ total pairs).",
      ],
      correctAnswer: 1,
      explanation:
        "CLIP constructs an $N \\times N$ similarity matrix. Each of the $N$ diagonal entries (image $i$ with text $i$) is a positive pair. All off-diagonal entries are negatives.\n\n**Step 1.** Positives: the $N$ diagonal entries (image $i$ matched with text $i$).\n\n**Step 2.** Negatives: all off-diagonal entries — image $i$ paired with every other text, and vice versa: $N^2 - N = 4^2 - 4 = 12$.\n\n**Step 3.** Large batch sizes ($N = 32768$) provide abundant negatives, which is crucial for CLIP's performance — more negatives means a harder contrastive task and better representations.",
      hints: [
        "An $N \\times N$ matrix has $N$ diagonal (positive) and $N^2 - N$ off-diagonal (negative) entries.",
        "For $N = 4$: $4^2 = 16$ total pairs, 4 on the diagonal are positives, $16 - 4 = 12$ are negatives.",
      ],
    },
    {
      id: "q-cv-kp30-3",
      type: "true-false",
      difficulty: "medium",
      question:
        'CLIP (Contrastive Language-Image Pretraining) can be used for zero-shot image classification by comparing image embeddings to text embeddings of class descriptions like "a photo of a {class}".',
      correctAnswer: 0,
      explanation:
        "CLIP trains dual ViT/ResNet image and text encoders with InfoNCE contrastive loss on 400M (image, text) pairs to produce aligned embeddings.\n\n**Step 1.** At inference, class prompts \"a photo of a {class}\" are embedded as text; the query image is embedded; cosine similarity identifies the closest class.\n\n**Step 2.** This enables zero-shot classification on unseen classes without any task-specific training.\n\n**Step 3.** The alignment between visual and textual embeddings in CLIP's shared space is what makes this possible — the model has learned that textual descriptions of classes correspond to visual features of those classes.",
      hints: [
        "CLIP learns a shared image-text embedding space where matching pairs are close — class names can act as label embeddings.",
        '"Zero-shot" means no labelled images of the test class are needed — the text description substitutes.',
      ],
    },
  ],
};

export default questions;
