// Re-export types and functions from registry
export type { QuestionsMap } from "./registry";
export { registerQuestions, getQuestions, getAllQuestions } from "./registry";

// Import question files to trigger registration
import "./rl-fundamentals";
import "./rl-applications";
import "./math-for-ml";
import "./rlhf-alignment";
import "./nlp-fundamentals";
import "./computer-vision";
import "./agentic-ai";
import "./deep-learning-fundamentals";
import "./ml-systems";
import "./transformers-llms";
import "./financial-ml";
import "./production-ml-engineering";
import "./speech-audio";
import "./quantum-ml";
import "./ai-climate";
import "./robotics-embodied";
import "./vision-3d";
import "./ai-healthcare";
import "./scientific-ml";
import "./generative-adversarial-networks";
import "./domain-adaptation-advanced";
import "./ml-system-design";
import "./linear-algebra-deep-dive";
import "./tabular-ml";
import "./ml-evaluation-benchmarking";
import "./data-centric-ai";
import "./advanced-optimization-ml";
import "./meta-learning";
import "./self-supervised-learning";
import "./coding-interviews-1";
import "./coding-interviews-2";
import "./coding-interviews-3";
import "./gemini-multimodal";
import "./karpathy-nn-zero-to-hero";
import "./fastai-deep-learning";
import "./causal-inference";
import "./diffusion-models";
import "./graph-neural-networks";
import "./systems-design-interview";
import "./systems-design-databases";
import "./systems-design-networking";
import "./systems-design-distributed";
import "./systems-design-scalability";
import "./systems-design-cloud";
import "./systems-design-social";
import "./systems-design-ecommerce";
import "./systems-design-streaming";
import "./systems-design-security";
import "./systems-design-mobile";
import "./systems-design-search";
import "./systems-design-interview-prep";
import "./systems-design-maps";
import "./systems-design-observability";
import "./systems-design-realtime";
import "./systems-design-gaming";
import "./systems-design-ml-platform";
import "./systems-design-fintech";
import "./systems-design-iot";
import "./systems-design-ridesharing";
import "./systems-design-api-gateway";
import "./systems-design-healthcare";
import "./systems-design-video";
import "./rl-finetuning-platforms";
import "./llm-inference-optimization";
import "./rag-systems";
import "./ai-engineering-sdks";
import "./ai-coding-assistants";
import "./data-engineering-ml";

// Export questionBanks for test access
import { getAllQuestions } from "./registry";
export const questionBanks = getAllQuestions();
