import type { Question } from "@/lib/curriculum";
import { registerQuestions } from "./registry";

const questions: Record<string, Question[]> = {
  "sdi-url-shortener": [
    {
      id: "q-sdi-url-1",
      type: "multiple-choice",
      difficulty: "medium",
      question: "A URL shortener needs to generate unique short codes. Which encoding scheme produces the most compact 7-character codes while using only URL-safe characters?",
      options: ["MD5 truncated to 7 hex chars", "Base62 encoding (a-z, A-Z, 0-9)", "Base64 encoding (with +, /)", "SHA-256 truncated to 7 chars"],
      correctAnswer: 1,
      explanation: "Base62 uses 62 characters (a-z, A-Z, 0-9), all URL-safe without percent-encoding. With 7 characters, Base62 yields 62^7 \approx 3.5 trillion unique codes - far more than the ~268 million from 7 hex characters (16^7). Base64 includes + and / which require URL encoding. MD5/SHA-256 truncation wastes character space by using only hex digits.",
      hints: ["Count how many unique symbols each encoding uses per character position.", "Compare 62^7 versus 16^7 to see which covers more IDs."],
    },
    {
      id: "q-sdi-url-2",
      type: "multiple-choice",
      difficulty: "hard",
      question: "Twitter Snowflake generates 64-bit IDs for distributed systems. Which component breakdown is correct?",
      options: ["41-bit timestamp + 10-bit machine ID + 12-bit sequence + 1 sign bit", "32-bit timestamp + 16-bit machine ID + 16-bit sequence", "48-bit timestamp + 8-bit datacenter + 8-bit sequence", "64-bit random number with no structure"],
      correctAnswer: 0,
      explanation: "Snowflake IDs are structured as: 1 sign bit (always 0) + 41-bit millisecond timestamp (gives ~69 years of IDs from a custom epoch) + 10-bit machine ID (1024 machines) + 12-bit sequence number (4096 IDs per millisecond per machine). This yields up to 4096 \$\\times\$ 1024 = ~4.2 million unique IDs per millisecond globally, with the IDs being roughly time-ordered for free.",
      hints: ["The total must be exactly 64 bits. Account for a sign bit.", "Think about what each component enables: time ordering, machine uniqueness, and burst capacity."],
    },
    {
      id: "q-sdi-url-3",
      type: "multiple-choice",
      difficulty: "medium",
      question: "A URL shortener analytics team wants to count every redirect hit on their servers. Which HTTP redirect status code should they use, and why?",
      options: ["301 Permanent Redirect - browsers cache it, reducing server load", "302 Temporary Redirect - browsers always re-contact the server, enabling accurate hit counting", "307 Temporary Redirect (method-preserving) - same as 302 for GET requests", "200 OK with a Location header - guarantees server always sees the request"],
      correctAnswer: 1,
      explanation: "A 301 Permanent Redirect instructs browsers to cache the redirect permanently, so subsequent clicks go directly to the long URL without hitting the shortener's server - analytics are lost. A 302 Temporary Redirect tells browsers never to cache the redirect, so every click passes through the shortener, enabling accurate hit counting and analytics. 307 is functionally equivalent for GET requests but the key distinction for analytics is 301 vs 302.",
      hints: ["Consider what browsers do with 'permanent' vs 'temporary' redirect instructions.", "Which status code would cause a browser to bypass the server on repeat visits?"],
    },
    {
      id: "q-sdi-url-4",
      type: "true-false",
      difficulty: "medium",
      question: "For a read-heavy URL shortener (100:1 read-to-write ratio), storing short_code as the primary key and caching hot entries in Redis with a TTL is an effective strategy for reducing database load.",
      correctAnswer: "True",
      explanation: "True. URL shorteners are extremely read-heavy - most short codes are created once but accessed millions of times. Using short_code as the primary key enables O(1) hash-based lookups. Redis with a TTL-based eviction policy (e.g., LRU) keeps the hottest mappings in memory, where cache hit latency is sub-millisecond vs. ~5ms for a database round-trip. This combination can handle >99% of reads from cache after warm-up.",
      hints: ["Think about the access pattern: one write, potentially millions of reads per short code.", "What does Redis TTL-based caching do to reduce pressure on the primary database?"],
    },
  ],

  "sdi-google-drive": [
    {
      id: "q-sdi-drive-1",
      type: "multiple-choice",
      difficulty: "hard",
      question: "Google Drive uses content-defined chunking instead of fixed-size chunking. What problem does this solve?",
      options: ["Fixed-size chunks cannot be encrypted", "Inserting bytes at the start of a file shifts all fixed-size chunk boundaries, causing every chunk to change", "Fixed-size chunks are too large for network transfer", "Content-defined chunks are smaller on average than fixed-size chunks"],
      correctAnswer: 1,
      explanation: "The 'boundary shift problem': if you insert or delete bytes at the start of a file using fixed-size chunks, every subsequent chunk boundary shifts, making nearly all chunks appear 'changed' even though the actual content at the end of the file is identical. Content-defined chunking (e.g., using Rabin fingerprinting to find chunk boundaries based on a rolling hash of content) means boundaries are determined by content patterns, so insertions only affect a few adjacent chunks.",
      hints: ["Imagine inserting a single byte at position 0 of a 1 GB file split into 4 MB fixed chunks.", "How many of those chunks would have different content after the insertion?"],
    },
    {
      id: "q-sdi-drive-2",
      type: "multiple-choice",
      difficulty: "medium",
      question: "When a client syncs a modified file, Google Drive's delta sync computes SHA-256 hashes for each chunk. What is the primary purpose of these hashes?",
      options: ["To encrypt each chunk before upload", "To identify which specific chunks changed so only those chunks are uploaded", "To compress the chunks before transfer", "To generate a content-addressable URL for each chunk"],
      correctAnswer: 1,
      explanation: "Delta sync works by computing SHA-256 (or a similar hash) for each chunk on the client side, then comparing these hashes with the server's stored hashes for the previous version. Only chunks whose hashes differ are actually uploaded. For a 10 GB file where only 1 KB changed, delta sync reduces upload bandwidth from 10 GB to ~4 MB (one chunk), making sync practical even on slow connections.",
      hints: ["SHA-256 is a deterministic function: same bytes always produce the same hash.", "If the hash of a chunk matches the server's stored hash, what does that tell you about the chunk's content?"],
    },
    {
      id: "q-sdi-drive-3",
      type: "true-false",
      difficulty: "hard",
      question: "Version vectors (one counter per device) are the standard conflict resolution mechanism in distributed file sync systems like Dropbox - when two devices edit the same file concurrently, version vectors can always determine which version is 'correct' and automatically merge them.",
      correctAnswer: "False",
      explanation: "False. Version vectors can detect that a conflict occurred (two concurrent writes with incomparable vector clocks), but they cannot automatically determine semantic correctness or merge arbitrary content. The standard approach is to preserve both versions as separate conflict copies (e.g., 'file (John's conflicted copy 2024-01-01).docx') and present both to the user. Automatic merging is only possible for certain data types (like CRDTs for text), not arbitrary binary files.",
      hints: ["Version vectors detect concurrency, but does detecting a conflict tell you how to resolve it?", "Think about what 'merging' two different versions of a binary file (like a JPEG) would even mean."],
    },
    {
      id: "q-sdi-drive-4",
      type: "multiple-choice",
      difficulty: "medium",
      question: "Google Drive separates file metadata from file content storage. Which combination correctly matches the storage technology to its purpose?",
      options: ["Bigtable for metadata + GCS for content blobs", "Spanner/MySQL for metadata (ACID transactions) + GCS/S3 for content blobs", "Redis for metadata + local disks for content", "Kafka for metadata + HDFS for content"],
      correctAnswer: 1,
      explanation: "Metadata (file name, owner, permissions, chunk hashes, version history) requires ACID transactions because concurrent operations like share/rename/delete must be atomic and consistent - a relational database like Spanner or MySQL is appropriate. Content blobs (the actual bytes) require massive scalable storage with high throughput but not ACID semantics - object stores like GCS or S3 are ideal, storing chunks addressed by their content hash for deduplication.",
      hints: ["Metadata operations like 'share a folder' involve multiple rows that must update atomically.", "File content is immutable once written (new versions create new blobs) - does that change the storage requirements?"],
    },
  ],

  "sdi-search-engine": [
    {
      id: "q-sdi-search-1",
      type: "multiple-choice",
      difficulty: "medium",
      question: "In a search engine's inverted index, each term maps to a posting list. What information does each entry in the posting list typically store?",
      options: ["Only the document ID", "Document ID, term frequency (tf), and position offsets within the document", "Document ID and document length only", "URL and page rank score only"],
      correctAnswer: 1,
      explanation: "A posting list entry stores (doc_id, tf, positions): doc_id identifies the document, term frequency (tf) counts how many times the term appears in that document (used for ranking), and position offsets enable phrase queries like 'New York' where both words must appear adjacent. Doc IDs within a posting list are stored in sorted order and delta-encoded (storing differences between consecutive doc IDs) to enable efficient compression with variable-byte encoding.",
      hints: ["What information do you need to answer 'does this document contain the query term, and how relevant is it?'", "Phrase queries like 'machine learning' require knowing not just which docs contain each word, but where in the doc."],
    },
    {
      id: "q-sdi-search-2",
      type: "multiple-choice",
      difficulty: "hard",
      question: "BM25 is preferred over TF-IDF for modern search ranking. Which properties does BM25 have that TF-IDF lacks?",
      options: ["BM25 uses neural embeddings; TF-IDF does not", "BM25 saturates term frequency (diminishing returns) and normalizes by document length; TF-IDF does neither", "BM25 considers query length; TF-IDF only considers document length", "BM25 is faster to compute; TF-IDF requires matrix decomposition"],
      correctAnswer: 1,
      explanation: "BM25 adds two critical improvements: (1) TF saturation via the parameter k1 - in BM25, doubling a term's frequency does not double its score (diminishing returns prevent keyword stuffing), while raw TF-IDF grows linearly. (2) Document length normalization via parameter b - longer documents are penalized so a word appearing once in a 100-word doc ranks higher than once in a 10,000-word doc. These make BM25 significantly better for web-scale ranking.",
      hints: ["What happens in TF-IDF if a spammer repeats a keyword 1000 times in a document?", "Should a word appearing once in a tweet be weighted the same as appearing once in a book chapter?"],
    },
    {
      id: "q-sdi-search-3",
      type: "true-false",
      difficulty: "hard",
      question: "In a term-partitioned index shard design, a single shard owns all posting lists for a subset of terms (e.g., one shard handles all documents for the term 'python'), meaning a query for 'python tutorial' requires hitting only the shard that owns the rarest term.",
      correctAnswer: "False",
      explanation: "False. In term-partitioned sharding, a query for 'python tutorial' must hit the shard owning 'python' AND the shard owning 'tutorial' separately, then intersect the results - this requires cross-shard coordination for every multi-term query. In contrast, document-partitioned sharding assigns all terms for a given document to the same shard, so multi-term queries can be executed within each shard independently; results are then merged (fan-out/gather). Most large-scale search engines use document partitioning for this reason.",
      hints: ["In term partitioning, where does the posting list for 'tutorial' live relative to 'python'?", "What does intersection of posting lists require when the lists are on different machines?"],
    },
    {
      id: "q-sdi-search-4",
      type: "multiple-choice",
      difficulty: "medium",
      question: "A web crawler must respect crawl budget constraints. Which of the following is a valid reason for prioritizing pages with high PageRank in the crawl frontier?",
      options: ["High PageRank pages have shorter URLs which are cheaper to fetch", "High PageRank pages are more likely to contain valuable content and be freshly updated, maximizing index quality per crawl request", "robots.txt rules only apply to low-PageRank pages", "High PageRank pages compress better in the inverted index"],
      correctAnswer: 1,
      explanation: "Crawl budget is the number of URLs a crawler can fetch per domain per day before the site's server is overloaded. By prioritizing high-PageRank pages, crawlers maximize the value of each fetch: authoritative, frequently-updated pages (news sites, Wikipedia) are indexed first. Low-PageRank pages (deep pagination, duplicate content) are deferred. Crawlers also respect robots.txt Crawl-delay directives and Disallow rules regardless of PageRank.",
      hints: ["A crawler can only fetch a finite number of pages per day. How should it decide which pages matter most?", "PageRank is a proxy for what quality signal about a page?"],
    },
  ],

  "sdi-distributed-cache": [
    {
      id: "q-sdi-cache-1",
      type: "multiple-choice",
      difficulty: "medium",
      question: "LRU (Least Recently Used) cache eviction is implemented in O(1) time for both get and put. Which data structure combination achieves this?",
      options: ["Min-heap + hash map", "Doubly linked list + hash map", "Sorted array + binary search", "Trie + queue"],
      correctAnswer: 1,
      explanation: "LRU requires O(1) access (to check if a key exists and get its value) and O(1) reordering (to move the accessed item to the 'most recently used' position). A hash map provides O(1) key lookup and stores pointers to nodes in a doubly linked list. The doubly linked list maintains insertion order (head = most recent, tail = least recent) and supports O(1) node removal and re-insertion because each node has prev/next pointers. On eviction, remove the tail node.",
      hints: ["You need O(1) lookup by key, but also O(1) reordering when an item is accessed. What data structure gives O(1) lookup?", "What data structure supports O(1) removal of any node, given a direct pointer to that node?"],
    },
    {
      id: "q-sdi-cache-2",
      type: "multiple-choice",
      difficulty: "hard",
      question: "A popular cache entry expires and 10,000 concurrent requests all miss the cache simultaneously and pound the database. This is called cache stampede (thundering herd). Which two mechanisms directly prevent this?",
      options: ["Increase cache TTL to infinity and use write-through caching", "Redis SET NX EX distributed lock (only one request rebuilds the cache) and probabilistic early expiration (XFetch)", "Use consistent hashing to distribute the load across more cache nodes", "Switch from Redis to Memcached for faster cache misses"],
      correctAnswer: 1,
      explanation: "Two proven solutions: (1) Distributed lock using Redis SET NX EX - when a cache miss occurs, one request acquires the lock and rebuilds the cache while others wait or return stale data. (2) Probabilistic early expiration (XFetch algorithm) - each request has a small probability of proactively refreshing the cache before it actually expires, based on recomputation time and time-to-expiry. This avoids the synchronized miss entirely. Consistent hashing helps distribution but does not prevent stampede when a key expires.",
      hints: ["If 10,000 requests all miss, you want only one of them to hit the database. How do you serialize this?", "What if the cache entry was refreshed slightly before its TTL expired, proactively, to avoid the synchronized expiration?"],
    },
    {
      id: "q-sdi-cache-3",
      type: "multiple-choice",
      difficulty: "medium",
      question: "An e-commerce site needs strong consistency: every database write must be immediately visible in the cache. Which write strategy guarantees the cache is always consistent with the database?",
      options: ["Write-around (skip cache on write, populate cache on read miss)", "Write-behind / write-back (write to cache first, async flush to DB)", "Write-through (write to cache and DB atomically in the same request path)", "Read-through (cache fetches from DB only on miss)"],
      correctAnswer: 2,
      explanation: "Write-through writes to both the cache and the database synchronously before the write request returns. This guarantees the cache is always consistent with the database - subsequent reads will always find fresh data. The trade-off is higher write latency (two writes instead of one). Write-behind risks data loss if the cache fails before flushing. Write-around leads to cache misses on the first read after each write, causing a brief inconsistency window.",
      hints: ["Consistency requires that after a write completes, all subsequent reads see the new value.", "Which strategy ensures both the cache and DB are updated before the write call returns to the client?"],
    },
    {
      id: "q-sdi-cache-4",
      type: "true-false",
      difficulty: "easy",
      question: "Cache warming (pre-populating the cache with hot data before a product launch) is a valid technique to prevent cache stampede caused by a cold start.",
      correctAnswer: "True",
      explanation: "True. A cold cache after deployment or a product launch means the first wave of users all experience cache misses simultaneously, causing a thundering herd on the database. Cache warming proactively loads predicted hot keys (e.g., top 1000 products, landing page data) into Redis before traffic arrives. This converts cold-start stampedes into cache hits. It is commonly used before planned high-traffic events like Black Friday launches, new product drops, or after a deploy.",
      hints: ["What is the state of the cache immediately after a fresh deployment?", "If you know in advance which data will be requested most, what can you do before the traffic arrives?"],
    },
  ],

  "sdi-ride-sharing": [
    {
      id: "q-sdi-ride-1",
      type: "multiple-choice",
      difficulty: "hard",
      question: "Uber uses S2 geometry library (Hilbert space-filling curve cells) for geospatial indexing, while Lyft and Yelp use geohash. What is the key locality advantage of Hilbert curve-based cells over geohash?",
      options: ["S2 cells are squares; geohash cells are rectangles", "S2 cells on a Hilbert curve maintain better spatial locality - nearby cells on the curve are geographically close - reducing edge cases at cell boundaries compared to geohash's Z-curve", "S2 cells support 3D coordinates for altitude; geohash is 2D only", "S2 cells are encoded in binary; geohash uses base32 characters"],
      correctAnswer: 1,
      explanation: "Both S2 and geohash partition the Earth into hierarchical grid cells, but they differ in how cells are ordered. Geohash uses a Z-order curve (Morton code) which has discontinuities - neighboring geohash strings can represent cells far apart on the map (e.g., at the boundary of two geohash prefixes). S2's Hilbert space-filling curve has better locality guarantees: nearby cells in Hilbert order are always geographically close. This matters for range queries like 'find all drivers within 2km' because S2 requires fewer cell unions to represent irregular shapes.",
      hints: ["Both systems divide the earth into cells. The question is about how adjacent cells in the indexing order relate to each other geographically.", "What happens to a geohash-based proximity query when the user is near a geohash cell boundary?"],
    },
    {
      id: "q-sdi-ride-2",
      type: "multiple-choice",
      difficulty: "medium",
      question: "Uber has 1 million active drivers each sending a location update every 4 seconds. What is the sustained write throughput required, and which storage system is best suited for this workload?",
      options: ["250K writes/s - best handled by PostgreSQL with indexes", "250K writes/s - best handled by a distributed key-value store like DynamoDB or Cassandra", "15K writes/s - best handled by Redis single node", "1M writes/s - best handled by Kafka with batch consumers"],
      correctAnswer: 1,
      explanation: "1,000,000 drivers \$\\div\$ 4 seconds per update = 250,000 writes per second sustained. PostgreSQL with indexes cannot scale to 250K writes/s on a single node (typical limit ~10K-50K). A distributed key-value store like DynamoDB or Cassandra is purpose-built for high-throughput, low-latency point writes with horizontal scaling. The data model is simple: key = driver_id, value = {lat, lng, timestamp, status}, with no complex joins needed.",
      hints: ["Divide the number of drivers by the update interval to find writes per second.", "A relational database with indexes has high write amplification. What storage systems are designed for hundreds of thousands of writes per second?"],
    },
    {
      id: "q-sdi-ride-3",
      type: "true-false",
      difficulty: "medium",
      question: "In a ride-sharing matching system, the 'nearest driver' is always selected for a ride request based purely on geographic distance (straight-line) to minimize passenger wait time.",
      correctAnswer: "False",
      explanation: "False. Geographic distance (straight-line or haversine) is only a proxy for actual travel time. The matching algorithm ranks available drivers by estimated time of arrival (ETA), which accounts for real-time traffic, road network topology, and one-way streets. A driver 500m away but on the other side of a highway may have a higher ETA than one 800m away on the same block. Additionally, driver heading and current ride state are considered. The assignment must also be atomic to prevent double-booking.",
      hints: ["Is the closest point in straight-line distance always the fastest to reach in a city with traffic?", "Think about one-way streets, highways, and real-time traffic conditions."],
    },
    {
      id: "q-sdi-ride-4",
      type: "multiple-choice",
      difficulty: "hard",
      question: "Uber implements surge pricing based on supply and demand. What is the correct architecture for computing surge multipliers in real time?",
      options: ["Query the relational database on every ride request and compute surge inline", "Use a streaming aggregation system (e.g., Kafka Streams or Flink) to compute supply/demand ratio per geohash cell every 1-5 minutes, store results in Redis, and read from Redis on every ride request", "Compute surge once per hour in a batch job and cache results in a CDN", "Use a simple threshold: if more than 10 requests/minute in a cell, apply 2x surge"],
      correctAnswer: 1,
      explanation: "Surge pricing requires near-real-time computation (1-5 minute windows) at geographic granularity (per geohash cell or S2 cell). A streaming system like Kafka Streams or Apache Flink continuously aggregates driver availability (supply) and ride requests (demand) per cell. The computed surge multipliers are written to Redis (low-latency reads). When a user requests a ride, the app reads the current surge from Redis in <1ms. This architecture separates the compute-intensive aggregation from the latency-sensitive request path.",
      hints: ["Surge must be computed frequently (every few minutes) but read on every single ride request. What does this access pattern suggest about separation of compute and read?", "Kafka Streams and Flink are designed for what kind of time-windowed computations over event streams?"],
    },
  ],

  "sdi-video-streaming": [
    {
      id: "q-sdi-video-1",
      type: "multiple-choice",
      difficulty: "medium",
      question: "YouTube and Netflix use Adaptive Bitrate (ABR) streaming via HLS or DASH. How does the player decide which quality to request?",
      options: ["The server selects quality based on the user's account tier", "The player measures available download bandwidth by monitoring segment download times, then requests the highest quality that can be sustained without buffering", "Quality is fixed at upload time and cannot change during playback", "The CDN selects quality based on server load"],
      correctAnswer: 1,
      explanation: "In HLS (HTTP Live Streaming) and DASH (Dynamic Adaptive Streaming over HTTP), videos are pre-transcoded into multiple bitrate variants (e.g., 360p/1Mbps, 720p/3Mbps, 1080p/8Mbps, 4K/25Mbps) and split into 2-4 second segments. The player uses a bandwidth estimation algorithm (measuring how fast each segment downloaded relative to its size) to predict available throughput. It then selects the highest quality variant whose bitrate fits within the estimated bandwidth with a safety buffer, switching quality at segment boundaries.",
      hints: ["The player downloads segments sequentially. What information does it have about network speed after downloading each segment?", "ABR stands for Adaptive Bitrate - what is it adapting to?"],
    },
    {
      id: "q-sdi-video-2",
      type: "multiple-choice",
      difficulty: "hard",
      question: "A video platform's transcoding pipeline processes uploaded videos. What is the correct sequence of stages?",
      options: ["Upload  ->  CDN  ->  transcode  ->  store in S3", "Upload raw video to object storage  ->  enqueue job  ->  worker fleet transcodes to multiple formats/bitrates (H.264, H.265, VP9) at multiple resolutions  ->  store segments in S3  ->  invalidate CDN cache", "Upload  ->  transcode on upload server inline  ->  stream directly from upload server", "Upload  ->  store in database as BLOB  ->  transcode on first playback request"],
      correctAnswer: 1,
      explanation: "The pipeline is asynchronous: (1) Raw video is stored in object storage immediately to avoid re-upload on failure. (2) A job is enqueued in a message queue (SQS, Kafka). (3) Worker fleet (potentially hundreds of EC2 instances or cloud functions) pulls jobs and transcodes to multiple formats - H.264 for broad compatibility, H.265 for 4K efficiency, VP9 for Chrome. (4) Multiple resolution outputs (360p through 4K) and 2-4s segments are stored in S3. (5) CDN edge caches are pre-warmed or lazily populated on first request. Inline transcoding would block uploads and waste upload server capacity.",
      hints: ["Transcoding a 2-hour 4K video can take hours. Should this block the upload response to the user?", "What is the advantage of storing the raw upload first, before any processing begins?"],
    },
    {
      id: "q-sdi-video-3",
      type: "true-false",
      difficulty: "medium",
      question: "Netflix's Open Connect Appliances (OCAs) are CDN servers placed inside Internet Service Providers' networks specifically to serve Netflix content, reducing the amount of Netflix traffic that traverses the public internet backbone.",
      correctAnswer: "True",
      explanation: "True. Netflix's Open Connect is a purpose-built CDN where Netflix deploys its own servers (Open Connect Appliances) inside ISP networks globally. Because video is served from within the user's ISP rather than across internet exchange points, it reduces transit costs for both Netflix and ISPs, improves video quality (lower latency, fewer hops), and reduces congestion on internet backbone links. Netflix proactively fills OCAs with the top ~95% of its catalog overnight during low-traffic periods using a process called 'proactive caching' or 'fill'.",
      hints: ["If a CDN server is inside your ISP's network, how many network hops does the video traffic need to cross?", "Netflix accounts for ~15% of global internet traffic. What happens to backbone congestion if that traffic stays within each ISP?"],
    },
    {
      id: "q-sdi-video-4",
      type: "multiple-choice",
      difficulty: "easy",
      question: "A video platform generates preview thumbnails for every uploaded video. What is the standard approach for storing and serving millions of thumbnails at scale?",
      options: ["Store thumbnail bytes in a PostgreSQL BYTEA column and serve via the API server", "Extract frames at regular intervals (every N seconds), store images in object storage (S3/GCS), and serve via CDN with long-lived cache-control headers", "Generate thumbnails on-demand per request using a Lambda function reading from the raw video", "Store thumbnails in Redis as base64-encoded strings for fast access"],
      correctAnswer: 1,
      explanation: "The standard approach: during the transcoding pipeline, a worker extracts a frame every N seconds (or at scene changes), compresses them as JPEGs, and stores them in object storage (S3/GCS) with a deterministic key like /thumbnails/{video_id}/{timestamp}.jpg. A CDN serves these with Cache-Control: max-age=31536000 (1 year), so edge servers cache thumbnails indefinitely (thumbnails don't change after processing). This offloads thumbnail traffic entirely from origin servers. PostgreSQL BLOBs and Redis base64 don't scale to petabytes of image data.",
      hints: ["Thumbnails are static assets that never change after generation. What class of infrastructure is optimized for serving immutable static assets at global scale?", "How do you make CDN edge caches hold thumbnails for as long as possible?"],
    },
  ],

  "sdi-payment-processing": [
    {
      id: "q-sdi-payment-1",
      type: "multiple-choice",
      difficulty: "medium",
      question: "A payment API client retries a failed charge request 3 times due to a network timeout. How do idempotency keys prevent the customer from being charged multiple times?",
      options: ["The server rate-limits retries to one per minute", "The client generates a UUID before the first attempt and sends it on all retries; the server stores (idempotency_key  ->  result) with a UNIQUE constraint and returns the cached result for duplicate requests", "The bank's API automatically detects duplicate charges by amount and timestamp", "The client checks the charge status before each retry"],
      correctAnswer: 1,
      explanation: "Idempotency keys work as follows: the client generates a UUID (e.g., UUID v4) before making any attempt. This same UUID is included in the header of every retry. The server stores the result of the first successful execution in a table keyed by idempotency_key (with a UNIQUE database constraint to prevent races). On subsequent requests with the same key, the server returns the cached result without re-executing the charge. This pattern makes the operation idempotent - calling it N times produces the same result as calling it once.",
      hints: ["The server needs to remember 'I already processed this request.' What does it need to store to look this up?", "What prevents two concurrent requests with the same idempotency key from both executing the charge?"],
    },
    {
      id: "q-sdi-payment-2",
      type: "multiple-choice",
      difficulty: "hard",
      question: "A checkout flow spans three microservices: Order Service, Inventory Service, and Payment Service. Which distributed transaction pattern is most appropriate for ensuring eventual consistency across all three?",
      options: ["Two-phase commit (2PC) coordinated by the Order Service", "Saga pattern with compensating transactions (e.g., cancel order if payment fails)", "Single synchronous database transaction across all three services", "Eventual consistency with no explicit coordination"],
      correctAnswer: 1,
      explanation: "2PC requires all participants to hold locks during the prepare phase - across three different services with their own databases, this creates long lock windows and is fragile to coordinator failure. The Saga pattern decomposes the transaction into local transactions, each publishing events: (1) Order created  ->  (2) Inventory reserved  ->  (3) Payment charged. If Payment fails, compensating transactions run in reverse: (2) Release inventory  ->  (1) Cancel order. Sagas trade strong consistency for availability and fault tolerance, which is appropriate for cross-service workflows where each service owns its own database.",
      hints: ["2PC works well when all participants share the same database system. What happens when they are separate microservices?", "What is a 'compensating transaction' and how does it roll back work that has already been committed?"],
    },
    {
      id: "q-sdi-payment-3",
      type: "multiple-choice",
      difficulty: "hard",
      question: "A user has $100 in their account and two concurrent requests attempt to debit $80 and $70 simultaneously (both read balance=$100). Without proper locking, both succeed, leaving -$50. Which database construct prevents this race condition?",
      options: ["Database index on account_id for faster reads", "SELECT FOR UPDATE on the account balance row, which acquires an exclusive lock until the transaction commits", "Optimistic locking with a version counter (read version, write with WHERE version=N)", "READ COMMITTED isolation level"],
      correctAnswer: 1,
      explanation: "SELECT FOR UPDATE acquires a pessimistic exclusive row lock immediately when the balance is read: 'SELECT balance FROM accounts WHERE id=? FOR UPDATE'. The second concurrent transaction blocks on this SELECT until the first transaction commits (deducting $80, leaving $20) then reads the updated balance $20. Since $20 < $70, the second debit is rejected. Optimistic locking (option C) is also valid but requires retry logic on conflict. READ COMMITTED isolation alone does not prevent this 'lost update' anomaly without explicit locking.",
      hints: ["Both transactions read the same stale balance because nothing prevents concurrent reads. What SQL clause forces a read to block until previous writes on the same row are committed?", "What is the difference between optimistic and pessimistic concurrency control in terms of when conflicts are detected?"],
    },
    {
      id: "q-sdi-payment-4",
      type: "true-false",
      difficulty: "medium",
      question: "PCI DSS compliance requires that payment systems store the full 16-digit primary account number (PAN) in their application database for processing future charges to the same card.",
      correctAnswer: "False",
      explanation: "False. PCI DSS explicitly prohibits storing the full PAN in application databases after authorization. The standard approach is tokenization: the raw card number is sent to a PCI-compliant payment vault (Stripe, Braintree, or a dedicated HSM-backed vault), which returns a non-reversible token (e.g., 'tok_abc123'). Only this token is stored in the application database. For display purposes, only the last 4 digits may be stored. The vault maps tokens back to raw PANs only during charge processing, and the vault itself is isolated in a separate PCI-compliant environment.",
      hints: ["If a hacker breaches your application database, what data could they extract?", "What is the purpose of a payment 'token' relative to the actual card number?"],
    },
  ],

  "sdi-real-time-leaderboard": [
    {
      id: "q-sdi-lb-1",
      type: "multiple-choice",
      difficulty: "medium",
      question: "A real-time game leaderboard needs to support: (1) update a player's score, (2) get the global top-100 players, (3) get a specific player's rank. Which Redis data structure and commands implement all three operations in O(log n) or better?",
      options: ["Redis Hash - HSET score, HGETALL for top-100", "Redis Sorted Set - ZADD for updates, ZREVRANGE for top-K, ZRANK for individual rank", "Redis List - LPUSH for scores, LRANGE for top-100", "Redis String - INCR for score, full scan for rank"],
      correctAnswer: 1,
      explanation: "Redis Sorted Sets (ZSETs) are the canonical solution: ZADD leaderboard score user_id is O(log n) and updates existing scores automatically. ZREVRANGE leaderboard 0 99 WITHSCORES returns the top 100 in O(log n + 100) time. ZRANK leaderboard user_id returns a 0-indexed rank in O(log n). Internally, Redis implements sorted sets using a skip list for ordering and a hash map for O(1) member-to-score lookup. This combination makes all three operations efficient at scale.",
      hints: ["Redis Sorted Sets maintain elements ordered by score automatically. What operations would you need for each of the three requirements?", "ZADD, ZREVRANGE, and ZRANK are all O(log n). How does this compare to a full scan approach?"],
    },
    {
      id: "q-sdi-lb-2",
      type: "multiple-choice",
      difficulty: "hard",
      question: "A global leaderboard for 1 billion players is sharded across 10 Redis nodes by user_id hash. A request comes in for the global top-10 players. What is the minimum number of nodes that must be queried, and how are results merged?",
      options: ["1 node - the shard with the highest scores can be determined from the hash", "All 10 nodes - query top-10 from each shard, then merge and take the global top-10 from 100 candidates", "2 nodes - primary and replica", "0 nodes - a dedicated global aggregator node maintains the merged leaderboard"],
      correctAnswer: 1,
      explanation: "With user_id hash sharding, any shard can contain a top player - you cannot know which shard holds the globally top-ranked user without querying all shards. The fan-out/gather pattern: query all N shards for their top-K candidates (each returns up to 10), collect N\$\\times\$K candidates (100 total), then perform a final merge sort on the coordinator to select the global top-K=10. This is the classic distributed top-K problem. Some architectures maintain a separate small 'global leaderboard' Redis instance updated by a streaming aggregator to avoid this fan-out on every read.",
      hints: ["User ID hashing distributes users randomly. Could the globally top-ranked player end up on any shard?", "If each of 10 shards returns its local top-10, how many candidates do you have to find the global top-10 from?"],
    },
  ],
};

registerQuestions(questions);
