import type { Question } from "@/lib/curriculum";
import { registerQuestions } from "./registry";

const questions: Record<string, Question[]> = {
  "sdi-stream-kafka": [
    {
      id: "q-sdi-stream-1",
      type: "multiple-choice",
      difficulty: "medium",
      question: "In Kafka, how many consumers within the same consumer group can read from a single partition at any given time?",
      options: ["As many as needed for throughput", "Exactly one", "Two — one primary, one standby", "Up to the replication factor"],
      correctAnswer: 1,
      explanation: "Kafka guarantees that each partition is consumed by exactly one consumer within a consumer group at a time. This is the core mechanism that provides ordering guarantees within a partition. If you have more consumers than partitions in a group, the extra consumers sit idle. The maximum parallelism for a consumer group equals the number of partitions in the topic.",
      hints: ["Think about how Kafka maintains ordering — if two consumers read the same partition simultaneously, how would ordering be preserved?", "Parallelism in Kafka is bounded by the number of partitions, not the number of consumers."],
    },
    {
      id: "q-sdi-stream-2",
      type: "multiple-choice",
      difficulty: "hard",
      question: "A Kafka producer is configured with acks=1. Which scenario best describes the durability guarantee this provides?",
      options: ["The message is lost if the network drops before any broker receives it, and also if the leader crashes before replicating to followers", "The message is guaranteed durable as long as at least one in-sync replica is alive", "The message is persisted to disk on all in-sync replicas before acknowledgment", "The producer receives no acknowledgment and assumes success after a timeout"],
      correctAnswer: 0,
      explanation: "With acks=1, the leader broker acknowledges the message after writing it to its local log, without waiting for followers to replicate. If the leader crashes immediately after acknowledging but before any follower has replicated the message, the message is lost (unclean leader election). acks=all (or acks=-1) waits for all in-sync replicas to acknowledge, providing the strongest durability guarantee. acks=0 is fire-and-forget with no acknowledgment at all.",
      hints: ["acks=1 means only the partition leader confirms receipt — what happens if that leader dies before followers catch up?", "Compare to acks=all which waits for the entire in-sync replica set (ISR) to confirm."],
    },
    {
      id: "q-sdi-stream-3",
      type: "multiple-choice",
      difficulty: "medium",
      question: "What is the primary purpose of Kafka log compaction, and how does it differ from time-based or size-based retention?",
      options: ["Log compaction compresses messages with gzip to reduce storage; time/size retention deletes old messages", "Log compaction retains only the most recent message per key, enabling Kafka to serve as a changelog store; time/size retention deletes messages based on age or total log size regardless of key", "Log compaction merges small segment files into larger ones to improve read throughput; time/size retention controls segment rollover", "Log compaction removes duplicate messages sent by producers; time/size retention removes messages consumers have already read"],
      correctAnswer: 1,
      explanation: "Log compaction ensures that for each unique message key, Kafka retains at least the most recent value. This makes the compacted topic act as a key-value store — consumers starting from the beginning get a full snapshot of the latest state. It is used for changelog topics in Kafka Streams and for database CDC (change data capture) where you want the current state of each entity. Time/size retention simply purges old segments without regard to keys, so you can lose the latest state of an entity if it was last updated before the retention window.",
      hints: ["Think of log compaction as maintaining a 'last known value' per key — useful when you need to reconstruct current state.", "Time-based retention treats all messages equally regardless of their key; compaction treats them by key."],
    },
    {
      id: "q-sdi-stream-4",
      type: "multiple-choice",
      difficulty: "medium",
      question: "A Kafka consumer group is processing a topic with 12 partitions. The team scales from 8 to 16 consumer instances. What happens to the extra 4 consumers?",
      options: ["They form a second consumer group automatically and consume from all partitions", "They share partitions with the existing 8 consumers, doubling throughput per partition", "They remain idle because partition count caps the parallelism of a single consumer group", "Kafka automatically adds 4 more partitions to match the consumer count"],
      correctAnswer: 2,
      explanation: "In a single Kafka consumer group, each partition is assigned to exactly one consumer. With 12 partitions and 16 consumers, only 12 consumers are active; the remaining 4 sit idle and serve as hot standbys. They will become active if one of the 12 active consumers fails and a rebalance occurs. To increase parallelism beyond 12, you must increase the partition count — this is an irreversible operation (partitions can only be added, not removed), so capacity planning is important.",
      hints: ["The ceiling on a consumer group's parallelism is set at topic creation time via the partition count.", "The 4 idle consumers are not wasted — they provide instant failover capacity during rebalancing."],
    },
    {
      id: "q-sdi-stream-5",
      type: "multiple-choice",
      difficulty: "hard",
      question: "What does 'consumer lag' measure in Kafka and why is it the most critical operational metric to monitor?",
      options: ["The network latency between producer and broker, measured in milliseconds", "The difference between the latest committed offset and the consumer's current offset per partition, indicating how far behind consumers are from producers", "The time taken for a message to be replicated across all in-sync replicas", "The number of failed consumer poll() calls due to rebalances"],
      correctAnswer: 1,
      explanation: "Consumer lag is the difference between the log end offset (where the producer is writing) and the committed offset (where the consumer has processed up to) for each partition. A growing lag means consumers cannot keep up with producer throughput, leading to increasing end-to-end latency or eventual data loss if retention expires before processing. Monitoring consumer lag (via Burrow, Kafka consumer_lag metrics, or kMinion) is essential — a spike often precedes SLA breaches and indicates the need to scale consumers or optimize processing.",
      hints: ["If producer offset is 10,000 and consumer committed offset is 9,500, the lag is 500 messages.", "Lag growing over time is more alarming than a constant lag — it means the gap is widening."],
    },
  ],

  "sdi-stream-flink": [
    {
      id: "q-sdi-stream-6",
      type: "multiple-choice",
      difficulty: "hard",
      question: "In Apache Flink, what is the key difference between keyed state and operator state?",
      options: ["Keyed state is stored in RocksDB; operator state is stored in heap memory only", "Keyed state is scoped per key within a keyed stream, partitioned and scaled automatically; operator state is scoped per operator task instance, not partitioned by key", "Keyed state supports exactly-once; operator state supports at-least-once only", "Keyed state is for batch jobs; operator state is for streaming jobs"],
      correctAnswer: 1,
      explanation: "In Flink, keyed state is associated with a specific key in a KeyedStream (after keyBy()). Each key has its own isolated state, and Flink automatically partitions this state across parallel subtasks — when you scale, state migrates with its key. Operator state is per-task-instance state that is not partitioned by key — examples include Kafka source partition offsets stored per source task. Keyed state supports richer backends (RocksDB for large state) and is far more common in stateful streaming applications like aggregations, joins, and pattern detection.",
      hints: ["keyBy() is the prerequisite for using keyed state — the state is isolated per unique key value.", "Kafka source connector uses operator state to remember which offset it has read from each partition."],
    },
    {
      id: "q-sdi-stream-7",
      type: "multiple-choice",
      difficulty: "hard",
      question: "A Flink streaming job processes clickstream events where events can arrive up to 5 minutes late. Which mechanism should be used to handle out-of-order events correctly?",
      options: ["Use processing time windows with a 5-minute offset parameter", "Use event time with watermarks set to current_event_time minus 5 minutes, and assign events to event-time windows", "Use session windows with a 5-minute gap threshold", "Enable exactly-once semantics in the Flink checkpoint configuration"],
      correctAnswer: 1,
      explanation: "Event time processing uses the timestamp embedded in the event itself rather than the wall clock. To handle late arrivals, Flink uses watermarks — a monotonically increasing timestamp that asserts 'all events with time <= watermark have arrived'. A watermark of event_time - 5min means Flink waits 5 minutes of event time before triggering a window, accommodating up to 5 minutes of out-of-order delivery. Events arriving after the watermark has passed the window boundary are considered 'late' and can be handled via side outputs or allowedLateness. Processing time (wall clock) cannot handle out-of-order events at all.",
      hints: ["Watermarks are the mechanism Flink uses to know 'I've seen enough events; now I can close this time window'.", "A watermark of T means: no more events with timestamp < T will arrive. Setting it to current_max_event_time - 5min accommodates 5-minute delays."],
    },
    {
      id: "q-sdi-stream-8",
      type: "multiple-choice",
      difficulty: "medium",
      question: "What is the difference between tumbling windows and sliding windows in Flink stream processing?",
      options: ["Tumbling windows overlap; sliding windows do not overlap", "Tumbling windows are non-overlapping fixed-size windows; sliding windows overlap because the slide interval is smaller than the window size", "Tumbling windows are gap-based; sliding windows are count-based", "They are equivalent but tumbling windows have lower memory overhead"],
      correctAnswer: 1,
      explanation: "Tumbling windows divide the stream into consecutive, non-overlapping fixed-size buckets (e.g., every 1 hour). Each event belongs to exactly one window. Sliding windows have a fixed size and a slide interval smaller than the window size — for example, a 1-hour window sliding every 15 minutes means each event belongs to 4 overlapping windows (1 hour / 15 min). Sliding windows are useful for rolling metrics (e.g., 'clicks in the last hour, updated every 15 minutes') but consume more state. Session windows are a third type: gap-based, where a window closes after a period of inactivity.",
      hints: ["If the slide interval equals the window size, a sliding window becomes a tumbling window.", "A 60-minute sliding window with a 10-minute slide interval means each event is counted in 6 different windows."],
    },
    {
      id: "q-sdi-stream-9",
      type: "multiple-choice",
      difficulty: "hard",
      question: "How does Flink achieve exactly-once end-to-end semantics when reading from Kafka and writing to Kafka?",
      options: ["Flink deduplicates messages using message UUIDs stored in a distributed cache", "Flink uses the two-phase commit (2PC) protocol: checkpoints snapshot operator state and Kafka offsets atomically, and Flink's Kafka sink uses Kafka transactions to commit output only after the checkpoint completes", "Flink replays the entire stream from the beginning on any failure, discarding previous output", "Flink writes to Kafka with idempotent producers which automatically deduplicate at the broker"],
      correctAnswer: 1,
      explanation: "Flink's exactly-once with Kafka uses the Chandy-Lamport distributed snapshot algorithm for checkpointing combined with Kafka transactions. During a checkpoint, Flink flushes all in-flight Kafka sink records to a pre-commit transaction but does not commit it. Once all operators have successfully snapshotted their state (including Kafka source offsets) and the checkpoint is confirmed durable, the Kafka sink commits the transaction. On failure, Flink restores from the last successful checkpoint — the uncommitted Kafka transaction is aborted, and the Kafka source replays from the checkpointed offset. This means each record is processed exactly once end-to-end.",
      hints: ["Think of the checkpoint as a consistent cut through the entire job — it captures both input position (Kafka offsets) and output state (uncommitted transactions).", "Kafka transactions allow a producer to write a batch of messages that become visible to consumers only after an explicit commit."],
    },
  ],

  "sdi-stream-spark": [
    {
      id: "q-sdi-stream-10",
      type: "multiple-choice",
      difficulty: "medium",
      question: "Which of the following best describes the key advantage of Spark DataFrames over RDDs?",
      options: ["DataFrames support Java and Scala only; RDDs support Python too", "DataFrames are untyped at compile time giving more flexibility; RDDs are strongly typed", "DataFrames benefit from Catalyst query optimizer and Tungsten execution engine which optimize execution plans automatically; RDDs bypass this optimization", "DataFrames do not support custom transformations; RDDs allow arbitrary code"],
      correctAnswer: 2,
      explanation: "Spark DataFrames (and Datasets) are processed through the Catalyst optimizer, which rewrites logical plans into optimized physical plans — pushing down filters, reordering joins, eliminating unnecessary columns. The Tungsten engine uses code generation for CPU-efficient execution and off-heap memory for GC pressure reduction. RDDs are an unoptimized execution model: Spark executes exactly the transformations you write with no query planning. In practice, the same operation on a DataFrame can be 2-10x faster than the equivalent RDD code. The tradeoff: RDDs give you full control over the execution (useful for non-tabular operations).",
      hints: ["Catalyst is Spark's SQL query optimizer — it rewrites your DataFrame operations before running them.", "Running a filter() on an RDD versus a DataFrame: the DataFrame version may push the filter before a join, avoiding processing unnecessary rows."],
    },
    {
      id: "q-sdi-stream-11",
      type: "multiple-choice",
      difficulty: "medium",
      question: "What is the fundamental difference between Spark Streaming (DStream API) and Structured Streaming?",
      options: ["Spark Streaming processes data continuously; Structured Streaming only supports micro-batch mode", "Spark Streaming is built on RDDs with time-based micro-batches; Structured Streaming treats a stream as an unbounded DataFrame with Catalyst optimization, event-time support, and optional continuous processing mode", "Structured Streaming requires Kafka; Spark Streaming supports any source", "They are architecturally identical but Structured Streaming has a different API"],
      correctAnswer: 1,
      explanation: "Spark Streaming (legacy DStream API) batches incoming data into RDDs over fixed time intervals and processes each RDD independently — there is no native event-time support or query optimization. Structured Streaming (Spark 2.0+) models the stream as an infinite append-only table using the DataFrame/Dataset API. This enables Catalyst optimization, event-time windowing with watermarks, stateful operations, and built-in exactly-once output modes (complete, append, update). Structured Streaming supports both micro-batch (default, low latency ~100ms) and experimental continuous processing mode (sub-millisecond latency). The DStream API is in maintenance mode.",
      hints: ["Structured Streaming inherits all of the SQL/DataFrame optimization stack — the same code that runs on a static DataFrame can often run on a stream.", "Event-time windows in Structured Streaming work the same way as in Flink — they require watermarks."],
    },
    {
      id: "q-sdi-stream-12",
      type: "multiple-choice",
      difficulty: "hard",
      question: "A Spark job performing a join between a 10 TB dataset and a 100 GB dataset is running very slowly due to excessive shuffle. What is the most effective optimization?",
      options: ["Increase executor memory to store both datasets in memory", "Repartition both datasets to 10,000 partitions before the join", "Broadcast the smaller 100 GB dataset to all executors, eliminating the shuffle entirely, or pre-partition both datasets by join key to co-locate matching records", "Switch from DataFrames to RDDs to avoid Catalyst overhead"],
      correctAnswer: 2,
      explanation: "Shuffle in Spark (during joins, groupBy, distinct) is the most expensive operation because it moves data across the network. Two strategies: (1) Broadcast join — if one dataset is small enough to fit in executor memory (typically < 8-10 GB; 100 GB is too large but the principle applies for smaller tables), replicate it to all executors so the join is local. (2) Co-partition — repartition both datasets by the same join key before the join, so matching rows are on the same executor and no shuffle is needed during the join itself. Data skew (hotspot keys) can be addressed with key salting — adding a random prefix to distribute a hot key across multiple partitions.",
      hints: ["Shuffle requires serializing data, sending it over the network, and deserializing — this is orders of magnitude slower than in-memory computation.", "If both sides of a join are partitioned identically by the join key, Spark can perform the join locally on each partition with no data movement."],
    },
    {
      id: "q-sdi-stream-13",
      type: "multiple-choice",
      difficulty: "hard",
      question: "A Spark job is failing with OutOfMemoryError on executors processing a groupBy aggregation. Profiling shows 95% of data maps to 10 keys out of 1 million. What is the recommended fix?",
      options: ["Increase executor memory to 128 GB per node", "Enable Spark adaptive query execution (AQE) and set spark.sql.adaptive.skewJoin.enabled=true", "Salt the skewed keys by appending a random integer suffix (0 to N-1) before groupBy, then aggregate in two stages to merge the salted partial results", "Switch to a HashPartitioner with a higher number of buckets"],
      correctAnswer: 2,
      explanation: "Key skew causes a few partitions to hold a disproportionate share of data, overwhelming those executors while others sit idle. The salting technique appends a random suffix (e.g., key+'_'+random(0,9)) to each key before the first aggregation — this spreads the hot key across 10 partitions processed in parallel. A second aggregation then strips the suffix and merges the partial results. AQE's skew join optimization (option B) helps for joins but does not address groupBy aggregation skew directly. Increasing memory treats the symptom, not the cause, and may not scale.",
      hints: ["If 'user_id=42' appears 90% of the time, appending a random 0-9 suffix creates 10 variants, each going to a different partition.", "Two-stage aggregation: first aggregate with salted key, then aggregate again with the real key to combine partial results."],
    },
  ],

  "sdi-stream-data-warehouse": [
    {
      id: "q-sdi-stream-14",
      type: "multiple-choice",
      difficulty: "easy",
      question: "What is the fundamental storage layout difference between OLTP and OLAP databases, and why does it matter for query performance?",
      options: ["OLTP stores data in binary format; OLAP stores data in JSON format", "OLTP uses row-oriented storage optimized for reading/writing complete records; OLAP uses column-oriented storage optimized for scanning specific columns across many rows", "OLTP uses SSDs; OLAP uses magnetic disks for cost efficiency", "OLTP is distributed; OLAP runs on a single node"],
      correctAnswer: 1,
      explanation: "OLTP (Online Transaction Processing) stores each row's columns together on disk — ideal for fetching or updating a complete record (e.g., one customer's order). OLAP (Online Analytical Processing) stores each column's values together — ideal for analytical queries that scan a single column across millions of rows (e.g., SUM(revenue) across all orders). Column storage achieves high compression ratios because similar data is stored together, and I/O is reduced by reading only the queried columns. BigQuery, Snowflake, Redshift, and ClickHouse are columnar; PostgreSQL and MySQL are row-oriented.",
      hints: ["An analytics query like 'average order value this month' reads the amount column from millions of rows — column storage reads only that column, not all columns.", "Compression works better on columnar stores because a column contains homogeneous values (e.g., all integers, all dates)."],
    },
    {
      id: "q-sdi-stream-15",
      type: "multiple-choice",
      difficulty: "medium",
      question: "In a star schema data warehouse, what is the relationship between the fact table and dimension tables, and why is this structure preferred for OLAP queries?",
      options: ["The fact table contains descriptive attributes; dimension tables contain numerical metrics for aggregation", "The fact table contains measurable events/metrics (e.g., order_amount, click_count) with foreign keys to dimension tables (users, products, dates) which contain descriptive attributes; this denormalization avoids joins during aggregation", "Star schema is fully normalized into 3NF to eliminate data redundancy, improving write performance", "Dimension tables are updated in real-time; the fact table is append-only"],
      correctAnswer: 1,
      explanation: "In a star schema, the central fact table records events or transactions with numerical measures (e.g., sale_amount, quantity_sold) and foreign keys pointing to dimension tables. Dimension tables (e.g., dim_customer, dim_product, dim_date) contain descriptive attributes that rarely change. The schema is intentionally denormalized — a customer's city is stored directly in dim_customer rather than in a separate city table — to minimize join depth. OLAP queries join the fact table to one or two dimensions, and because dimension tables are small and can be broadcast, these joins are fast. The snowflake schema further normalizes dimension tables but increases query complexity.",
      hints: ["Think of the fact table as your event log (what happened, how much) and dimension tables as context (who, what product, when).", "Denormalization trades storage for query speed — the same city name may be repeated in dim_customer, but analytics queries are much faster."],
    },
    {
      id: "q-sdi-stream-16",
      type: "multiple-choice",
      difficulty: "hard",
      question: "A BigQuery table stores 5 years of clickstream data (10 TB). Queries always filter by date range and group by user_id. Which combination of table features will minimize query cost?",
      options: ["Cluster by date, partition by user_id", "Partition by date column, cluster by user_id", "Use a materialized view that pre-aggregates all data by user_id and date", "Shard the table into separate tables per year"],
      correctAnswer: 1,
      explanation: "BigQuery partitioning by a date/timestamp column allows the query engine to skip entire partitions that fall outside the WHERE clause date range — this is partition pruning and directly reduces bytes scanned (= cost). Within each partition, clustering by user_id physically sorts the data so that queries filtering or grouping by user_id scan fewer blocks. Clustering is most effective when the clustering column has high cardinality and is frequently used in filters or GROUP BY. Combining partition pruning + clustering typically reduces bytes scanned by 80-95% for common query patterns. Sharding into separate tables is a manual anti-pattern that BigQuery's partitioning replaces.",
      hints: ["Partitioning eliminates entire date partitions not in your WHERE clause before any data is read.", "Clustering sorts data within a partition — if your query filters on user_id, BigQuery reads only the relevant byte ranges within the partition."],
    },
    {
      id: "q-sdi-stream-17",
      type: "multiple-choice",
      difficulty: "medium",
      question: "What is a materialized view in a data warehouse, and what is the primary tradeoff compared to a regular view?",
      options: ["A materialized view is a view with indexes; a regular view has no indexes. No storage difference.", "A materialized view stores precomputed query results physically on disk and is refreshed periodically; a regular view re-executes the underlying query on every access. Tradeoff: storage cost and potential staleness vs query speed.", "A materialized view is only available in BigQuery; regular views are standard SQL", "A materialized view is always up to date because it uses triggers; a regular view may return stale data"],
      correctAnswer: 1,
      explanation: "A materialized view physically persists the result of a query — when a user queries the materialized view, they read the precomputed result rather than re-running an expensive aggregation over raw data. This can reduce query latency from minutes to milliseconds. The tradeoffs: (1) Storage: the result set occupies storage. (2) Staleness: results are only as fresh as the last refresh (scheduled or triggered). (3) Refresh cost: refreshing a materialized view consumes compute. For dashboards showing yesterday's data, this is acceptable. For real-time monitoring, a streaming table or approximate indexes are better. Some systems (BigQuery, Redshift) support incremental refresh that only reprocesses changed data.",
      hints: ["Think of a materialized view as a cached query result — fast to read, but potentially stale.", "The refresh schedule determines the latency tradeoff: refresh every hour means data is up to 1 hour old."],
    },
  ],

  "sdi-stream-etl": [
    {
      id: "q-sdi-stream-18",
      type: "multiple-choice",
      difficulty: "easy",
      question: "What is the practical difference between ETL and ELT pipelines, and when is ELT preferred?",
      options: ["ETL uses Python; ELT uses SQL. The choice is purely a language preference.", "ETL transforms data before loading it into the destination (requires a transformation layer outside the warehouse); ELT loads raw data first then transforms inside the warehouse using its compute. ELT is preferred when the warehouse has powerful compute (BigQuery, Snowflake) and raw data retention is valuable.", "ETL is for batch processing; ELT is for real-time streaming only", "ETL writes to object storage; ELT writes directly to RDBMS"],
      correctAnswer: 1,
      explanation: "In traditional ETL, raw data is extracted from sources, transformed (cleaned, joined, filtered) in an external compute layer (e.g., Spark, Python), and only the cleaned data is loaded into the warehouse — the raw data may be discarded. In ELT, raw data is loaded directly into the warehouse (cheap object storage in modern cloud DWs), and transformation happens inside the warehouse using SQL compute (dbt is a popular tool for ELT transformations). ELT is preferred because: (1) raw data is preserved for future reprocessing, (2) modern warehouses have elastic compute that scales for transformation, (3) transformations can be iterated in SQL without rebuilding an external pipeline. ETL is still useful when heavy data cleaning or PII masking must happen before data enters the warehouse.",
      hints: ["dbt (data build tool) is the canonical ELT transformation layer — it writes SQL SELECT statements that define transformations inside the warehouse.", "ELT's 'load raw first' approach means you can reprocess historical data if your transformation logic changes."],
    },
    {
      id: "q-sdi-stream-19",
      type: "multiple-choice",
      difficulty: "hard",
      question: "A data pipeline loads user events into a warehouse and is designed to be retried on failure. Which approach makes the pipeline idempotent?",
      options: ["Use INSERT INTO on every run, which automatically deduplicates using the warehouse's built-in UNIQUE constraint", "Use MERGE (UPSERT) on the natural key of the record, so re-running the pipeline for the same input data updates existing records rather than inserting duplicates", "Add a pipeline_run_id column and query the warehouse to skip already-processed records before inserting", "Use append-only inserts and deduplicate downstream in the analytics queries using ROW_NUMBER()"],
      correctAnswer: 1,
      explanation: "An idempotent pipeline produces the same result regardless of how many times it is run with the same input. INSERT INTO without deduplication is not idempotent — retrying creates duplicates. The standard solution is MERGE/UPSERT: for each incoming record, if a record with the same natural key exists in the destination, update it; otherwise, insert it. This makes the pipeline safe to retry after any failure. BigQuery supports MERGE, Snowflake supports MERGE, and most modern warehouses do too. Using a pipeline_run_id (option C) works but requires reading existing data before each load, which is expensive at scale. Deduplicating in queries (option D) is a workaround but doesn't fix the underlying data quality problem.",
      hints: ["Idempotent means: running the same operation twice has the same effect as running it once — like a safe 'apply state' rather than an 'append event'.", "MERGE on a natural key (e.g., event_id, user_id + date) ensures each logical record exists exactly once in the destination."],
    },
    {
      id: "q-sdi-stream-20",
      type: "multiple-choice",
      difficulty: "medium",
      question: "A data team wants to rename a column user_id to customer_id in a widely-used warehouse table. Which approach handles schema evolution safely?",
      options: ["Rename the column directly in the table — downstream queries will automatically update column references", "Add the new customer_id column as a copy of user_id (backward compatible), migrate downstream consumers to use customer_id, then drop user_id after all consumers are updated", "Drop the table and recreate it with the new schema, backfilling from source systems", "Use a view that aliases user_id as customer_id so no migration is needed"],
      correctAnswer: 1,
      explanation: "Renaming or deleting columns is a breaking change — any downstream queries, dashboards, or pipelines referencing user_id will fail immediately. Safe schema evolution follows these rules: (1) Adding nullable columns is always backward compatible. (2) Renaming requires a multi-step migration: add the new column, dual-write to both, migrate consumers, deprecate the old column, then drop it after a safe window. (3) Never drop columns without verifying zero downstream dependencies. In practice, teams use a view (option D) as a transitional shim, but eventually the view must be replaced with direct column access. The expand-contract pattern (add → migrate → remove) is the industry standard for zero-downtime schema changes.",
      hints: ["Schema evolution rule: you can add nullable columns safely; you cannot rename or delete columns without a migration plan.", "The expand-contract pattern: expand the schema (add new column), contract it (remove old column) only after all consumers have migrated."],
    },
    {
      id: "q-sdi-stream-21",
      type: "multiple-choice",
      difficulty: "medium",
      question: "Which of the following is NOT a standard data quality check that should be applied to a data pipeline in production?",
      options: ["Null rate: the fraction of null values in a required column should be below a threshold", "Row count validation: the number of rows loaded matches expectations based on source row count or historical patterns", "Query plan validation: verifying the optimizer chose the correct join strategy for each pipeline run", "Referential integrity: every foreign key in the fact table has a corresponding record in the dimension table"],
      correctAnswer: 2,
      explanation: "Data quality checks in pipelines focus on data correctness, not query execution plans. Standard checks include: null rate (critical columns should not exceed X% nulls), row count (e.g., daily events should be within +/-20% of the 30-day average), referential integrity (orphaned foreign keys indicate upstream data issues), value range checks (e.g., age must be 0-150), schema conformance (expected columns exist with expected types), and duplicate detection. Tools like Great Expectations and dbt tests automate these. Query plan validation (option C) is a performance optimization concern, not a data quality check — it does not detect incorrect or missing data.",
      hints: ["Data quality checks answer: 'Is the data correct and complete?' — not 'Is the database running efficiently?'", "Great Expectations and dbt tests are the most common frameworks for automated data quality validation in modern pipelines."],
    },
  ],

  "sdi-stream-metrics": [
    {
      id: "q-sdi-stream-22",
      type: "multiple-choice",
      difficulty: "medium",
      question: "What is the key architectural difference between Prometheus's pull model and a push-based metrics system like StatsD?",
      options: ["Prometheus requires agents on every host; StatsD is agentless", "In Prometheus, the server scrapes a /metrics HTTP endpoint on each target at a configured interval; in push-based systems, applications send metrics to a central collector proactively", "Prometheus stores metrics in object storage; StatsD uses a relational database", "Pull models have higher latency than push models by definition"],
      correctAnswer: 1,
      explanation: "Prometheus uses a pull model: the Prometheus server sends HTTP GET requests to /metrics endpoints exposed by each monitored service, typically every 15 seconds. This means Prometheus controls the scrape rate and can detect when targets go down (no response = target down alert). The pull model also makes it easy to add new services without reconfiguring a central collector. Push-based systems (StatsD, CloudWatch, InfluxDB with Telegraf) have applications send metrics to a central aggregator — better for ephemeral jobs (e.g., batch jobs that finish before a scrape occurs). The Prometheus Pushgateway bridges this: short-lived jobs push to the gateway, which Prometheus then scrapes.",
      hints: ["Pull: Prometheus asks 'what are your metrics?' every 15s. Push: the application says 'here are my metrics' whenever it wants.", "Pushgateway exists specifically for batch jobs and functions that finish too quickly to be scraped."],
    },
    {
      id: "q-sdi-stream-23",
      type: "multiple-choice",
      difficulty: "hard",
      question: "A Prometheus TSDB is growing to 500 GB and needs to retain 2 years of data with efficient long-term querying. Which architecture addresses this?",
      options: ["Increase local SSD storage to 10 TB and extend Prometheus retention to 730 days", "Use Thanos or Cortex: sidecar uploads Prometheus TSDB blocks to object storage (S3/GCS), downsample old data, and serve long-term queries via a query layer that federates local and remote data", "Deploy a separate Prometheus instance per month and federate them all into a meta-Prometheus", "Export all metrics to a PostgreSQL time-series extension and query with SQL"],
      correctAnswer: 1,
      explanation: "Prometheus's local TSDB is designed for short-term retention (15 days default, ~2 weeks typical). For long-term retention, Thanos and Cortex are the standard solutions. Thanos adds a sidecar to each Prometheus instance that uploads completed 2-hour TSDB blocks to object storage (S3, GCS). Old data is downsampled (5-minute resolution after 40 days, 1-hour resolution after 1 year) to reduce storage and query time. The Thanos Query layer provides a unified view across all Prometheus instances and object storage. This approach provides: unlimited retention, global query view across multiple Prometheus shards, and high availability.",
      hints: ["Prometheus is not designed for multi-year retention on local disk — it's optimized for recent data and fast scraping.", "Thanos's downsampling rule: raw data for <40 days, 5-minute aggregates for <1 year, 1-hour aggregates for >1 year."],
    },
    {
      id: "q-sdi-stream-24",
      type: "multiple-choice",
      difficulty: "medium",
      question: "In Prometheus alerting, what is the role of AlertManager and how does it prevent alert storms?",
      options: ["AlertManager evaluates PromQL rules and fires alerts; Prometheus routes them to PagerDuty", "Prometheus evaluates PromQL alert rules and sends alerts to AlertManager, which handles deduplication (groups repeated alerts into one), grouping (combines related alerts), inhibition (suppresses low-priority alerts when high-priority ones fire), and routing to receivers (PagerDuty, Slack, email)", "AlertManager stores alert history in a time-series database for trend analysis", "AlertManager is only used for SLA reporting — not for real-time alerting"],
      correctAnswer: 1,
      explanation: "The alerting pipeline in Prometheus is: Prometheus evaluates PromQL alert expressions every evaluation_interval — when a condition is true for longer than the 'for' duration, the alert fires and is sent to AlertManager. AlertManager then applies: (1) Grouping — multiple alerts from the same service are batched into one notification. (2) Deduplication — the same alert firing from multiple Prometheus replicas is deduplicated. (3) Inhibition — if a datacenter-down alert fires, AlertManager suppresses all individual-service alerts from that datacenter. (4) Silencing — planned maintenance windows suppress known alerts. (5) Routing — alerts are dispatched to the correct team via PagerDuty/OpsGenie/Slack based on labels. Without AlertManager, a single incident could generate thousands of individual alerts.",
      hints: ["AlertManager's grouping + deduplication prevents a single outage from generating hundreds of pages for each affected service separately.", "Inhibition is the most powerful tool: if a root cause alert fires (e.g., host down), suppress all its symptoms (e.g., all services on that host)."],
    },
    {
      id: "q-sdi-stream-25",
      type: "multiple-choice",
      difficulty: "easy",
      question: "A Grafana dashboard shows a metric query returning data from both Prometheus and ClickHouse on the same panel. What does this demonstrate about Grafana's architecture?",
      options: ["Grafana stores data from all sources in a unified internal database", "Grafana is a visualization layer that queries multiple data sources (Prometheus, ClickHouse, BigQuery, CloudWatch, etc.) directly and renders them in panels — it does not store metric data itself", "Grafana can only show data from a single data source per dashboard", "ClickHouse must export data to Prometheus before Grafana can query it"],
      correctAnswer: 1,
      explanation: "Grafana is a pure visualization and querying tool — it stores no time-series data. It connects to data source plugins (Prometheus, ClickHouse, BigQuery, Loki, Elasticsearch, CloudWatch, and 100+ others) and issues queries directly to each source when a panel renders. A single panel can query multiple sources and overlay the results. This architecture makes Grafana the de facto standard for operational dashboards because teams can mix real-time metrics (from Prometheus) with historical analytics (from ClickHouse or BigQuery) on the same dashboard. Panel types include time-series graphs, gauges, tables, heatmaps, stat panels, and bar charts.",
      hints: ["Grafana's job is to draw charts — it delegates the data storage and query execution entirely to the configured data sources.", "A Prometheus panel uses PromQL; a ClickHouse panel uses SQL — Grafana sends each query to the correct backend."],
    },
  ],

  "sdi-stream-batch": [
    {
      id: "q-sdi-stream-26",
      type: "multiple-choice",
      difficulty: "medium",
      question: "In the MapReduce programming model, what happens during the 'shuffle' phase and why is it the most expensive step?",
      options: ["The shuffle phase compresses intermediate data to reduce storage", "The shuffle phase groups all map output records by key and transfers them across the network to the reducer responsible for each key — this involves serialization, network I/O, and deserialization, making it the dominant cost in most MapReduce jobs", "The shuffle phase writes the final output to HDFS", "The shuffle phase distributes input data to mappers before processing begins"],
      correctAnswer: 1,
      explanation: "In MapReduce: (1) Map — each mapper processes a local HDFS split and emits (key, value) pairs. (2) Shuffle — the framework collects all mapper outputs, sorts them by key, and transfers records with the same key to the same reducer node across the network. (3) Reduce — each reducer receives all values for its assigned keys and aggregates. The shuffle is expensive because it moves potentially terabytes of intermediate data across the network, requires sorting (O(n log n)), and involves serialization overhead. Optimizations: combiner functions (local pre-aggregation on the mapper), choosing a good partitioner, and using a format with efficient serialization (Avro, Protocol Buffers).",
      hints: ["The shuffle solves a fundamental problem: after parallel mapping, all values for the same key must be brought to one place for reduction.", "Combiners act like local mini-reducers on each mapper node, reducing the volume of data sent during shuffle."],
    },
    {
      id: "q-sdi-stream-27",
      type: "multiple-choice",
      difficulty: "medium",
      question: "In Apache Spark, what is lazy evaluation and what triggers actual execution?",
      options: ["Lazy evaluation means Spark caches all intermediate results to avoid recomputation", "Transformations (map, filter, join) build a DAG of operations but do not execute immediately; an action (collect, count, write, saveAsTable) triggers the Catalyst optimizer to plan and execute the entire DAG", "Lazy evaluation is a Spark Streaming concept only — batch jobs execute eagerly", "Lazy evaluation means Spark delays reading input data until the output directory is checked for existing files"],
      correctAnswer: 1,
      explanation: "Spark's execution model is fundamentally lazy: calling df.filter(...).groupBy(...).agg(...) builds a logical plan (DAG of transformations) but reads no data and does no computation. When you call an action — df.count(), df.collect(), df.write.parquet(...) — Spark submits the DAG to the Catalyst optimizer, which generates an optimized physical plan, divides it into stages separated by shuffles, and executes the stages on the cluster. Lazy evaluation benefits: Catalyst can optimize across the entire chain of transformations (e.g., push filters down before joins, eliminate unused columns). Drawback: you see no output until an action is called, which can surprise developers expecting immediate feedback.",
      hints: ["Think of transformations as building a recipe and actions as cooking the recipe — the recipe is built lazily, cooking only starts when you're ready to eat.", "Calling df.show() is an action — it triggers execution of the entire DAG up to that point."],
    },
    {
      id: "q-sdi-stream-28",
      type: "multiple-choice",
      difficulty: "medium",
      question: "An Airflow DAG processes daily data and needs to reprocess the last 90 days of data after a bug fix in the transformation logic. Which Airflow feature handles this?",
      options: ["Airflow SLA miss callbacks, which trigger automatic reruns for missed execution windows", "Airflow backfill: running 'airflow dags backfill -s START_DATE -e END_DATE' creates and executes DAG runs for each historical execution date within the range", "Airflow sensors detect missing output files and automatically trigger reruns for affected dates", "Airflow XComs can store historical results that get automatically reprocessed on code change"],
      correctAnswer: 1,
      explanation: "Airflow's backfill feature creates historical DAG runs for past execution dates that either did not run or need to be reprocessed. The command 'airflow dags backfill --dag-id my_dag -s 2024-01-01 -e 2024-03-31' will create one DAG run per scheduled interval (e.g., daily) between the start and end date and execute them. This is only effective if the pipeline is idempotent (using MERGE/UPSERT, not INSERT) — otherwise reprocessing will create duplicates. Backfill runs are marked with a special 'backfill' tag and run with lower priority by default to avoid starving normal scheduled runs.",
      hints: ["Backfill is to Airflow what 'replay' is to streaming — it re-executes historical runs to apply updated transformation logic.", "Backfill only works correctly if your pipeline is idempotent — running it twice for the same date should produce the same result."],
    },
    {
      id: "q-sdi-stream-29",
      type: "multiple-choice",
      difficulty: "medium",
      question: "What is the primary difference between a data lake and a data warehouse, and when would you use each?",
      options: ["A data lake stores structured data only; a data warehouse stores unstructured data only", "A data lake stores raw data in any format (Parquet, JSON, images, logs) on cheap object storage (S3, GCS) with schema-on-read; a data warehouse stores structured, queryable data with schema-on-write. Lakes are used for raw storage and ML; warehouses for BI and analytics.", "A data lake is always faster for SQL queries than a data warehouse", "Data lakes require Hadoop; data warehouses require proprietary cloud services"],
      correctAnswer: 1,
      explanation: "A data lake (S3, GCS, ADLS) is raw storage — you dump any format (Parquet, ORC, JSON, CSV, images, audio) cheaply and define the schema when you read (schema-on-read). This flexibility is ideal for ML training data, raw event archives, and data science exploration. A data warehouse (BigQuery, Snowflake, Redshift) enforces schema on write — data must conform to a table structure, enabling fast SQL queries with columnar storage and query optimization. In practice, modern architectures use a lakehouse pattern (Delta Lake, Apache Iceberg, Apache Hudi) that adds ACID transactions and schema enforcement on top of object storage, combining lake flexibility with warehouse query performance.",
      hints: ["Lakes are cheap and flexible; warehouses are expensive and queryable — choose based on your primary use case.", "The lakehouse pattern (Delta Lake, Iceberg) is the modern convergence: raw object storage with warehouse-grade SQL performance."],
    },
  ],

  "sdi-stream-realtime-analytics": [
    {
      id: "q-sdi-stream-30",
      type: "multiple-choice",
      difficulty: "hard",
      question: "ClickHouse is described as 'column-oriented OLAP.' What specific design choices make ClickHouse capable of scanning 100 billion rows per second?",
      options: ["ClickHouse uses in-memory processing exclusively, storing no data on disk", "ClickHouse combines columnar storage (reads only queried columns), vectorized query execution (SIMD instructions process 64-256 values per CPU cycle), aggressive compression per column type, and MergeTree engine that pre-sorts data by primary key — making full-column scans extremely cache-efficient", "ClickHouse distributes queries across 10,000 nodes to achieve parallelism", "ClickHouse pre-materializes all possible aggregation combinations at ingest time"],
      correctAnswer: 1,
      explanation: "ClickHouse's performance comes from a stack of complementary optimizations: (1) Columnar storage — only the queried columns are read from disk, dramatically reducing I/O for wide tables. (2) Vectorized execution — operations are applied to batches of values using SIMD CPU instructions (AVX-512), achieving ~10-50x speedup over row-by-row processing. (3) Per-column compression — LZ4 and ZSTD with column-specific codecs (Delta encoding for timestamps, Gorilla for floats) achieve 5-10x compression, reducing disk reads further. (4) MergeTree engine — the primary key determines sort order, enabling binary search and range scans. ClickHouse is best suited for append-only event data (analytics, logs, metrics) and is not optimized for high-rate point updates or transactional workloads.",
      hints: ["Vectorization means 'process 256 values at once using one CPU instruction' instead of 'loop 256 times processing one value each'.", "ClickHouse's MergeTree is analogous to LSM trees — data is written to sorted parts and merged in the background, similar to LevelDB/RocksDB."],
    },
    {
      id: "q-sdi-stream-31",
      type: "multiple-choice",
      difficulty: "hard",
      question: "Apache Druid is designed for sub-second OLAP queries on real-time data. Which of the following best describes its ingestion and segment architecture?",
      options: ["Druid loads data exclusively from HDFS files processed nightly, making it unsuitable for real-time use cases", "Druid ingests from Kafka in real-time and stores data in columnar segments on deep storage (S3). Real-time nodes serve recent data from memory; historical nodes serve older segments from disk. Segments are pre-aggregated at ingest using rollup to reduce storage.", "Druid uses a shared-nothing row-store architecture partitioned by primary key for low-latency lookups", "Druid requires Spark to preprocess data before ingestion and cannot ingest raw events directly"],
      correctAnswer: 1,
      explanation: "Druid's architecture is purpose-built for user-facing analytics dashboards requiring sub-second query latency on large datasets. Key design choices: (1) Real-time ingestion from Kafka via Kafka Supervisor — events are indexed in memory and served immediately with sub-second freshness. (2) Columnar segment files — data is stored in immutable segments on deep storage (S3/GCS), loaded into memory/disk on Historical nodes. (3) Rollup — at ingestion, Druid can pre-aggregate multiple raw events into one row (e.g., all clicks for user X in minute Y become one row with count=N), reducing storage 10-100x for high-cardinality datasets. (4) Tiering — hot segments in memory, cold segments on disk. Used by Airbnb, Netflix, and LinkedIn for product analytics dashboards.",
      hints: ["Druid's rollup is like a streaming GROUP BY at ingest time — it trades raw event fidelity for dramatic storage reduction.", "Real-time nodes and historical nodes serve different data freshness ranges — recent data from memory, historical data from segment files."],
    },
    {
      id: "q-sdi-stream-32",
      type: "multiple-choice",
      difficulty: "hard",
      question: "A system needs to count unique users across 1 billion events per day in real-time, with results available within 1 second. Exact counting requires 10 GB of memory (one bit per user_id). Which probabilistic data structure solves this with 0.81% error and 12 KB of memory?",
      options: ["Bloom filter — probabilistic set membership check with configurable false positive rate", "HyperLogLog — probabilistic cardinality estimator using hash functions and bucket statistics to estimate distinct count with 0.81% standard error using ~12 KB", "Count-Min Sketch — frequency estimation structure that answers 'how many times did X appear?' with bounded error", "MinHash — similarity estimation for set intersection/union using hash-based sampling"],
      correctAnswer: 1,
      explanation: "HyperLogLog (HLL) is the standard algorithm for approximate cardinality estimation (counting distinct elements). It works by hashing each element, observing the maximum number of leading zeros in the hash (which correlates with the number of distinct values seen), and aggregating across multiple buckets (registers) to reduce variance. With 2^14 = 16,384 registers (12 KB), HLL achieves 0.81% standard error for any cardinality from 1 to 10^18. This is used in Redis (PFADD/PFCOUNT), BigQuery (APPROX_COUNT_DISTINCT), Druid, and ClickHouse. Count-Min Sketch (option C) answers frequency queries ('how often did item X appear?'), not cardinality. Bloom filters test set membership ('have I seen X before?').",
      hints: ["HyperLogLog observes patterns in hash values to estimate 'how many distinct things have I seen?' without storing the items themselves.", "Redis's PFADD and PFCOUNT implement HyperLogLog in 12 KB per key — the 'PF' prefix honors Philippe Flajolet who invented the algorithm."],
    },
  ],

  "sdi-stream-data-governance": [
    {
      id: "q-sdi-stream-33",
      type: "multiple-choice",
      difficulty: "medium",
      question: "What is data lineage and which tool is commonly used to document it in modern ELT pipelines?",
      options: ["Data lineage is the compression ratio of data as it moves through the pipeline; monitored with Prometheus", "Data lineage tracks how data flows from source systems through transformations to final destinations — showing which upstream tables a downstream model depends on and which columns feed which metrics. dbt automatically generates lineage graphs from its DAG of SQL models.", "Data lineage refers to the geographic location where data was originally collected, required for GDPR residency compliance", "Data lineage is a Kafka concept describing the sequence of consumer groups that processed a message"],
      correctAnswer: 1,
      explanation: "Data lineage provides end-to-end visibility into data provenance: where did this number come from? Which raw events fed into this dashboard metric? Which tables would be affected if I change this upstream model? dbt (data build tool) automatically builds a lineage DAG from SQL model dependencies — if model B uses model A as a source, dbt records that dependency and visualizes it. This enables impact analysis (if I change table X, which downstream tables break?), debugging (why does this metric look wrong?), and compliance auditing (where does this customer's PII flow?). Apache Atlas, OpenMetadata, and DataHub are dedicated data catalog tools that extend lineage to cross-system tracking.",
      hints: ["dbt's --select flag can use lineage to run a model and all its downstream dependencies: 'dbt run --select my_model+'.", "Lineage answers the 'where did this data come from?' question — essential for debugging incorrect metrics in production."],
    },
    {
      id: "q-sdi-stream-34",
      type: "multiple-choice",
      difficulty: "hard",
      question: "A company must comply with GDPR's right to erasure. A user requests deletion of all their data. Which approach correctly handles this in a data pipeline with both a Kafka event stream and a BigQuery data warehouse?",
      options: ["Delete the user record from the source RDBMS only — downstream systems automatically sync the deletion via CDC", "In Kafka, publish a tombstone record (key=user_id, value=null) to trigger log compaction deletion of that key's events; in BigQuery, run DELETE FROM table WHERE user_id = X for all tables, then audit that no derived tables or materialized views retain the PII", "GDPR right to erasure only applies to the source system — warehouses and event streams are exempt as they are analytical systems", "Encrypt the user's data at rest and delete the encryption key (crypto-shredding) — this makes the data unreadable without full deletion"],
      correctAnswer: 1,
      explanation: "GDPR right to erasure (Article 17) requires deletion across all systems storing personal data — including data warehouses, event streams, backups, and derived tables. The two-part solution: (1) Kafka — publish a tombstone record with the user's key and null value. Kafka log compaction will remove all prior events for that key during the next compaction pass. Note: messages in non-compacted topics with time-based retention must wait for retention to expire. (2) BigQuery — DELETE statements on all tables containing user_id, followed by an audit of derived tables, materialized views, and snapshots. Crypto-shredding (option D) is a valid alternative when direct deletion is impractical (e.g., immutable data lakes) — encrypting per-user data and deleting the key renders the data unreadable, which regulators generally accept as 'erasure.'",
      hints: ["GDPR erasure is not just about the primary database — every downstream copy (warehouse, event stream, cache, backup) must also be addressed.", "A Kafka tombstone (key=user_id, value=null) signals log compaction to remove all prior messages for that key — but compaction is asynchronous and not immediate."],
    },
  ],
};

registerQuestions(questions);
