import type { Question } from "@/lib/curriculum";
import { registerQuestions } from "./registry";

const questions: Record<string, Question[]> = {
  "sdi-rt-ot": [
    {
      id: "q-rt-1",
      type: "multiple-choice",
      difficulty: "medium",
      question: "In Operational Transformation (OT), two concurrent insert operations are performed on the string \"hello\": User A inserts \"X\" at index 2 and User B inserts \"Y\" at index 2 simultaneously. After applying B's operation at A's site using OT, what should the transformed insert position for B's \"Y\" be?",
      options: ["Index 2 (unchanged)", "Index 3 (shifted past A's insertion)", "Index 0 (reset to start)", "Index 4 (shifted by two)"],
      correctAnswer: 1,
      explanation: "**Step 1:** Identify the concurrent operations. User A inserts \"X\" at index 2; User B inserts \"Y\" at index 2. A's operation arrives at the server first and is applied to the canonical document state.\\n\\n**Step 2:** Transform B's operation against A's. The OT transformation rule states: if A inserts at a position <= B's position, B's position must shift right by the length of A's insertion. Since A inserted \"X\" at index 2, B's target position (originally 2) shifts to index 3.\\n\\n**Step 3:** Verify convergence. At A's site, applying B's transformed insert at index 3 produces \"heXYllo\" — the same result as at B's site after transforming A against B. This shift-by-1 transformation is the fundamental OT rule for insert-conflict resolution.",
      hints: ["OT asks: given that A's operation has already been applied, where should B's operation now target?", "A's insert at index 2 shifts all subsequent characters one position to the right."],
    },
    {
      id: "q-rt-2",
      type: "multiple-choice",
      difficulty: "hard",
      question: "Which formal property must OT transformation functions satisfy to guarantee convergence when operations pass through a central server that applies them in a canonical order?",
      options: ["CP1 (convergence property 1): transform(A, B) applied after B = transform(B, A) applied after A", "Commutativity: apply(A, B) = apply(B, A) for all operation pairs", "Idempotency: applying the same operation twice yields the same result", "Associativity: (A op B) op C = A op (B op C) for sequential operations"],
      correctAnswer: 0,
      explanation: "**Step 1:** Understand CP1's formal definition. For any two concurrent operations A and B applied at the same site, the transformed sequences transform(A,B); B and transform(B,A); A must produce identical document state. This is the convergence property — all sites must agree on the final state regardless of operation ordering.\\n\\n**Step 2:** Distinguish CP1 from CP2. CP1 handles two operations; CP2 handles three concurrent operations and requires transform(transform(A,B),C') = transform(transform(A,C),B'). CP2 is dramatically harder to satisfy correctly. Google Wave required both, making it notoriously complex.\\n\\n**Step 3:** Recognize practical implications. Google Docs sidesteps CP2 by using a single server that imposes a total order — only CP1 is needed. CRDT-based systems (Figma, Notion) also avoid CP2 entirely because their merge semantics are inherently commutative and associative.",
      hints: ["CP1 is about two concurrent operations — if you apply A then transform(B against A), and also apply B then transform(A against B), you should reach the same state.", "Google Docs simplifies this by routing all operations through a single server, requiring only CP1."],
    },
    {
      id: "q-rt-3",
      type: "multiple-choice",
      difficulty: "easy",
      question: "In a Google Docs-style architecture using Operational Transformation, what is the primary role of the central server?",
      options: ["Storing the document as a CRDT lattice and broadcasting state snapshots", "Serializing all incoming concurrent operations into a canonical order and broadcasting transformed operations to all clients", "Performing client-side rendering of rich text and returning HTML diffs", "Providing a last-write-wins conflict resolution using Lamport timestamps"],
      correctAnswer: 1,
      explanation: "**Step 1:** Recognize the server's role as the single authority. Every client sends operations to the server along with the revision number they were based on. The server is the sole source of truth for the canonical document state and the definitive ordering of operations.\\n\\n**Step 2:** Understand the revision tracking mechanism. Each client maintains lastAckedRevision. When sending a new operation, the client includes this revision. The server finds all operations applied after that revision and transforms the incoming operation against each one sequentially.\\n\\n**Step 3:** Observe the broadcast step. The server assigns the operation a new revision number, applies it to canonical state, and broadcasts it to all other connected clients. Clients receive the transformed operation and apply it to their local state, advancing their revision. This centralization is what makes OT practical.",
      hints: ["The server acts as a 'referee' that determines the definitive order of all concurrent edits.", "Clients track a revision number; when they send an operation, they also send the revision they were at when they composed it."],
    },
  ],

  "sdi-rt-crdt": [
    {
      id: "q-rt-4",
      type: "multiple-choice",
      difficulty: "medium",
      question: "What is the key structural difference between a state-based CRDT (CvRDT) and an operation-based CRDT (CmRDT)?",
      options: ["CvRDTs require a central server; CmRDTs are fully peer-to-peer", "CvRDTs merge full state snapshots using a join-semilattice; CmRDTs broadcast individual operations that must be delivered exactly once in causal order", "CvRDTs support only counters; CmRDTs support arbitrary data types including text", "CvRDTs are used in Google Docs; CmRDTs are used in Figma"],
      correctAnswer: 1,
      explanation: "**Step 1:** Contrast the two CRDT paradigms by their communication pattern. CvRDTs (state-based) periodically exchange full state snapshots — the merge function is the heart of the system. CmRDTs (operation-based) broadcast compact operation messages — the delivery requirements are the heart of the system.\\n\\n**Step 2:** Examine merge semantics. CvRDT merge must be commutative, associative, and idempotent — the three properties of a join-semilattice. These properties ensure that merging replicas A and B in any order always produces the same result. CvRDTs are safe for unreliable networks but O(state_size) per merge.\\n\\n**Step 3:** Compare delivery guarantees. CmRDTs require exactly-once causal delivery — if an operation is dropped or duplicated, convergence breaks. This is harder to guarantee than CvRDT's idempotent merge. Delta-state CRDTs bridge the gap: O(delta_size) efficiency with CvRDT-like safety.",
      hints: ["CvRDT merges 'what the state looks like'; CmRDT sends 'what changed'.", "If your network can guarantee causal delivery with no duplicates, CmRDT is more efficient; if not, CvRDT's idempotent merge is safer."],
    },
    {
      id: "q-rt-5",
      type: "multiple-choice",
      difficulty: "medium",
      question: "A G-Counter CRDT is implemented across 3 nodes (N0, N1, N2) as a vector [N0_count, N1_count, N2_count]. Node N1 increments its counter. What is the correct merge rule when two replicas share their state?",
      options: ["Sum all vector entries from both replicas to get total count", "Take the element-wise maximum of both vectors; the total value is the sum of the merged vector", "Overwrite with the replica that has the higher vector sum", "Use the median value for each position to avoid outliers"],
      correctAnswer: 1,
      explanation: "**Step 1:** Understand the vector structure. A G-Counter across N nodes stores a vector [count_0, count_1, ..., count_N]. Each node N_i owns slot i and is the only one allowed to increment it. No node ever decrements or reads from another node's slot.\\n\\n**Step 2:** Apply the merge rule. Given two replicas R1 and R2, the merged vector takes element-wise maximum: merged[i] = max(R1[i], R2[i]). This handles the case where a replica has fallen behind — max correctly preserves the newer value.\\n\\n**Step 3:** Compute the read (total). The current value is sum(merged_vector). In the example, merge([3,1,2], [3,2,1]) = [3,2,2] giving total 7. The merge is commutative, associative, and idempotent — satisfying all CvRDT requirements.",
      hints: ["Each node 'owns' one slot in the vector and only increments its own slot.", "Taking the element-wise max handles the case where you receive an older state — the max is at least as current as either replica."],
    },
    {
      id: "q-rt-6",
      type: "multiple-choice",
      difficulty: "hard",
      question: "Figma's multiplayer system uses Y.js, a CRDT library. Which type of CRDT does Y.js implement for collaborative text editing, and what unique identifier does it assign to each character?",
      options: ["G-Set CRDT; each character gets a UUID generated at insertion time", "LSEQ CRDT; each character gets a fractional index between its neighbors", "YATA (Yet Another Transformation Approach) / Logoot-style CRDT; each character gets a unique (clientID, clock) tuple as its identity", "RGA (Replicated Growable Array); each character is identified by its position in a linked list with wall-clock timestamps"],
      correctAnswer: 2,
      explanation: "**Step 1:** Understand the YATA identifier scheme. Each character gets a permanent (clientID, clock) tuple at insertion time. The clientID is unique to the originating device/session; the clock is a Lamport timestamp. Together, these tuples are globally unique and stable — they never change, even as surrounding text is edited.\\n\\n**Step 2:** Grasp how ordering works. Characters are sorted by their (clientID, clock) tuples. A new character inserted between \"h\" and \"e\" gets an ID that sorts between theirs. Because IDs are permanent, this relative ordering is preserved regardless of concurrent insertions elsewhere.\\n\\n**Step 3:** Handle deletions via tombstones. When a character is deleted, it is not removed from the CRDT structure — it is marked as deleted (a tombstone). The tombstone remains to prevent the same logical character from being re-inserted and causing ambiguity.",
      hints: ["The key insight of CRDT-based text editing is that each character has a stable, unique identity regardless of what gets inserted or deleted around it.", "Unlike OT which transforms position indices, CRDTs use stable IDs so positions never need transformation."],
    },
    {
      id: "q-rt-7",
      type: "multiple-choice",
      difficulty: "medium",
      question: "What is the primary tradeoff between OT-based systems (Google Docs) and CRDT-based systems (Figma/Notion) for real-time collaborative editing?",
      options: ["OT requires more storage; CRDTs require more CPU for rendering", "OT requires a central server for operation serialization and cannot work offline; CRDTs can work fully offline and peer-to-peer but accumulate tombstones causing memory growth", "OT supports richer text formatting; CRDTs only support plain text", "OT is open source; CRDTs are proprietary algorithms"],
      correctAnswer: 1,
      explanation: "**Step 1:** Analyze OT's server dependency. OT requires a single server to serialize operations and apply CP1 transformations. This works well when online but creates problems offline: the client must buffer operations, and on reconnect the server must transform buffered ops against all ops that occurred during disconnection.\\n\\n**Step 2:** Recognize CRDT's offline-first advantage. Any two CRDT replicas can merge at any time — no server required, no special reconciliation step. Edits made offline on a plane are merged deterministically when connectivity returns.\\n\\n**Step 3:** Acknowledge CRDT's tombstone cost. Deleted characters remain as tombstones in the CRDT structure forever. Over time, a heavily edited document accumulates tombstones proportional to total edit history. Production systems like Y.js periodically garbage-collect tombstones when all replicas confirm the deletion has propagated.",
      hints: ["Ask: can a user edit the document on an airplane with no internet? OT makes this hard; CRDTs make it natural.", "Tombstones are the price CRDTs pay for never needing coordination — the structure remembers everything that was ever deleted."],
    },
  ],

  "sdi-rt-presence": [
    {
      id: "q-rt-8",
      type: "multiple-choice",
      difficulty: "easy",
      question: "In a real-time collaborative document editor, how is the \"presence\" system (showing which users are online with live cursors) typically implemented at scale?",
      options: ["Each client polls the server every 100ms asking for all other users' cursor positions", "Clients publish cursor position updates via WebSocket; the server maintains an in-memory presence store (e.g., Redis) and broadcasts updates to all subscribers of that document session", "Cursor positions are written to the primary database and read by other clients via long-polling", "A separate HTTP/2 server-sent events endpoint streams cursor positions from a database change feed"],
      correctAnswer: 1,
      explanation: "**Step 1:** Identify why presence is a special data type. Cursor positions change dozens of times per second, have no long-term value (they are immediately stale), and are broadcast to many subscribers. They do not belong in a persistent database — they belong in an in-memory store optimized for high-frequency writes and reads.\\n\\n**Step 2:** Design the pub/sub flow. Client A publishes a cursor update over the existing document WebSocket. The presence service stores {userId: {cursor, timestamp}} in Redis with a 15-30 second TTL. The service then publishes a delta event on the document's presence channel.\\n\\n**Step 3:** Handle disconnection cleanly. If Client A's WebSocket closes, no explicit \"leave\" event is needed — the Redis TTL naturally expires. Heartbeat messages (sent every 5-10 seconds by the client) refresh the TTL while the connection is alive.",
      hints: ["Presence data is ephemeral — if the server restarts, it is fine to lose it and rebuild from reconnecting clients.", "Redis TTL provides automatic cleanup: if a user disconnects without sending a 'leave' event, their presence expires naturally."],
    },
    {
      id: "q-rt-9",
      type: "multiple-choice",
      difficulty: "medium",
      question: "A user's cursor position is stored as a character index in a collaborative document. Another user inserts 50 characters before the cursor. How should the cursor position be updated to remain semantically correct?",
      options: ["The cursor index is frozen and never updated automatically", "The server applies the same OT transformation used for text operations to shift the cursor index by 50", "The cursor is stored as an anchor to a specific character's CRDT node ID, so it automatically follows the character regardless of insertions elsewhere", "The client re-requests the cursor position from the server after each remote operation"],
      correctAnswer: 2,
      explanation: "**Step 1:** Diagnose the index-based cursor problem. A cursor at character index 100 is meaningful only in the document state when it was recorded. If 50 characters are inserted at index 0, the cursor's semantic intent is preserved only if the index is updated to 150. Index-based systems require explicit update logic.\\n\\n**Step 2:** Anchor to a stable node ID instead. In CRDT text, each character has a unique, permanent (clientID, clock) identifier. A cursor is stored as \"after character with ID X\" — the anchor is the character itself, not its position. Since character IDs never change, the cursor always points to the right place.\\n\\n**Step 3:** Recognize this works for OT too. ProseMirror (OT-based) anchors cursors to node positions in its document tree, not raw character indices. Cursor transformation in OT is essentially the same problem as text operation transformation.",
      hints: ["Index-based: cursor at 100, someone inserts 50 chars at position 0 -> cursor should move to 150, but only if you remember to update it.", "CRDT anchor: cursor is 'after character with ID (alice, 42)' — that relationship never changes no matter what else is inserted."],
    },
    {
      id: "q-rt-10",
      type: "true-false",
      difficulty: "easy",
      question: "In a collaborative editor presence system, a user's \"online\" status should be determined solely by whether their WebSocket connection is open, without any heartbeat mechanism.",
      options: ["True", "False"],
      correctAnswer: "False",
      explanation: "**Step 1:** Understand why TCP keepalive is insufficient. TCP keepalive is designed for network diagnostics, not application-level liveness. It typically has a default timeout of 2 hours on Linux, far too long for real-time collaborative apps. Many NAT routers and corporate firewalls silently drop idle TCP connections after 30-90 seconds.\\n\\n**Step 2:** Implement application-level heartbeats. The client sends a ping message (or a WebSocket ping frame) every 10-30 seconds. The server maintains a last-heard timestamp for each connection. If no message is received within the heartbeat interval multiplied by some factor, the server closes the connection.\\n\\n**Step 3:** Recognize dual-purpose heartbeats. Heartbeats serve both connection liveness (detecting zombie connections) and presence TTL refresh in Redis. Embedding presence data in the heartbeat eliminates a separate round-trip for presence updates.",
      hints: ["NAT routers and corporate firewalls often silently discard idle TCP connections after 30-90 seconds.", "The heartbeat also refreshes presence TTLs in Redis, providing a dual purpose."],
    },
  ],

  "sdi-rt-undo-history": [
    {
      id: "q-rt-11",
      type: "multiple-choice",
      difficulty: "hard",
      question: "In a collaborative document editor, why is implementing per-user undo (\"undo only my own changes\") significantly harder than in a single-user editor?",
      options: ["Multi-user editors have more users, so the undo stack grows too large to store in memory", "Undoing your own operation may conflict with operations other users have applied on top of it, requiring the undo operation itself to be transformed against all intervening operations", "The database cannot support concurrent undo transactions from multiple users", "Per-user undo requires client-side storage that is wiped when the browser tab closes"],
      correctAnswer: 1,
      explanation: "**Step 1:** Analyze why single-user undo fails in multi-user. In single-user undo, you pop the last operation from the stack and apply its inverse. In collaborative undo, Bob's operations may have been applied between Alice's original operation and her undo request. Alice's original position (5) may no longer be where \"X\" is.\\n\\n**Step 2:** Transform the anti-operation against intervening ops. Alice's undo is the inverse of her original insert. Before applying it, the system must transform this anti-operation against all of Bob's operations that occurred after Alice's insert.\\n\\n**Step 3:** Implement per-user undo efficiently. Google Docs tags each operation with a user ID and maintains a per-user operation log. Per-user undo replays the log with the target operation omitted. Modern systems use CRDT-based approaches where undo is yet another operation in the log.",
      hints: ["The undo stack is no longer a simple LIFO stack when interleaved with concurrent operations from others.", "Think of undo as inserting a new 'anti-operation' at the current revision, not literally rewinding time."],
    },
    {
      id: "q-rt-12",
      type: "multiple-choice",
      difficulty: "medium",
      question: "A document collaboration system stores the complete operation log to enable version history. As the document accumulates millions of operations, what is the standard approach to prevent slow reconstruction of document state from the beginning of time?",
      options: ["Delete old operations once they are older than 30 days", "Periodically write a full document snapshot and store only the tail of the operation log after the snapshot; reconstruct by loading the snapshot and replaying the tail", "Compress all operations before storing to reduce log size", "Use a write-ahead log that automatically garbage-collects applied operations"],
      correctAnswer: 1,
      explanation: "**Step 1:** Understand why naive replay fails at scale. A 5-year-old document with 10 million operations would require replaying all 10 million to reconstruct its current state — seconds to minutes of computation per reconstruction.\\n\\n**Step 2:** Apply checkpointing. Periodically (every N operations or T minutes), serialize the complete document state as a snapshot and store it alongside the operation log. Reconstructing state at revision M means loading the snapshot at K and replaying only operations K+1 through M.\\n\\n**Step 3:** Optimize for multiple access patterns. Store snapshots at multiple granularities: hourly snapshots for recent history (fast to access), daily for older history. Combine with delta compression of the operation log to reduce storage.",
      hints: ["Think of it like database WAL + periodic checkpoints: the checkpoint prunes how far back you need to replay the log.", "Notion and Google Docs both store snapshots; named version history creates explicit snapshots."],
    },
  ],

  "sdi-rt-offline-sync": [
    {
      id: "q-rt-13",
      type: "multiple-choice",
      difficulty: "medium",
      question: "A user edits a Notion document offline for 2 hours, accumulating 200 local operations. When they reconnect, what is the correct procedure for synchronizing with the server?",
      options: ["Discard local changes and reload the server version to avoid conflicts", "Send all 200 operations to the server; the server transforms them against all server-side operations that occurred during the offline period and applies them in order", "Merge the local document state with the server state by computing a diff of the two text strings", "Lock the document for all other users during the sync to prevent concurrent modifications"],
      correctAnswer: 1,
      explanation: "**Step 1:** The offline client maintains a local operation log tagged with the revision number at which each operation was composed. When connectivity returns, the client sends all buffered operations along with the base revision (the last revision the client knew when it went offline).\\n\\n**Step 2:** The server computes the operation delta — all operations applied to the canonical state after the client's base revision. In OT systems, each buffered client operation is transformed against server-side operations. In CRDT systems, the client's operations are simply merged into the CRDT structure.\\n\\n**Step 3:** The reconciled operations are applied to the server state, assigned new revision numbers, and broadcast to other online clients. From other clients' perspective, the offline user's edits appear as a burst of new operations.",
      hints: ["The client kept a log of operations with their revision base — that's the key information the server needs to transform them.", "CRDT systems: the merge function handles offline sync 'for free' since merge(A, B) = merge(B, A) = converged state."],
    },
    {
      id: "q-rt-14",
      type: "multiple-choice",
      difficulty: "medium",
      question: "When a client reconnects after an offline period in a WebSocket-based collaborative system, which reconnection strategy ensures no operations are missed?",
      options: ["Reconnect and re-download the full document from the server", "Reconnect and send the last acknowledged server revision; the server sends all operations from that revision onward, allowing the client to replay them", "Reconnect and compute a hash of the local document to check if it matches the server", "Reconnect and wait for other clients to broadcast their current state"],
      correctAnswer: 1,
      explanation: "**Step 1:** The server assigns each operation a monotonically increasing revision number (1, 2, 3, ...). This total order is the backbone of OT synchronization — every client knows that revision 5 happened before revision 6. The client tracks localState = last applied revision.\\n\\n**Step 2:** On reconnect, the client sends {lastRevision: 42} to the server. The server responds with all operations from 43 to current. This is the operation tail — the missing history the client needs to replay to catch up.\\n\\n**Step 3:** Handle the long-offline case. If the gap is very large, the server detects this and sends the current full document snapshot plus the few operations after the most recent snapshot. This snapshot-based catch-up mirrors database replication techniques.",
      hints: ["This is analogous to Kafka consumer replay: the client stores its 'offset' (revision) and asks the server to send everything it missed.", "The server-side operation log is the source of truth — clients are just materialized views of it."],
    },
  ],

  "sdi-rt-comments-annotations": [
    {
      id: "q-rt-15",
      type: "multiple-choice",
      difficulty: "hard",
      question: "A user anchors a comment to the phrase \"hello world\" at character positions 10-20 in a collaborative document. Another user then inserts 50 characters at position 5, making the phrase start at position 60. How should the comment anchor be stored to survive such edits?",
      options: ["Store the raw character indices (10-20) and update them on every operation", "Store a reference to the CRDT node IDs of the first and last characters of the anchored phrase, so the anchor follows the content rather than a position", "Store the comment anchor as a regex pattern to re-locate the phrase after edits", "Store the anchor relative to the nearest paragraph break, which changes less frequently"],
      correctAnswer: 1,
      explanation: "**Step 1:** Identify the fragility of index-based anchors. Comment anchored at positions 10-20 in a 100-character document. Someone inserts 50 characters at position 5. The comment now references positions 60-70 — the wrong content.\\n\\n**Step 2:** Anchor to stable node IDs. In CRDT text, each character has a permanent (clientID, clock) identifier. The comment stores references to the first and last character's IDs. When the document is rendered, the comment span is computed by finding characters whose IDs fall within that range.\\n\\n**Step 3:** Handle the \"hello world\" scenario. When the phrase \"hello world\" is anchored, the comment references the node IDs of 'h' and 'd'. After 50 chars are inserted before, these nodes still exist with the same IDs. The comment follows the content it anchors to.",
      hints: ["The comment should 'follow' the highlighted text as the document is edited — the only way to do this reliably is to reference the content itself, not its position.", "Google Docs comments survive large insertions/deletions around them precisely because they anchor to stable document structure, not character offsets."],
    },
  ],

  "sdi-rt-access-control": [
    {
      id: "q-rt-16",
      type: "multiple-choice",
      difficulty: "medium",
      question: "In a real-time collaborative document system, where should permission checks for edit operations be enforced?",
      options: ["Only on the client side to reduce server latency", "Only at document open time; subsequent operations are trusted since the user already has access", "On the server for every incoming operation, since the client cannot be trusted and permissions can change mid-session", "In the database layer using row-level security to block unauthorized writes"],
      correctAnswer: 2,
      explanation: "**Step 1:** Establish the security boundary. The server is the only trusted component — the client is untrusted and can be reverse-engineered or modified. Every incoming operation must be validated against the current permission state, not a cached permission snapshot from session start.\\n\\n**Step 2:** Check permissions per-operation. For each incoming operation, the server queries the current permission for (userId, documentId). This must be fast — typically cached in Redis with a 1-5 second TTL. If permission is absent or expired, the operation is rejected.\\n\\n**Step 3:** Push permission changes reactively. When a permission is revoked, the server pushes a \"permission changed\" event to the affected client's WebSocket. The client transitions to read-only mode immediately, without waiting for the next operation attempt to fail.",
      hints: ["Security rule: never trust the client. Checks must be on the server, every time.", "Permissions are dynamic — a user can have edit rights revoked while they are actively editing."],
    },
  ],

  "sdi-rt-rich-text-model": [
    {
      id: "q-rt-17",
      type: "multiple-choice",
      difficulty: "medium",
      question: "Quill editor represents document changes as 'Deltas' — a list of retain/insert/delete operations. Which property of the Delta format makes it suitable for OT-based collaborative editing?",
      options: ["Deltas are stored as compressed binary to minimize network bandwidth", "Deltas are composable (two deltas can be merged into one equivalent delta) and transformable (given two concurrent deltas, you can compute a transformed delta), making them a natural fit for OT", "Deltas use absolute character positions, making them easy to index in a database", "Deltas support rich media embedding via MIME type annotations"],
      correctAnswer: 1,
      explanation: "**Step 1:** Understand Delta's three primitive operations. retain(N) advances the cursor N characters without changing them. insert(text) adds new content with optional attributes (bold, italic). delete(N) removes N characters. Every document change is a sequence of these three operations.\\n\\n**Step 2:** Examine Delta's two key operations. compose(A, B) produces a Delta C such that applying A then B produces the same result as applying C. transform(A, B) produces A' such that applying B then A' produces the same result as applying A then B.\\n\\n**Step 3:** Recognize why Deltas suit OT. Rich text attributes are embedded in the insert operation itself ({insert: \"X\", attributes: {bold: true}}). When transforming concurrent formatting changes, the attribute map is transformed alongside the text.",
      hints: ["The 'retain' operation (advance the cursor N characters without change) is crucial — it encodes context about where edits happen.", "compose and transform are the two operations that make a Delta format OT-compatible."],
    },
    {
      id: "q-rt-18",
      type: "multiple-choice",
      difficulty: "hard",
      question: "ProseMirror represents documents as an immutable tree of nodes (paragraph, text, heading, etc.) rather than a flat string. How does this tree structure affect collaborative editing compared to flat-string models?",
      options: ["Tree structures are slower to render but easier to transmit over WebSocket", "Operations on tree nodes (split node, join nodes, wrap in list) require more sophisticated transformation logic than character-level insertions, but the tree enables semantic conflict resolution (e.g., two users cannot independently wrap the same paragraph in different list types in a way that creates invalid document structure)", "Tree structures prevent any conflicts since each node is independently editable", "ProseMirror uses a flat string internally and only renders as a tree"],
      correctAnswer: 1,
      explanation: "**Step 1:** Contrast flat and tree document models. Flat-string OT treats the document as characters[] with insert/delete at integer positions. Tree-based models (ProseMirror) treat the document as an immutable node tree with semantic node types (paragraph, heading, table, list). Structural operations operate on tree topology, not character indices.\\n\\n**Step 2:** Recognize why tree OT is more complex. Two concurrent operations might both try to wrap the same paragraph in a list — one as ordered, one as unordered. In tree OT, this is a schema conflict that requires the OT layer to decide whether to allow both, reject one, or merge them.\\n\\n**Step 3:** Appreciate schema validation as a conflict resolution tool. ProseMirror's schema ensures the document can never be in an invalid state — even after concurrent structural changes are merged, the resulting tree is always valid.",
      hints: ["With a flat string, all you can conflict on is 'who inserted what where'. With a tree, you can conflict on 'what is this node's type, parent, or attributes'.", "Schema validation in ProseMirror means the document can never be in an invalid state — even after merging concurrent structural changes."],
    },
  ],

  "sdi-rt-spreadsheet": [
    {
      id: "q-rt-19",
      type: "multiple-choice",
      difficulty: "hard",
      question: "In Google Sheets, two users simultaneously edit cell A1 and cell B1, where B1 contains the formula =A1*2. What concurrency challenge does this formula dependency create compared to a plain-text document?",
      options: ["Formula cells cannot be edited by multiple users simultaneously and are locked automatically", "The formula dependency graph must be re-evaluated after every merge, and if A1's new value conflicts with B1's expected input type, the system must decide which edit to prioritize", "Formulas are converted to static values during collaborative sessions to avoid dependency tracking", "Spreadsheets use last-write-wins per cell, so the formula always overwrites the data"],
      correctAnswer: 1,
      explanation: "**Step 1:** Understand the dependency graph. A spreadsheet is a live computation graph: each cell either holds a raw value or a formula referencing other cells. When a cell changes, all cells that transitively depend on it must be re-evaluated in topological order.\\n\\n**Step 2:** Handle concurrent edits with topological re-evaluation. When two users edit A1 and B1 concurrently (where B1 = A1*2), both changes are merged at the cell level. Then the dependency graph is re-traversed from changed cells.\\n\\n**Step 3:** Manage deletion conflicts. If User A deletes row 1 while User B's formula =A1*2 is open, the formula references a deleted cell. Google Sheets keeps deleted cells as tombstones, allowing formulas to resolve #REF! gracefully rather than crashing.",
      hints: ["A plain-text document has no semantic dependencies between its parts — a spreadsheet is a live computation graph.", "Think of it as: merging cell edits is the easy part; re-evaluating the dependency DAG consistently across all clients is the hard part."],
    },
  ],

  "sdi-rt-whiteboard": [
    {
      id: "q-rt-20",
      type: "multiple-choice",
      difficulty: "medium",
      question: "In a Figma or Miro-style collaborative whiteboard, objects exist on a 2D canvas with a z-order (stacking order). Two users simultaneously bring different objects to the front. How should the z-order conflict be resolved?",
      options: ["Reject the second operation since z-order is a global property", "Use a fractional indexing scheme for z-order values; each 'bring to front' assigns a new fractional value greater than the current maximum, allowing both operations to be applied without conflict", "Use last-write-wins based on server timestamp for all z-order changes", "Lock the entire canvas z-order index while any user is performing a z-order operation"],
      correctAnswer: 1,
      explanation: "**Step 1:** Identify why integer z-indices fail concurrently. With integer z-indices [0, 1, 2], to insert an object between 0 and 1, you must renumber all objects from 1 onward — a write collision. Two concurrent insertions both trying to claim position 1 create a conflict.\\n\\n**Step 2:** Apply fractional indexing. Each object's z-key is a floating-point number. The maximum z-key in the document is tracked. Bring-to-front assigns max_z + 1.0, which is guaranteed to be greater than all existing z-keys without renumbering anything.\\n\\n**Step 3:** Resolve tie-breaking and precision limits. When two objects' z-keys are very close, the floating-point resolution limit is approached. The system periodically renormalizes all z-keys by collecting all objects, sorting them, and reassigning evenly-spaced floating-point values.",
      hints: ["Fractional indexing is the same technique used in Notion's block ordering and Figma's layer ordering.", "Two concurrent 'bring to front' operations assign different new max values — both succeed, and the tie is broken by the value magnitude."],
    },
    {
      id: "q-rt-21",
      type: "multiple-choice",
      difficulty: "medium",
      question: "In a collaborative drawing application like Miro, a user draws a stroke consisting of 500 points over 2 seconds. What is the most efficient strategy for broadcasting this stroke to other users in real-time?",
      options: ["Wait until the stroke is complete, then send all 500 points as a single message", "Send individual point events for every mouse move event (~60/second)", "Stream intermediate 'stroke-in-progress' events with batched points (e.g., every 50ms), followed by a final 'stroke-complete' event with the full stroke and a stable ID", "Store the stroke locally and sync only when the user explicitly saves"],
      correctAnswer: 2,
      explanation: "**Step 1:** Recognize wall-clock unreliability. NTP accuracy of 1ms LAN / 100ms internet means two events 50ms apart can appear reversed under clock skew. Manual time changes and NTP corrections (which can step time backwards) further violate the monotonicity that distributed ordering requires.\\n\\n**Step 2:** Use Lamport logical clocks. Each node maintains a counter incremented on every send/receive event. If event A happens before event B (causally), then L(A) < L(B). Lamport timestamps provide a total ordering consistent with causality.\\n\\n**Step 3:** Use vector clocks for true concurrency detection. Each node maintains a vector of counters [c0, c1, c2]. If one component is greater and another lesser, the replicas have diverged and must merge. Vector clocks reveal true concurrency that Lamport clocks cannot detect.",
      options: ["True", "False"],
      correctAnswer: "False",
      explanation: "Wall-clock timestamps are unreliable for ordering distributed events even with NTP. NTP synchronization accuracy varies from ~1ms on a LAN to ~100ms over the internet, meaning two writes that appear simultaneous to humans can have their order reversed by clock skew. Additionally, clocks can be set backwards (by NTP corrections or manual intervention), violating monotonicity. The correct tool is Lamport clocks (logical clocks that increment on every send/receive) or vector clocks (which track causality per node). Lamport timestamps provide a total order consistent with causality; vector clocks reveal true concurrency. Production systems like Cassandra use hybrid logical clocks (HLC) that combine wall-clock time with logical counters for a best-of-both-worlds approach.",
      hints: ["Two events on different machines with timestamps 1ms apart might actually be concurrent or even in reverse causal order.", "Lamport's insight: you don't need a real clock to order events; you just need a counter that advances consistently."],
    },
    {
      id: "q-rt-23",
      type: "multiple-choice",
      difficulty: "hard",
      question: "A PN-Counter CRDT is used to track the number of 'likes' on a collaborative document. It consists of two G-Counters: P (increments) and N (decrements). What is the correct way to read the current value and why can the value temporarily appear negative?",
      options: ["Value = max(P - N, 0); the floor at zero prevents negative display values", "Value = sum(P) - sum(N); this can temporarily go negative because decrement operations may be observed before their corresponding increment operations due to network reordering", "Value = sum(P) only; decrements are handled by the database, not the CRDT", "Value = sum(P) - sum(N) clamped to the shard's local view, preventing cross-shard inconsistency"],
      correctAnswer: 1,
      explanation: "**Step 1:** Understand the PN-Counter structure. A PN-Counter is two G-Counters: P (positive) tracks increments, N (negative) tracks decrements. Each replica has its own P and N vectors. The value at any replica is sum(P) - sum(N). Each node can only increment its own P slot and its own N slot.\\n\\n**Step 2:** Explain transient negatives. Operation-based CRDTs deliver operations in causal order (via causal broadcast), but causally-ordered delivery does not mean real-time delivery order. A decrement at replica R may arrive before its paired increment if the increment took a slower network path.\\n\\n**Step 3:** Verify eventual convergence. Once all operations have propagated to all replicas, sum(P) = total_increments across all nodes and sum(N) = total_decrements. The converged value is always correct. Application-level constraints can mask the transient negativity from end users.",
      hints: ["Eventual consistency means 'correct eventually' not 'correct always' — transient negative values are a known tradeoff.", "The invariant is convergence: once all updates propagate, sum(P) - sum(N) is the same at all replicas."],
    },
  ],

  "sdi-rt-merkle-sync": [
    {
      id: "q-rt-24",
      type: "multiple-choice",
      difficulty: "hard",
      question: "How do Merkle trees enable efficient state synchronization between two replicas of a collaborative document without transferring the entire document?",
      options: ["Merkle trees compress the document using a tree-based Huffman encoding", "Each node in the Merkle tree hashes the content below it; two replicas compare root hashes first, then recursively compare subtree hashes, transferring only the leaf nodes (data chunks) where hashes differ", "Merkle trees store operation logs in a balanced BST for O(log n) lookup", "Replicas exchange only the top-level Merkle root and use it as a version identifier for cache invalidation"],
      correctAnswer: 1,
      explanation: "**Step 1:** Identify the latency problem. The speed of light puts a hard lower bound on US-East to APAC round-trip time: ~150ms. OT requires every operation to be serialized by the server before broadcast. A user in APAC pressing a key would wait 150ms for acknowledgment.\\n\\n**Step 2:** Evaluate the three solutions. (1) Single primary region: operations sent to the primary region, serialized, then broadcast. Low latency for users near the primary, high for others. (2) CRDT: operations applied locally immediately; no server serialization required. (3) Hybrid: local CRDT-style application with periodic server reconciliation.\\n\\n**Step 3:** Recognize CRDT's multi-region advantage. CRDT merge is commutative — the order in which operations are merged across regions does not affect the final state. This means APAC and US-East can each apply operations locally and merge later, converging regardless of merge order.",
      options: ["Inter-region bandwidth costs make it prohibitively expensive to synchronize operations", "OT requires a single total ordering of operations, but multi-region systems have higher latency between regions, making it expensive to achieve consensus on ordering; CRDTs are often preferred for multi-region because they do not require global ordering", "Multi-region systems cannot use WebSockets due to BGP routing limitations", "Different regions use different OT algorithms that are incompatible with each other"],
      correctAnswer: 1,
      explanation: "**Step 1:** Understand the LSP position problem. LSP features (hover, autocomplete, go-to-definition) are all anchored to specific document positions. In a collaborative edit, by the time the LSP server processes a hover request, concurrent edits may have shifted the document.\\n\\n**Step 2:** Route through the host's LSP server. VS Code Live Share forwards all LSP requests from guest clients to the host's LSP server, which has the authoritative document state. The host processes the LSP request and returns the result with its current document positions.\\n\\n**Step 3:** Transform response positions for guests. The guest's document may differ from the host's by a few operations. The guest transforms the host's LSP response positions to match its local document state before displaying. Semantic conflicts like simultaneous Rename Symbol require language-aware resolution beyond standard OT.",
      options: ["LSP requires a separate WebSocket connection per user for each file", "LSP requests (hover, autocomplete, go-to-definition) reference document positions that may have changed due to concurrent edits by the time the LSP server responds, requiring position remapping", "LSP is stateless and does not support collaborative sessions", "LSP diagnostics are user-specific and cannot be shared across a collaborative session"],
      correctAnswer: 1,
      explanation: "**Step 1:** Analyze JSON's overhead. For an operation like {op:\"insert\", pos:42, text:\"X\"}, JSON encodes field names (\"op\", \"pos\", \"text\") and string-delimiting quotes in every message. At 100 ops/sec, this overhead is enormous.\\n\\n**Step 2:** Apply binary encoding with Protocol Buffers. Protobuf encodes the same operation as a compact binary message using field tags (1, 2, 3) instead of names. A 200-byte JSON message might become 40-60 bytes in Protobuf — a 3-5x reduction.\\n\\n**Step 3:** Layer on delta compression and batching. For cursor position streams, send only the delta: {pos:43} instead of the full operation. Batch 10 operations into one WebSocket frame, reducing per-frame header overhead. Combined improvements of 5-10x.",
      options: ["Switch from WebSocket to HTTP/2 multiplexing to reduce connection overhead", "Use binary encoding (Protocol Buffers or MessagePack) to reduce per-operation size by 3-5x, apply delta compression to send only changed fields, and batch multiple operations into a single WebSocket frame", "Use gzip compression on the HTTP layer, which WebSocket already provides", "Switch to UDP-based transport for lower latency, accepting occasional packet loss"],
      correctAnswer: 1,
      explanation: "**Step 1:** Prioritize local durability. Every user action is written to a local SQLite database before being applied to the UI and before being sent to the server. If the app is killed, the operation log persists. On restart, the app resumes where it left off.\\n\\n**Step 2:** Reconcile on reconnection. When connectivity returns, the client sends its buffered operations (with base revision) to the server. The server applies OT transformation or CRDT merge. Background sync is handled by iOS Background App Refresh and Android WorkManager.\\n\\n**Step 3:** Acknowledge the tradeoffs. Offline-first with durable local storage (SQLite) adds complexity: storage management, schema migrations, and conflict resolution at the application level. But the user benefit is enormous — edits are never lost, and the app feels instant because writes are local.",
      options: ["Disable collaborative editing on mobile and show a read-only view when the connection drops", "Implement an offline-first architecture: write all operations to a local durable log (SQLite), apply them to the local document immediately, and sync with the server opportunistically when connectivity is available", "Queue operations in memory and replay them on reconnection, accepting that changes made while offline will be lost if the app is killed", "Show a 'connection lost' modal that blocks editing until the connection is restored"],
      correctAnswer: 1,
      explanation: "**Step 1:** Analyze pessimistic locking's user experience problem. In a document where two users want to edit different sentences in the same paragraph, locking forces them to wait for each other. If User A forgets to release the lock, User B is blocked indefinitely.\\n\\n**Step 2:** Embrace optimistic concurrency. OT and CRDTs take the stance: assume concurrent edits are usually compatible (they affect different parts of the document), and handle conflicts when they arise. Two users inserting in different paragraphs: no conflict, both succeed.\\n\\n**Step 3:** Identify legitimate locking use cases. Section locking is appropriate when a structural operation (e.g., \"reformat entire document using AI\") would be disrupted by concurrent edits. The lock prevents new edits during the operation, and the operation is typically restartable.",
      options: ["Pessimistic locking requires a relational database, which is too slow for real-time editing", "Locking blocks other users from editing locked sections, causing poor user experience for short edits; OT and CRDTs eliminate the need for locks by automatically merging concurrent edits without blocking", "Pessimistic locking cannot be implemented over WebSocket connections", "Google Docs is patent-protected from using locking algorithms"],
      correctAnswer: 1,
      explanation: "Pessimistic locking (as used in older collaborative editors like SharePoint document checkout) requires a user to explicitly lock a section before editing and release it after. This blocks all other users from editing that section, causing bottlenecks for any non-trivial editing scenario (e.g., two people editing different sentences in the same paragraph). OT and CRDTs make locking unnecessary: they allow truly concurrent edits to the same content and automatically produce a consistent merged result. The only legitimate use case for section-level locking in modern collaborative editors is for heavyweight operations (e.g., 'currently running a script that reformats the entire document') where you want to prevent conflicting structural changes.",
      hints: ["Optimistic concurrency says: 'assume no conflict; if conflict occurs, merge it'. Pessimistic says: 'prevent conflict by blocking others'. For frequent small edits, blocking is terrible UX.", "Spreadsheet cell locking (Sheets does optionally lock ranges) is a domain-specific pessimistic lock — appropriate when two users independently modifying the same formula cell has unclear semantics."],
    },
  ],

  "sdi-rt-video-annotation": [
    {
      id: "q-rt-30",
      type: "multiple-choice",
      difficulty: "hard",
      question: "In a collaborative video annotation tool (e.g., Frame.io), a comment is anchored to a specific video timecode (e.g., 01:23.456). Two users simultaneously add comments at timecodes 01:23.100 and 01:23.200. How should the comment list be ordered, and what CRDT structure is most appropriate?",
      options: ["Use a first-come-first-served server queue; the server's receive order determines comment position in the list", "Use a CRDT-based ordered list where each comment is assigned a unique (clientID, timestamp) identifier and sorted by (video_timecode, clientID) to produce a deterministic total order without coordination", "Lock the comment panel while any user is adding a comment to prevent ordering conflicts", "Display comments in server-receive order, which naturally matches video playback order due to NTP synchronization"],
      correctAnswer: 1,
      explanation: "**Step 1:** Establish the ordering requirement. Comments must appear in video playback order (timecode ascending) as the primary sort key. Two comments at the same timecode need a deterministic tie-breaker. The total order must be consistent across all replicas without requiring coordination.\\n\\n**Step 2:** Use a CRDT composite key. Each comment is assigned a key (timecode, clientID, counter). The timecode is the video timestamp. The clientID ensures uniqueness across devices. The counter handles multiple comments at the same timecode from the same client.\\n\\n**Step 3:** Handle video re-cutting. When the video is re-cut (frames added/removed), timecodes shift. Comments anchored to old timecodes become \"orphaned.\" A floating comment system relocates comments to the nearest valid timecode after a re-cut, or displays them in a separate section.",
      hints: ["Timecode is the primary sort key (semantic order); the clientID or counter is the tie-breaker for same-timecode conflicts.", "The CRDT property needed here is: any two replicas that have seen the same set of comment insertions produce the same sorted list, regardless of insertion order."],
    },
  ],
};

registerQuestions(questions);

export default questions;
