import type { Question } from "@/lib/curriculum";
import { registerQuestions } from "./registry";

const questions: Record<string, Question[]> = {
  "sdip-powers-of-two": [
    {
      id: "q-sdip-1",
      type: "multiple-choice",
      difficulty: "easy",
      question: "According to Google's powers-of-2 table used in back-of-envelope estimation, what is 2^10?",
      options: ["1 KB (1,024 bytes)", "1 MB (1,048,576 bytes)", "1 GB (1,073,741,824 bytes)", "1 TB (1,099,511,627,776 bytes)"],
      correctAnswer: 0,
      explanation: "2^10 = 1,024, which is approximately 1 KB. The key milestones are: 2^10 \u2248 1 KB, 2^20 \u2248 1 MB, 2^30 \u2248 1 GB, 2^40 \u2248 1 TB. Memorizing these four anchors lets you rapidly estimate storage and memory needs by knowing that each 10 additional powers of 2 multiplies the unit by 1,000.",
      hints: ["Each increment of 10 in the exponent adds one unit tier: KB, MB, GB, TB.", "2^10 = 1,024 \u2248 10^3."],
    },
    {
      id: "q-sdip-2",
      type: "multiple-choice",
      difficulty: "easy",
      question: "In back-of-envelope estimation, approximately how many bytes are in 1 GB?",
      options: ["10^6 bytes", "10^7 bytes", "10^9 bytes", "10^12 bytes"],
      correctAnswer: 2,
      explanation: "1 GB \u2248 10^9 bytes (exactly 2^30 = 1,073,741,824 bytes). In estimation work we round to 10^9 for simplicity. The full chain is: 1 KB \u2248 10^3, 1 MB \u2248 10^6, 1 GB \u2248 10^9, 1 TB \u2248 10^12. This decimal approximation is acceptable in interviews because you are aiming for the right order of magnitude, not exact byte counts.",
      hints: ["2^30 is the exact value; what is its rough decimal equivalent?", "Each jump from KB to MB to GB multiplies by roughly 1,000."],
    },
    {
      id: "q-sdip-3",
      type: "true-false",
      difficulty: "easy",
      question: "In systems design interview estimation, being within a factor of 10 (one order of magnitude) of the true answer is generally considered acceptable.",
      correctAnswer: "True",
      explanation: "True. The purpose of back-of-envelope estimation is to determine whether a system needs 1 server or 100 servers, or 1 TB or 1 PB of storage. An answer within 10x of reality still points you at the same architectural tier. Interviewers look for structured reasoning, correct units, and sound assumptions \u2014 not spreadsheet-precision arithmetic.",
      hints: ["The goal is to pick the right class of solution, not the exact number.", "Would knowing you need '~5 servers' vs exactly 4.7 servers change your architecture?"],
    },
  ],

  "sdip-latency-numbers": [
    {
      id: "q-sdip-4",
      type: "multiple-choice",
      difficulty: "medium",
      question: "Which latency ordering is correct for the famous numbers every engineer should know (from Jeff Dean's lecture)?",
      options: [
        "L1 cache < Main memory < SSD random read < Network roundtrip (same datacenter) < Network roundtrip (cross-continent)",
        "L1 cache < SSD random read < Main memory < Network roundtrip (same datacenter) < Network roundtrip (cross-continent)",
        "Main memory < L1 cache < SSD random read < Network roundtrip (same datacenter) < Network roundtrip (cross-continent)",
        "L1 cache < Main memory < Network roundtrip (same datacenter) < SSD random read < Network roundtrip (cross-continent)",
      ],
      correctAnswer: 0,
      explanation: "The correct ordering is L1 cache (\u22481 ns) < Main memory (\u2248100 ns) < SSD random read (\u2248100 \u03bcs) < Same-datacenter roundtrip (\u22480.5 ms) < Cross-continental roundtrip (\u2248150 ms). Each step is roughly 100-1,000x slower. These numbers anchor all latency SLA decisions: if you need sub-millisecond response, you must stay in L1/RAM; if you need sub-100 ms, you can afford one network hop.",
      hints: ["L1 cache is on-chip; memory is on the motherboard; SSD is behind a PCIe bus.", "A cross-continental packet crosses thousands of miles of fiber \u2014 that light-speed delay alone is ~70 ms each way."],
    },
    {
      id: "q-sdip-5",
      type: "multiple-choice",
      difficulty: "medium",
      question: "A systems design interview asks you to design a feature requiring sub-10 ms p99 latency for user-facing reads. Which storage tier is appropriate as the primary read path?",
      options: ["Spinning disk HDD (seek time ~10 ms)", "SSD with NVMe (random read ~100 \u03bcs)", "In-memory cache like Redis (\u22641 ms round-trip)", "Object storage like S3 (first-byte latency ~50-200 ms)"],
      correctAnswer: 2,
      explanation: "For sub-10 ms p99 latency on user-facing reads, an in-memory cache (Redis, Memcached) is the right primary read path with <1 ms typical round-trip. NVMe SSD (~100 \u03bcs per random read) could theoretically work but network overhead plus tail latency push p99 beyond 10 ms. HDD seek time alone is ~10 ms, and object storage latency of 50-200 ms for first byte is far too slow. In-process caching (e.g., Guava) is even faster but can\u2019t be shared across instances.",
      hints: ["p99 latency includes queueing, serialization, and network overhead \u2014 not just storage access time.", "Which option\u2019s maximum latency fits comfortably within 10 ms?"],
    },
  ],

  "sdip-qps-estimation": [
    {
      id: "q-sdip-6",
      type: "multiple-choice",
      difficulty: "medium",
      question: "Twitter has 300 million daily active users (DAU). 20% of users post each day and each posting user sends an average of 5 tweets. Approximately how many tweet write QPS must the system handle at peak (assume 2x day-average peak)?",
      options: ["\u22484 writes/sec average, \u22488 writes/sec peak", "\u224840 writes/sec average, \u224880 writes/sec peak", "\u2248400 writes/sec average, \u2248800 writes/sec peak", "\u22484,000 writes/sec average, \u22488,000 writes/sec peak"],
      correctAnswer: 3,
      explanation: "300M DAU \u00d7 20% posting = 60M posting users/day. 60M \u00d7 5 tweets = 300M tweets/day. 300M / 86,400 seconds/day \u2248 3,472 tweets/sec (average). Peak at 2x day-average = \u22487,000 writes/sec, closest to 4,000 avg / 8,000 peak. Key formula: QPS = (DAU \u00d7 actions_per_user) / seconds_per_day. 86,400 \u2248 10^5 is a handy approximation. Always state your assumptions and show the multiplication chain; interviewers care about your reasoning process.",
      hints: ["86,400 seconds per day \u2248 10^5 for fast estimation.", "DAU \u00d7 fraction_active \u00d7 actions_per_session / seconds_per_day = average QPS."],
    },
    {
      id: "q-sdip-7",
      type: "multiple-choice",
      difficulty: "hard",
      question: "A system processes 10,000 QPS at steady state and each request takes exactly 100 ms to process. How many concurrent request-handling threads (or goroutines) must be available to sustain this load without queueing?",
      options: ["10 threads", "100 threads", "1,000 threads", "10,000 threads"],
      correctAnswer: 2,
      explanation: "Little\u2019s Law: L = \u03bb \u00d7 W, where L = average concurrency (threads in flight), \u03bb = arrival rate (10,000/sec), W = average service time (0.1 sec). L = 10,000 \u00d7 0.1 = 1,000 concurrent threads. This is the minimum thread pool size; in practice you add a safety buffer (e.g., 1,500). Little\u2019s Law is one of the most powerful and underused tools in capacity planning \u2014 knowing it demonstrates senior-level systems thinking.",
      hints: ["Little\u2019s Law: average_concurrency = arrival_rate \u00d7 service_time.", "10,000 requests/sec \u00d7 0.1 sec/request = ? requests simultaneously in flight."],
    },
    {
      id: "q-sdip-8",
      type: "true-false",
      difficulty: "medium",
      question: "When estimating QPS in a systems design interview, it is acceptable to treat 1 day as 100,000 seconds (10^5) rather than the exact 86,400 seconds.",
      correctAnswer: "True",
      explanation: "True. 86,400 \u2248 10^5 is a standard approximation used in back-of-envelope calculations. The error is only 16%, well within the 10x tolerance for order-of-magnitude estimation. Using 10^5 simplifies mental math dramatically: if you have 1 billion events per day, dividing by 10^5 immediately gives 10,000 events/sec. Top interviewers at Google, Meta, and Amazon explicitly encourage this kind of approximation.",
      hints: ["86,400 vs 100,000 \u2014 what is the percentage difference?", "Is a 16% error acceptable when you\u2019re estimating to determine server count?"],
    },
  ],

  "sdip-storage-estimation": [
    {
      id: "q-sdip-9",
      type: "multiple-choice",
      difficulty: "easy",
      question: "A social network has 1 billion users, each with a profile stored as approximately 1 KB of metadata. What is the total storage required for all user profiles?",
      options: ["1 GB", "1 TB", "1 PB", "1 EB"],
      correctAnswer: 1,
      explanation: "1 billion users \u00d7 1 KB/user = 10^9 \u00d7 10^3 bytes = 10^12 bytes = 1 TB. This is a canonical estimation example: 1B \u00d7 1KB = 1TB. The pattern generalizes: N (billion) users \u00d7 M KB/user = N\u00d7M TB. So 1B users at 10 KB each = 10 TB. Knowing this lets you quickly sanity-check storage designs during interviews.",
      hints: ["1 billion = 10^9, 1 KB = 10^3 bytes. Multiply the exponents.", "10^9 \u00d7 10^3 = 10^12 bytes. What storage unit is 10^12 bytes?"],
    },
    {
      id: "q-sdip-10",
      type: "multiple-choice",
      difficulty: "medium",
      question: "Twitter has accumulated 100 billion tweets, each tweet averaging 280 characters (1 byte/char in ASCII, but Twitter stores UTF-8 with metadata overhead bringing average to \u2248280 bytes). What is the approximate total raw text storage?",
      options: ["28 GB", "2.8 TB", "28 TB", "280 TB"],
      correctAnswer: 2,
      explanation: "100 billion tweets \u00d7 280 bytes/tweet = 10^11 \u00d7 2.8 \u00d7 10^2 = 2.8 \u00d7 10^13 bytes \u2248 28 TB. The calculation: 10^11 \u00d7 280 = 2.8 \u00d7 10^13 bytes. 10^12 bytes = 1 TB, so 2.8 \u00d7 10^13 = 28 TB. This excludes media, indices, and replication. In practice Twitter\u2019s total storage is petabytes when you include all replicas, indices, and media, but raw text alone is in the tens of TB range.",
      hints: ["100 billion = 10^11. 280 bytes \u2248 3 \u00d7 10^2.", "10^11 \u00d7 10^2 = 10^13 bytes. How many TB is 10^13 bytes?"],
    },
    {
      id: "q-sdip-11",
      type: "multiple-choice",
      difficulty: "hard",
      question: "A photo-sharing service stores 100 million photos/day. Each original photo is 3 MB, and the service generates 3 additional thumbnails at 100 KB each. How much raw storage (before replication) is needed per year?",
      options: ["\u224811 PB/year", "\u2248110 PB/year", "\u22481.1 PB/year", "\u2248110 TB/year"],
      correctAnswer: 1,
      explanation: "Per photo: 3 MB original + 3 \u00d7 100 KB thumbnails = 3 MB + 0.3 MB = 3.3 MB/photo. Per day: 10^8 photos \u00d7 3.3 MB = 3.3 \u00d7 10^8 MB = 3.3 \u00d7 10^14 bytes \u2248 330 TB/day. Per year: 330 TB/day \u00d7 365 \u2248 120,000 TB \u2248 120 PB/year. Closest answer: ~110 PB/year (rounding). With 3x replication this becomes ~360 PB/year. Always break storage estimation into: per-item-size \u00d7 items-per-day \u00d7 days \u00d7 replication-factor.",
      hints: ["Calculate per-photo storage first (original + all thumbnails), then scale to daily volume, then annual.", "330 TB/day \u00d7 365 days = ? PB/year."],
    },
    {
      id: "q-sdip-12",
      type: "true-false",
      difficulty: "medium",
      question: "When estimating storage in a systems design interview, you should always multiply your raw storage estimate by the replication factor (typically 3x) to get the true infrastructure storage cost.",
      correctAnswer: "True",
      explanation: "True. Raw data storage and infrastructure storage are different quantities. Standard replication factor is 3x (one primary + two replicas) in systems like HDFS, Cassandra, and Google Spanner. If you estimate 10 TB of raw data, the true disk provisioning need is 30 TB. Forgetting replication is one of the most common mistakes in storage estimation and can throw off your server count calculation by 3x.",
      hints: ["Think about what happens to a file stored in HDFS with the default replication factor.", "If 3 copies of each byte are stored, what does that do to total disk usage?"],
    },
  ],

  "sdip-bandwidth-estimation": [
    {
      id: "q-sdip-13",
      type: "multiple-choice",
      difficulty: "hard",
      question: "A video streaming platform has 1 million concurrent viewers, each watching HD video at 5 Mbps. What is the total egress bandwidth required?",
      options: ["5 Gbps", "50 Gbps", "500 Gbps", "5 Tbps"],
      correctAnswer: 3,
      explanation: "1,000,000 concurrent streams \u00d7 5 Mbps/stream = 5,000,000 Mbps = 5,000,000 \u00d7 10^6 bits/sec = 5 \u00d7 10^12 bits/sec = 5 Tbps. For context, Netflix at peak serves ~15% of global internet bandwidth, estimated at 200+ Tbps. A single datacenter cannot serve 5 Tbps \u2014 you immediately need a CDN. This calculation directly motivates CDN architecture: serve from edge nodes near users to avoid backhauling all this traffic to origin.",
      hints: ["1 million = 10^6 streams. 5 Mbps = 5 \u00d7 10^6 bits/sec.", "10^6 \u00d7 5 \u00d7 10^6 = 5 \u00d7 10^12 bits/sec. What unit is 10^12 bits/sec?"],
    },
    {
      id: "q-sdip-14",
      type: "multiple-choice",
      difficulty: "medium",
      question: "A file upload service receives 10,000 file uploads per second, each file averaging 1 MB. What is the required ingress bandwidth?",
      options: ["10 Mbps", "100 Mbps", "10 Gbps", "80 Gbps"],
      correctAnswer: 3,
      explanation: "10,000 files/sec \u00d7 1 MB/file = 10,000 MB/sec = 10 GB/sec. Converting to bits: 10 GB/sec \u00d7 8 bits/byte = 80 Gbps. The byte-to-bit conversion (multiply by 8) is commonly forgotten \u2014 network bandwidth is specified in bits per second (bps), not bytes per second (Bps). 80 Gbps requires multiple 100GbE links, which pushes you toward distributed ingestion with load balancing across many frontend servers.",
      hints: ["Network bandwidth is in bits; storage is in bytes. Remember to multiply by 8.", "10,000 \u00d7 1 MB = 10,000 MB/sec = 10 GB/sec. Convert to Gbps."],
    },
    {
      id: "q-sdip-15",
      type: "true-false",
      difficulty: "easy",
      question: "In bandwidth estimation, 1 Gbps = 125 MB/s because there are 8 bits in a byte.",
      correctAnswer: "True",
      explanation: "True. 1 Gbps = 10^9 bits/sec. Since 1 byte = 8 bits, we get 10^9 / 8 = 125 \u00d7 10^6 bytes/sec = 125 MB/s. This conversion is essential for cross-checking estimates: if your storage team thinks in MB/s and your network team thinks in Mbps, you need to convert fluently. A 10 Gbps link can sustain ~1,250 MB/s of actual data throughput (ignoring protocol overhead).",
      hints: ["How many bits are in a byte?", "Divide Gbps by 8 to get GB/s, then adjust units."],
    },
  ],

  "sdip-read-write-ratio": [
    {
      id: "q-sdip-16",
      type: "multiple-choice",
      difficulty: "medium",
      question: "A social media feed system has a 100:1 read-to-write ratio. If the system handles 1,000 writes/sec, what is the total read QPS, and what architectural pattern does this ratio motivate?",
      options: [
        "1,000 reads/sec; vertical scaling of the write database",
        "100,000 reads/sec; read replicas or separate read-optimized stores",
        "1,000,000 reads/sec; write-ahead logging only",
        "10,000 reads/sec; synchronous replication to all nodes",
      ],
      correctAnswer: 1,
      explanation: "100:1 ratio \u00d7 1,000 writes/sec = 100,000 reads/sec. Heavy read:write skew motivates read replicas, caching, and fanout-on-read vs fanout-on-write strategies. The key insight: you cannot simply scale the primary database for writes to also handle reads \u2014 you need a dedicated read tier. Twitter's fanout-on-write (pre-computed timelines) vs fanout-on-read tradeoff is a classic example of optimizing for this ratio.",
      hints: ["Multiply write QPS by the read:write ratio to get read QPS.", "A 100:1 read-heavy system means reads dominate \u2014 which layer should you scale?"],
    },
    {
      id: "q-sdip-17",
      type: "multiple-choice",
      difficulty: "medium",
      question: "A key-value store has 1 ms cache hit latency and 100 ms database latency. If the cache hit rate is 99%, what is the average read latency?",
      options: ["\u22481 ms", "\u22481.99 ms", "\u22482.99 ms", "\u224850 ms"],
      correctAnswer: 1,
      explanation: "Average latency = (hit_rate \u00d7 cache_latency) + (miss_rate \u00d7 db_latency) = (0.99 \u00d7 1 ms) + (0.01 \u00d7 100 ms) = 0.99 ms + 1 ms = 1.99 ms. This is why a 99% cache hit rate with a 100x latency differential produces average latency only ~2x the cache latency, not 50x. A 1% miss rate sounds tiny but contributes 1 ms to the average \u2014 equal to the entire cache latency contribution. Improving cache hit rate from 99% to 99.9% would drop average latency to 0.999 + 0.1 = 1.1 ms.",
      hints: ["Weighted average: (probability of each path) \u00d7 (latency of each path), summed.", "0.99 \u00d7 1ms + 0.01 \u00d7 100ms = ?"],
    },
  ],

  "sdip-replication-sla": [
    {
      id: "q-sdip-18",
      type: "multiple-choice",
      difficulty: "medium",
      question: "A service advertises 99.9% uptime SLA. How many minutes of downtime per year does this correspond to?",
      options: ["\u22488.7 hours (522 minutes)", "\u224852 minutes", "\u22485 minutes", "\u224887 hours (5,220 minutes)"],
      correctAnswer: 0,
      explanation: "99.9% uptime means 0.1% downtime. Minutes/year = 365 \u00d7 24 \u00d7 60 = 525,600 minutes. 0.001 \u00d7 525,600 \u2248 526 minutes \u2248 8.76 hours. The quick reference: 99% = 87.6 hours/year downtime, 99.9% = 8.76 hours/year, 99.99% = 52 minutes/year, 99.999% = 5.25 minutes/year. Each additional 9 reduces downtime by 10x. Knowing these numbers lets you immediately assess whether your design needs multiple redundancy layers.",
      hints: ["Downtime fraction = 1 - uptime fraction = 0.001. Multiply by minutes/year.", "525,600 minutes/year \u00d7 0.001 = ?"],
    },
    {
      id: "q-sdip-19",
      type: "multiple-choice",
      difficulty: "hard",
      question: "A system requires 99.99% uptime (four nines). If two independent components are in series (both must work), each with 99.99% uptime, what is the combined system uptime?",
      options: ["99.99%", "99.98%", "99.9%", "99.0%"],
      correctAnswer: 1,
      explanation: "For components in series, system availability = product of individual availabilities. 0.9999 \u00d7 0.9999 = 0.9998 = 99.98%. Each component contributes its downtime additively in the small-downtime approximation: 0.01% + 0.01% \u2248 0.02% downtime = 99.98% uptime. This is why adding dependencies reduces overall SLA. A microservices chain with 10 services each at 99.99% has combined availability of 0.9999^10 \u2248 99.9% \u2014 you\u2019ve lost a nine just by chaining services.",
      hints: ["Series components: multiply individual availabilities.", "0.9999 \u00d7 0.9999 = 0.9999^2 \u2248 ?"],
    },
    {
      id: "q-sdip-20",
      type: "true-false",
      difficulty: "medium",
      question: "Standard replication factor of 3 in distributed systems (like HDFS or Cassandra) means the system can tolerate the simultaneous failure of any 2 nodes without data loss.",
      correctAnswer: "False",
      explanation: "False. A replication factor of 3 guarantees that at least 3 copies of each data item exist. With a quorum read/write (majority = 2 out of 3), the system can tolerate 1 node failure while maintaining consistency. For data durability (no data loss), you can tolerate up to 2 node failures only if at least 1 replica survives \u2014 but losing all 3 nodes holding a particular shard would cause data loss. Additionally, in Cassandra with RF=3 and QUORUM consistency, 1 node failure is the maximum for consistent reads/writes; 2 failures break quorum.",
      hints: ["Replication factor 3 = 3 copies, but quorum for consistency requires majority.", "Can you still do a quorum read/write with only 1 out of 3 nodes alive?"],
    },
  ],

  "sdip-server-capacity": [
    {
      id: "q-sdip-21",
      type: "multiple-choice",
      difficulty: "medium",
      question: "A single application server can handle approximately 10,000 QPS for simple in-memory requests. If the system needs to handle 500,000 QPS, how many servers are needed (ignoring overhead)?",
      options: ["5 servers", "50 servers", "500 servers", "5,000 servers"],
      correctAnswer: 1,
      explanation: "Servers needed = Total QPS / QPS per server = 500,000 / 10,000 = 50 servers. In practice you add a safety margin (e.g., 20-30%) and account for uneven load distribution, so you might provision 70-80 servers. The formula servers_needed = peak_QPS / single_server_capacity is fundamental to capacity planning. In interviews, state your per-server capacity assumption explicitly \u2014 it demonstrates you understand the hardware tier.",
      hints: ["Divide total required QPS by per-server QPS capacity.", "500,000 / 10,000 = ?"],
    },
    {
      id: "q-sdip-22",
      type: "multiple-choice",
      difficulty: "hard",
      question: "Which capacity rule of thumb is most commonly cited for a single database server handling mixed read/write workloads?",
      options: [
        "~1,000 QPS for complex queries with joins",
        "~10,000 QPS for simple key-value lookups on indexed columns",
        "~100,000 QPS for in-memory databases like Redis",
        "All of the above are correct for their respective scenarios",
      ],
      correctAnswer: 3,
      explanation: "All three are commonly accepted rules of thumb: (1) Relational DB with complex joins: ~1,000 QPS. (2) Relational DB with simple indexed lookups: ~10,000 QPS. (3) In-memory stores like Redis: ~100,000-1,000,000 QPS. The 10x step between each tier reflects the latency profile. Knowing all three lets you quickly determine whether you need DB optimization, caching, or a fundamentally different storage layer. This multi-tier awareness is what separates strong candidates from average ones.",
      hints: ["Consider what makes each workload different: disk I/O, index traversal, network, pure RAM.", "Does a Redis GET and a PostgreSQL JOIN have the same bottleneck?"],
    },
  ],

  "sdip-interview-structure": [
    {
      id: "q-sdip-23",
      type: "multiple-choice",
      difficulty: "easy",
      question: "What is the recommended first step when starting a systems design interview at companies like Google, Amazon, and Meta?",
      options: [
        "Immediately draw the system architecture on the whiteboard",
        "Start writing API endpoints and data models",
        "Clarify functional and non-functional requirements with the interviewer",
        "Choose the database technology and justify your choice",
      ],
      correctAnswer: 2,
      explanation: "The universally recommended first step is clarifying requirements \u2014 both functional (what the system does) and non-functional (scale, latency, consistency, availability). Jumping to solutions before understanding the problem is the #1 interview mistake cited by Google, Amazon, and Meta interviewers. Spend the first 5 minutes asking: What features are in scope? What is the expected scale (DAU, QPS)? What is the latency SLA? What consistency model is required? This sets the entire direction of your design.",
      hints: ["What happens if you design for 1,000 users when the interviewer meant 1 billion?", "Requirements clarification is free; redesigning mid-interview wastes your limited time."],
    },
    {
      id: "q-sdip-24",
      type: "multiple-choice",
      difficulty: "medium",
      question: "In a Google systems design interview, what is the recommended structure for a 45-minute session?",
      options: [
        "5 min requirements, 5 min estimation, 10 min API/data model, 20 min high-level design, 5 min deep dive",
        "2 min requirements, 30 min detailed component design, 13 min Q&A",
        "15 min requirements, 15 min architecture, 15 min coding a component",
        "10 min estimation only, then let the interviewer lead",
      ],
      correctAnswer: 0,
      explanation: "The widely recommended structure for a 45-minute systems design interview is: 5 min \u2014 clarify requirements and scope; 5 min \u2014 capacity estimation (DAU, QPS, storage, bandwidth); 10 min \u2014 API design and data model; 20 min \u2014 high-level architecture diagram; 5 min \u2014 deep dive on one component the interviewer probes. This pacing ensures you cover the full breadth before going deep and shows interviewers you can structure an open-ended problem. Time management is itself evaluated.",
      hints: ["What do interviewers need to see to give full marks: breadth first or depth first?", "A complete high-level design is more valuable than a perfect but incomplete subsystem."],
    },
    {
      id: "q-sdip-25",
      type: "true-false",
      difficulty: "easy",
      question: "In a systems design interview, it is acceptable to explicitly tell the interviewer \u201cI am going to make an assumption here\u201d and state that assumption before proceeding, rather than waiting to be given exact numbers.",
      correctAnswer: "True",
      explanation: "True. Making and stating explicit assumptions is a core interview skill. Interviewers rarely have perfect answers to \u201chow many users will this system have?\u201d They want to see you handle ambiguity by reasoning from first principles. Saying \u201cI\u2019ll assume 10 million DAU \u2014 is that reasonable?\u201d demonstrates structured thinking and invites correction. Never silently assume; always verbalize your assumptions so the interviewer can redirect you if needed.",
      hints: ["What is worse: making a wrong assumption or making no assumption and stalling?", "How does stating assumptions help the interviewer understand your thought process?"],
    },
  ],

  "sdip-cap-theorem": [
    {
      id: "q-sdip-26",
      type: "multiple-choice",
      difficulty: "medium",
      question: "A financial payment system must never show inconsistent account balances to users (strong consistency required). During a network partition, what does CAP theorem dictate?",
      options: [
        "The system can maintain both consistency and availability during a partition",
        "The system must choose to sacrifice availability (return errors) to preserve consistency",
        "The system should use eventual consistency with compensating transactions",
        "CAP theorem does not apply to databases with ACID guarantees",
      ],
      correctAnswer: 1,
      explanation: "CAP theorem states that during a network partition (P), a system must choose between Consistency (C) and Availability (A). For a payment system requiring strong consistency, the correct choice is CP: during a partition, the system refuses to serve stale reads (returns errors or waits) rather than risk showing inconsistent balances. Examples: Google Spanner (CP), HBase (CP). In contrast, DNS and Cassandra are AP \u2014 they stay available but may serve stale data. Partitions in production are rare but inevitable; the CAP choice defines your failure behavior.",
      hints: ["Strong consistency for payments means you cannot show balance A to one node and balance B to another.", "What happens to a bank if it processes a debit on stale data?"],
    },
    {
      id: "q-sdip-27",
      type: "multiple-choice",
      difficulty: "hard",
      question: "A social media \u201clike count\u201d feature can tolerate showing counts that are a few seconds stale. Which consistency model and database are most appropriate?",
      options: [
        "Strong consistency; PostgreSQL with synchronous replication",
        "Eventual consistency; Cassandra with AP configuration",
        "Linearizability; Google Spanner",
        "Causal consistency; CockroachDB",
      ],
      correctAnswer: 1,
      explanation: "Like counts are a classic AP use case: the cost of showing a count that is 2 seconds stale is negligible (user sees 10,432 instead of 10,433 likes). Cassandra with eventual consistency is ideal \u2014 it offers high write throughput, geographic distribution, and fault tolerance. Strong consistency (Spanner, PostgreSQL sync) would add latency and reduce availability for no user-visible benefit. Causal consistency is overkill \u2014 you do not need to guarantee that likes are observed in causal order. Matching consistency level to business requirements is a key systems design skill.",
      hints: ["What is the real cost to the user of seeing a like count that is 2 seconds behind?", "Does the business requirement justify the availability sacrifice of strong consistency?"],
    },
  ],

  "sdip-bottleneck-identification": [
    {
      id: "q-sdip-28",
      type: "multiple-choice",
      difficulty: "hard",
      question: "During a systems design interview, you have designed a system with: Load Balancer \u2192 10 App Servers \u2192 1 Primary DB. The system handles 50,000 reads/sec and 5,000 writes/sec. Where is the likely bottleneck?",
      options: [
        "The load balancer \u2014 it cannot distribute 55,000 QPS",
        "The app servers \u2014 10 servers cannot handle 50,000 reads/sec",
        "The single primary database \u2014 a single DB struggles above 10,000-50,000 QPS for mixed workloads",
        "The network \u2014 bandwidth between app servers and DB is exhausted",
      ],
      correctAnswer: 2,
      explanation: "A single primary relational database is almost always the bottleneck in a three-tier architecture at this scale. A single DB handles ~1,000-10,000 QPS for complex queries or ~10,000-50,000 QPS for simple indexed reads. At 50,000 reads + 5,000 writes = 55,000 QPS total, you are at or beyond its limits. Solutions: add read replicas, introduce a caching layer (Redis), or shard the database. Modern load balancers handle millions of QPS. 10 app servers at 10,000 QPS each = 100,000 QPS capacity, so app tier is fine. The database is the single point of contention.",
      hints: ["What is the capacity of a single relational DB vs. a load balancer?", "Which component has only 1 instance vs. 10 instances?"],
    },
    {
      id: "q-sdip-29",
      type: "true-false",
      difficulty: "medium",
      question: "Adding more application servers will always solve performance problems in a web system that is already showing slow response times.",
      correctAnswer: "False",
      explanation: "False. Adding app servers only helps if the app tier is the bottleneck. If the database is saturated (the most common bottleneck), adding more app servers will increase the number of concurrent connections hitting the DB, potentially making things worse due to connection pool exhaustion and lock contention. Proper diagnosis requires measuring where latency is spent: is the app server CPU-bound, or is most time waiting for DB responses? Scaling the right tier requires identifying the actual bottleneck first.",
      hints: ["What if the database can only handle 10,000 QPS and you have 20 app servers each sending 1,000 QPS?", "Is adding capacity to a non-bottleneck component useful?"],
    },
  ],

  "sdip-sharding-caching": [
    {
      id: "q-sdip-30",
      type: "multiple-choice",
      difficulty: "hard",
      question: "A messaging system needs to shard its message database. User IDs range from 1 to 1 billion. Which sharding strategy avoids hotspots when most messages are sent by a small number of power users?",
      options: [
        "Range-based sharding on user_id (users 1-100M on shard 1, etc.)",
        "Hash-based sharding on user_id (user_id % num_shards)",
        "Directory-based sharding with a shard lookup table",
        "Sharding by message timestamp (recent messages on the latest shard)",
      ],
      correctAnswer: 1,
      explanation: "Hash-based sharding (user_id mod N) distributes users uniformly across shards, regardless of how active individual users are. Range-based sharding creates hotspots if popular users cluster in the same range. Timestamp-based sharding creates a write hotspot on the most recent shard. Directory-based sharding adds lookup latency and the directory itself becomes a bottleneck. Hash sharding is the default choice when the goal is uniform load distribution. The downside: range queries (e.g., all users in a region) become scatter-gather across all shards.",
      hints: ["Which strategy makes it most likely that celebrity accounts end up on different shards?", "What happens with range sharding if users 1-1000 are all power users?"],
    },
  ],
};

registerQuestions(questions);
