import type { Question } from "@/lib/curriculum";
import { registerQuestions } from "./registry";

const questions: Record<string, Question[]> = {
  "sdi-mob-push-notifications": [
    {
      id: "q-sdi-mob-1",
      type: "multiple-choice",
      difficulty: "medium",
      question: "Apple Push Notification service (APNs) requires a device token to deliver notifications. What happens to a device token when a user uninstalls and reinstalls the app on the same iPhone, and why does this matter for your backend?",
      options: [
        "The device token stays the same across reinstalls; the backend can reuse stored tokens indefinitely.",
        "iOS generates a new device token on reinstall; the backend must handle token rotation — stale tokens cause APNs to return a 410 Gone response, signaling the backend to delete the old token.",
        "iOS blocks notifications entirely after reinstall until the user re-enables them in Settings.",
        "APNs automatically forwards notifications to the new token without backend changes.",
      ],
      correctAnswer: 1,
      explanation: "On iOS, APNs may generate a new device token when the app is reinstalled. When your backend sends to an old token, APNs returns a 410 Gone (or 'Unregistered' error) meaning the token is invalid. The backend must listen for these feedback signals — via the APNs feedback service or HTTP/2 response status — and remove or update stale tokens. Failing to do so wastes network calls and can cause APNs to throttle your provider. This is a critical part of device token lifecycle management.",
      hints: [
        "APNs returns specific error codes for invalid tokens — what should the backend do when it receives a 410?",
        "Think about how a user's uninstall creates an orphaned token in your database.",
      ],
    },
    {
      id: "q-sdi-mob-2",
      type: "multiple-choice",
      difficulty: "hard",
      question: "You need to send a promotional push notification to 50 million Android devices via Firebase Cloud Messaging (FCM). Your backend sends individual HTTP requests per token. What is the critical architectural problem and how do you solve it?",
      options: [
        "FCM rate-limits individual HTTP requests; the solution is to use FCM topic messaging where all users subscribe to a broadcast topic.",
        "Sending 50M individual HTTP requests serially would take hours and violates FCM's recommended usage; use FCM batch send API (up to 500 tokens per request) with a distributed job queue (Kafka + worker pool), reducing requests by 500x and completing fan-out in minutes.",
        "FCM does not support Android; use APNs for all platforms.",
        "Individual HTTP requests are fine; FCM handles all fan-out server-side automatically.",
      ],
      correctAnswer: 1,
      explanation: "Sending one HTTP request per device token for 50M devices is infeasible — it requires 50M network round trips and would overwhelm a single server. FCM's batch API accepts up to 500 registration tokens per request, reducing the HTTP call count from 50M to 100K. Combine this with a distributed job queue (e.g., Kafka partitioned by token shard) and a pool of worker services to parallelize the fan-out. FCM topic messaging is another option for broadcast but offers less targeting control. For segmented campaigns, the batch approach is standard (used at Uber, Lyft, Airbnb).",
      hints: [
        "50M / 500 per batch = 100K HTTP requests — what infrastructure can parallelize 100K requests efficiently?",
        "Topic messaging vs. batch send: which gives you fine-grained targeting per user segment?",
      ],
    },
    {
      id: "q-sdi-mob-3",
      type: "multiple-choice",
      difficulty: "medium",
      question: "A user has the same app installed on three devices (iPhone, iPad, Android). They change their email notification preference to 'off'. How should the notification routing layer handle deduplication and preference enforcement across devices?",
      options: [
        "Store per-device preferences; each device independently determines whether to show the notification.",
        "Store notification preferences at the user account level (not per-device); the routing service resolves all device tokens for a user, checks account-level preferences before fan-out, and filters suppressed notification categories before dispatching — ensuring one preference change applies to all devices atomically.",
        "Send the notification to all devices and include the preference in the payload so each device can silently discard it.",
        "Deduplication is not necessary for push notifications since each device is independent.",
      ],
      correctAnswer: 1,
      explanation: "Storing preferences at the user account level (not per-device) is the correct architecture. The notification routing service maintains a mapping of user_id -> [device_token_1, device_token_2, device_token_3]. Before dispatching, it loads the user's notification preferences and filters out suppressed categories. This ensures a single settings change propagates to all devices without requiring per-device updates. Sending to all devices and discarding client-side wastes bandwidth and battery, and can still surface a notification briefly before it is dismissed.",
      hints: [
        "Where should the source of truth for notification preferences live — user level or device level?",
        "What happens to battery and bandwidth if you send to all devices and discard client-side?",
      ],
    },
    {
      id: "q-sdi-mob-4",
      type: "true-false",
      difficulty: "easy",
      question: "APNs (Apple Push Notification service) guarantees at-least-once delivery of push notifications, meaning every notification sent by the backend is guaranteed to be received by the device.",
      options: ["True", "False"],
      correctAnswer: 1,
      explanation: "APNs does NOT guarantee delivery. Apple's documentation explicitly states that push notifications are best-effort. If the device is offline, APNs stores only the most recent notification per app (the previous one is discarded). If the device remains offline beyond a storage period, the notification is dropped entirely. Additionally, APNs may drop notifications under high load or network issues. Apps requiring guaranteed delivery must implement an inbox/pull model where the client fetches missed notifications on reconnect, supplementing push with a persistent message store.",
      hints: [
        "What does APNs do when a device is offline for an extended period with multiple incoming notifications?",
        "What should the app do on launch/reconnect to catch notifications that may have been dropped?",
      ],
    },
    {
      id: "q-sdi-mob-5",
      type: "multiple-choice",
      difficulty: "hard",
      question: "Instagram's notification system must avoid sending duplicate push notifications when a post receives 1,000 likes in rapid succession (you should receive 'X people liked your photo', not 1,000 individual notifications). What is the standard deduplication architecture?",
      options: [
        "Throttle the push notification sender to 1 notification per second per user.",
        "Use a notification aggregation buffer: incoming like events are written to a time-windowed bucket (e.g., Redis key with 30-second TTL) per (user, post, notification_type); a delayed job reads the bucket after the window closes and sends one aggregated notification ('Alice, Bob, and 998 others liked your photo').",
        "Use a message queue with deduplication IDs; the queue automatically collapses duplicate messages.",
        "Store all likes in the database and run a batch job every hour to send one summary notification.",
      ],
      correctAnswer: 1,
      explanation: "The standard approach is time-windowed aggregation. When a like event arrives, instead of immediately dispatching a push notification, it is written to an aggregation buffer keyed by (recipient_user_id, content_id, event_type) with a short TTL (e.g., 30 seconds). A delayed dispatcher (scheduled job or stream processor) fires after the window and reads the accumulated events, composing a single aggregated message. This is how Instagram, Facebook, and Twitter implement notification collapsing. The APNs 'apns-collapse-id' header can also collapse in-flight notifications on the device side, but server-side aggregation is the primary mechanism.",
      hints: [
        "What Redis data structure lets you accumulate events in a time window and count them atomically?",
        "APNs supports a collapse key — how does that work client-side for already-delivered notifications?",
      ],
    },
  ],
  "sdi-mob-offline-sync": [
    {
      id: "q-sdi-mob-6",
      type: "multiple-choice",
      difficulty: "hard",
      question: "A collaborative notes app (like Apple Notes or Google Keep) allows offline edits on multiple devices. User A edits paragraph 1 offline on their iPhone, and simultaneously User B edits paragraph 2 offline on their iPad. Both sync when reconnected. What conflict resolution strategy handles this without data loss?",
      options: [
        "Last-write-wins (LWW) based on wall-clock timestamp; whichever device syncs last wins.",
        "Operational Transformation (OT) or CRDT (Conflict-free Replicated Data Type) at the field or character level — both edits are applied since they target different parts of the document; CRDTs mathematically guarantee convergence without coordination.",
        "Lock the document on one device before allowing edits; reject offline edits from the second device.",
        "Prompt the user to manually merge conflicting versions when both come online.",
      ],
      correctAnswer: 1,
      explanation: "CRDTs (Conflict-free Replicated Data Types) and Operational Transformation are the standard approaches for collaborative offline-first editing. Since User A edited paragraph 1 and User B edited paragraph 2 (non-overlapping regions), both edits can be applied without conflict — a CRDT text data structure (e.g., a sequence CRDT like RGA or LSEQ) represents characters with unique IDs and merge rules that always produce the same result regardless of application order. Last-write-wins at the document level would cause User A's edits to be lost. Google Docs uses OT; Linear and Notion use CRDTs. Apple Notes uses a simpler per-field LWW with merge at the paragraph level.",
      hints: [
        "CRDTs have a mathematical property called commutativity — what does that mean for merge order?",
        "If A edits paragraph 1 and B edits paragraph 2, is there actually a conflict? What determines that?",
      ],
    },
    {
      id: "q-sdi-mob-7",
      type: "multiple-choice",
      difficulty: "medium",
      question: "A mobile app uses delta sync to only send changes since the last sync. The client sends its last known version vector (logical clock) to the server. What does the server return, and why is this more efficient than full data sync?",
      options: [
        "The server returns the entire dataset; version vectors are only used for conflict detection, not data filtering.",
        "The server computes the diff between the client's version vector and current state, returning only records modified after the client's vector — typically a fraction of total data; this reduces payload size, bandwidth, and parse time proportionally to the unchanged data ratio.",
        "The server returns a checksum; the client compares it against local data and requests specific missing records.",
        "Version vectors are only used in database replication, not mobile sync protocols.",
      ],
      correctAnswer: 1,
      explanation: "Delta sync using version vectors (or logical timestamps) is fundamental to mobile sync efficiency. The client sends its last sync vector (e.g., {server: 1042, client_device_A: 17}). The server queries for all records with version > client's known version, returning only the delta. For an app with 10,000 records where only 12 changed, the response is 12 records instead of 10,000. This is how CouchDB/PouchDB sync, Realm sync, and Firebase Firestore offline sync work. Version vectors handle multi-device sync by tracking each writer's logical clock independently, enabling detection of concurrent edits.",
      hints: [
        "What fraction of records typically change between sync cycles in a notes or calendar app?",
        "How does the server know which records the client has already seen without sending everything?",
      ],
    },
    {
      id: "q-sdi-mob-8",
      type: "multiple-choice",
      difficulty: "hard",
      question: "An Uber driver app must work offline (accept ride, record GPS track, complete ride) and sync when connectivity resumes. What consistency model and sync architecture handles the case where a driver completes a ride while offline?",
      options: [
        "Strong consistency required; the app should block until a server roundtrip confirms each action.",
        "Optimistic local-first writes: all driver actions are persisted to a local SQLite journal with a pending-sync flag; on reconnect, the client replays the journal to the server in causal order with timestamps; the server validates business rules (e.g., surge pricing at trip-start time) and confirms or resolves discrepancies.",
        "The app stores actions in memory only; if the connection drops, the driver must restart the ride.",
        "Use WebSockets only; if the WebSocket disconnects, queue actions in a browser localStorage and replay on reconnect.",
      ],
      correctAnswer: 1,
      explanation: "Uber's driver app uses a local-first architecture with a durable write-ahead log (WAL) in SQLite. Each action (accept, start, GPS point, complete) is written locally first, then queued for sync. On reconnect, the client sends the journal in causal order. The server applies business logic against the time-of-action state (e.g., surge pricing is recorded at trip acceptance, not sync time). This is the same pattern used by Lyft and other ride-sharing apps. Strong consistency would make the app unusable in poor network areas. The key insight is that the local journal is the source of truth until the server confirms receipt.",
      hints: [
        "What data structure records all writes in order and can be replayed? (Hint: databases use it for crash recovery.)",
        "If a ride was accepted at 11:00 PM but synced at 11:05 PM, which time should determine surge pricing?",
      ],
    },
    {
      id: "q-sdi-mob-9",
      type: "true-false",
      difficulty: "easy",
      question: "In an offline-first mobile app, last-write-wins (LWW) conflict resolution based on device wall-clock timestamps is reliable because mobile devices have accurate clocks synchronized via NTP.",
      options: ["True", "False"],
      correctAnswer: 1,
      explanation: "LWW based on wall-clock timestamps is unreliable for mobile devices. Mobile clocks can be skewed by several seconds or even minutes due to clock drift, NTP sync delays, manual time changes by users, or timezone misconfigurations. A device with a clock set 5 minutes ahead would always 'win' conflicts, silently discarding edits from other devices. The correct approach is to use server-assigned logical timestamps or Lamport clocks on sync, use hybrid logical clocks (HLC), or avoid LWW entirely by using CRDTs. If LWW is used, the server should assign the authoritative timestamp at the time of sync, not rely on client-reported wall-clock time.",
      hints: [
        "What can cause a mobile device's clock to be incorrect by several minutes?",
        "If two devices have clocks skewed by 3 minutes relative to each other, what does LWW do to edits made within that window?",
      ],
    },
  ],
  "sdi-mob-caching-api": [
    {
      id: "q-sdi-mob-10",
      type: "multiple-choice",
      difficulty: "medium",
      question: "A mobile news app needs content to load instantly even on slow connections. Which client caching strategy serves cached content immediately while updating it in the background, and what is its main tradeoff?",
      options: [
        "Cache-first: always serve from cache, never check the network. Fast but content never updates.",
        "Stale-while-revalidate: serve the cached response immediately (eliminating perceived latency), then issue a background network request to update the cache; on the next load, the fresh content is ready. The tradeoff is the user sees potentially stale content on the first load after a cache miss interval.",
        "Network-first: always try the network, fall back to cache only on failure. Guarantees freshness but adds latency on every request.",
        "No-store: never cache; always fetch from network for guaranteed freshness.",
      ],
      correctAnswer: 1,
      explanation: "Stale-while-revalidate (SWR) is the standard strategy for content-heavy mobile apps (news, social feeds). It eliminates loading spinners by instantly serving cached content, then silently updates the cache. The next visit gets the fresh version. The tradeoff: the user may see content that is one fetch cycle stale. This is acceptable for news (where 30-second-old content is fine) but not for financial quotes. HTTP uses the Cache-Control: stale-while-revalidate=N header to configure this. Libraries like SWR (React) and TanStack Query implement this pattern. Instagram's feed uses a variant where cached items are shown while fresh items load above them.",
      hints: [
        "What is the user experience difference between 'loading spinner then content' vs. 'content immediately, then refresh'?",
        "In what scenarios would showing 30-second-old data be unacceptable, and what strategy would you use instead?",
      ],
    },
    {
      id: "q-sdi-mob-11",
      type: "multiple-choice",
      difficulty: "hard",
      question: "Google designed HTTP/3 (QUIC) partly to solve mobile network performance problems that HTTP/2 could not. What specific mobile network characteristic does QUIC's connection migration address that HTTP/2 over TCP cannot handle?",
      options: [
        "QUIC eliminates TLS handshake overhead, which HTTP/2 requires on every request.",
        "HTTP/2 over TCP suffers from head-of-line blocking at the TCP layer — one lost packet stalls all streams. QUIC additionally solves connection migration: when a mobile device switches from WiFi to LTE, the TCP connection (tied to the IP:port 4-tuple) breaks and must be re-established; QUIC connections use a Connection ID independent of IP/port, surviving network handoffs transparently without a new handshake.",
        "QUIC supports binary framing which HTTP/2 does not, reducing parse overhead on mobile CPUs.",
        "HTTP/2 requires a dedicated connection per domain; QUIC allows a single connection for all domains.",
      ],
      correctAnswer: 1,
      explanation: "QUIC (HTTP/3's transport layer) solves two critical mobile problems: (1) Head-of-line blocking — HTTP/2 multiplexes streams over one TCP connection, but a single lost TCP packet stalls ALL streams until retransmitted; QUIC implements per-stream loss recovery so one lost packet only blocks its own stream. (2) Connection migration — TCP connections are identified by (src IP, src port, dst IP, dst port); when a phone switches from WiFi (192.168.x.x) to LTE (carrier IP), the IP changes, breaking the TCP connection requiring a new TLS handshake (adds 1-2 RTT). QUIC connections use an opaque Connection ID, allowing the connection to survive IP address changes. This is why Google and Cloudflare prioritize QUIC for mobile.",
      hints: [
        "What 4-tuple identifies a TCP connection, and why does an IP address change break it?",
        "On a commute, a phone may switch WiFi access points or move between WiFi and LTE — how often does this happen?",
      ],
    },
    {
      id: "q-sdi-mob-12",
      type: "multiple-choice",
      difficulty: "medium",
      question: "A mobile app team at Airbnb adopts GraphQL to reduce over-fetching. The iOS listing detail screen needs 15 fields; the Android version needs 12 different fields. How does GraphQL solve the over-fetching problem compared to a REST endpoint, and what is a persisted query?",
      options: [
        "GraphQL uses HTTP GET instead of POST, reducing payload size by 30%.",
        "With REST, both platforms get the same 40-field response; with GraphQL, each client specifies exactly which fields it needs in its query, receiving only those fields. Persisted queries replace the full query string with a short hash (e.g., sha256 of the query) pre-registered on the server, reducing request size from kilobytes to bytes and enabling CDN caching.",
        "GraphQL automatically detects the client platform and returns the appropriate subset of fields.",
        "GraphQL's introspection feature allows clients to download the schema and filter fields client-side.",
      ],
      correctAnswer: 1,
      explanation: "REST endpoints return fixed shapes — a listing endpoint might return 40 fields even if a screen only needs 12. GraphQL lets the iOS team declare exactly which 15 fields they need and the Android team declare their 12 — no over-fetching, smaller payloads, faster parses, less battery drain. Persisted queries are an optimization where the client registers its query with the server during build time and at runtime sends only the hash (e.g., sha256 of the query string). The server resolves the hash to the full query. This: (1) reduces request body from ~2KB to 64 bytes, (2) allows GET requests (enabling CDN caching), and (3) prevents arbitrary query execution. GitHub, Shopify, and Airbnb all use persisted queries.",
      hints: [
        "What is the byte difference between sending a 2KB GraphQL query body vs. a 64-byte hash?",
        "Why can GET requests be CDN-cached but POST requests typically cannot?",
      ],
    },
    {
      id: "q-sdi-mob-13",
      type: "multiple-choice",
      difficulty: "medium",
      question: "A mobile app's API needs cursor-based pagination for an infinite-scroll feed. The cursor encodes the last seen item's ID and timestamp. What is the advantage of a cursor-encoded as an opaque base64 string over exposing raw offset integers to the client?",
      options: [
        "Base64 encoding compresses the cursor value, reducing URL length.",
        "An opaque cursor decouples the client from the server's pagination implementation — the server can change the internal cursor format (e.g., from sequential IDs to composite keys) without breaking clients; clients treat cursors as black boxes, preventing them from constructing arbitrary cursors to skip to arbitrary positions.",
        "Base64 cursors are encrypted, preventing users from guessing other users' cursors.",
        "Opaque cursors are required by the HTTP spec for pagination headers.",
      ],
      correctAnswer: 1,
      explanation: "Opaque cursors (base64-encoded server-side state) provide two key benefits: (1) Implementation hiding — the server can evolve the cursor format from 'integer offset' to 'timestamp + ID composite' without breaking existing clients; clients that store cursors (e.g., for resume on app reopen) continue to work after a server-side format change. (2) Access control — clients cannot craft arbitrary cursors to jump to specific positions in a feed, preventing data leakage (e.g., paging directly to another user's private content by constructing a cursor). GitHub's API, Stripe's API, and Facebook's Graph API all use opaque cursor strings.",
      hints: [
        "If a client stores 'page=5' and the server changes the dataset, what happens vs. storing an opaque cursor?",
        "What prevents a user from constructing cursor=base64('user_id=12345') to access another user's paginated data?",
      ],
    },
    {
      id: "q-sdi-mob-14",
      type: "multiple-choice",
      difficulty: "hard",
      question: "A mobile team needs a versioning strategy for a public API that 50 million active app installations call. The team plans to deprecate endpoint v1 in favor of v2. What is the correct sunset strategy to avoid breaking older app versions?",
      options: [
        "Immediately redirect v1 calls to v2; older clients will receive the v2 response format.",
        "Add a Sunset HTTP header to v1 responses announcing the deprecation date; maintain v1 in parallel for at least the app's P95 upgrade cycle (typically 6-12 months for mobile apps); instrument v1 call volume and only shut it down when traffic drops below a defined threshold (e.g., <0.1% of total).",
        "Use semantic versioning in the URL (/v2.1.3/endpoint) so clients can target specific minor versions.",
        "Deprecate v1 after 30 days — users who haven't updated the app in 30 days are not active users.",
      ],
      correctAnswer: 1,
      explanation: "Mobile API versioning requires a longer sunset window than web APIs because you cannot force users to update their apps. A significant fraction of users never update or update months late — P95 mobile app upgrade cycles can be 6-12 months. The correct strategy: (1) Add Sunset and Deprecation HTTP headers to v1 responses so developer tools surface warnings. (2) Instrument v1 call volume over time. (3) Define a traffic threshold for shutdown (e.g., <0.1% of v1 calls). (4) Consider forcing an in-app update prompt for critically old versions before v1 shuts down. Abrupt v1 shutdown causes crashes for unupdated users, generating support costs and App Store rating drops.",
      hints: [
        "What percentage of users have typically updated their app 30 days after a new release? 90 days?",
        "What HTTP header officially communicates API deprecation timelines to API consumers?",
      ],
    },
  ],
  "sdi-mob-performance": [
    {
      id: "q-sdi-mob-15",
      type: "multiple-choice",
      difficulty: "medium",
      question: "iOS Background App Refresh allows apps to fetch content while in the background. What constraint does iOS impose on background fetch tasks, and how should the app design its sync to respect this constraint?",
      options: [
        "iOS allows unlimited background fetch time as long as the device is charging.",
        "iOS grants background tasks a limited execution window (approximately 30 seconds for BGAppRefreshTask); the app must complete its sync and call task.setTaskCompleted() within this window or iOS terminates it; the sync must be incremental (delta sync) and prioritize critical content to fit within the time budget.",
        "Background App Refresh only works on WiFi; LTE background fetches are blocked by iOS.",
        "Background tasks run at a fixed interval of exactly 15 minutes regardless of user behavior.",
      ],
      correctAnswer: 1,
      explanation: "iOS background tasks (BGAppRefreshTask) receive a limited execution window — typically around 30 seconds — before iOS suspends the app. The OS also adaptively schedules background refresh based on the user's usage patterns (ML-driven scheduling in iOS 13+), not at fixed intervals. Apps must: (1) Use incremental/delta sync to fetch only changed data. (2) Prioritize the most impactful content (e.g., latest messages > historical messages). (3) Call setTaskCompleted(success:) promptly so iOS trusts the app for future background launches. Apps that exceed the time budget or fail to complete tasks are deprioritized by the scheduler. This is why efficient delta sync is essential for mobile apps.",
      hints: [
        "What happens if an iOS background task takes 60 seconds — does it complete or get killed?",
        "How does iOS decide when to grant background fetch time to an app?",
      ],
    },
    {
      id: "q-sdi-mob-16",
      type: "multiple-choice",
      difficulty: "medium",
      question: "A mobile team is optimizing image delivery for a product listing page on iOS and Android. The page displays 20 product images. Which combination of techniques most reduces bandwidth and battery consumption?",
      options: [
        "Send full-resolution JPEG images; mobile GPUs can decode JPEG efficiently.",
        "Serve WebP (or AVIF) format at device-appropriate resolution via a CDN image service that accepts size parameters; use lazy loading so only images in or near the viewport are fetched; add HTTP Cache-Control headers with long max-age for immutable product images identified by content hash.",
        "Use PNG for all images to avoid JPEG compression artifacts; compress with GZIP at the HTTP layer.",
        "Pre-download all 20 images on app launch to eliminate scroll-time loading; store in the app's document directory.",
      ],
      correctAnswer: 1,
      explanation: "The optimal mobile image strategy combines: (1) Modern format — WebP provides ~30% smaller files than JPEG at equivalent quality; AVIF provides ~50% savings but has slightly slower decode on older chips. (2) Responsive sizing — serve images at the actual display size (e.g., 300x300px for a 150pt thumbnail on @2x screen) not at full resolution. (3) Lazy loading — only request images that are visible or one screen ahead; fetching all 20 upfront wastes ~5-10x more bandwidth than the user may consume before scrolling. (4) Long-lived CDN caching using content-addressed URLs — product images rarely change, so cache forever with hash-based URLs. This is the approach used by Airbnb, Amazon, and Instagram.",
      hints: [
        "How many of the 20 images does a user typically see before closing a listing page?",
        "What is the approximate byte savings of WebP vs. JPEG for a 1MB product image?",
      ],
    },
    {
      id: "q-sdi-mob-17",
      type: "multiple-choice",
      difficulty: "hard",
      question: "A mobile app's crash reporting system captures crashes with native stack traces (memory addresses). The traces are meaningless without symbolication. What is the symbolication process and why must you retain dSYM files (iOS) or ProGuard mapping files (Android)?",
      options: [
        "Symbolication is a client-side process that runs on the device before uploading the crash report.",
        "Symbolication maps raw memory addresses or obfuscated class names in a crash stack trace to human-readable function names, file names, and line numbers using debug symbol files (dSYM for iOS, ProGuard/R8 mapping files for Android). These files must be uploaded to the crash reporter (e.g., Crashlytics, Sentry) at build time because the App Store strip symbols from production binaries to reduce app size.",
        "dSYM files are automatically included in App Store builds; no manual retention is needed.",
        "Symbolication is only needed for C/C++ code; Swift and Kotlin crashes are always human-readable.",
      ],
      correctAnswer: 1,
      explanation: "Production iOS binaries have debug symbols stripped before App Store submission to reduce download size. A crash stack trace from a stripped binary contains only memory addresses like 0x0000000100a4b3c2. The dSYM (debug symbol) file — generated at build time — contains the mapping from addresses to Swift/ObjC function names, file names, and line numbers. Crash reporters like Crashlytics and Sentry perform symbolication server-side using uploaded dSYMs. Without the matching dSYM (matched by UUID), crashes cannot be symbolicated. Similarly, Android Release builds use ProGuard/R8 to obfuscate class/method names; the mapping.txt file reverses the obfuscation. Both files must be archived per release build and retained for as long as that build version is in production.",
      hints: [
        "Why does the App Store strip debug symbols from production builds before distribution?",
        "Each build produces a unique dSYM with a UUID — what happens if you upload a dSYM from a different build?",
      ],
    },
    {
      id: "q-sdi-mob-18",
      type: "multiple-choice",
      difficulty: "hard",
      question: "React Native's CodePush (now App Center) allows JavaScript bundle updates to be pushed to users without an App Store submission. What is the fundamental constraint on what can be updated via OTA (over-the-air) updates, and what binary delta algorithm minimizes the download size?",
      options: [
        "OTA updates can modify any part of the app including native modules and OS permissions.",
        "OTA updates in React Native can only update the JavaScript bundle and static assets — native code changes (new native modules, permission additions, binary dependencies) require a full App Store release. The bsdiff algorithm computes a binary delta between the old and new JS bundle, so users download only the changed bytes rather than the full new bundle.",
        "OTA updates bypass App Store review entirely and have no content restrictions.",
        "bsdiff is used for full app updates; OTA updates use gzip compression only.",
      ],
      correctAnswer: 1,
      explanation: "React Native's JS-powered OTA update model has a critical constraint enforced by Apple's App Store guidelines: only interpreted code (JavaScript) can be hot-patched; native code (Swift, ObjC, C++) changes require a full App Store review. This means native module additions, permission manifest changes, or new binary frameworks cannot be OTA-deployed. For the JS bundle itself, bsdiff (binary diff/patch) computes the byte-level diff between the current and new bundle. A typical small feature change might be a 500KB diff on a 5MB bundle, reducing download size by 90%. CodePush/App Center uses this approach. Expo Updates uses a similar mechanism with Expo's runtime.",
      hints: [
        "Apple's App Review Guidelines section 2.5.2 restricts what can be changed via interpreted code — what category does JavaScript fall into?",
        "If a JS bundle changes from 5MB to 5.2MB with one new screen added, how large is the bsdiff output?",
      ],
    },
    {
      id: "q-sdi-mob-19",
      type: "multiple-choice",
      difficulty: "hard",
      question: "A mobile banking app implements certificate pinning to prevent man-in-the-middle attacks. A new TLS certificate is deployed on the backend server. What critical operational risk does certificate pinning introduce, and how is it mitigated?",
      options: [
        "Certificate pinning has no operational risk; it only affects attackers.",
        "Certificate pinning bakes the expected certificate or public key hash into the app binary; if the backend rotates its TLS certificate (due to expiry, compromise, or CA change) without a prior app release that includes the new pin, all users on the old app version lose connectivity — effectively a self-inflicted outage. Mitigation: pin the CA intermediate or root (not the leaf cert), maintain a backup pin, use a pin rotation mechanism, and ship the updated pin in a new app release before rotating the certificate.",
        "Certificate pinning only affects Android; iOS handles TLS validation automatically via ATS.",
        "The risk is that certificate pinning prevents app updates from being downloaded over HTTPS.",
      ],
      correctAnswer: 1,
      explanation: "Certificate pinning is a double-edged sword. It prevents MITM attacks but creates an operational dependency: the pinned certificate hash in the app must match the server's certificate. When the certificate expires (typically annually) or is compromised, the backend must rotate it. If the pin in the app hasn't been updated first, every user on old app versions receives TLS validation errors and cannot connect. Best practices: (1) Pin the CA intermediate or public key rather than the leaf certificate (leaf certs rotate more frequently). (2) Always include a backup pin (at least 2 pins). (3) Ship the new pin in a release 2-4 weeks before cert rotation. (4) Monitor pin failure rates. Google recommends against leaf cert pinning for this reason.",
      hints: [
        "TLS certificates have expiry dates — what happens to a pinned cert when it expires?",
        "What is the difference between pinning the leaf certificate vs. pinning the CA public key?",
      ],
    },
    {
      id: "q-sdi-mob-20",
      type: "multiple-choice",
      difficulty: "medium",
      question: "iOS Secure Enclave powers FaceID and TouchID authentication. When a user authenticates with FaceID to access their banking app, what actually leaves the Secure Enclave, and how does the app verify the authentication?",
      options: [
        "The biometric template (facial scan data) is sent to the app for local comparison.",
        "The biometric data never leaves the Secure Enclave. On successful biometric authentication, the Secure Enclave performs a private key signing operation using a key that was generated and stored inside the Enclave; the app receives a signed assertion which it verifies against the corresponding public key — proof of authentication without ever seeing biometric data.",
        "FaceID sends a one-time token to Apple servers which the app verifies via API.",
        "The Secure Enclave returns a boolean true/false to the app indicating authentication success.",
      ],
      correctAnswer: 1,
      explanation: "The Secure Enclave is a dedicated security coprocessor with its own isolated memory and flash storage. Biometric data (Face ID templates, Touch ID fingerprint data) is processed and stored entirely within the Secure Enclave — it never reaches the Application Processor or the operating system. Authentication works via asymmetric cryptography: during enrollment, the Secure Enclave generates a private/public key pair; the private key never leaves the Enclave. During authentication, after successful biometric match, the Enclave signs a challenge using the private key. The app (or server) verifies the signature using the public key. This is the architecture behind FIDO2/WebAuthn on mobile platforms.",
      hints: [
        "What cryptographic operation proves 'I have the private key' without revealing the key itself?",
        "Where is the biometric template stored — on the main processor, in iCloud, or in the Secure Enclave?",
      ],
    },
  ],
  "sdi-mob-location-streaming": [
    {
      id: "q-sdi-mob-21",
      type: "multiple-choice",
      difficulty: "medium",
      question: "A ride-sharing app (like Uber) needs to track driver locations. The naive approach streams GPS coordinates every second. What battery-efficient alternative does iOS provide for low-frequency tracking, and when should the app switch to high-frequency updates?",
      options: [
        "iOS does not allow background location updates; tracking must stop when the app is backgrounded.",
        "iOS offers 'significant location change' monitoring (cell tower triangulation, ~500m accuracy, triggers only on significant movement) for battery-efficient background awareness; the app switches to high-accuracy GPS (CLLocationManager with desiredAccuracy = kCLLocationAccuracyBest at 1-second intervals) only when an active ride is in progress, minimizing GPS drain when the driver is idle.",
        "iOS forces all location apps to use 1-second GPS intervals; battery optimization is the app's responsibility.",
        "Geofencing APIs provide sub-meter accuracy equivalent to GPS with no battery impact.",
      ],
      correctAnswer: 1,
      explanation: "iOS provides a tiered location API spectrum. Significant Location Change (SLC) uses cell towers and WiFi positioning — battery cost is negligible and it fires only when the device moves ~500 meters. Geofencing (CLRegion monitoring) triggers on entry/exit from defined circular regions with minimal battery impact. High-accuracy GPS (kCLLocationAccuracyBest) turns on the full GPS chipset and can drain battery at 5-15% per hour. Uber's driver app uses SLC or geofencing when a driver is not on an active trip, switching to high-frequency GPS during an active ride. This tiered strategy is also used by Lyft. The app can receive a background location 'wake' from SLC to re-evaluate whether to upgrade to full GPS.",
      hints: [
        "What is the battery cost difference between cell-tower location and GPS chipset location?",
        "In Uber's case, when does the driver truly need 1-second GPS accuracy vs. approximate location?",
      ],
    },
    {
      id: "q-sdi-mob-22",
      type: "multiple-choice",
      difficulty: "hard",
      question: "A video streaming app needs adaptive bitrate (ABR) streaming for mobile. The device is on LTE with 5 Mbps throughput but moves into a tunnel with 200 Kbps. How does HLS (HTTP Live Streaming) adapt, and what is the algorithm that governs quality switching?",
      options: [
        "HLS downloads the entire video at the highest quality before playback begins, then switches quality for the next video.",
        "HLS breaks video into 2-10 second segments at multiple bitrates (e.g., 400K, 1.5M, 4M bps); the player downloads segments one at a time and measures download throughput per segment; a bandwidth estimation algorithm (BOLA, MPC, or throughput-based) selects the highest quality rendition whose bitrate fits within estimated bandwidth minus a safety buffer, switching down proactively as throughput degrades.",
        "HLS requires a persistent TCP connection; when entering a tunnel, the connection drops and playback stops.",
        "Quality adaptation in HLS is controlled server-side based on the client's IP address geolocation.",
      ],
      correctAnswer: 1,
      explanation: "HLS (and MPEG-DASH) use segmented delivery to enable adaptive bitrate streaming. The M3U8 master playlist lists multiple renditions at different bitrates/resolutions. The player downloads short segments (2-10s) and measures actual download time vs. segment duration to estimate bandwidth. When entering a tunnel and bandwidth drops to 200 Kbps, the ABR algorithm (e.g., throughput-based: use 80% of measured bandwidth) selects the 400 Kbps rendition for the next segment. The player buffer (typically 15-30s) provides smoothing time to absorb transient drops before visible quality degradation. Netflix's open-sourced Bola algorithm and Apple's implementation use buffer occupancy in addition to throughput for more stable switching decisions.",
      hints: [
        "What does 'buffering' during video playback mean in terms of HLS segments?",
        "Why does the ABR algorithm use 80% of measured bandwidth rather than 100% as the target?",
      ],
    },
    {
      id: "q-sdi-mob-23",
      type: "multiple-choice",
      difficulty: "hard",
      question: "A mobile app needs to upload large files (e.g., 500MB video) that may be interrupted by network changes. How do resumable uploads work, and what protocol mechanism does Google and AWS use to implement them?",
      options: [
        "Resumable uploads require the client to re-upload the entire file if the upload is interrupted.",
        "The client initiates a resumable upload session via a POST request, receiving a session URI; subsequent PUT requests upload chunks (e.g., 5-10MB each) to the session URI with a Content-Range header specifying byte range; if interrupted, the client sends a status query to the session URI to discover how many bytes the server received, then resumes from the next byte — no re-upload of already-transmitted bytes.",
        "Resumable uploads are only supported over WebSocket connections, not HTTP.",
        "The TUS (Tus Resumable Upload) protocol requires a separate server distinct from the storage backend.",
      ],
      correctAnswer: 1,
      explanation: "Resumable uploads use session-based chunked transfer. The flow: (1) Initiate: POST to create a resumable upload session, server returns a session URI. (2) Upload: PUT chunks to the session URI with Content-Range: bytes 0-5242879/524288000 headers. (3) On interruption: GET to the session URI with Content-Range: bytes */size returns 308 Resume Incomplete with Range: bytes=0-N indicating the last confirmed byte. (4) Resume: PUT starting at byte N+1. Google Cloud Storage, AWS S3 multipart upload, and the open TUS protocol all implement this pattern. Instagram's video upload and YouTube's upload both use this approach. For mobile, 5-10MB chunks balance between too many roundtrips and too much wasted work on interruption.",
      hints: [
        "What HTTP header communicates which byte range a PUT request is uploading?",
        "How does the client know where to resume after a network interruption — does it guess or ask the server?",
      ],
    },
    {
      id: "q-sdi-mob-24",
      type: "multiple-choice",
      difficulty: "medium",
      question: "A chat app (like WhatsApp or iMessage) must guarantee message ordering in a distributed mobile backend. Two users on different devices send messages simultaneously to the same group chat. What is the challenge of ordering, and how do Lamport timestamps or sequence numbers solve it?",
      options: [
        "Message ordering is guaranteed by TCP; as long as TCP is used, messages arrive in the correct order.",
        "In a distributed backend with multiple servers, messages may arrive out of order due to network latency differences; the server assigns a monotonically increasing sequence number per conversation at write time (using a single authoritative sequencer or distributed sequence like a Cassandra counter with leader arbitration); clients buffer and sort by sequence number, displaying messages in server-assigned order regardless of arrival time.",
        "Mobile clients timestamp messages with wall-clock time; the server sorts by client timestamp for ordering.",
        "Message ordering is handled by the OS message queue and requires no application-level sequencing.",
      ],
      correctAnswer: 1,
      explanation: "TCP guarantees ordering within a single connection, but messages in a chat system flow through multiple servers, queues, and client connections. Wall-clock timestamps from clients are unreliable (clock skew). The standard solution is server-side sequence numbers: a designated sequencer (or consensus-based sequence generator) assigns a monotonically increasing sequence_id to each message in a conversation. Clients receive messages potentially out of order (due to network), buffer them, and render in sequence_id order. WhatsApp uses a server-assigned message ID. For read receipts, the server tracks which sequence_id each participant has acknowledged. This is simpler than Lamport clocks for single-chat ordering since there's no need for partial ordering across conversations.",
      hints: [
        "If server A processes message 1 and server B processes message 2 simultaneously, which arrives first at a third server?",
        "Why can't mobile clients use their local clock for message ordering?",
      ],
    },
    {
      id: "q-sdi-mob-25",
      type: "multiple-choice",
      difficulty: "medium",
      question: "A mobile app wants to run A/B experiments on a new onboarding flow. The team debates client-side (app-bundled) vs. server-side experiment assignment. What is the critical advantage of server-side assignment, and what is the main disadvantage?",
      options: [
        "Client-side experiments are always faster and should be preferred for all experiments.",
        "Server-side assignment: the experiment group is determined by the backend on each app launch, enabling instant experiment changes without an app release, accurate holdout analysis, and consistent cross-device experience. The main disadvantage is the added network round-trip latency on launch before the correct UI variant can be shown — mitigated by caching the assignment locally and refreshing it asynchronously.",
        "Server-side experiments require user consent under GDPR; client-side experiments do not.",
        "Client-side experiments allow larger sample sizes because they do not require a server call.",
      ],
      correctAnswer: 1,
      explanation: "Server-side experiment assignment (used by Lyft, Airbnb, Google, and most sophisticated mobile teams) has critical advantages: (1) Instant experiment changes — modify traffic splits, stop experiments, or fix misconfigured experiments without shipping a new app binary. (2) Consistent assignment across devices — the same user gets the same variant on iPhone and Android. (3) No holdout leakage — the server can enforce clean holdout groups. (4) Accurate logging — the server knows which variant was assigned and can join with conversion events. The main cost is launch latency: the app must wait for the assignment response before rendering the correct variant. The standard mitigation is to cache the last known assignment locally (for instant first render) and refresh it on each launch in the background for the next session.",
      hints: [
        "If an A/B test has a critical bug in variant B, how quickly can a server-side vs. client-side experiment be stopped?",
        "What caching pattern eliminates the server-side assignment latency on app launch?",
      ],
    },
  ],
  "sdi-mob-data-privacy": [
    {
      id: "q-sdi-mob-26",
      type: "multiple-choice",
      difficulty: "medium",
      question: "A mobile app compresses API request/response payloads using Brotli. The iOS team also considers switching from JSON to Protocol Buffers (protobuf). What are the two distinct types of compression at play and what performance characteristics differ?",
      options: [
        "Brotli and protobuf are both compression algorithms and can be used interchangeably.",
        "Brotli is a general-purpose byte-level compression algorithm (applied at the HTTP transport layer to any payload type, including JSON or protobuf); Protocol Buffers is a binary serialization format that replaces JSON's text encoding with a compact binary schema-driven encoding. They are complementary: protobuf reduces payload size via efficient binary encoding before Brotli further compresses it. Protobuf also eliminates JSON parsing overhead (string-to-integer conversions, UTF-8 parsing) improving CPU and battery use.",
        "Brotli only works for HTML content; protobuf is used exclusively for database storage.",
        "Protocol Buffers include built-in compression; applying Brotli on top has no additional benefit.",
      ],
      correctAnswer: 1,
      explanation: "These are two orthogonal optimizations: Brotli (or gzip) is a transport-layer compression codec applied to the byte stream, agnostic to the payload format. Protocol Buffers is a serialization format that encodes structured data in a compact binary schema (field IDs instead of field names, varint encoding for integers, no null values transmitted). JSON: field names are strings transmitted verbatim ('user_id'), values are text-encoded. Protobuf: field 1 = varint. Applying Brotli to JSON achieves ~60-70% compression. Protobuf alone achieves ~30-50% size reduction. Protobuf + Brotli combines both benefits. Additionally, protobuf deserialization is 5-10x faster than JSON parsing on mobile CPUs, directly reducing battery usage per API call. gRPC uses protobuf by default over HTTP/2.",
      hints: [
        "In a JSON payload {\"user_id\": 12345}, how many bytes does the field name 'user_id' consume vs. a 1-byte protobuf field tag?",
        "Can you apply Brotli to a protobuf binary payload? What would be the combined savings?",
      ],
    },
    {
      id: "q-sdi-mob-27",
      type: "multiple-choice",
      difficulty: "hard",
      question: "Apple introduced App Tracking Transparency (ATT) in iOS 14.5, which broke IDFA-based device fingerprinting used by ad networks. What privacy-preserving alternative identifier does Apple provide for first-party analytics within a single app developer's apps?",
      options: [
        "Apple provides no alternative; all user tracking is blocked after ATT.",
        "Apple provides IDFV (Identifier for Vendor) — a UUID stable across all apps from the same developer on a device, reset only if all apps from that vendor are uninstalled. For cross-app or cross-network advertising measurement, Apple introduced SKAdNetwork (server-side attribution without device-level data) and the Privacy-Preserving Ad Attribution API, which uses differential privacy and aggregation to report conversion events without individual user identification.",
        "Apple replaced IDFA with a per-session random UUID that changes every app launch.",
        "Developers can use the device's MAC address as a stable identifier after ATT prompt denial.",
      ],
      correctAnswer: 1,
      explanation: "Post-ATT, the identifier landscape changed significantly. IDFV (Identifier for Vendor) is available without user permission and is stable for first-party analytics within one developer's app family — useful for cross-app funnel analysis (e.g., a user moves from App A to App B from the same company). It resets when all vendor apps are uninstalled. For advertising attribution, SKAdNetwork provides aggregated, privacy-preserving conversion reporting: the OS sends conversion data to ad networks via Apple's servers with delays and noise (differential privacy), preventing individual user attribution while still measuring campaign effectiveness at a cohort level. IDFA requires explicit ATT opt-in (~20-30% opt-in rates post-prompt). MAC addresses have been randomized per network on iOS since iOS 14.",
      hints: [
        "What is the scope of IDFV — is it shared across all apps, or scoped to apps from the same developer?",
        "How does SKAdNetwork report conversion events without identifying individual users?",
      ],
    },
    {
      id: "q-sdi-mob-28",
      type: "multiple-choice",
      difficulty: "hard",
      question: "A mobile app integrates Apple Pay and Google Pay for checkout. What is tokenization in this context, and how does it prevent the merchant's backend from ever receiving the user's real card number (PAN)?",
      options: [
        "Tokenization is a form of encryption where the merchant decrypts the token server-side to get the PAN.",
        "In Apple Pay/Google Pay, the device stores a Device Account Number (DAN) — a payment token unique to the device and card — rather than the real PAN. At checkout, the device generates a one-time cryptogram (dynamic token) signed by the Secure Enclave using the DAN. The merchant's backend passes this cryptogram to the payment gateway, which forwards it to the card network (Visa/Mastercard). The card network resolves the DAN to the real PAN internally — the merchant's backend never sees the real card number.",
        "Tokenization replaces the card number with a merchant-specific alias stored in the merchant's database.",
        "Apple Pay sends the encrypted card number to the merchant; the merchant decrypts it using Apple's public key.",
      ],
      correctAnswer: 1,
      explanation: "Apple Pay / Google Pay implement network tokenization. The card network (Visa, Mastercard) issues a Device Account Number (DAN/DPAN) specific to the device + card combination. This DAN is stored in the device's Secure Element / Secure Enclave and never transmitted in plaintext. At payment time: (1) The device uses the DAN + a transaction counter to generate a one-time cryptogram via EMVCo's tokenization spec. (2) The cryptogram is passed to the merchant's payment gateway. (3) The gateway sends it to the acquirer, then the card network. (4) The card network detokenizes internally, routing to the issuer using the real PAN. The merchant receives only an authorization result. Even if the merchant's backend is breached, there are no real PANs to steal — only DANs which are device-specific and transaction-bound.",
      hints: [
        "If a DAN is compromised, can it be used on a different device or for a different merchant? Why not?",
        "What happens to the DAN if the physical card is reissued with a new PAN due to fraud?",
      ],
    },
    {
      id: "q-sdi-mob-29",
      type: "multiple-choice",
      difficulty: "medium",
      question: "An app implements server-driven UI (SDUI) where the server returns a JSON payload describing which components to render, their layout, and content — allowing the team to change the app's UI without an app release. What is the primary operational risk of SDUI at scale?",
      options: [
        "Server-driven UI is slower than static UI because the server must compute layouts.",
        "The server payload becomes a single point of failure for rendering — a malformed JSON response, an unrecognized component type, or a schema version mismatch between the server and an older app version can cause blank screens or crashes; the app must implement strict error boundaries, fallback rendering for unknown components, and backward compatibility in the schema to support older app versions that may not understand new component types.",
        "SDUI cannot support animations or interactive elements like swipe gestures.",
        "SDUI increases app binary size because all possible UI components must be bundled.",
      ],
      correctAnswer: 1,
      explanation: "Server-driven UI (used by Airbnb with its Ghost Platform, Lyft, and many fintech apps) provides deployment agility but introduces new failure modes: (1) Schema mismatch — older app versions receive a payload with a new component type they don't recognize; the app must gracefully skip unknown components rather than crash. (2) Network dependency — the initial render depends on a server response; if the server is slow or unavailable, the user sees a loading state or stale cached render. (3) Rendering errors — a malformed payload can corrupt an entire screen. Mitigations include: strict schema versioning, client-side component type whitelisting with graceful degradation, caching the last good payload for offline/error scenarios, and A/B testing schema changes with canary deployments before full rollout.",
      hints: [
        "What should an app do when it receives a JSON payload with a component type it has never seen before?",
        "If the SDUI payload server goes down, what does the user see? How do you mitigate this?",
      ],
    },
    {
      id: "q-sdi-mob-30",
      type: "multiple-choice",
      difficulty: "hard",
      question: "An offline mapping app (like Google Maps offline or HERE Maps) needs to cache vector tiles for a metropolitan area so the user can navigate without connectivity. A metro area requires ~500MB of vector tile data. What is the architecture for tile storage, cache eviction, and differential tile updates?",
      options: [
        "Store all 500MB as a single binary file; reload the entire file when map data updates.",
        "Organize tiles in a quadtree hierarchy by zoom level and tile coordinates (z/x/y), stored in an SQLite MBTiles database or per-tile files in a content-addressed store; evict tiles using LRU or geographic proximity (evict tiles far from the user's home region first); on update, a tile manifest on the server tracks per-tile version hashes so the client downloads only changed tiles (delta update), not the full 500MB.",
        "Vector tiles cannot be cached offline; only raster (PNG) tiles support offline storage.",
        "Use a CDN with aggressive caching; mobile devices stream tiles in real time with no local storage.",
      ],
      correctAnswer: 1,
      explanation: "Offline map tile architecture is a well-studied problem. The MBTiles format (SQLite database with a tiles table indexed by z/x/y) is the standard for packaging vector tile datasets — it supports efficient random access by tile coordinate. For 500MB of metro data, the client stores tiles indexed by the quadtree tile address. Cache eviction for storage management uses: (1) LRU by access time, (2) geographic distance (tiles far from the user's current region or home are lower priority). For updates, each tile has a content hash; the server provides a tile manifest mapping (z/x/y -> hash). The client compares local hashes against the manifest, downloading only tiles with changed hashes. A metropolitan area might have only 2-5% of tiles changed in a monthly update cycle, reducing a 500MB update to ~10-25MB of actual downloads. Google Maps offline uses a similar differential update system.",
      hints: [
        "What fraction of map tiles for a city change in a typical weekly update (new roads, businesses)?",
        "How does the quadtree tile addressing scheme (z/x/y) enable efficient geographic bounding box queries?",
      ],
    },
  ],
};

registerQuestions(questions);
