import type { Question } from "@/lib/curriculum";
import { registerQuestions } from "./registry";

const questions: Record<string, Question[]> = {
  "sdip-powers-of-two": [
    {
      id: "q-sdip-1",
      type: "multiple-choice",
      difficulty: "easy",
      question: "According to Google's powers-of-2 table used in back-of-envelope estimation, what is 2^10?",
      options: ["1 KB (1,024 bytes)", "1 MB (1,048,576 bytes)", "1 GB (1,073,741,824 bytes)", "1 TB (1,099,511,627,776 bytes)"],
      correctAnswer: 0,
      explanation: "**Step 1:** Recognize that $2^{10}$ is the fundamental building block for digital storage units.\n\n**Step 2:** Each additional 10 powers of 2 multiplies the unit by roughly 1,000. The four anchor values: $2^{10} \\approx 1$ KB, $2^{20} \\approx 1$ MB, $2^{30} \\approx 1$ GB, $2^{40} \\approx 1$ TB.\n\n**Step 3:** Therefore, $2^{10} = 1{,}024 \\approx 1$ KB. Memorizing these four anchors lets you rapidly estimate storage and memory needs.",
      hints: ["Each increment of 10 in the exponent adds one unit tier: KB, MB, GB, TB.", "2^10 = 1,024, which is close to 10^3 = 1,000."],
    },
    {
      id: "q-sdip-2",
      type: "multiple-choice",
      difficulty: "easy",
      question: "In back-of-envelope estimation, approximately how many bytes are in 1 GB?",
      options: ["10^6 bytes", "10^7 bytes", "10^9 bytes", "10^12 bytes"],
      correctAnswer: 2,
      explanation: "**Step 1:** Know the exact value: 1 GB = $2^{30} = 1{,}073{,}741{,}824$ bytes.\n\n**Step 2:** Round for estimation: $1{,}073{,}741{,}824 \\approx 10^9$ bytes. The full decimal chain: 1 KB $\\approx 10^3$, 1 MB $\\approx 10^6$, 1 GB $\\approx 10^9$, 1 TB $\\approx 10^{12}$.\n\n**Step 3:** In estimation work, the right order of magnitude determines whether you need 1 server or 100 servers. Being within 10x is acceptable. Thus, 1 GB $\\approx 10^9$ bytes.",
      hints: ["2^30 is exactly 1,073,741,824 — what is its rough decimal equivalent?", "Each jump from KB to MB to GB multiplies by roughly 1,000 (10^3)."],
    },
    {
      id: "q-sdip-3",
      type: "true-false",
      difficulty: "easy",
      question: "In systems design interview estimation, being within a factor of 10 (one order of magnitude) of the true answer is generally considered acceptable.",
      correctAnswer: "True",
      explanation: "**Step 1:** Understand the goal: back-of-envelope estimation determines whether a system needs 1 server or 100 servers, or 1 TB or 1 PB of storage.\n\n**Step 2:** Assess the tolerance: an answer within 10x of reality still places you in the correct architectural tier.\n\n**Step 3:** Recognize what interviewers evaluate: structured reasoning, correct units, and sound assumptions — not spreadsheet-precision arithmetic.\n\nTherefore, within a factor of 10 is acceptable for estimation.",
      hints: ["The goal is to pick the right class of solution, not the exact number.", "Would knowing you need '~5 servers' vs exactly 4.7 servers change your architecture?"],
    },
  ],

  "sdip-latency-numbers": [
    {
      id: "q-sdip-4",
      type: "multiple-choice",
      difficulty: "medium",
      question: "Which latency ordering is correct for the famous numbers every engineer should know (from Jeff Dean's lecture)?",
      options: [
        "L1 cache < Main memory < SSD random read < Network roundtrip (same datacenter) < Network roundtrip (cross-continent)",
        "L1 cache < SSD random read < Main memory < Network roundtrip (same datacenter) < Network roundtrip (cross-continent)",
        "Main memory < L1 cache < SSD random read < Network roundtrip (same datacenter) < Network roundtrip (cross-continent)",
        "L1 cache < Main memory < Network roundtrip (same datacenter) < SSD random read < Network roundtrip (cross-continent)",
      ],
      correctAnswer: 0,
      explanation: "**Step 1:** Memorize the famous latency numbers: L1 cache $\\approx 1$ ns, main memory $\\approx 100$ ns, SSD random read $\\approx 100$ $\\mu$s, same-datacenter roundtrip $\\approx 0.5$ ms, cross-continental roundtrip $\\approx 150$ ms.\n\n**Step 2:** Verify the ordering: L1 cache (1 ns) < Main memory (100 ns) < SSD random read (100 $\\mu$s = 100,000 ns) < Same-datacenter roundtrip (0.5 ms = 500,000 ns) < Cross-continental (150 ms = 150,000,000 ns). Each step is roughly 100x to 1,000x slower.\n\n**Step 3:** Apply the hierarchy: sub-millisecond response requires staying in L1/RAM; sub-100 ms allows one network hop.\n\nThe correct ordering is L1 cache < Main memory < SSD random read < Same-datacenter roundtrip < Cross-continental roundtrip.",
      hints: ["L1 cache is on-chip SRAM; memory is on the motherboard DRAM; SSD is behind a PCIe bus.", "A cross-continental packet crosses thousands of miles of fiber — light-speed delay alone is ~70 ms each way."],
    },
    {
      id: "q-sdip-5",
      type: "multiple-choice",
      difficulty: "medium",
      question: "A systems design interview asks you to design a feature requiring sub-10 ms p99 latency for user-facing reads. Which storage tier is appropriate as the primary read path?",
      options: ["Spinning disk HDD (seek time ~10 ms)", "SSD with NVMe (random read ~100 us)", "In-memory cache like Redis (<=1 ms round-trip)", "Object storage like S3 (first-byte latency ~50-200 ms)"],
      correctAnswer: 2,
      explanation: "**Step 1:** Identify the latency requirement: sub-10 ms p99 for user-facing reads. Remember that p99 includes queueing, serialization, and network overhead — not just storage access time.\n\n**Step 2:** Evaluate each option against the 10 ms budget:\n- HDD seek time $\\approx 10$ ms — at the limit, no margin for overhead\n- NVMe SSD random read $\\approx 100$ $\\mu$s — fast per-read, but network overhead plus tail latency pushes p99 beyond 10 ms\n- Object storage (S3): first-byte latency $\\approx 50$–$200$ ms — far too slow\n- In-memory cache (Redis): round-trip $\\le 1$ ms — comfortably within 10 ms\n\n**Step 3:** Choose the in-memory cache as the primary read path.\n\nRedis or Memcached is the appropriate choice.",
      hints: ["p99 latency includes queueing, serialization, and network overhead — not just storage access time.", "Which option's maximum latency fits comfortably within 10 ms, with margin for overhead?"],
    },
  ],

  "sdip-qps-estimation": [
    {
      id: "q-sdip-6",
      type: "multiple-choice",
      difficulty: "medium",
      question: "Twitter has 300 million daily active users (DAU). 20% of users post each day and each posting user sends an average of 5 tweets. Approximately how many tweet write QPS must the system handle at peak (assume 2x day-average peak)?",
      options: ["\$\\approx\$4 writes/sec average, \$\\approx\$8 writes/sec peak", "\$\\approx\$40 writes/sec average, \$\\approx\$80 writes/sec peak", "\$\\approx\$400 writes/sec average, \$\\approx\$800 writes/sec peak", "\$\\approx\$4,000 writes/sec average, \$\\approx\$8,000 writes/sec peak"],
      correctAnswer: 3,
      explanation: "**Step 1:** Calculate total daily tweets: 300M DAU $\\times 20\\%$ posting rate $\\times 5$ tweets per posting user = 300M tweets/day.\n\n**Step 2:** Convert to average QPS: 300M tweets $\\div 86{,}400$ seconds/day $\\approx 3{,}472$ tweets/sec. Using the approximation $86{,}400 \\approx 10^5$: 300M $\\div 10^5 = 3{,}000$ tweets/sec — close enough for estimation.\n\n**Step 3:** Apply peak multiplier: peak QPS = 2 $\\times$ average = approximately 7,000 writes/sec, which rounds to $\\approx 4{,}000$ average / $\\approx 8{,}000$ peak.\n\nKey formula: $\\text{QPS} = \\frac{\\text{DAU} \\times \\text{actions per user}}{\\text{seconds per day}}$.",
      hints: ["86,400 seconds per day $\\approx 10^5$ for fast estimation.", "QPS = DAU $\\times$ fraction active $\\times$ actions per session $\\div$ seconds per day."],
    },
    {
      id: "q-sdip-7",
      type: "multiple-choice",
      difficulty: "hard",
      question: "A system processes 10,000 QPS at steady state and each request takes exactly 100 ms to process. How many concurrent request-handling threads (or goroutines) must be available to sustain this load without queueing?",
      options: ["10 threads", "100 threads", "1,000 threads", "10,000 threads"],
      correctAnswer: 2,
      explanation: "**Step 1:** Apply Little's Law: $L = \\lambda \\cdot W$, where $L$ = average concurrency, $\\lambda$ = arrival rate, $W$ = average service time.\n\n**Step 2:** Plug in the values: $\\lambda = 10{,}000$ requests/sec, $W = 100$ ms $= 0.1$ sec. Thus $L = 10{,}000 \\times 0.1 = 1{,}000$ concurrent threads.\n\n**Step 3:** Interpret the result: 1,000 is the minimum thread pool size. In practice, add a safety buffer (e.g., 1,500 threads).\n\nLittle's Law is one of the most powerful tools in capacity planning — knowing it demonstrates senior-level systems thinking.",
      hints: ["Little's Law: average_concurrency = arrival_rate $\\times$ service_time.", "10,000 requests/sec $\\times$ 0.1 sec/request = 1,000 requests simultaneously in flight."],
    },
    {
      id: "q-sdip-8",
      type: "true-false",
      difficulty: "medium",
      question: "When estimating QPS in a systems design interview, it is acceptable to treat 1 day as 100,000 seconds ($10^5$) rather than the exact 86,400 seconds.",
      correctAnswer: "True",
      explanation: "**Step 1:** Calculate the error: $(100{,}000 - 86{,}400) \\div 86{,}400 \\approx 0.16 = 16\\%$.\n\n**Step 2:** Assess acceptability: a 16% error is well within the 10x tolerance for order-of-magnitude estimation.\n\n**Step 3:** Appreciate the benefit: using $10^5$ simplifies mental math. For example, 1 billion events per day $\\div 10^5 = 10{,}000$ events/sec.\n\nTop interviewers at Google, Meta, and Amazon explicitly encourage this approximation.",
      hints: ["86,400 vs 100,000 — what is the percentage difference?", "Is a 16% error acceptable when you're estimating to determine server count?"],
    },
  ],

  "sdip-storage-estimation": [
    {
      id: "q-sdip-9",
      type: "multiple-choice",
      difficulty: "easy",
      question: "A social network has 1 billion users, each with a profile stored as approximately 1 KB of metadata. What is the total storage required for all user profiles?",
      options: ["1 GB", "1 TB", "1 PB", "1 EB"],
      correctAnswer: 1,
      explanation: "**Step 1:** Convert units: 1 billion users = $10^9$ users, 1 KB = $10^3$ bytes.\n\n**Step 2:** Multiply: $10^9$ users $\\times 10^3$ bytes/user = $10^{12}$ bytes.\n\n**Step 3:** Convert to storage unit: $10^{12}$ bytes = 1 TB. The pattern generalizes: N billion users $\\times$ M KB/user = N$\\cdot$M TB.\n\n1B $\\times$ 1KB = 1TB.",
      hints: ["1 billion = $10^9$, 1 KB = $10^3$ bytes. Multiply the exponents.", "$10^9 \\times 10^3 = 10^{12}$ bytes = 1 TB."],
    },
    {
      id: "q-sdip-10",
      type: "multiple-choice",
      difficulty: "medium",
      question: "Twitter has accumulated 100 billion tweets, each averaging 280 bytes (including UTF-8 storage and metadata overhead). What is the approximate total raw text storage?",
      options: ["28 GB", "2.8 TB", "28 TB", "280 TB"],
      correctAnswer: 2,
      explanation: "**Step 1:** Convert units: 100 billion tweets = $10^{11}$ tweets, 280 bytes/tweet $\\approx 2.8 \\times 10^2$ bytes.\n\n**Step 2:** Multiply: $10^{11} \\times 2.8 \\times 10^2 = 2.8 \\times 10^{13}$ bytes.\n\n**Step 3:** Convert to TB: $10^{12}$ bytes = 1 TB, so $2.8 \\times 10^{13}$ bytes $\\approx 28$ TB.\n\nThis excludes media, indices, and replication. Twitter's total storage is petabytes when those are included.",
      hints: ["100 billion = $10^{11}$. 280 bytes $\\approx 3 \\times 10^2$.", "$10^{11} \\times 10^2 = 10^{13}$ bytes. How many TB is $10^{13}$ bytes?"],
    },
    {
      id: "q-sdip-11",
      type: "multiple-choice",
      difficulty: "hard",
      question: "A photo-sharing service stores 100 million photos/day. Each original photo is 3 MB, and the service generates 3 additional thumbnails at 100 KB each. How much raw storage (before replication) is needed per year?",
      options: ["\$\\approx\$11 PB/year", "\$\\approx\$110 PB/year", "\$\\approx\$1.1 PB/year", "\$\\approx\$110 TB/year"],
      correctAnswer: 1,
      explanation: "**Step 1:** Calculate per-photo storage: 3 MB original + 3 $\\times$ 100 KB thumbnails = 3 MB + 0.3 MB = 3.3 MB/photo.\n\n**Step 2:** Calculate daily volume: $10^8$ photos $\\times$ 3.3 MB = $3.3 \\times 10^8$ MB = $3.3 \\times 10^{14}$ bytes $\\approx 330$ TB/day.\n\n**Step 3:** Calculate annual: 330 TB/day $\\times$ 365 $\\approx 120{,}000$ TB $\\approx 120$ PB/year. Closest answer: $\\approx 110$ PB/year. With 3x replication this becomes $\\approx 360$ PB/year.\n\nAlways break storage estimation into: per-item-size $\\times$ items-per-day $\\times$ days $\\times$ replication-factor.",
      hints: ["Calculate per-photo storage first (original + all thumbnails), then scale to daily volume, then annual.", "330 TB/day $\\times$ 365 days $\\approx 120{,}000$ TB $\\approx 120$ PB/year."],
    },
    {
      id: "q-sdip-12",
      type: "true-false",
      difficulty: "medium",
      question: "When estimating storage in a systems design interview, you should always multiply your raw storage estimate by the replication factor (typically 3x) to get the true infrastructure storage cost.",
      correctAnswer: "True",
      explanation: "**Step 1:** Understand the distinction: raw data storage (logical size) differs from infrastructure storage (physical disk provisioning).\n\n**Step 2:** Apply the replication factor: standard RF = 3x (one primary + two replicas) in HDFS, Cassandra, and Google Spanner. If raw data = 10 TB, physical disk needed = 30 TB.\n\n**Step 3:** Recognize the impact: forgetting replication is one of the most common estimation mistakes and throws off server count by 3x.\n\nForgetting replication is a common mistake that can throw off your server count calculation by 3x.",
      hints: ["Think about what happens to a file stored in HDFS with the default replication factor.", "If 3 copies of each byte are stored, what does that do to total disk usage?"],
    },
  ],

  "sdip-bandwidth-estimation": [
    {
      id: "q-sdip-13",
      type: "multiple-choice",
      difficulty: "hard",
      question: "A video streaming platform has 1 million concurrent viewers, each watching HD video at 5 Mbps. What is the total egress bandwidth required?",
      options: ["5 Gbps", "50 Gbps", "500 Gbps", "5 Tbps"],
      correctAnswer: 3,
      explanation: "**Step 1:** Convert units: 1 million concurrent streams = $10^6$ streams, 5 Mbps = $5 \\times 10^6$ bits/sec.\n\n**Step 2:** Multiply: $10^6 \\times 5 \\times 10^6 = 5 \\times 10^{12}$ bits/sec = 5 Tbps.\n\n**Step 3:** Interpret the result: a single datacenter cannot serve 5 Tbps — you immediately need a CDN. This calculation motivates CDN architecture: serve from edge nodes near users.\n\nThe total egress bandwidth is 5 Tbps.",
      hints: ["1 million = $10^6$ streams. 5 Mbps = $5 \\times 10^6$ bits/sec.", "$10^6 \\times 5 \\times 10^6 = 5 \\times 10^{12}$ bits/sec = 5 Tbps."],
    },
    {
      id: "q-sdip-14",
      type: "multiple-choice",
      difficulty: "medium",
      question: "A file upload service receives 10,000 file uploads per second, each file averaging 1 MB. What is the required ingress bandwidth?",
      options: ["10 Mbps", "100 Mbps", "10 Gbps", "80 Gbps"],
      correctAnswer: 3,
      explanation: "**Step 1:** Calculate bytes per second: 10,000 files/sec $\\times$ 1 MB/file = 10,000 MB/sec = 10 GB/sec.\n\n**Step 2:** Convert to bits: 10 GB/sec $\\times$ 8 bits/byte = 80 Gbps.\n\n**Step 3:** Recognize the implication: the byte-to-bit conversion (multiply by 8) is commonly forgotten. 80 Gbps requires multiple 100GbE links.\n\nThe required ingress bandwidth is 80 Gbps.",
      hints: ["Network bandwidth is in bits; storage is in bytes. Remember to multiply by 8.", "10,000 $\\times$ 1 MB = 10,000 MB/sec = 10 GB/sec. Convert to Gbps."],
    },
    {
      id: "q-sdip-15",
      type: "true-false",
      difficulty: "easy",
      question: "In bandwidth estimation, 1 Gbps = 125 MB/s because there are 8 bits in a byte.",
      correctAnswer: "True",
      explanation: "**Step 1:** Apply the conversion: 1 Gbps = $10^9$ bits/sec. Since 1 byte = 8 bits, we get $10^9 \\div 8 = 125 \\times 10^6$ bytes/sec = 125 MB/s.\n\n**Step 2:** Practice the reverse: 10 Gbps $\\div$ 8 $\\approx$ 1,250 MB/s of actual data throughput.\n\n**Step 3:** Use in cross-checking: convert fluently between Mbps and MB/s when working with storage and network teams.\n\nThe statement is true: 1 Gbps = 125 MB/s.",
      hints: ["How many bits are in a byte?", "Divide Gbps by 8 to get GB/s, then adjust units."],
    },
  ],

  "sdip-read-write-ratio": [
    {
      id: "q-sdip-16",
      type: "multiple-choice",
      difficulty: "medium",
      question: "A social media feed system has a 100:1 read-to-write ratio. If the system handles 1,000 writes/sec, what is the total read QPS, and what architectural pattern does this ratio motivate?",
      options: [
        "1,000 reads/sec; vertical scaling of the write database",
        "100,000 reads/sec; read replicas or separate read-optimized stores",
        "1,000,000 reads/sec; write-ahead logging only",
        "10,000 reads/sec; synchronous replication to all nodes",
      ],
      correctAnswer: 1,
      explanation: "**Step 1:** Calculate read QPS: 100:1 ratio $\\times$ 1,000 writes/sec = 100,000 reads/sec.\n\n**Step 2:** Recognize the architectural implication: heavy read:write skew motivates read replicas, caching, and fanout-on-read vs. fanout-on-write strategies.\n\n**Step 3:** Apply the insight: you cannot scale the primary database for writes to also handle reads — you need a dedicated read tier.\n\nThe answer is 100,000 reads/sec, motivating read replicas or separate read-optimized stores.",
      hints: ["Multiply write QPS by the read:write ratio to get read QPS.", "A 100:1 read-heavy system means reads dominate — which layer should you scale?"],
    },
    {
      id: "q-sdip-17",
      type: "multiple-choice",
      difficulty: "medium",
      question: "A key-value store has 1 ms cache hit latency and 100 ms database latency. If the cache hit rate is 99%, what is the average read latency?",
      options: ["\$\\approx\$1 ms", "\$\\approx\$1.99 ms", "\$\\approx\$2.99 ms", "\$\\approx\$50 ms"],
      correctAnswer: 1,
      explanation: "**Step 1:** Apply the weighted average formula: average latency = (hit rate $\\times$ cache latency) + (miss rate $\\times$ DB latency).\n\n**Step 2:** Plug in values: $(0.99 \\times 1$ ms) + $(0.01 \\times 100$ ms) = 0.99 ms + 1 ms = 1.99 ms.\n\n**Step 3:** Interpret the result: a 99% cache hit rate with 100x latency differential produces average latency only ~2x the cache latency. A 1% miss rate contributes 1 ms — equal to the entire cache latency.\n\nThe average read latency is approximately 1.99 ms.",
      hints: ["Weighted average: (probability of each path) $\\times$ (latency of each path), summed.", "$0.99 \\times 1$ms + $0.01 \\times 100$ms = 1.99 ms."],
    },
  ],

  "sdip-replication-sla": [
    {
      id: "q-sdip-18",
      type: "multiple-choice",
      difficulty: "medium",
      question: "A service advertises 99.9% uptime SLA. How many minutes of downtime per year does this correspond to?",
      options: ["\$\\approx\$8.7 hours (522 minutes)", "\$\\approx\$52 minutes", "\$\\approx\$5 minutes", "\$\\approx\$87 hours (5,220 minutes)"],
      correctAnswer: 0,
      explanation: "**Step 1:** Calculate downtime fraction: 99.9% uptime means 0.1% downtime = $0.001$.\n\n**Step 2:** Calculate minutes per year: 365 $\\times$ 24 $\\times$ 60 = 525,600 minutes.\n\n**Step 3:** Multiply: $0.001 \\times 525{,}600 \\approx 526$ minutes $\\approx 8.76$ hours.\n\nQuick reference: 99% = 87.6 hours/year, 99.9% = 8.76 hours/year, 99.99% = 52 minutes/year, 99.999% = 5.25 minutes/year. Each additional 9 reduces downtime by 10x.\n\nThe answer is approximately 8.7 hours (522 minutes).",
      hints: ["Downtime fraction = 1 - uptime fraction = 0.001. Multiply by minutes/year.", "525,600 minutes/year $\\times$ 0.001 = 526 minutes $\\approx$ 8.76 hours."],
    },
    {
      id: "q-sdip-19",
      type: "multiple-choice",
      difficulty: "hard",
      question: "A system requires 99.99% uptime (four nines). If two independent components are in series (both must work), each with 99.99% uptime, what is the combined system uptime?",
      options: ["99.99%", "99.98%", "99.9%", "99.0%"],
      correctAnswer: 1,
      explanation: "**Step 1:** Apply series availability formula: system availability = product of individual availabilities.\n\n**Step 2:** Calculate: $0.9999 \\times 0.9999 = 0.9998 = 99.98\\%$.\n\n**Step 3:** Interpret the impact: in the small-downtime approximation, each component contributes additively: 0.01% + 0.01% $\\approx$ 0.02% downtime = 99.98% uptime. A microservices chain with 10 services each at 99.99% has combined availability of $0.9999^{10} \\approx 99.9\\%$.\n\nThe combined system uptime is 99.98%.",
      hints: ["Series components: multiply individual availabilities.", "$0.9999 \\times 0.9999 = 0.9999^2 \\approx 0.9998 = 99.98\\%$."],
    },
    {
      id: "q-sdip-20",
      type: "true-false",
      difficulty: "medium",
      question: "Standard replication factor of 3 in distributed systems (like HDFS or Cassandra) means the system can tolerate the simultaneous failure of any 2 nodes without data loss.",
      correctAnswer: "False",
      explanation: "**Step 1:** Understand replication factor: RF = 3 means 3 copies of each data item exist.\n\n**Step 2:** Apply quorum rules: with a quorum read/write (majority = 2 out of 3), the system tolerates 1 node failure for consistency. For data durability, you tolerate up to 2 failures only if at least 1 replica survives.\n\n**Step 3:** Recognize the limit: losing all 3 nodes holding a particular shard causes data loss. In Cassandra with RF=3 and QUORUM, 1 node failure is tolerable; 2 failures break quorum.\n\nThe statement is false. RF=3 tolerates 1 failure for consistency, not 2 simultaneous failures.",
      hints: ["Replication factor 3 = 3 copies, but quorum for consistency requires majority.", "Can you still do a quorum read/write with only 1 out of 3 nodes alive?"],
    },
  ],

  "sdip-server-capacity": [
    {
      id: "q-sdip-21",
      type: "multiple-choice",
      difficulty: "medium",
      question: "A single application server can handle approximately 10,000 QPS for simple in-memory requests. If the system needs to handle 500,000 QPS, how many servers are needed (ignoring overhead)?",
      options: ["5 servers", "50 servers", "500 servers", "5,000 servers"],
      correctAnswer: 1,
      explanation: "**Step 1:** Apply the capacity formula: servers needed = Total QPS / QPS per server.\n\n**Step 2:** Calculate: 500,000 / 10,000 = 50 servers.\n\n**Step 3:** Add practical margin: in practice, add a safety buffer (e.g., 20–30%) for uneven load distribution, so you might provision 70–80 servers.\n\nThe answer is 50 servers (ignoring overhead).",
      hints: ["Divide total required QPS by per-server QPS capacity.", "500,000 / 10,000 = 50."],
    },
    {
      id: "q-sdip-22",
      type: "multiple-choice",
      difficulty: "hard",
      question: "Which capacity rule of thumb is most commonly cited for a single database server handling mixed read/write workloads?",
      options: [
        "~1,000 QPS for complex queries with joins",
        "~10,000 QPS for simple key-value lookups on indexed columns",
        "~100,000 QPS for in-memory databases like Redis",
        "All of the above are correct for their respective scenarios",
      ],
      correctAnswer: 3,
      explanation: "**Step 1:** Know the three tiers: (1) Relational DB with complex joins: ~1,000 QPS. (2) Relational DB with simple indexed lookups: ~10,000 QPS. (3) In-memory stores like Redis: ~100,000–1,000,000 QPS.\n\n**Step 2:** Recognize the 10x step between each tier reflects the latency profile (disk I/O vs. index traversal vs. network vs. pure RAM).\n\n**Step 3:** Apply appropriately: knowing all three lets you quickly determine whether you need DB optimization, caching, or a fundamentally different storage layer.\n\nAll three are correct for their respective scenarios.",
      hints: ["Consider what makes each workload different: disk I/O, index traversal, network, pure RAM.", "Does a Redis GET and a PostgreSQL JOIN have the same bottleneck?"],
    },
  ],

  "sdip-interview-structure": [
    {
      id: "q-sdip-23",
      type: "multiple-choice",
      difficulty: "easy",
      question: "What is the recommended first step when starting a systems design interview at companies like Google, Amazon, and Meta?",
      options: [
        "Immediately draw the system architecture on the whiteboard",
        "Start writing API endpoints and data models",
        "Clarify functional and non-functional requirements with the interviewer",
        "Choose the database technology and justify your choice",
      ],
      correctAnswer: 2,
      explanation: "**Step 1:** Understand why requirements matter: jumping to solutions before understanding the problem is the #1 interview mistake cited by Google, Amazon, and Meta interviewers.\n\n**Step 2:** Ask the right questions: What features are in scope? What is the expected scale (DAU, QPS)? What is the latency SLA? What consistency model is required?\n\n**Step 3:** Set the direction: requirements clarification sets the entire trajectory of your design and demonstrates structured thinking.\n\nThe recommended first step is clarifying functional and non-functional requirements.",
      hints: ["What happens if you design for 1,000 users when the interviewer meant 1 billion?", "Requirements clarification is free; redesigning mid-interview wastes your limited time."],
    },
    {
      id: "q-sdip-24",
      type: "multiple-choice",
      difficulty: "medium",
      question: "In a Google systems design interview, what is the recommended structure for a 45-minute session?",
      options: [
        "5 min requirements, 5 min estimation, 10 min API/data model, 20 min high-level design, 5 min deep dive",
        "2 min requirements, 30 min detailed component design, 13 min Q&A",
        "15 min requirements, 15 min architecture, 15 min coding a component",
        "10 min estimation only, then let the interviewer lead",
      ],
      correctAnswer: 0,
      explanation: "**Step 1:** Know the recommended structure: 5 min — clarify requirements and scope; 5 min — capacity estimation (DAU, QPS, storage, bandwidth); 10 min — API design and data model; 20 min — high-level architecture diagram; 5 min — deep dive.\n\n**Step 2:** Understand the pacing: this ensures full breadth before going deep and shows you can structure an open-ended problem.\n\n**Step 3:** Recognize time management is evaluated: a complete high-level design is more valuable than a perfect but incomplete subsystem.\n\nThe recommended structure is option 0.",
      hints: ["What do interviewers need to see to give full marks: breadth first or depth first?", "A complete high-level design is more valuable than a perfect but incomplete subsystem."],
    },
    {
      id: "q-sdip-25",
      type: "true-false",
      difficulty: "easy",
      question: "In a systems design interview, it is acceptable to explicitly tell the interviewer 'I am going to make an assumption here' and state that assumption before proceeding, rather than waiting to be given exact numbers.",
      correctAnswer: "True",
      explanation: "**Step 1:** Understand the skill: making and stating explicit assumptions is a core interview skill. Interviewers rarely have perfect answers to \"how many users will this system have?\"\n\n**Step 2:** Demonstrate structured thinking: saying \"I'll assume 10 million DAU — is that reasonable?\" invites correction and shows you reason from first principles.\n\n**Step 3:** Never silently assume: always verbalize your assumptions so the interviewer can redirect you if needed.\n\nThe statement is true. Making explicit assumptions is a core interview skill.",
      hints: ["What is worse: making a wrong assumption or making no assumption and stalling?", "How does stating assumptions help the interviewer understand your thought process?"],
    },
  ],

  "sdip-cap-theorem": [
    {
      id: "q-sdip-26",
      type: "multiple-choice",
      difficulty: "medium",
      question: "A financial payment system must never show inconsistent account balances to users (strong consistency required). During a network partition, what does CAP theorem dictate?",
      options: [
        "The system can maintain both consistency and availability during a partition",
        "The system must choose to sacrifice availability (return errors) to preserve consistency",
        "The system should use eventual consistency with compensating transactions",
        "CAP theorem does not apply to databases with ACID guarantees",
      ],
      correctAnswer: 1,
      explanation: "**Step 1:** Apply CAP theorem: during a network partition (P), a system must choose between Consistency (C) and Availability (A).\n\n**Step 2:** Make the trade-off: for a payment system requiring strong consistency, the correct choice is CP — during a partition, the system refuses to serve stale reads rather than risk showing inconsistent balances.\n\n**Step 3:** Know the examples: Google Spanner (CP), HBase (CP) vs. DNS, Cassandra (AP). Partitions are rare but inevitable; the CAP choice defines failure behavior.\n\nThe system must choose to sacrifice availability to preserve consistency.",
      hints: ["Strong consistency for payments means you cannot show balance A to one node and balance B to another.", "What happens to a bank if it processes a debit on stale data?"],
    },
    {
      id: "q-sdip-27",
      type: "multiple-choice",
      difficulty: "hard",
      question: "A social media 'like count' feature can tolerate showing counts that are a few seconds stale. Which consistency model and database are most appropriate?",
      options: [
        "Strong consistency; PostgreSQL with synchronous replication",
        "Eventual consistency; Cassandra with AP configuration",
        "Linearizability; Google Spanner",
        "Causal consistency; CockroachDB",
      ],
      correctAnswer: 1,
      explanation: "**Step 1:** Assess business requirements: the cost of showing a count 2 seconds stale is negligible (user sees 10,432 instead of 10,433 likes).\n\n**Step 2:** Match to technology: Cassandra with eventual consistency offers high write throughput, geographic distribution, and fault tolerance — ideal for this use case.\n\n**Step 3:** Reject alternatives: strong consistency adds latency and reduces availability for no user-visible benefit. Causal consistency is overkill.\n\nEventual consistency with Cassandra is the most appropriate choice.",
      hints: ["What is the real cost to the user of seeing a like count that is 2 seconds behind?", "Does the business requirement justify the availability sacrifice of strong consistency?"],
    },
  ],

  "sdip-bottleneck-identification": [
    {
      id: "q-sdip-28",
      type: "multiple-choice",
      difficulty: "hard",
      question: "During a systems design interview, you have designed a system with: Load Balancer -> 10 App Servers -> 1 Primary DB. The system handles 50,000 reads/sec and 5,000 writes/sec. Where is the likely bottleneck?",
      options: [
        "The load balancer — it cannot distribute 55,000 QPS",
        "The app servers — 10 servers cannot handle 50,000 reads/sec",
        "The single primary database — a single DB struggles above 10,000-50,000 QPS for mixed workloads",
        "The network — bandwidth between app servers and DB is exhausted",
      ],
      correctAnswer: 2,
      explanation: "**Step 1:** Analyze each tier: load balancers handle millions of QPS; 10 app servers at 10,000 QPS each = 100,000 QPS capacity — both are fine.\n\n**Step 2:** Check the database: a single DB handles ~1,000–10,000 QPS for complex queries or ~10,000–50,000 QPS for simple indexed reads. At 55,000 QPS total, you are at or beyond its limits.\n\n**Step 3:** Identify solutions: add read replicas, introduce a caching layer (Redis), or shard the database. The single primary database is the single point of contention.\n\nThe single primary database is the likely bottleneck.",
      hints: ["What is the capacity of a single relational DB vs. a load balancer?", "Which component has only 1 instance vs. 10 instances?"],
    },
    {
      id: "q-sdip-29",
      type: "true-false",
      difficulty: "medium",
      question: "Adding more application servers will always solve performance problems in a web system that is already showing slow response times.",
      correctAnswer: "False",
      explanation: "**Step 1:** Diagnose before scaling: adding app servers only helps if the app tier is the bottleneck.\n\n**Step 2:** Recognize the risk: if the database is saturated (the most common bottleneck), adding more app servers increases concurrent connections, potentially worsening the problem via connection pool exhaustion and lock contention.\n\n**Step 3:** Measure first: determine where latency is spent — is the app server CPU-bound, or is most time waiting for DB responses?\n\nThe statement is false. Scaling the right tier requires identifying the actual bottleneck first.",
      hints: ["What if the database can only handle 10,000 QPS and you have 20 app servers each sending 1,000 QPS?", "Is adding capacity to a non-bottleneck component useful?"],
    },
  ],

  "sdip-sharding-caching": [
    {
      id: "q-sdip-30",
      type: "multiple-choice",
      difficulty: "hard",
      question: "A messaging system needs to shard its message database. User IDs range from 1 to 1 billion. Which sharding strategy avoids hotspots when most messages are sent by a small number of power users?",
      options: [
        "Range-based sharding on user_id (users 1-100M on shard 1, etc.)",
        "Hash-based sharding on user_id (user_id % num_shards)",
        "Directory-based sharding with a shard lookup table",
        "Sharding by message timestamp (recent messages on the latest shard)",
      ],
      correctAnswer: 1,
      explanation: "**Step 1:** Analyze each strategy: range-based sharding creates hotspots if popular users cluster in the same range. Timestamp-based sharding creates a write hotspot on the most recent shard. Directory-based sharding adds lookup latency and the directory itself becomes a bottleneck.\n\n**Step 2:** Apply hash-based sharding: user_id mod N distributes users uniformly across shards regardless of individual user activity.\n\n**Step 3:** Accept the trade-off: hash sharding is the default choice for uniform load distribution, but range queries become scatter-gather across all shards.\n\nHash-based sharding (user_id % num_shards) is the correct answer.",
      hints: ["Which strategy makes it most likely that celebrity accounts end up on different shards?", "What happens with range sharding if users 1-1000 are all power users?"],
    },
  ],
};

registerQuestions(questions);

export default questions;
