import type { Question } from "@/lib/curriculum";
import { registerQuestions } from "./registry";

const questions: Record<string, Question[]> = {
  "sdi-scale-horizontal": [
    {
      id: "q-sdi-scale-1",
      type: "multiple-choice",
      difficulty: "easy",
      question: "What is the primary advantage of horizontal scaling over vertical scaling for web services?",
      options: [
        "Horizontal scaling always provides lower latency per request.",
        "Horizontal scaling adds more machines to distribute load, providing near-linear capacity growth and eliminating single points of failure.",
        "Horizontal scaling is always cheaper than vertical scaling.",
        "Horizontal scaling requires no changes to application code.",
      ],
      correctAnswer: 1,
      explanation: "Horizontal scaling (scale-out) adds more machines and distributes traffic across them via load balancers. This provides near-linear capacity growth, fault tolerance (one machine failure doesn't take down the service), and avoids the hard ceiling on vertical scaling (you can only get so big a machine). Vertical scaling (scale-up) is simpler but hits hardware limits and creates a SPOF. Cost and latency comparisons depend heavily on workload specifics.\n\n**Step 1:** Understand the capacity difference. Vertical scaling increases the capacity of a single machine. Horizontal scaling adds more machines, and capacity grows roughly linearly with each added node.\n\n**Step 2:** Consider fault tolerance. With vertical scaling, a single machine failure takes down the entire service. With horizontal scaling, one node can fail and the load balancer routes traffic to healthy instances.\n\n**Step 3:** Recognize the ceiling. There is a physical limit to how large a single machine can be (RAM, CPU, storage). Horizontal scaling has no theoretical ceiling — you can keep adding nodes.",
      hints: [
        "Think about what happens when a single large machine fails versus when one of ten smaller machines fails.",
        "Vertical scaling has a hard ceiling - you can only make a machine so large. Horizontal scaling has no such ceiling.",
      ],
    },
    {
      id: "q-sdi-scale-2",
      type: "true-false",
      difficulty: "medium",
      question: "A stateless service - one that stores no in-process session state - is a prerequisite for safe horizontal scaling.",
      options: ["True", "False"],
      correctAnswer: 0,
      explanation: "Horizontal scaling routes requests across many identical instances. If session state lives in-process on one instance, a user whose next request lands on a different instance will lose their session. Stateless services store all session data externally (e.g., Redis) so any instance can serve any request. This is why statelessness is a foundational prerequisite, not merely a nice-to-have, for horizontal scaling.\n\n**Step 1:** Understand the routing problem. A load balancer distributes requests across N identical instances using round-robin or least-connections.\n\n**Step 2:** Identify the statefulness problem. If instance 1 stores user A's cart in its local memory, and the next request from user A is routed to instance 2, instance 2 has no record of that cart — causing a broken user experience.\n\n**Step 3:** Apply the stateless principle. All persistent state is moved to an external store (Redis, a database, or a signed JWT) that every instance can access. Instances themselves hold no user-specific state in memory.",
      hints: [
        "If user A's cart is in memory on server 1, what happens when the load balancer sends their next request to server 2?",
        "The 12-factor app methodology lists 'processes are stateless and share-nothing' as a core principle.",
      ],
    },
    {
      id: "q-sdi-scale-3",
      type: "multiple-choice",
      difficulty: "medium",
      question: "Which approach correctly externalizes session state to enable horizontal scaling of a web application?",
      options: [
        "Use sticky sessions (session affinity) on the load balancer so each user always hits the same server.",
        "Store session data in a shared Redis cluster so any application server can retrieve any session.",
        "Encode all session state in a signed JWT cookie stored client-side.",
        "Both B and C are valid strategies for enabling stateless horizontal scaling.",
      ],
      correctAnswer: 3,
      explanation: "Both Redis-backed server-side sessions and signed JWT client-side tokens eliminate in-process state. Redis provides a shared session store any server can access. JWTs embed state in a tamper-proof token the client presents on every request. Sticky sessions (option A) are a workaround that still stores state in-process — it does not truly enable stateless scaling and breaks when a node is removed from the pool.\n\n**Step 1:** Evaluate option A (sticky sessions). The load balancer routes each user to the same server. However, when that server is decommissioned or crashes, the user's session is lost — this is a brittle solution.\n\n**Step 2:** Consider option B (Redis sessions). All servers share a Redis cluster. Any server can read or write any user's session — no affinity needed, and sessions survive server failures.\n\n**Step 3:** Consider option C (JWT). The session state is encoded in a signed token the client stores and presents on every request. The server only validates the signature — no shared state needed at all.",
      hints: [
        "Sticky sessions route a user to the same server, but what happens during a deployment or when that server crashes?",
        "A JWT carries its own payload - the server just validates the signature, no shared store needed.",
      ],
    },
    {
      id: "q-sdi-scale-4",
      type: "multiple-choice",
      difficulty: "hard",
      question: "Your autoscaler is configured to trigger on CPU utilization > 70%. A sudden spike causes CPU to jump from 30% to 95% in 10 seconds, but new instances take 90 seconds to provision. What is the correct mitigation strategy?",
      options: [
        "Lower the CPU threshold to 50% so scaling triggers sooner.",
        "Use predictive scaling based on historical traffic patterns combined with a queue-depth or p99 latency signal as a faster-reacting secondary trigger.",
        "Pre-warm instances continuously so they are always ready.",
        "Switch entirely to vertical scaling to avoid provisioning delays.",
      ],
      correctAnswer: 1,
      explanation: "CPU-based reactive scaling has an inherent lag equal to (detection delay + provisioning time). Lowering the threshold helps marginally but does not solve the 90-second provisioning gap. The correct approach combines:\n\n**Step 1:** Add predictive/scheduled scaling. Analyze historical traffic patterns to pre-provision instances before demand spikes arrive — eliminating the lag for known peak windows.\n\n**Step 2:** Use faster-reacting secondary signals. Queue depth (work already waiting) and p99 latency (user-visible impact) rise faster than CPU during request bursts, giving the autoscaler earlier warning.\n\n**Step 3:** Reject the alternatives. Pre-warming constantly wastes money. Switching to vertical scaling still faces provisioning delays and a hardware ceiling.",
      hints: [
        "If provisioning takes 90 seconds and the spike lasts 30 seconds, reactive scaling will always be too late for that spike.",
        "Queue depth and p99 latency reflect actual workload pressure faster than CPU - they rise before CPU does during request bursts.",
      ],
    },
  ],
  "sdi-scale-queue-worker": [
    {
      id: "q-sdi-scale-5",
      type: "multiple-choice",
      difficulty: "easy",
      question: "What is the primary architectural benefit of using a message queue between a producer service and worker services?",
      options: [
        "It guarantees exactly-once delivery of every message.",
        "It decouples producers from consumers so each can scale independently and absorb burst traffic.",
        "It eliminates the need for a database in the system.",
        "It reduces total system latency by batching requests.",
      ],
      correctAnswer: 1,
      explanation: "The queue+worker pattern's core value is temporal and scaling decoupling: the producer writes to the queue without waiting for processing, and workers drain the queue at their own pace. During traffic spikes, the queue absorbs the burst (acts as a buffer). Workers can be scaled up independently of producers. This prevents backpressure from cascading failures between services. Exactly-once delivery requires additional design (queues alone are typically at-least-once). Latency may increase, not decrease.\n\n**Step 1:** Recognize the decoupling benefit. Without a queue, a slow consumer causes backpressure on producers — a surge in workers brings down the API. With a queue, producers and consumers evolve independently.\n\n**Step 2:** Understand the burst-absorption role. The queue holds excess requests during a spike, releasing them at the workers' natural pace. No request is dropped, no producer is overwhelmed.\n\n**Step 3:** Note the scaling independence. Producers and workers scale on separate schedules. You can have 1 producer and 100 workers (or vice versa) without redesigning either component.",
      hints: [
        "What happens without a queue if workers are slow and the producer keeps sending requests at high throughput?",
        "Think of the queue as a shock absorber between bursty producers and capacity-limited workers.",
      ],
    },
    {
      id: "q-sdi-scale-6",
      type: "multiple-choice",
      difficulty: "medium",
      question: "In Amazon SQS, a worker receives a message and begins processing. The visibility timeout is set to 30 seconds but processing takes 45 seconds. What happens?",
      options: [
        "SQS deletes the message after 30 seconds automatically.",
        "The message becomes visible again to other workers after 30 seconds, risking duplicate processing.",
        "SQS pauses delivery of new messages to that worker until it finishes.",
        "The worker's connection is terminated after 30 seconds.",
      ],
      correctAnswer: 1,
      explanation: "SQS visibility timeout hides a message from other consumers while one worker processes it. If the worker does not delete or extend the timeout before it expires, SQS assumes the worker failed and makes the message visible again. Another worker can then pick it up, resulting in double processing. The fix is to either set the visibility timeout conservatively longer than the maximum expected processing time, or programmatically extend it (ChangeMessageVisibility) as processing progresses.",
      hints: [
        "SQS cannot know if a worker succeeded or crashed - it only knows if the message was deleted within the timeout window.",
        "Visibility timeout is not a hard processing deadline; workers can call ChangeMessageVisibility to extend it.",
      ],
    },
    {
      id: "q-sdi-scale-7",
      type: "true-false",
      difficulty: "medium",
      question: "The optimal number of concurrent worker threads for a CPU-bound task is equal to the number of CPU cores, while for an I/O-bound task it can be significantly higher than the number of cores.",
      options: ["True", "False"],
      correctAnswer: 0,
      explanation: "CPU-bound tasks keep the CPU fully utilized during execution. Adding more threads than cores causes context-switching overhead with no throughput gain — the bottleneck is compute. I/O-bound tasks (DB queries, HTTP calls, disk reads) spend most time waiting; during waits the CPU is idle. More threads than cores allows overlapping waits, increasing throughput. A common heuristic for I/O-bound workers:\n\n\\[\n\\text{thread count} = \\text{cores} \\cdot \\left(1 + \\frac{\\text{wait}\\_\\text{time}}{\\text{compute}\\_\\text{time}}\\right)\n\\]\n\nThread pools like those in Node.js (async/await), Java (virtual threads), or Python (asyncio) exploit this distinction.\n\n**Step 1:** CPU-bound tasks. N cores can run N threads simultaneously with maximum efficiency. Adding a (N+1)th thread forces context switching, reducing effective throughput.\n\n**Step 2:** I/O-bound tasks. While thread 1 waits for a database response (milliseconds of wall-clock time), threads 2 through 100 can be doing useful work or waiting. More threads than cores pays off here.\n\n**Step 3:** Apply the heuristic. If wait_time is 4ms and compute_time is 1ms, the multiplier is (1 + 4) = 5 — so on an 8-core machine, 40 threads maximizes throughput.",
      hints: [
        "For CPU-bound: N cores doing N computations simultaneously is optimal. N+1 threads means one waits, creating overhead.",
        "For I/O-bound: while thread 1 waits for a DB response (milliseconds), threads 2-100 can all be computing or waiting in parallel.",
      ],
    },
    {
      id: "q-sdi-scale-8",
      type: "multiple-choice",
      difficulty: "hard",
      question: "A message processing job has failed 3 times and been returned to the main queue each time. What is the correct pattern to prevent this message from blocking other work indefinitely?",
      options: [
        "Increase the visibility timeout on each retry so the worker has more time.",
        "Delete the message after 3 failures to prevent queue pollution.",
        "Route the message to a Dead Letter Queue (DLQ) after N failures so engineers can inspect and replay it without blocking normal processing.",
        "Log the failure and continue retrying indefinitely with exponential backoff.",
      ],
      correctAnswer: 2,
      explanation: "A Dead Letter Queue captures messages that exceed the maxReceiveCount threshold. This prevents poison pill messages from cycling endlessly through the main queue and blocking healthy message processing. Engineers can inspect DLQ messages to diagnose bugs, fix them, and replay the messages back to the main queue once resolved. Indefinite retries with exponential backoff waste worker resources and delay discovery of root causes. Deleting failed messages loses data permanently.",
      hints: [
        "A 'poison pill' message is one that always fails processing - without a DLQ it loops forever, consuming worker capacity.",
        "DLQs are for isolation, not for giving up - messages there can be replayed after the underlying bug is fixed.",
      ],
    },
  ],
  "sdi-scale-cqrs-event-sourcing": [
    {
      id: "q-sdi-scale-9",
      type: "multiple-choice",
      difficulty: "medium",
      question: "What problem does CQRS (Command Query Responsibility Segregation) solve, and how?",
      options: [
        "It eliminates the need for a message queue by combining reads and writes into a single model.",
        "It separates the write model (commands that change state) from the read model (queries that return data), allowing each to be optimized and scaled independently.",
        "It ensures all database reads are strongly consistent by routing all queries through the primary write replica.",
        "It is primarily a security pattern that restricts who can issue write commands.",
      ],
      correctAnswer: 1,
      explanation: "Most applications are read-heavy; the query path has very different performance requirements than the command path. CQRS splits these: commands go through a write-optimized model (normalized, transactional), while queries hit a read-optimized model (denormalized, cached, potentially read replicas or separate data stores). This lets you scale reads and writes independently, optimize schemas differently, and add query-side caching without affecting write consistency. The trade-off is eventual consistency between the two models.\n\n**Step 1:** Identify the mismatch. If reads are 100 times more frequent than writes, why should both use the same normalized relational schema optimized for writes? The query path is starved.\n\n**Step 2:** Apply the split. The command side stays normalized and transactional. The query side is denormalized, cached, and served from read replicas or a specialized data store (e.g., Elasticsearch).\n\n**Step 3:** Note the consistency trade-off. Because the read model is updated asynchronously from the event stream, there is a brief window where the read model may show stale data.",
      hints: [
        "If reads are 100 times more frequent than writes, why should both share the same normalized relational schema?",
        "CQRS often pairs with event sourcing: commands produce events, events update the read model projection.",
      ],
    },
    {
      id: "q-sdi-scale-10",
      type: "true-false",
      difficulty: "medium",
      question: "In event sourcing, the current state of an entity is derived by replaying all events that have occurred to that entity since the beginning of time, not by storing the entity's current field values directly.",
      options: ["True", "False"],
      correctAnswer: 0,
      explanation: "Event sourcing stores the append-only log of state-changing events (e.g., OrderPlaced, ItemAdded, OrderShipped) as the source of truth. Current state is a projection computed by replaying events. This enables full audit history, temporal queries ('what was the state at time T?'), and easy event-driven integration. The downside is replay cost for entities with long histories, which snapshots mitigate.\n\n**Step 1:** Think of a bank account. Instead of storing the current balance (which is derived data), you store every debit and credit transaction. The balance at any moment is the sum of all transactions up to that point.\n\n**Step 2:** Understand the replay mechanism. To find the current state, start from an empty account and apply every event in sequence. The final balance is the answer.\n\n**Step 3:** Accept the trade-off. Replaying 100,000 events on every read is expensive. Snapshots (periodic materialized state) solve this by giving you a starting point close to the present.",
      hints: [
        "Think of a bank account: instead of storing the current balance, store every debit and credit transaction - the balance is the sum.",
        "Event sourcing trades storage space for complete auditability and the ability to rebuild any past state.",
      ],
    },
    {
      id: "q-sdi-scale-11",
      type: "multiple-choice",
      difficulty: "hard",
      question: "An event-sourced aggregate has 100,000 events. Replaying all events on every read is too slow. What is the standard solution?",
      options: [
        "Delete old events and replace them with a single 'summary' event to reduce the log.",
        "Store a periodic snapshot of the aggregate's state at a known event sequence number, and replay only events after that snapshot.",
        "Switch to a traditional database for aggregates with more than 1,000 events.",
        "Increase read replica count so more machines can replay events in parallel.",
      ],
      correctAnswer: 1,
      explanation: "Snapshots capture the materialized state of an aggregate at event N. On read, load the latest snapshot plus only the events from N+1 onward. This bounds replay cost to (events since last snapshot) rather than all-time events. Snapshots are typically taken periodically (every 100 events, or every hour) and stored alongside the event log. Deleting events would violate event sourcing's immutability and auditability guarantees.",
      hints: [
        "Snapshots are checkpoints - like saving a game at chapter 10 so you don't replay chapters 1-9 every time.",
        "The snapshot doesn't replace events; both coexist so full history is still available if needed.",
      ],
    },
    {
      id: "q-sdi-scale-12",
      type: "multiple-choice",
      difficulty: "hard",
      question: "In CQRS with event sourcing, a 'projection' is best described as:",
      options: [
        "A database index that speeds up write-side command processing.",
        "A read-side view model built by consuming events and materializing them into a query-optimized data structure.",
        "A cryptographic proof that an event has not been tampered with.",
        "A load balancer rule that routes commands to the correct aggregate handler.",
      ],
      correctAnswer: 1,
      explanation: "A projection subscribes to the event stream and transforms events into a denormalized, query-optimized read model (e.g., a Redis hash, an Elasticsearch index, or a SQL read table). Projections can be rebuilt from scratch by replaying the full event log, making them disposable and evolvable. Multiple projections can serve different query shapes from the same event stream without modifying the write model.",
      hints: [
        "If events are the raw facts, a projection is the report or view you derive from those facts for a specific query purpose.",
        "Because projections are derived, they can be dropped and rebuilt - the event log is the source of truth, not the projection.",
      ],
    },
  ],
  "sdi-scale-database-patterns": [
    {
      id: "q-sdi-scale-13",
      type: "multiple-choice",
      difficulty: "easy",
      question: "Your application performs 90% reads and 10% writes. Which database scaling pattern is most appropriate to scale read throughput?",
      options: [
        "Vertical scaling of the primary database instance.",
        "Adding read replicas and routing read queries to replicas while writes go to the primary.",
        "Sharding the database by user ID.",
        "Adding more indexes to the primary to speed up reads.",
      ],
      correctAnswer: 1,
      explanation: "Read replicas asynchronously replicate data from the primary and serve read queries, multiplying read throughput proportionally to the number of replicas. Writes still go to the primary, maintaining a single source of truth. This is the standard first step for read-heavy workloads. Sharding is more complex and appropriate when write throughput or data volume exceeds what a single primary can handle. Adding indexes helps per-query performance but does not increase overall read throughput.\n\n**Step 1:** Route read queries to replicas. The application or load balancer sends SELECT queries to replica nodes; INSERT/UPDATE/DELETE go to the primary. Replication is asynchronous, so replicas may lag slightly behind.\n\n**Step 2:** Scale horizontally for reads. Each additional replica adds roughly one primary's worth of read capacity. With 5 replicas, you can handle 5 times the read load.\n\n**Step 3:** Know the trade-off. Because replication is asynchronous, a read immediately after a write may return the old value (eventual consistency). For strongly consistent reads, route to the primary.",
      hints: [
        "Read replicas are cheap to add and don't require application redesign - just route SELECT queries to replicas.",
        "Trade-off: replicas have replication lag, so reads may see slightly stale data (eventual consistency).",
      ],
    },
    {
      id: "q-sdi-scale-14",
      type: "multiple-choice",
      difficulty: "medium",
      question: "A PostgreSQL service under load shows thousands of 'connection pool exhausted' errors. The database has 200 max_connections. What is the correct solution?",
      options: [
        "Increase max_connections to 10,000 so all application instances can connect directly.",
        "Add PgBouncer as a connection pooler between the application and PostgreSQL to multiplex many application connections over a small pool of real database connections.",
        "Add a read replica for every application server instance.",
        "Switch to a NoSQL database which has no connection limits.",
      ],
      correctAnswer: 1,
      explanation: "PostgreSQL allocates significant memory per connection (~5-10MB). Setting max_connections to 10,000 would exhaust RAM. PgBouncer is a lightweight connection pooler that sits between the application and Postgres. Applications connect to PgBouncer (which supports thousands of connections cheaply), and PgBouncer multiplexes them over a small real connection pool (e.g., 100 connections). In transaction-mode pooling, a real connection is only held during an active transaction, dramatically increasing effective concurrency.",
      hints: [
        "Each Postgres connection is a forked OS process - 10,000 connections means 10,000 processes and ~50-100GB RAM just for connections.",
        "PgBouncer is invisible to the application - it speaks the Postgres wire protocol, so no code changes are needed.",
      ],
    },
    {
      id: "q-sdi-scale-15",
      type: "multiple-choice",
      difficulty: "hard",
      question: "A query runs in 8 seconds. EXPLAIN ANALYZE shows a sequential scan on a 10-million-row table. The WHERE clause filters on `user_id`. What is the most likely fix and why does it work?",
      options: [
        "Add more RAM to the database server so the full table fits in memory.",
        "Add a B-tree index on `user_id`; the query planner will use an index scan instead of a full sequential scan, reducing I/O from O(n) to O(log n) for the lookup.",
        "Partition the table by date so fewer rows are scanned.",
        "Rewrite the query to use a subquery instead of a WHERE clause.",
      ],
      correctAnswer: 1,
      explanation: "A sequential scan reads every row in the table (O(n) I/O). A B-tree index on user_id allows the planner to find matching rows in O(log n) comparisons plus direct page reads. For selective predicates (low cardinality fraction), an index scan is dramatically faster — often 100–1000 times on large tables. Adding RAM helps if the table fits in the buffer cache, but 10M rows may be gigabytes. Partitioning helps with time-range queries, not user_id lookups. Subqueries do not change the access path.\n\n**Step 1:** Read the EXPLAIN ANALYZE output. A 'Seq Scan' on 10 million rows means the database is reading every row, not using any index to skip to the relevant ones.\n\n**Step 2:** Create the right index. A B-tree index on user_id gives the planner a sorted structure to binary-search, jumping directly to pages containing matching user_ids.\n\n**Step 3:** Verify the improvement. After creating the index, re-run EXPLAIN ANALYZE — expect to see 'Index Scan' or 'Index Only Scan' with rows filtered to the matching subset, not 10 million.",
      hints: [
        "EXPLAIN ANALYZE output showing 'Seq Scan' with 'rows=10000000' means the DB is reading every row, not just matching ones.",
        "Index scans are effective when the predicate is selective - filtering to a small fraction of rows.",
      ],
    },
    {
      id: "q-sdi-scale-16",
      type: "true-false",
      difficulty: "medium",
      question: "The N+1 query problem occurs when an application executes one query to fetch N parent records and then issues N additional queries to fetch related child records, causing N+1 total database round-trips instead of 1 or 2.",
      options: ["True", "False"],
      correctAnswer: 0,
      explanation: "The N+1 problem is a common ORM anti-pattern. For example: fetch 100 blog posts (1 query), then for each post fetch its author (100 queries) = 101 total queries. The fix is eager loading: use a JOIN or an IN (...) query to fetch all related records in a single additional query. ORMs like Hibernate, ActiveRecord, and Sequelize all support eager loading (includes/preload/joinedload) to solve this. At scale, N+1 can turn a fast endpoint into a slow one — 100 ms + 100 \\times 5 ms = 600 ms.\n\n**Step 1:** Identify the pattern. A loop in application code that issues a database call inside each iteration is the classic smell. Count the queries: more than 5–10 for a single API call warrants investigation.\n\n**Step 2:** Apply eager loading. Instead of N+1 queries, use a JOIN to fetch parent and children in 2 queries total, or an IN (...) clause to batch-fetch all children in one call.\n\n**Step 3:** Measure the impact. EXPLAIN or query logging reveals the query count per request. Reducing 101 queries to 2 cuts endpoint latency dramatically.",
      hints: [
        "If you see a loop in code that calls a database method inside each iteration, that's the N+1 pattern.",
        "Use EXPLAIN or query logging to count queries per request - more than 5-10 for a single API call is often a red flag.",
      ],
    },
  ],
  "sdi-scale-caching-layers": [
    {
      id: "q-sdi-scale-17",
      type: "multiple-choice",
      difficulty: "easy",
      question: "Arranging caches in a hierarchy (L1: in-process -> L2: Redis -> L3: CDN -> database), what is the primary benefit of checking L1 before L2?",
      options: [
        "L1 caches are always more accurate than L2 caches.",
        "L1 in-process cache avoids network round-trips entirely, providing sub-microsecond latency versus Redis which requires a network call (~0.5ms).",
        "L1 caches are cheaper to operate than Redis clusters.",
        "L2 Redis caches cannot handle the same data types as L1 caches.",
      ],
      correctAnswer: 1,
      explanation: "L1 in-process caches (e.g., a LRU HashMap inside the application) are accessed in nanoseconds - no serialization, no network, no I/O. Redis L2 requires a TCP round-trip (~0.1-1ms). For high-frequency reads of small, stable data (config, feature flags, user roles), L1 is orders of magnitude faster. The trade-off is that L1 caches are per-instance (inconsistency across instances) and limited by heap memory, while Redis is shared and larger.",
      hints: [
        "Memory access: ~100ns. Redis network round-trip: ~500μs. The L1 cache is ~5000 times faster for a cache hit.",
        "L1 works best for rarely-changing data; for user-specific or frequently-updated data, the staleness risk increases.",
      ],
    },
    {
      id: "q-sdi-scale-18",
      type: "multiple-choice",
      difficulty: "medium",
      question: "In the cache-aside (lazy loading) pattern, which sequence correctly describes a cache read?",
      options: [
        "Application writes to cache first, then asynchronously writes to the database.",
        "Application reads from cache; on a miss, reads from the database, then populates the cache and returns the result.",
        "The cache intercepts all database writes and proactively updates itself.",
        "The database writes to the cache on every commit to keep the cache warm.",
      ],
      correctAnswer: 1,
      explanation: "Cache-aside (also called lazy loading) puts the application in control: (1) check cache, (2) on miss: query the DB, (3) write result to cache with a TTL, (4) return result. Future reads hit the cache. Advantages: only requested data is cached, failures are isolated (cache miss just hits DB). Disadvantages: first request after a miss or TTL expiry is slow, and there's a small window of stale data. Write-through (option C/D) is a different pattern where the cache is always updated on write.",
      hints: [
        "Cache-aside is 'lazy' because data is only loaded into the cache when first requested, not proactively.",
        "Compare to read-through: the cache itself fetches from the DB on a miss, transparent to the application.",
      ],
    },
    {
      id: "q-sdi-scale-19",
      type: "multiple-choice",
      difficulty: "hard",
      question: "After deploying a new feature, you invalidate a large portion of the cache. Within seconds, your database CPU spikes to 100% and latency degrades severely. What phenomenon is this, and what are two mitigations?",
      options: [
        "Cache stampede / thundering herd: all clients simultaneously miss the cache and flood the database. Mitigations: mutex/lock-based reconstruction (only one thread fetches, others wait) and probabilistic early expiration.",
        "Cache poisoning: malicious data was injected. Mitigations: input validation and signed cache values.",
        "Write amplification: too many small writes. Mitigations: batch writes and use SSDs.",
        "Connection pool exhaustion: too many DB connections. Mitigations: PgBouncer and connection limits.",
      ],
      correctAnswer: 0,
      explanation: "The thundering herd / cache stampede occurs when many requests simultaneously hit an empty cache (after expiry or invalidation) and all concurrently execute the expensive DB query.\n\n**Step 1:** Diagnose the cause. After a mass invalidation, the cache is empty. If 10,000 requests arrive before any single one finishes repopulating the cache, each independently queries the database — overwhelming it instantly.\n\n**Step 2:** Apply mutex-based reconstruction. Only one thread is permitted to compute and write the cache entry. The other 9,999 threads wait for that thread to finish, then read the result from cache. This guarantees exactly one database query instead of 10,000.\n\n**Step 3:** Use probabilistic early expiration. Rather than waiting for the TTL to expire for all entries simultaneously, some requests slightly ahead of TTL expiry voluntarily recompute the cache. This spreads the refresh load over time and prevents synchronized empty-cache events.",
      hints: [
        "Imagine 10,000 requests all finding an empty cache at the same moment - each independently queries the database.",
        "A mutex ensures only one 'lucky' request rebuilds the cache entry; the other 9,999 wait for it and read from cache.",
      ],
    },
    {
      id: "q-sdi-scale-20",
      type: "multiple-choice",
      difficulty: "medium",
      question: "Which cache invalidation strategy is best suited for a product catalog that changes infrequently but must be fresh within 5 minutes of an update?",
      options: [
        "No TTL - cache entries live forever and are manually invalidated by the operations team.",
        "TTL-based expiration set to 5 minutes - entries automatically expire and are lazily reloaded from the database.",
        "Event-driven invalidation: publish an event when a product changes, cache subscriber invalidates the specific key immediately.",
        "Polling: a background job checks the database every 5 seconds and updates all cache entries.",
      ],
      correctAnswer: 2,
      explanation: "Event-driven invalidation is the most accurate strategy: when a product changes, an event (via a message bus or CDN purge API) invalidates only the affected cache key immediately. This means cache is fresh within seconds, not up to 5 minutes as with TTL. TTL works but has up to 5-minute staleness even for data that changed 1 second after the cache was set. Polling every 5 seconds is expensive and imprecise. No-TTL requires operational intervention and risks perpetually stale data.\n\n**Step 1:** Compare with TTL. A 5-minute TTL means data can be stale for nearly 5 minutes after an update — unacceptable if business rules require near-real-time accuracy.\n\n**Step 2:** Implement event-driven invalidation. When the product service writes an update, it publishes an event. A cache subscriber (or CDN purge call) immediately invalidates the specific cache key. The next request repopulates the cache with the fresh value.\n\n**Step 3:** Recognize the trade-off. Event-driven invalidation requires the application to publish events on every write. TTL is simpler and works when approximate freshness is acceptable.",
      hints: [
        "TTL is a blunt instrument - the cache may be stale for almost the full TTL duration right after an update.",
        "Event-driven invalidation is surgical - it only invalidates what changed, immediately.",
      ],
    },
  ],
  "sdi-scale-async-patterns": [
    {
      id: "q-sdi-scale-21",
      type: "multiple-choice",
      difficulty: "easy",
      question: "Why should image resizing after a user uploads a photo be handled asynchronously rather than synchronously in the HTTP request handler?",
      options: [
        "Asynchronous processing is always faster than synchronous processing.",
        "Image resizing is CPU/I/O intensive and could take seconds; blocking the HTTP response for that duration degrades user experience and ties up server threads.",
        "Asynchronous processing avoids the need for error handling.",
        "Image resizing can only be done asynchronously due to file format constraints.",
      ],
      correctAnswer: 1,
      explanation: "HTTP request handlers should return quickly (under 100ms ideally). CPU-intensive or variable-duration work (resizing, video transcoding, PDF generation, sending emails) should be offloaded to a background worker. The handler accepts the upload, enqueues a job, and immediately returns a 202 Accepted response. The worker processes asynchronously. This frees server threads to handle other requests and provides a better user experience. The user can be notified via webhook, polling, or real-time push when processing completes.",
      hints: [
        "Each blocked server thread cannot serve other requests. If resizing takes 5 seconds, a server with 50 threads can only handle 10 concurrent uploads before new requests queue up.",
        "202 Accepted is the HTTP status code for 'I received your request and will process it asynchronously.'",
      ],
    },
    {
      id: "q-sdi-scale-22",
      type: "multiple-choice",
      difficulty: "medium",
      question: "A third-party payment processor completes transactions asynchronously and needs to notify your system. Which delivery pattern is most appropriate and why?",
      options: [
        "Your system polls the payment processor API every second to check transaction status.",
        "The payment processor sends a webhook (HTTP POST) to your system's callback URL when the transaction completes.",
        "Your system keeps a long-lived TCP connection open to receive real-time events.",
        "The payment processor emails the result to a dedicated inbox your system monitors.",
      ],
      correctAnswer: 1,
      explanation: "Webhooks are the industry standard for async third-party notifications. The processor POSTs to your registered callback URL with the transaction result. This is push-based: no wasted polling requests, low latency (notification arrives as soon as processing completes), and scalable (no persistent connections). Polling every second generates high API load and still has up to 1-second latency. Long-lived TCP connections are complex to manage at scale. Email is unreliable and slow for machine-to-machine communication.",
      hints: [
        "Webhooks invert the call direction: instead of you asking 'are you done?', the processor tells you 'I'm done' when it's ready.",
        "Always validate webhook authenticity using a shared secret or signature header to prevent spoofing.",
      ],
    },
    {
      id: "q-sdi-scale-23",
      type: "true-false",
      difficulty: "medium",
      question: "An idempotent job is one that can be safely executed multiple times with the same input and will produce the same result each time, making it safe to retry on failure.",
      options: ["True", "False"],
      correctAnswer: 0,
      explanation: "Idempotency is a critical property for jobs in distributed systems because networks fail, workers crash, and at-least-once delivery means jobs can be executed more than once. An idempotent job handles this gracefully: sending the same email twice is not idempotent (user receives duplicates), but charging a payment with a unique idempotency key is idempotent (second charge attempt returns the first result without re-charging). Design jobs to be idempotent by using idempotency keys, checking-then-acting patterns, and database upserts.",
      hints: [
        "The mathematical analog: f(f(x)) = f(x). Applying the function twice gives the same result as applying it once.",
        "Idempotency keys are unique tokens per operation stored in the DB - if seen before, return the cached result instead of re-executing.",
      ],
    },
    {
      id: "q-sdi-scale-24",
      type: "multiple-choice",
      difficulty: "hard",
      question: "Your job queue contains a mix of time-sensitive jobs (user-initiated password resets, expiring in 5 minutes) and bulk background jobs (weekly report generation). How should you design the queue system?",
      options: [
        "Use a single queue with FIFO ordering so all jobs are treated fairly.",
        "Use separate queues with different priority levels and dedicated worker pools: high-priority workers exclusively drain the critical queue, lower-priority workers drain the bulk queue.",
        "Sort all jobs by deadline inside the single queue and have workers process in deadline order.",
        "Route critical jobs to a synchronous code path and keep only bulk jobs in the queue.",
      ],
      correctAnswer: 1,
      explanation: "Single FIFO queues let bulk jobs starve critical jobs during bursts. Priority queues with dedicated worker pools solve this: critical workers only consume from the high-priority queue, guaranteeing SLA even when the bulk queue is backed up. Alternative: a single queue with priority numbers, where workers always prefer higher-priority messages. A middle-ground is to allocate X% of workers to bulk and the rest to critical, with overflow capacity. Routing critical jobs synchronously undermines the benefits of async architecture.",
      hints: [
        "If 10,000 bulk report jobs are enqueued and a password reset arrives, a single FIFO queue means the user waits for all 10,000 jobs first.",
        "Dedicated worker pools provide hard isolation guarantees; shared pools with priority provide soft guarantees that depend on load.",
      ],
    },
  ],
  "sdi-scale-data-pipeline": [
    {
      id: "q-sdi-scale-25",
      type: "multiple-choice",
      difficulty: "hard",
      question: "In Lambda Architecture, what are the three layers and what problem does each solve?",
      options: [
        "Load, Analyze, Monitor: for separating ingestion, analysis, and alerting responsibilities.",
        "Speed layer (real-time low-latency processing), Batch layer (high-throughput accurate reprocessing), and Serving layer (merges both for queries).",
        "Lambda, API Gateway, DynamoDB: the AWS serverless stack for event-driven pipelines.",
        "Leader, Follower, Arbiter: the three roles in a distributed stream processing cluster.",
      ],
      correctAnswer: 1,
      explanation: "Lambda Architecture addresses the tension between latency and accuracy. The Speed layer processes incoming events in real-time (e.g., Apache Storm, Spark Streaming) with low latency but approximate results. The Batch layer reprocesses all historical data periodically (e.g., Hadoop MapReduce, Spark) with full accuracy but high latency. The Serving layer merges both: recent data from the speed layer and accurate historical data from batch views. Queries union both. The main drawback is maintaining two separate codebases.",
      hints: [
        "Speed layer: low latency, approximate. Batch layer: high latency, accurate. Serving layer: merges both.",
        "Kappa Architecture is the simplification: eliminate the batch layer and use a replayable stream (Kafka) for both real-time and reprocessing.",
      ],
    },
    {
      id: "q-sdi-scale-26",
      type: "multiple-choice",
      difficulty: "hard",
      question: "In Kappa Architecture, how is the batch layer of Lambda Architecture replaced?",
      options: [
        "By running the stream processing job twice: once for real-time and once for batch.",
        "By using a replayable event log (e.g., Kafka with infinite retention); reprocessing is done by replaying the log through the same stream processing code from the beginning.",
        "By storing all data in a columnar database that supports both streaming and batch queries.",
        "By discarding old data after 24 hours and only processing recent events.",
      ],
      correctAnswer: 1,
      explanation: "Kappa Architecture, proposed by Jay Kreps, simplifies Lambda by using only a streaming system. The key insight is that Kafka (or similar) can retain events indefinitely and allow replay from any offset. When you need to reprocess (e.g., to fix a bug or add a new feature), spin up a new consumer group reading from offset 0, process all historical events through the updated streaming code, and swap the output. This eliminates the two-codebase problem of Lambda while maintaining the ability to recompute from scratch.",
      hints: [
        "Lambda's main drawback is two codebases (batch + streaming) that must produce identical results. Kappa eliminates the batch layer.",
        "The trick is treating the Kafka log as an infinitely replayable source of truth - like an event-sourced log for your data pipeline.",
      ],
    },
    {
      id: "q-sdi-scale-27",
      type: "multiple-choice",
      difficulty: "medium",
      question: "In stream processing, a tumbling window of 1 minute groups events into non-overlapping 1-minute buckets. What is a sliding window and how does it differ?",
      options: [
        "A sliding window is identical to a tumbling window but processes events one at a time.",
        "A sliding window moves forward continuously by a configurable step smaller than its size, so windows overlap and an event can belong to multiple windows.",
        "A sliding window only processes the most recent event, discarding all older events.",
        "A sliding window groups events by a user session rather than by clock time.",
      ],
      correctAnswer: 1,
      explanation: "Tumbling windows: fixed size, no overlap (e.g., 09:00-09:01, 09:01-09:02). Each event belongs to exactly one window. Sliding windows: fixed size but advance by a step < size (e.g., 1-minute window, 10-second step). At 09:00:10, windows 08:59:10-09:00:10 and 09:00:00-09:01:00 both include the event. Sliding windows are used for moving averages, rolling metrics, and detecting patterns that cross bucket boundaries. Session windows are a third type: they group events within a gap-bounded activity session.",
      hints: [
        "Tumbling: no overlap, every second of time belongs to exactly one window. Sliding: overlap means a moment in time belongs to multiple windows.",
        "A 5-minute sliding window with 1-minute step gives you a 'rolling 5-minute average' that updates every minute.",
      ],
    },
    {
      id: "q-sdi-scale-28",
      type: "multiple-choice",
      difficulty: "hard",
      question: "What combination of techniques achieves exactly-once semantics in a Kafka-based stream processing pipeline?",
      options: [
        "At-most-once delivery on the consumer plus idempotent writes to the output.",
        "Idempotent producers (to avoid duplicate writes to Kafka) combined with idempotent consumers (to handle replayed messages) and Kafka transactions (to atomically commit the output write and the consumer offset).",
        "Setting Kafka replication factor to 3, which guarantees exactly-once delivery automatically.",
        "Using a separate deduplication service that tracks all message IDs and filters duplicates before processing.",
      ],
      correctAnswer: 1,
      explanation: "Exactly-once in Kafka requires three components working together: (1) Idempotent producers: Kafka assigns sequence numbers to detect and deduplicate retried writes at the broker level. (2) Kafka transactions: allow atomically writing output records and committing consumer offsets in a single transaction - if either fails, both roll back, preventing partial state. (3) Idempotent/transactional consumers: read committed offsets only. Together, these ensure each input event produces its output exactly once even under failures. High replication alone provides durability, not exactly-once semantics.",
      hints: [
        "At-least-once + idempotent consumers = effectively exactly-once. But Kafka transactions provide atomicity between the output write and offset commit.",
        "The problem without transactions: write output, crash before committing offset, replay event, write output again = duplicate output.",
      ],
    },
  ],
  "sdi-scale-observability": [
    {
      id: "q-sdi-scale-29",
      type: "multiple-choice",
      difficulty: "easy",
      question: "What is the correct hierarchy of SLI, SLO, and SLA in site reliability engineering?",
      options: [
        "SLA is the internal metric, SLO is the internal target, SLI is the contractual commitment with customers.",
        "SLI (Service Level Indicator) is the measured metric; SLO (Service Level Objective) is the internal target for that metric; SLA (Service Level Agreement) is the contractual commitment to customers, often with financial penalties for breach.",
        "SLI and SLO are synonymous; SLA is the subset of SLOs that apply to paid customers.",
        "SLA is set first by the business, SLO is derived from the SLA, and SLI measures whether SLO is met.",
      ],
      correctAnswer: 1,
      explanation: "SLI: the raw measurement (e.g., 'fraction of HTTP requests returning 2xx within 200ms'). SLO: the target for that SLI (e.g., 'SLI >= 99.9% over a 30-day window'). SLA: the legal contract with customers that specifies consequences (credits, refunds) if SLOs are not met. SLOs are typically set more conservatively than SLAs to maintain an error budget - if you breach your internal SLO, you have time to fix before breaching the customer-facing SLA.",
      hints: [
        "SLI = what you measure. SLO = what you promise internally. SLA = what you promise legally (with teeth).",
        "Google's SRE book describes keeping SLOs tighter than SLAs so that an SLO breach is a warning, not yet a contractual failure.",
      ],
    },
    {
      id: "q-sdi-scale-30",
      type: "multiple-choice",
      difficulty: "medium",
      question: "When diagnosing a slow database server, you apply the USE method. What do Utilization, Saturation, and Errors measure in this context?",
      options: [
        "Utilization: CPU usage; Saturation: memory swap usage; Errors: application 5xx errors.",
        "Utilization: how busy the resource is as a percentage of capacity; Saturation: how much work is queued waiting for the resource; Errors: the rate of resource-level errors such as disk I/O errors or TCP retransmits.",
        "Utilization: request rate; Saturation: cache hit ratio; Errors: number of failed deployments.",
        "USE is the same as the RED method - Rate, Errors, Duration - just applied to infrastructure.",
      ],
      correctAnswer: 1,
      explanation: "The USE method, by Brendan Gregg, is for diagnosing infrastructure resource bottlenecks. For a database server: Utilization = CPU%, disk I/O%, network bandwidth% used. Saturation = run queue length (CPU), I/O wait queue depth, memory paging rate - work waiting because the resource is fully utilized. Errors = hardware errors, disk errors, network packet drops. The RED method (Rate, Errors, Duration) is complementary but applies to services/microservices, not hardware resources.",
      hints: [
        "USE starts with the hardware layer: CPUs, disks, memory, network interfaces. RED starts with the service layer: request throughput and latency.",
        "High Utilization + high Saturation = the resource is a bottleneck. High Utilization alone may be acceptable if no queue is forming.",
      ],
    },
    {
      id: "q-sdi-scale-31",
      type: "multiple-choice",
      difficulty: "medium",
      question: "You are monitoring a microservice using the RED method. Rate is high, Errors are low, but Duration (p99 latency) is slowly increasing day over day. What does this indicate and what should you investigate first?",
      options: [
        "The service is healthy - high rate with low errors means everything is working.",
        "A gradual resource leak or accumulating technical debt: investigate memory growth, database query plan degradation, growing queue depths, or slow index bloat.",
        "The load balancer is misconfigured and routing unequal traffic to instances.",
        "p99 latency increasing means the SLA is already breached and the incident should be declared immediately.",
      ],
      correctAnswer: 1,
      explanation: "Gradual p99 latency increase with stable rate and low error rate is a classic signal of a slow resource leak or accumulation: memory leak causing GC pressure, database table bloat slowing queries, growing job queue depth, index fragmentation, or connection pool near exhaustion. This is often a canary for a future outage - the system works but is degrading. Investigate: memory trends (heap, GC pause times), DB query plans (EXPLAIN), queue depths, and connection pool metrics. Proactive fixes prevent the eventual incident.",
      hints: [
        "If p99 grows while p50 stays flat, the tail is getting worse - often a sign of resource contention or background work interfering.",
        "Set SLO alerts on p99 trends, not just static thresholds - a monotonically increasing p99 is an anomaly even if it hasn't crossed the threshold yet.",
      ],
    },
  ],
  "sdi-scale-capacity-planning": [
    {
      id: "q-sdi-scale-32",
      type: "multiple-choice",
      difficulty: "medium",
      question: "A service has 1 million users, each making 10 requests per day on average. What is the average requests per second (RPS), and what peak RPS should you plan for assuming an 8-hour peak window with 3 times peak-to-average ratio?",
      options: [
        "Average: 116 RPS; Peak: ~348 RPS (plan for ~400 RPS with headroom).",
        "Average: 10 RPS; Peak: 30 RPS.",
        "Average: 1,000 RPS; Peak: 3,000 RPS.",
        "Average: 11.6 RPS; Peak: 34.8 RPS.",
      ],
      correctAnswer: 0,
      explanation: "This back-of-envelope calculation converts daily request volume to per-second throughput and then applies a peak multiplier.\n\n**Step 1:** Convert daily requests to average RPS.\n\n\\[\n1{,}000{,}000 \\text{ users} \\cdot 10 \\frac{\\text{requests}}{\\text{user} \\cdot \\text{day}} = 10{,}000{,}000 \\frac{\\text{requests}}{\\text{day}}\n\\]\n\n\\[\n\\frac{10{,}000{,}000}{86{,}400 \\text{ seconds/day}} \\approx 115.7 \\text{ RPS (average)}\n\\]\n\n**Step 2:** Apply the peak multiplier. If traffic during the 8-hour peak window is 3 times the daily average:\n\n\\[\n115.7 \\text{ RPS} \\times 3 \\approx 347 \\text{ RPS (peak)}\n\\]\n\n**Step 3:** Add headroom. Plan for 400–500 RPS to absorb variability above the modeled peak.",
      hints: [
        "Seconds in a day: 60 * 60 * 24 = 86,400. Memorize this for estimation interviews.",
        "Peak multiplier depends on usage patterns — consumer apps often see 5–10 times daily peak vs trough; enterprise apps may be flatter.",
      ],
    },
    {
      id: "q-sdi-scale-33",
      type: "multiple-choice",
      difficulty: "easy",
      question: "A social network stores a user profile with an average size of 2KB. With 10 million users, how much storage is required for profiles alone?",
      options: [
        "20 GB",
        "200 GB",
        "2 TB",
        "20 TB",
      ],
      correctAnswer: 0,
      explanation: "This back-of-envelope calculation converts user count and per-user size to total storage.\n\n**Step 1:** Calculate raw storage.\n\n\\[\n10{,}000{,}000 \\text{ users} \\cdot 2 \\text{ KB/user} = 20{,}000{,}000 \\text{ KB} = 20{,}000 \\text{ MB} = 20 \\text{ GB}\n\\]\n\nThis is surprisingly small — a single commodity server has 1–8 TB of SSD storage, so 20 GB fits easily on one node.\n\n**Step 2:** Apply replication and overhead. With a 3\\times replication factor and indexes, the total grows to approximately 60 GB — still well within a single server's capacity.\n\n**Step 3:** Stress-test your assumptions. If each profile also stores a 1 MB profile photo, the same calculation yields 10 TB, which decidedly requires distributed storage. Always clarify what data is included in the 'profile' estimate.",
      hints: [
        "1KB = 1,000 bytes. 1MB = 1,000KB. 1GB = 1,000MB. 1TB = 1,000GB. Build a mental ladder for quick estimation.",
        "Always state your assumptions: what is a 'profile'? Text only or including profile photos? The answer changes by 500 times.",
      ],
    },
    {
      id: "q-sdi-scale-34",
      type: "multiple-choice",
      difficulty: "medium",
      question: "A product has 50 million monthly active users (MAU). Which is the most accurate estimate of daily active users (DAU) for capacity planning, and what does the DAU/MAU ratio signify?",
      options: [
        "DAU = MAU / 30 \approx 1.67M; assumes users are perfectly evenly distributed across days with no engagement patterns.",
        "DAU = MAU * DAU/MAU ratio, where the ratio reflects engagement (e.g., 0.5 for highly engaging apps like Facebook, 0.1 for low-engagement apps); for a 0.2 ratio, DAU \\approx 10M.",
        "DAU = MAU because all monthly active users are also daily active users.",
        "DAU cannot be estimated from MAU without real traffic data.",
      ],
      correctAnswer: 1,
      explanation: "The DAU/MAU ratio (also called the 'stickiness ratio') measures how often monthly users return daily. Highly engaging social apps (Facebook, TikTok) achieve 0.5–0.65 (50–65% of MAU are active on any given day). Moderate apps: 0.2–0.3. Low-engagement apps: 0.05–0.1. MAU/30 assumes uniform distribution and a ratio of approximately 0.033, drastically underestimating daily load for sticky apps.\n\n**Step 1:** Apply the correct formula. DAU = MAU \\times DAU/MAU ratio. For 50 million MAU with DAU/MAU = 0.2:\n\n\\[\n\\text{DAU} = 50{,}000{,}000 \\times 0.2 = 10{,}000{,}000 \\text{ users/day}\n\\]\n\n**Step 2:** Recognize the magnitude of error. Using MAU/30 gives 1.67 M — a 6\\times underestimate compared with DAU/MAU = 0.2. This leads to drastically under-provisioned infrastructure.\n\n**Step 3:** Use benchmarks. Compare your app's engagement category to industry ratios rather than assuming uniform distribution.",
      hints: [
        "If MAU = 50M and DAU/MAU = 0.5 (Facebook-like), then DAU = 25M. MAU/30 gives 1.67M — a 15 times underestimate.",
        "DAU/MAU is also a key investor metric: above 0.5 is considered excellent engagement for a consumer app.",
      ],
    },
  ],
};

registerQuestions(questions);
