import type { Question } from "@/lib/curriculum";
import { registerQuestions } from "./registry";

const questions: Record<string, Question[]> = {
  "sdi-social-feed": [
    {
      id: "q-sdi-soc-1",
      type: "multiple-choice",
      difficulty: "hard",
      question: "A social platform has mostly regular users (<1K followers) but 0.1% are celebrities with 10M+ followers. Fan-out-on-write delivers posts to all followers' feeds at write time. What problem arises for celebrities and what is the standard mitigation?",
      options: [
        "Read latency spikes for celebrities; solved by adding more read replicas.",
        "Write amplification: a single celebrity post triggers 10M+ feed insertions, overwhelming the write path; mitigated by using fan-out-on-read for accounts above a follower threshold (~10K) while keeping fan-out-on-write for normal users.",
        "Celebrities have duplicate posts in feeds; solved by deduplication at read time.",
        "Fan-out-on-write has no celebrity problem; the issue only affects fan-out-on-read systems.",
      ],
      correctAnswer: 1,
      explanation: "Fan-out-on-write precomputes feeds by writing to every follower's timeline at post time. For a user with 10M followers, one post generates 10M writes, causing severe write amplification and hotspot pressure. The hybrid approach applies fan-out-on-write only to accounts below a follower threshold (e.g., 10K) and fan-out-on-read for celebrities — merging the celebrity's posts at read time from a separate celebrity feed store. Twitter/X and Instagram both use this hybrid model.",
      hints: [
        "Think about how many DB writes occur when a user with 10M followers posts once — who bears that cost?",
        "The fix separates the population into 'regular users' (precompute) and 'celebrities' (compute at read time).",
      ],
    },
    {
      id: "q-sdi-soc-2",
      type: "multiple-choice",
      difficulty: "medium",
      question: "Redis sorted sets are used to store a user's timeline cache. What is stored as the score and what is stored as the member, and why does this choice enable efficient pagination?",
      options: [
        "Score = post_id (integer), member = JSON blob; enables range scans by post ID.",
        "Score = Unix timestamp of the post, member = post_id; ZREVRANGEBYSCORE returns posts in reverse-chronological order in O(log N + M) and cursor pagination uses the last seen timestamp as the score bound.",
        "Score = engagement score, member = post_id; enables ranking by popularity.",
        "Score = user_id of the author, member = post_id; enables grouping posts by author.",
      ],
      correctAnswer: 1,
      explanation: "A Redis sorted set with score=Unix timestamp and member=post_id lets the system call ZREVRANGEBYSCORE to fetch the most recent N posts before a given timestamp cursor. This is O(log N + M) where M is the page size. Cursor-based pagination using timestamps avoids the 'page drift' problem of offset pagination (where new posts shift all offsets) and works naturally with time-ordered feeds. The post payloads are fetched separately from a post store using the returned post_ids.",
      hints: [
        "Redis sorted sets are ordered by score — what ordering property does a feed need?",
        "Cursor pagination needs a stable 'position marker' — timestamps provide that without re-indexing on new writes.",
      ],
    },
    {
      id: "q-sdi-soc-3",
      type: "true-false",
      difficulty: "easy",
      question: "Fan-out-on-read (pull model) always provides lower read latency than fan-out-on-write (push model) because it avoids precomputation overhead.",
      options: ["True", "False"],
      correctAnswer: 1,
      explanation: "Fan-out-on-read actually has higher read latency because the feed must be assembled at request time by querying all accounts the user follows, then merging and ranking the results. Fan-out-on-write has lower read latency because the feed is precomputed and stored, making a read just a sequential scan of the user's timeline. The tradeoff is write amplification (fan-out-on-write) vs. read amplification (fan-out-on-read).",
      hints: [
        "With fan-out-on-read, how many DB queries does loading a feed require if a user follows 500 accounts?",
        "With fan-out-on-write, what does reading a feed require — just one lookup or many?",
      ],
    },
    {
      id: "q-sdi-soc-4",
      type: "multiple-choice",
      difficulty: "medium",
      question: "A product team wants to switch the home feed from reverse-chronological ordering to engagement-ranked ordering. What is the key systems challenge this introduces beyond changing the ranking function?",
      options: [
        "Engagement-ranked feeds require more storage than chronological feeds.",
        "Engagement ranking requires near-real-time engagement signals (likes, comments, shares) that must be fetched or cached alongside post data; the feed can no longer be a static sorted list by timestamp — it must be periodically re-ranked or signals must be joined at read time, increasing latency and complexity.",
        "Engagement ranking is computationally impossible to implement at scale.",
        "Engagement-ranked feeds cannot use cursor-based pagination.",
      ],
      correctAnswer: 1,
      explanation: "A chronological feed is a simple reverse-sorted list that is stable once written. An engagement-ranked feed requires continuously updated engagement signals (like counts, comment counts, share counts, recency decay) per post. These signals change after the feed is written, invalidating static precomputed feeds. Solutions include: (1) periodic background re-ranking of cached feeds, (2) lightweight re-ranking at read time using cached engagement counters, or (3) a dedicated ranking service that scores candidates at request time. Each approach has latency, freshness, and cost tradeoffs.",
      hints: [
        "A post's engagement score at write time vs. 1 hour later can differ dramatically — how does the system reflect this?",
        "What extra data does the ranking function need that a timestamp-sort does not?",
      ],
    },
    {
      id: "q-sdi-soc-5",
      type: "multiple-choice",
      difficulty: "hard",
      question: "Why does offset-based pagination (LIMIT 20 OFFSET 100) cause a 'page drift' problem for social feeds, and how does cursor-based pagination with timestamps solve it?",
      options: [
        "Offset pagination is slower because SQL OFFSET requires scanning all skipped rows; cursor pagination avoids this scan.",
        "Offset pagination causes page drift because new posts inserted at the top shift all row positions — a user who fetched page 1 then page 2 may see duplicates or miss posts. Cursor pagination uses the last seen post's timestamp as the exclusive upper bound for the next query (WHERE created_at < :cursor), so new posts do not shift existing positions.",
        "Cursor pagination uses less memory than offset pagination at the database layer.",
        "Offset pagination only works for chronological feeds; cursor pagination only works for ranked feeds.",
      ],
      correctAnswer: 1,
      explanation: "With OFFSET-based pagination, the database skips the first N rows to return page K. If new posts are written between page fetches, they push all existing rows down — the user sees duplicates (a row that was at position 19 moves to position 21, appearing on both page 1 and page 2) or skips posts. Cursor pagination encodes position as a value (timestamp or ID) rather than a row count. The query WHERE created_at < :last_seen_timestamp is unaffected by new inserts at the head of the feed, giving stable pagination. This is why all major social APIs use cursor/token-based pagination.",
      hints: [
        "Imagine 5 new posts arrive between fetching page 1 and page 2 — what happens to the OFFSET boundary?",
        "A WHERE clause on a column value vs. OFFSET N — which is affected by concurrent inserts?",
      ],
    },
  ],
  "sdi-social-graph": [
    {
      id: "q-sdi-soc-6",
      type: "multiple-choice",
      difficulty: "medium",
      question: "When designing social graph storage, what is the key advantage of a dedicated graph database (e.g., Neo4j) over an edge table in a relational database for traversal queries?",
      options: [
        "Graph databases store more data per node than relational databases.",
        "Graph databases use index-free adjacency — each node directly references its neighbors in memory, so multi-hop traversals (e.g., 'friends of friends') follow pointers in O(1) per hop rather than performing repeated index lookups or JOIN operations that scale with total graph size.",
        "Graph databases automatically shard across machines without any configuration.",
        "Relational edge tables cannot represent directed graphs.",
      ],
      correctAnswer: 1,
      explanation: "In a relational edge table (user_id, friend_id), a 2-hop query requires two JOIN operations, each scanning an index proportional to the graph size. In a graph database using index-free adjacency, each node stores direct pointers to its neighbor nodes — traversal follows pointers in memory, making hop cost proportional to the local neighborhood size rather than total graph size. For deep traversals at scale, this difference is significant. However, relational edge tables are simpler operationally and sufficient for 1-hop lookups (direct friends/followers), which is why many social platforms use SQL edge tables with graph DBs reserved for analytics.",
      hints: [
        "In SQL, how does a 3-hop friend query differ from a 1-hop query in terms of JOIN operations?",
        "'Index-free adjacency' means node A knows exactly where node B lives in memory — no index lookup needed.",
      ],
    },
    {
      id: "q-sdi-soc-7",
      type: "multiple-choice",
      difficulty: "easy",
      question: "Twitter uses directed follows (A follows B without B following A). Facebook uses undirected friendship (mutual consent required). How does this architectural difference affect the edge table schema?",
      options: [
        "Directed follows require two rows per relationship (A->B and B->A); undirected friendship requires one row.",
        "Directed follows require one row per relationship (follower_id, followee_id); undirected friendship can use one row (user_a_id, user_b_id with user_a_id < user_b_id) or two rows for bidirectional lookup, plus a pending/accepted status column for the consent workflow.",
        "There is no schema difference; both models use the same edge table.",
        "Undirected friendship requires a graph database; directed follows can use a relational table.",
      ],
      correctAnswer: 1,
      explanation: "A directed follow is a single directed edge: (follower_id, followee_id). To fetch 'who does user A follow' and 'who follows user A', you index both columns. Undirected friendship can be stored as one canonical row (min_id, max_id) with a status enum (pending, accepted), or as two rows for O(1) bidirectional lookup. The mutual consent workflow requires a state machine (request sent -> accepted/rejected), which directed follow systems do not need. This affects both schema design and the application logic for connection management.",
      hints: [
        "For directed follows, what query fetches followers vs. followees — are they symmetric?",
        "For friendship requests, what states does the relationship transition through before becoming active?",
      ],
    },
    {
      id: "q-sdi-soc-8",
      type: "multiple-choice",
      difficulty: "hard",
      question: "A 'people you may know' feature requires finding friends-of-friends (2-hop traversal). At Facebook scale (3B users, avg 200 friends), why is real-time 2-hop traversal infeasible and what is the standard precomputation approach?",
      options: [
        "2-hop traversal is feasible in real time with enough read replicas.",
        "A 2-hop traversal for one user visits up to 200 * 200 = 40K nodes, each requiring a graph lookup, resulting in tens of thousands of random reads per request. At scale this is too slow and too expensive per query. The standard approach is offline precomputation: periodically run batch graph jobs (Hadoop/Spark) to compute and store friend-of-friend candidate sets per user in a key-value store, then serve suggestions from the precomputed store.",
        "2-hop traversal only works with directed graphs, not undirected friendship graphs.",
        "Precomputation is not used; instead, approximate nearest-neighbor algorithms are applied to user embeddings.",
      ],
      correctAnswer: 1,
      explanation: "For a user with 200 friends, each with 200 friends, a naive 2-hop traversal visits up to 40,000 nodes. Each node lookup is a DB read. At millions of simultaneous users, this creates enormous read load. Offline precomputation using Hadoop/Spark graph processing (or specialized systems like LinkedIn's PYMK pipeline) computes friend-of-friend sets in batch and materializes them in a key-value store. The online serving path is then a single key lookup. LinkedIn's 'People You May Know' and Facebook's friend suggestions both use this architecture.",
      hints: [
        "How many DB reads does a 2-hop traversal require for a user with 200 friends who each have 200 friends?",
        "If you precompute the answer nightly and store it, what does the real-time serving path look like?",
      ],
    },
    {
      id: "q-sdi-soc-9",
      type: "multiple-choice",
      difficulty: "hard",
      question: "A social graph is sharded by user_id across 100 database shards. User A (shard 7) sends a friend request to User B (shard 43). What is the fundamental challenge and how is it typically handled?",
      options: [
        "The friend request cannot be stored because A and B are on different shards.",
        "Writing the friendship edge requires a cross-shard transaction (A's edge on shard 7, B's edge on shard 43). True distributed transactions (2PC) are expensive and reduce availability. Instead, the edge is written to both shards asynchronously — one shard is primary, and the second write is retried until consistent, accepting brief inconsistency or using an event queue for eventual consistency.",
        "Sharding by user_id is incompatible with social graph storage — user_id sharding must never be used.",
        "The system automatically routes both writes to the same shard using consistent hashing.",
      ],
      correctAnswer: 1,
      explanation: "Social graph edges between users on different shards require cross-shard writes. Two-phase commit (2PC) ensures atomicity but is slow and reduces availability. Most social platforms accept eventual consistency: write the canonical edge to one shard (e.g., the lower user_id's shard) and enqueue an async job to replicate the reverse edge to the other shard. If the async write fails, a retry queue ensures it eventually completes. Reads for 'who are my friends' hit the user's own shard; reads for 'do A and B have a connection' may need to check one canonical shard. This eventual consistency tradeoff is standard in large-scale social graph systems.",
      hints: [
        "What are the ACID properties you sacrifice when you replace 2PC with async replication?",
        "If A's shard writes the edge successfully but B's shard write fails, what does a user on B's side see?",
      ],
    },
  ],
  "sdi-social-search": [
    {
      id: "q-sdi-soc-10",
      type: "multiple-choice",
      difficulty: "medium",
      question: "A social platform wants to implement people search with full-text matching on names and bios. Why is Elasticsearch preferred over a standard SQL LIKE query for this use case?",
      options: [
        "Elasticsearch stores data in memory, making it faster than disk-based SQL.",
        "SQL LIKE '%john%' requires a full table scan (cannot use B-tree indexes for leading wildcards) and does not support fuzzy matching, stemming, or relevance ranking. Elasticsearch uses inverted indexes for O(1) term lookup, supports n-gram tokenization for partial matches, fuzzy matching for typos, and scores results by TF-IDF or BM25 relevance — critical for ranking millions of profiles.",
        "SQL databases cannot store text fields with more than 255 characters.",
        "Elasticsearch automatically scales to multiple nodes while SQL cannot.",
      ],
      correctAnswer: 1,
      explanation: "SQL LIKE with a leading wildcard ('%john%') cannot leverage B-tree indexes and performs a sequential scan across all rows — O(N) with N being the number of users. At 100M users this is unusable. Elasticsearch maintains an inverted index mapping each token to the list of documents containing it, enabling O(log N) term lookups. It also supports: n-gram tokenization (for prefix/infix matching), fuzzy matching (Levenshtein distance for typos), field boosting (name match weighted higher than bio match), and BM25 relevance scoring. These capabilities make it the standard choice for social search.",
      hints: [
        "What index structure does SQL use for equality lookups vs. what Elasticsearch uses for text search?",
        "How does SQL handle 'find users whose name sounds like John' — does it have built-in support?",
      ],
    },
    {
      id: "q-sdi-soc-11",
      type: "multiple-choice",
      difficulty: "medium",
      question: "A username typeahead feature must return results within 100ms as a user types each character. What data structure and storage choice is optimal for prefix matching on usernames at scale?",
      options: [
        "A full Elasticsearch cluster with full-text search on each keystroke.",
        "A trie (prefix tree) stored in Redis: each node represents a character prefix and stores the top-K matching usernames by popularity score. Prefix lookup traverses the trie in O(L) where L is the query length, and Redis's in-memory speed delivers sub-millisecond lookup, easily meeting the 100ms budget even with network latency.",
        "A SQL table with a B-tree index on username and a LIKE 'prefix%' query.",
        "A hash map from every possible prefix to a list of matching usernames, stored in application memory.",
      ],
      correctAnswer: 1,
      explanation: "Typeahead requires sub-100ms latency per keystroke at high query volume. A trie is the canonical data structure: O(L) lookup where L is the prefix length, regardless of the number of stored usernames. Storing the trie in Redis (as a sorted set per prefix with score=popularity, or using a Redis module) provides in-memory speed. SQL LIKE 'prefix%' can use a B-tree index for left-anchored prefixes and is viable at smaller scale, but a Redis trie scales better and is more operationally predictable. Elasticsearch with prefix queries is also used but is heavier than a Redis trie for pure prefix matching.",
      hints: [
        "A trie nodes are character prefixes — how many nodes do you visit to find all usernames starting with 'joh'?",
        "Why is an in-memory store like Redis preferred over a disk-based store for sub-100ms typeahead?",
      ],
    },
    {
      id: "q-sdi-soc-12",
      type: "multiple-choice",
      difficulty: "hard",
      question: "When ranking people search results, a social platform boosts accounts that are mutual friends with the searcher. What system component computes and provides this mutual-friend signal, and what is the latency challenge?",
      options: [
        "The search index directly computes mutual friends during query time by scanning the full friend list.",
        "A separate graph service or precomputed friend-of-friend store provides the mutual-friend count per (searcher, candidate) pair. The challenge is that the search query returns hundreds of candidates and the system must look up mutual-friend counts for each in parallel; these lookups add latency. The signal is often precomputed offline or approximated using bloom filter intersection of friend sets.",
        "Mutual-friend boosting is applied only after the user scrolls past the initial results to avoid latency.",
        "Elasticsearch natively supports graph traversal to compute mutual friends during indexing.",
      ],
      correctAnswer: 1,
      explanation: "Mutual-friend count is a graph property that cannot be computed from the search index alone — it requires knowing both the searcher's friend set and the candidate's friend set, then computing their intersection. At query time with 100+ candidates, doing this in real time is expensive. Solutions: (1) Precompute and store friend-of-friend counts in a key-value store (batch updated), (2) Cache the searcher's friend set in memory and use bloom filters for fast approximate intersection, (3) Use a dedicated graph service that answers 'how many mutual friends do A and B have?' with low latency. The signal is then merged with the search score using a weighted ranking formula.",
      hints: [
        "After Elasticsearch returns 100 candidate profiles, how do you efficiently add mutual-friend scores to each?",
        "If precomputing mutual friends for all pairs is infeasible, what approximation can you use at query time?",
      ],
    },
    {
      id: "q-sdi-soc-13",
      type: "true-false",
      difficulty: "medium",
      question: "In a social search system, index rebuild latency (the delay between a user updating their profile and the change appearing in search results) is typically acceptable to be several hours because user profile changes are infrequent.",
      options: ["True", "False"],
      correctAnswer: 1,
      explanation: "While profile changes are less frequent than posts, several hours of latency is not acceptable for key fields. If a user changes their username or deactivates their account, stale search results for hours cause user confusion and potential privacy issues. Production social search systems use near-real-time indexing: profile update events are published to a message queue (Kafka), consumed by an indexing service, and pushed to Elasticsearch within seconds to minutes. Full re-index is only used for schema migrations; incremental updates handle routine changes with low latency.",
      hints: [
        "What happens if a user deactivates their account but still appears in search results for 6 hours?",
        "How do change data capture (CDC) systems and Kafka help propagate profile updates to the search index quickly?",
      ],
    },
  ],
  "sdi-social-reactions": [
    {
      id: "q-sdi-soc-14",
      type: "multiple-choice",
      difficulty: "medium",
      question: "A social platform stores a like count for each post in a SQL table (posts.like_count INTEGER). Users like posts concurrently. What SQL operation ensures the counter is incremented correctly under concurrent writes, and what problem does naive read-modify-write create?",
      options: [
        "Use SELECT then UPDATE in a transaction; this is always correct because transactions serialize all access.",
        "Use UPDATE posts SET like_count = like_count + 1 WHERE post_id = :id (atomic INCREMENT at the DB layer). Naive read-modify-write (SELECT count, then UPDATE count = old_count + 1) causes lost updates under concurrency: two concurrent readers both read count=5, both write count=6, losing one increment. DB-level atomic increment holds a row lock for the duration of the operation, preventing this.",
        "Store like counts in application memory and flush to the database periodically.",
        "Use a queue to serialize all like operations through a single writer thread.",
      ],
      correctAnswer: 1,
      explanation: "The atomic UPDATE posts SET like_count = like_count + 1 evaluates the increment within the database engine under row-level locking, ensuring no two transactions see the same value and both write the same result. The read-modify-write pattern (SELECT count; UPDATE count = count+1) has a TOCTOU (time-of-check to time-of-use) race condition: both transactions read the same stale value and write identical results, losing one increment. This is the classic lost-update problem, and atomic DB-level increments (or Redis INCR) are the standard fix.",
      hints: [
        "Two concurrent transactions both read like_count=5 and both try to write like_count=6 — what is the final count?",
        "What does the database guarantee when you write the increment inside the UPDATE expression vs. in application code?",
      ],
    },
    {
      id: "q-sdi-soc-15",
      type: "multiple-choice",
      difficulty: "hard",
      question: "A viral post receives 100K likes per minute. Updating the like_count column in the posts table for every like causes a write hotspot on that row. What are two architectural strategies to mitigate this?",
      options: [
        "Use database read replicas and cache the like count on CDN edge nodes.",
        "Strategy 1 — Redis counter: route all like increments to a Redis INCR on a key per post (Redis handles 100K+ ops/sec on a single key); periodically flush the Redis count back to the SQL table asynchronously. Strategy 2 — Counter sharding: maintain N counter shards per post (post_likes_shard_0..N), distribute writes across shards, and sum shards at read time to get the total, reducing per-shard write rate by N*.",
        "Partition the posts table by post_id to distribute the hot row across shards.",
        "Rate-limit likes to 1 per user per second to reduce write volume.",
      ],
      correctAnswer: 1,
      explanation: "A single SQL row being updated 100K times/minute is a write hotspot — row-level locking creates contention. Redis INCR is atomic, in-memory, and can handle millions of operations per second on a single key, making it ideal for high-throughput counters. The count is periodically persisted to SQL for durability. Counter sharding splits the counter across N rows/keys, writes go to a randomly chosen shard, and reads aggregate all shards — this reduces contention by N* at the cost of a fan-out read. Both strategies are used in production; Redis counters are more common due to simplicity.",
      hints: [
        "What is the bottleneck when 100K writes/min all target the same DB row with row-level locking?",
        "How does Redis INCR differ from a SQL atomic increment in terms of throughput characteristics?",
      ],
    },
    {
      id: "q-sdi-soc-16",
      type: "multiple-choice",
      difficulty: "hard",
      question: "A feature requires showing whether the current user has liked a specific post ('has user X liked post Y?'). At 1B users and 100B posts, a full table scan is infeasible. What data structure provides a fast negative lookup with probabilistic guarantees?",
      options: [
        "A B-tree index on (user_id, post_id) in the likes table; index lookup is O(log N).",
        "A Bloom filter per post: when user X likes post Y, add user_id to post Y's bloom filter. A negative result (user NOT in filter) is 100% accurate — fast definitive 'not liked' answer. A positive result may be a false positive, requiring a confirmatory DB lookup. This eliminates most DB lookups since the majority of (user, post) pairs are NOT likes.",
        "A hash table mapping user_id to all liked post_ids, stored in application memory.",
        "Cache the last 1000 likes per post in Redis and fall back to DB for older likes.",
      ],
      correctAnswer: 1,
      explanation: "A Bloom filter is a space-efficient probabilistic data structure that answers set membership queries. It has zero false negatives (if the filter says 'not present', the element is definitely not in the set) and a configurable false positive rate. For the 'has user X liked post Y?' query, the vast majority of answers are 'no' (most users haven't liked any given post). The Bloom filter answers these definitively in O(k) hash operations without a DB lookup. Only when the filter says 'yes' (potentially a false positive) does the system make a confirmatory DB read. This dramatically reduces DB load. A B-tree index (option A) is also valid and simpler; Bloom filters provide additional savings when memory is cheaper than DB IOPS.",
      hints: [
        "Bloom filters guarantee no false negatives — what does this mean for the 'not liked' case?",
        "If 99% of (user, post) pairs are 'not liked', how much DB load does a Bloom filter with 1% false positive rate save?",
      ],
    },
    {
      id: "q-sdi-soc-17",
      type: "multiple-choice",
      difficulty: "medium",
      question: "A social platform needs to count unique users who have reacted to a post for analytics (deduplicating the same user reacting multiple times). The post has 50M reactions from 30M unique users. Which data structure provides an approximate unique count in O(1) space with ~1% error?",
      options: [
        "A HashSet storing all user_ids; exact count but O(N) space proportional to unique users.",
        "HyperLogLog: a probabilistic cardinality estimation algorithm that counts distinct elements using O(log log N) space (~12KB for any cardinality) with ~0.81% standard error. Redis implements HyperLogLog natively (PFADD/PFCOUNT). For analytics where approximate counts are acceptable, this trades ~1% accuracy for a 10,000* reduction in memory vs. a HashSet.",
        "A Bloom filter per post storing all user_ids; supports cardinality estimation natively.",
        "Count-min sketch: approximates frequency of elements and can derive unique count.",
      ],
      correctAnswer: 1,
      explanation: "HyperLogLog (HLL) is the standard algorithm for approximate cardinality estimation. It uses clever hashing and leading-zero counting to estimate the number of distinct elements with ~0.81% error using only ~12KB of memory regardless of cardinality. Redis's PFADD/PFCOUNT commands implement HLL natively. For a post with 50M reactions from 30M unique users, a HashSet would require ~240MB (30M * 8 bytes per user_id); HLL uses 12KB — a 20,000* reduction. For analytics dashboards where '~30M unique reactors' is sufficient (vs. exact 30,001,234), HLL is the industry standard. LinkedIn, Twitter, and Facebook all use HLL for unique-count analytics.",
      hints: [
        "How much memory does storing 30M user_ids in a HashSet require vs. HyperLogLog's fixed 12KB?",
        "What Redis commands implement HyperLogLog, and what is the tradeoff in answer accuracy?",
      ],
    },
  ],
  "sdi-social-stories": [
    {
      id: "q-sdi-soc-18",
      type: "multiple-choice",
      difficulty: "medium",
      question: "Instagram Stories disappear after 24 hours. How does Cassandra's TTL feature implement this deletion automatically, and what is the advantage over application-level deletion jobs?",
      options: [
        "Cassandra runs a daily cron job that scans all story rows and deletes expired ones.",
        "Cassandra supports per-row or per-column TTL: when a story is written, the TTL is set to 86400 seconds. Cassandra marks the data with a tombstone at expiry and the compaction process physically removes it. No application code is needed — deletion is guaranteed by the storage engine even if the application crashes, and there is no separate deletion job to maintain or monitor.",
        "Application code must query all stories older than 24 hours and issue DELETE statements on a schedule.",
        "Stories are not actually deleted — they are hidden by a flag column that the application checks at read time.",
      ],
      correctAnswer: 1,
      explanation: "Cassandra's TTL mechanism is a first-class storage feature: INSERT INTO stories (...) VALUES (...) USING TTL 86400. After 86400 seconds, Cassandra writes a tombstone marker. During the next compaction, tombstoned data is physically removed. This is operationally superior to application-level deletion jobs because: (1) TTL is enforced by the storage engine regardless of application state, (2) no separate scheduled job to maintain, (3) deletion is gradual during compaction rather than a write spike from batch deletes, (4) TTL is accurate to the second rather than relying on job scheduling granularity. This pattern is also used for session tokens, OTPs, and cache entries.",
      hints: [
        "What happens to a Cassandra row when its TTL expires — is it immediately gone or does it go through a process?",
        "What operational risk exists with a separate nightly deletion job that Cassandra TTL avoids?",
      ],
    },
    {
      id: "q-sdi-soc-19",
      type: "multiple-choice",
      difficulty: "hard",
      question: "A story has been viewed by 50M users. Tracking exact unique viewer counts in a SQL table (one row per view) at this scale creates what problem, and what is the recommended approach?",
      options: [
        "SQL cannot store more than 10M rows per table, so a NoSQL database must be used.",
        "A view table with 50M rows per popular story creates massive write volume and storage costs. Querying exact unique viewer count requires a COUNT(DISTINCT viewer_id) which is O(N). The recommended approach is HyperLogLog for approximate unique viewer counts (stored in Redis as a PFADD per story), which uses ~12KB regardless of viewer count and returns approximate count in O(1), accepting ~1% error.",
        "The view table should be partitioned by viewer_id to distribute the 50M rows.",
        "Exact unique viewer counts must be maintained; approximations violate product requirements.",
      ],
      correctAnswer: 1,
      explanation: "For viral stories with tens of millions of views, inserting one row per view generates enormous write volume and storage. COUNT(DISTINCT viewer_id) over 50M rows is expensive even with indexes. HyperLogLog solves this: each view event calls PFADD story:{story_id}:viewers {viewer_id} in Redis. At any point, PFCOUNT returns the approximate unique viewer count in O(1). Memory usage is ~12KB per story regardless of viewer count. The ~1% error is acceptable for displaying '50.3M views' vs the exact 50,287,441. Instagram Stories and Snapchat use approximate counting for view metrics.",
      hints: [
        "At 50M viewers, how many rows does an exact view-tracking table have per story, and what does COUNT(DISTINCT) cost?",
        "HyperLogLog memory usage is O(log log N) — what does that mean for the difference between 50K and 50M viewers?",
      ],
    },
    {
      id: "q-sdi-soc-20",
      type: "multiple-choice",
      difficulty: "medium",
      question: "Instagram's 'Close Friends' feature allows users to share stories with a subset of followers. How does the system enforce per-view privacy without storing a separate copy of the story for close-friends vs. public audiences?",
      options: [
        "Two separate story objects are created: one for close friends and one for public, each with different CDN URLs.",
        "The story media (video/image) is stored once in object storage. A close-friends list is stored per story (or per user). At each view request, the serving layer checks: (1) is this a close-friends story, and (2) is the requesting viewer in the close-friends list. Access to the CDN URL is controlled via signed URLs with short expiry times, preventing direct URL sharing from bypassing the check.",
        "Close-friends stories are encrypted with a key shared only with close friends.",
        "The close-friends list is embedded in the CDN cache key so different audiences get different cached responses.",
      ],
      correctAnswer: 1,
      explanation: "Storing two copies of story media is wasteful (video files can be 100MB+). Instead, one media object is stored in S3/GCS, and the privacy check is enforced at the application layer: the story metadata includes a privacy flag and the close-friends list (or a reference to it). When a viewer requests the story, the API server validates membership before generating a short-lived signed CDN URL. The signed URL has a short TTL (minutes) so sharing the URL directly doesn't grant persistent access. This separates the media storage (one copy) from access control (enforced per request), which is the standard pattern for privacy-controlled media.",
      hints: [
        "Where is the privacy decision made — at the CDN, the object storage, or the application API layer?",
        "How do signed URLs with short expiry prevent URL sharing from bypassing the close-friends access control?",
      ],
    },
    {
      id: "q-sdi-soc-21",
      type: "true-false",
      difficulty: "easy",
      question: "Stories should be displayed in engagement-ranked order (most-liked story first) rather than chronological order, because ranked feeds always improve user engagement metrics.",
      options: ["True", "False"],
      correctAnswer: 1,
      explanation: "Stories are displayed in chronological order by default (most recent first) on major platforms including Instagram, WhatsApp, and Snapchat. The ephemeral 24-hour nature of stories makes recency the primary relevance signal — a story from 2 hours ago is inherently more relevant than one from 22 hours ago. Engagement ranking is applied to persistent feed content (posts, videos) where recency is not the dominant factor. Additionally, stories from people you interact with most frequently may be ordered higher (interaction-based ranking), but this is different from engagement-score ranking. The statement 'ranked feeds always improve engagement' is also false — ranking can harm perceived authenticity.",
      hints: [
        "Stories expire in 24 hours — does an older story (e.g., 20 hours old) benefit from being ranked higher?",
        "What user expectation does chronological ordering satisfy that engagement ranking might violate?",
      ],
    },
  ],
  "sdi-social-messaging": [
    {
      id: "q-sdi-soc-22",
      type: "multiple-choice",
      difficulty: "hard",
      question: "Signal uses the Double Ratchet Algorithm for end-to-end encrypted messaging. What property does this provide that simple public-key encryption (encrypt with recipient's public key) does not?",
      options: [
        "Double Ratchet compresses messages more efficiently than RSA encryption.",
        "Forward secrecy: even if an attacker records all ciphertext today and later compromises a device's long-term key, they cannot decrypt past messages because each message uses a unique ephemeral key derived from a ratcheting key chain. Simple public-key encryption with a static key means all historical messages are compromised if the private key is ever exposed.",
        "Double Ratchet allows messages to be sent without an internet connection.",
        "Double Ratchet prevents metadata analysis of who is communicating with whom.",
      ],
      correctAnswer: 1,
      explanation: "Forward secrecy (also called perfect forward secrecy) ensures that compromise of long-term keys does not expose past session keys. The Double Ratchet Algorithm (used by Signal, WhatsApp, and Facebook Messenger) combines a Diffie-Hellman ratchet (for forward secrecy of sessions) with a symmetric-key ratchet (for forward secrecy within a session). Each message derives a unique key from the ratchet state; once a message is decrypted, the key is discarded. An attacker who records ciphertext today and steals the device's private key years later cannot decrypt those old messages. This is impossible with simple RSA encryption of messages using a static key pair.",
      hints: [
        "If someone records your encrypted messages today and steals your private key in 5 years, can they read your old messages with static RSA?",
        "What does 'ratcheting' mean — does it allow going backward to derive old keys?",
      ],
    },
    {
      id: "q-sdi-soc-23",
      type: "multiple-choice",
      difficulty: "medium",
      question: "In a group chat with 500 members, when User A sends a message, how does server-side fan-out differ from client-side fan-out, and which does WhatsApp/Signal use for groups?",
      options: [
        "Server-side fan-out: the server sends the message to all 500 members; client-side fan-out: User A's device sends 500 individual encrypted messages. Signal uses client-side fan-out; WhatsApp uses server-side fan-out for groups above a threshold.",
        "Server-side fan-out and client-side fan-out are equivalent; both result in the same number of messages being sent.",
        "Client-side fan-out is always preferred because it reduces server load.",
        "Server-side fan-out is only used for groups with fewer than 10 members.",
      ],
      correctAnswer: 0,
      explanation: "Server-side fan-out: User A sends one message to the server, which then delivers it to all 500 group members. This requires the server to manage delivery to many recipients but is efficient for User A. Client-side fan-out: User A's device sends 500 individually encrypted messages (one per member). For end-to-end encryption, client-side fan-out is necessary because the server must not see plaintext — each message is encrypted with the recipient's key. However, 500 encryptions and sends from a mobile device is expensive. Signal uses a hybrid: the Sender Key protocol allows one encryption with a shared group key after an initial key distribution phase, reducing client-side work. WhatsApp (which uses Signal protocol) uses server-side fan-out with Sender Keys for large groups.",
      hints: [
        "For true E2E encryption, can the server decrypt and re-encrypt the message for each recipient?",
        "What is the bandwidth and battery cost on User A's mobile device if they must send 500 individually encrypted copies?",
      ],
    },
    {
      id: "q-sdi-soc-24",
      type: "multiple-choice",
      difficulty: "medium",
      question: "A messaging app shows 'delivered' and 'read' receipts (double checkmarks). How are these receipt events delivered back to the sender, and what system component enables real-time delivery?",
      options: [
        "The sender polls the server every second to check if the message was delivered or read.",
        "WebSocket connections maintained between each client and the server enable real-time bidirectional communication. When recipient B opens the message, the client sends a read-receipt event to the server over the WebSocket; the server forwards it to sender A's WebSocket connection. This avoids polling and delivers receipts within milliseconds of the read event.",
        "Push notifications (APNs/FCM) are used exclusively for delivering read receipts.",
        "Read receipts are delivered via SMS fallback to ensure reliability.",
      ],
      correctAnswer: 1,
      explanation: "Persistent WebSocket connections are the core transport for real-time messaging events. When the sender and recipient both have active WebSocket connections to the server, events (message delivery confirmation, read receipt, typing indicator) are pushed over these connections with millisecond latency. Polling at 1-second intervals would generate enormous unnecessary load. Push notifications (APNs/FCM) serve as a fallback when the app is backgrounded and the WebSocket connection is closed — they wake the app to re-establish the WebSocket. For foreground users with active connections, WebSocket events are the primary delivery mechanism for all real-time state changes in messaging apps.",
      hints: [
        "Why is polling every second problematic at 1B concurrent users — how many unnecessary requests does that generate?",
        "WebSocket vs. HTTP: which maintains a persistent connection that allows server-to-client push without a new request?",
      ],
    },
    {
      id: "q-sdi-soc-25",
      type: "multiple-choice",
      difficulty: "hard",
      question: "In an E2E encrypted messaging system, messages are encrypted on the sender's device with the recipient's public key. Where should the ciphertext be stored to ensure message availability across device restores?",
      options: [
        "On the server in plaintext — E2E encryption only applies during transit.",
        "The ciphertext is stored on the server (the server cannot decrypt it without the recipient's private key). The private key is stored only on the recipient's device and is never uploaded. This means if the recipient loses their device without backup, messages are lost. Signal accepts this tradeoff (no server-side history). WhatsApp optionally backs up the private key to iCloud/Google Drive encrypted with a user-chosen PIN, trading some security for recoverability.",
        "The plaintext is stored in the client's local database only; the server stores no message content.",
        "The private key is stored on the server in a hardware security module (HSM) so users can restore messages.",
      ],
      correctAnswer: 1,
      explanation: "Storing ciphertext on the server is the standard design: the server acts as a reliable store-and-forward system but holds only opaque encrypted blobs it cannot decrypt. The recipient's private key remains on-device. This provides E2E encryption (the server cannot read messages) while enabling message delivery when the recipient is offline. The fundamental tension is between security (private key never leaves the device -> no message recovery if device is lost) and usability (users expect their message history to survive a phone replacement). WhatsApp's optional encrypted backup to cloud storage (encrypted with a key derived from a user PIN) is the practical compromise. Signal's stance is stricter: no cloud backup of keys.",
      hints: [
        "If the server stores only ciphertext and you lose your phone, what is needed to decrypt your message history?",
        "Why can't the server simply store the private key in a secure enclave and provide it back when you log in?",
      ],
    },
  ],
  "sdi-social-auth": [
    {
      id: "q-sdi-soc-26",
      type: "multiple-choice",
      difficulty: "medium",
      question: "A social platform must choose between stateful sessions and stateless JWTs for user authentication. What is the key operational difference regarding token revocation?",
      options: [
        "JWTs are always more secure than sessions because they are cryptographically signed.",
        "Sessions are stored server-side (in a session store like Redis); revocation is instant — delete the session record. JWTs are self-contained and validated without a server lookup; revocation requires either waiting for the token to expire or maintaining a server-side denylist, which reintroduces statefulness. Short JWT expiry (15 minutes) with refresh tokens is the common mitigation.",
        "Sessions cannot be used in distributed systems because they require sticky sessions.",
        "JWTs cannot encode user roles or permissions, requiring a separate authorization service.",
      ],
      correctAnswer: 1,
      explanation: "The core tradeoff: sessions are stateful (require a session store lookup on every request, but can be instantly revoked by deleting the record) vs. JWTs are stateless (verified by signature without a store lookup, scaling well, but cannot be revoked before expiry without a denylist). For social platforms where account suspension or logout must take effect immediately, pure JWT without a denylist is problematic — a suspended user's JWT remains valid until expiry. The common pattern is short-lived JWTs (15-minute access tokens) plus longer-lived refresh tokens (stored server-side for revocability). This provides scalability benefits of JWTs while maintaining revocability for security events.",
      hints: [
        "If a user's account is compromised and you want to invalidate their session immediately, which approach lets you do this without touching the client?",
        "What is the 'window of risk' when using JWTs with a 24-hour expiry and no denylist?",
      ],
    },
    {
      id: "q-sdi-soc-27",
      type: "multiple-choice",
      difficulty: "hard",
      question: "A social platform integrates 'Login with Google' using OAuth 2.0. Which OAuth 2.0 flow should be used for a web application where the server can keep a client secret, and why is the implicit flow deprecated?",
      options: [
        "Implicit flow: simpler and requires no server-side code.",
        "Authorization Code flow: the browser receives an authorization code (not the access token), which is exchanged for tokens server-side using the client secret. The access token never travels through the browser redirect URL. The implicit flow is deprecated because it returned access tokens directly in the URL fragment, which were exposed to browser history, referrer headers, and JavaScript on the page — a significant security risk.",
        "Client Credentials flow: designed for web apps authenticating on behalf of users.",
        "Device Code flow: optimal for web apps because it does not require browser redirects.",
      ],
      correctAnswer: 1,
      explanation: "Authorization Code flow is the secure choice for server-side web apps: (1) browser redirects to Google with a code challenge, (2) Google redirects back with a short-lived authorization code in the URL, (3) the server exchanges this code + client_secret for access and refresh tokens via a back-channel HTTPS POST. The access token never appears in the browser URL. The implicit flow returned the access token directly in the URL fragment (#access_token=...) — exposed to browser history, JS snippets, referrer headers, and URL logging. OAuth 2.0 formally deprecated the implicit flow in RFC 8252. Authorization Code with PKCE (Proof Key for Code Exchange) is now recommended for all clients including SPAs.",
      hints: [
        "In the implicit flow, where does the access token appear — in the URL fragment. Who else can see browser URL fragments?",
        "What is the 'back-channel' in authorization code flow, and why is it more secure than the browser redirect channel?",
      ],
    },
    {
      id: "q-sdi-soc-28",
      type: "multiple-choice",
      difficulty: "medium",
      question: "A social platform offers TOTP (Google Authenticator), SMS OTP, and FIDO2 hardware keys as MFA options. Rank these from least to most resistant to phishing attacks.",
      options: [
        "FIDO2 < TOTP < SMS (hardware keys are the weakest because they require physical possession).",
        "SMS < TOTP < FIDO2: SMS is vulnerable to SIM swap attacks and SS7 interception; TOTP codes can be phished in real time (attacker proxies login and enters the stolen TOTP immediately); FIDO2 hardware keys use origin-bound cryptographic challenges — the key signs a challenge that includes the site's origin, making phishing impossible because a fake site gets a response bound to its own origin, not the legitimate site's.",
        "TOTP < SMS < FIDO2: TOTP is weakest because codes are short-lived.",
        "All three MFA methods provide equal protection against phishing.",
      ],
      correctAnswer: 1,
      explanation: "SMS OTP is weakest: SIM swap attacks (social engineering the carrier to transfer your number) or SS7 protocol attacks allow attackers to intercept SMS codes. TOTP is stronger but still phishable: a real-time phishing attack proxies the login, steals the TOTP code the user enters on the fake site, and immediately replays it on the real site (within the 30-second window). FIDO2/WebAuthn is phishing-resistant by design: the authenticator signs a challenge that cryptographically includes the website's origin (domain). A phishing site at evil.com cannot produce a valid signature for bank.com — the origin is bound to the key, not just displayed to the user. This makes FIDO2 the gold standard for phishing-resistant MFA.",
      hints: [
        "Can a TOTP code entered on a fake site be immediately replayed on the real site before it expires?",
        "FIDO2 includes the site's domain in the signed challenge — what happens when a phishing site tries to use this response?",
      ],
    },
    {
      id: "q-sdi-soc-29",
      type: "multiple-choice",
      difficulty: "medium",
      question: "A user forgets their password and requests account recovery. What makes a time-limited email recovery token more secure than a simple random token without expiry?",
      options: [
        "Time-limited tokens are longer and therefore harder to brute-force.",
        "A token without expiry remains valid indefinitely — if the recovery email is intercepted or the user's email is later compromised, the token can be used to take over the account at any time. A time-limited token (e.g., valid for 15 minutes) reduces the window of exploitation. Additionally, the token should be single-use (invalidated after use), stored as a hash in the database (not plaintext), and tied to the specific user account to prevent token substitution attacks.",
        "Time-limited tokens are stored in a faster database table, improving recovery performance.",
        "Token expiry is not important; the token's length determines security.",
      ],
      correctAnswer: 1,
      explanation: "Security of a recovery token has multiple dimensions: (1) Entropy — should be cryptographically random with sufficient length (128+ bits) to resist brute force regardless of expiry. (2) Time limitation — reduces the window of exploitation from indefinite to minutes, limiting damage from email compromise after the fact. (3) Single-use — the token is invalidated after first use, preventing replay. (4) Hashed storage — storing a hash (not plaintext) means a DB breach does not expose valid tokens. (5) Account binding — the token is tied to a specific user_id, preventing cross-account substitution. All five properties together constitute a secure account recovery flow; time limitation is one critical component.",
      hints: [
        "If a recovery email arrives in your inbox and you never use it, and your email account is hacked 6 months later, what can the attacker do with a non-expiring token?",
        "What are the five security properties a well-designed recovery token should have?",
      ],
    },
  ],
  "sdi-social-content-moderation": [
    {
      id: "q-sdi-soc-30",
      type: "multiple-choice",
      difficulty: "hard",
      question: "PhotoDNA is used to detect known CSAM (child sexual abuse material) by comparing perceptual hashes. Why does perceptual hashing work for this use case when a simple MD5/SHA-256 hash of the image file does not?",
      options: [
        "Perceptual hashes are faster to compute than cryptographic hashes.",
        "Cryptographic hashes (MD5/SHA-256) change entirely when even one pixel or metadata byte changes — an abuser can evade detection by trivially re-encoding, resizing, or adding noise to an image. Perceptual hashes (like pHash or DCT-based hashing) compute a fingerprint based on visual content (low-frequency image features) that is robust to these transformations: two visually identical images produce similar or identical perceptual hashes even after resizing, re-compression, or minor edits.",
        "Perceptual hashes encrypt the image content, preventing unauthorized access.",
        "MD5 hashes are too short to uniquely identify images, while perceptual hashes are longer.",
      ],
      correctAnswer: 1,
      explanation: "Cryptographic hash functions are designed to be extremely sensitive to input changes (avalanche effect) — this is a feature for integrity checking but a fatal flaw for image matching where the goal is to catch visually identical content despite file-level modifications. PhotoDNA uses a perceptual hash that captures the visual 'essence' of an image using DCT (discrete cosine transform) on a grayscale downscaled version. Two visually identical images produce hashes with small Hamming distance even after re-encoding, resizing, or adding a text watermark. The hash of the known bad image is stored in a database, and each uploaded image is compared via Hamming distance — if below a threshold, it matches. This achieves O(1) detection per upload.",
      hints: [
        "What happens to an MD5 hash if you resize an image from 1920*1080 to 1920*1079?",
        "What image properties does a perceptual hash capture that make it robust to minor modifications?",
      ],
    },
    {
      id: "q-sdi-soc-31",
      type: "multiple-choice",
      difficulty: "hard",
      question: "A social platform deploys an ML content moderation classifier. Setting a high confidence threshold reduces false positives (incorrectly removed content) but increases false negatives (harmful content that passes through). How should the threshold be set differently for 'spam' vs. 'terrorist recruitment content'?",
      options: [
        "Use the same threshold for all content categories to ensure consistency.",
        "For spam, a higher false-negative tolerance is acceptable (some spam slips through, which is annoying but not severely harmful); set threshold higher to minimize false positives (legitimate content wrongly removed is more costly than occasional spam). For terrorist recruitment, the harm of false negatives (content that radicalizes users) far outweighs the cost of false positives (legitimate content reviewed by humans); set a lower threshold with human review of borderline cases.",
        "For terrorist content, use a higher threshold because accuracy is more important.",
        "Threshold selection is irrelevant if the model has AUC > 0.95.",
      ],
      correctAnswer: 1,
      explanation: "The precision-recall tradeoff should be calibrated to the severity of each error type per content category. For spam: a false negative (spam shown) is mildly annoying; a false positive (legitimate post removed) damages user trust. Set a higher threshold (high precision) and accept some false negatives. For terrorist recruitment: a false negative means harmful content reaches users and potentially radicalizes them — severe real-world harm. A false positive means a legitimate post goes to human review — disruptive but recoverable. Set a lower threshold (high recall) and route borderline content to human review queues. This asymmetric cost analysis per content category is fundamental to responsible content moderation system design.",
      hints: [
        "Assign rough dollar or harm values to each error type for spam vs. terrorism — which error type costs more in each case?",
        "What does a human review queue provide that an automated binary decision (approve/remove) cannot?",
      ],
    },
    {
      id: "q-sdi-soc-32",
      type: "multiple-choice",
      difficulty: "medium",
      question: "A social platform has a human review queue for content flagged by automated classifiers. The queue receives 10,000 items per hour but only has capacity to review 2,000 per hour. How should items be prioritized?",
      options: [
        "First-in-first-out (FIFO): review items in the order they were flagged.",
        "Priority score = severity * classifier_confidence * viral_velocity, where severity is the harm category weight (e.g., terrorism > hate speech > spam), classifier_confidence is the model's predicted probability, and viral_velocity is the current share/impression rate. Items scoring highest are reviewed first — maximizing harm reduction per review hour by prioritizing high-severity, high-confidence, high-reach content.",
        "Review items in reverse chronological order (newest first) to address recent content.",
        "Randomly sample from the queue to avoid bias in the review process.",
      ],
      correctAnswer: 1,
      explanation: "Human review is a scarce resource; the goal is to maximize harm prevented per reviewer-hour. A priority score combining severity (harm category), classifier confidence (how likely it is actually violating), and viral velocity (how fast it is spreading) achieves this: high-severity + high-confidence + high-spread items cause the most harm if left unreviewed and should be prioritized. FIFO is suboptimal because a low-severity item submitted at 9:00 AM would block a high-severity viral item submitted at 9:01 AM. This prioritization framework is used by major platforms including Facebook's integrity review systems and YouTube's trusted flagger program.",
      hints: [
        "If you had to choose between reviewing a high-confidence terrorism post with 1M impressions/hour vs. a low-confidence spam post, which do you review first and why?",
        "What does 'viral velocity' measure, and why does it factor into harm from delayed moderation?",
      ],
    },
  ],
  "sdi-social-analytics": [
    {
      id: "q-sdi-soc-33",
      type: "multiple-choice",
      difficulty: "hard",
      question: "A social platform's analytics pipeline collects browser events and must make them available for ad-hoc analysis within minutes. What is the standard streaming architecture from browser to analytical query layer?",
      options: [
        "Browser -> REST API -> PostgreSQL -> Tableau; simplest path for real-time analytics.",
        "Browser sends events to a collection endpoint -> Kafka topic (durable buffer, decouples producers from consumers) -> Flink or Spark Streaming job (real-time aggregation, deduplication, enrichment) -> ClickHouse or BigQuery (columnar OLAP store optimized for analytical queries). This pipeline achieves end-to-end latency of seconds to minutes while handling millions of events per second.",
        "Browser -> S3 batch upload every hour -> Athena for query; batch processing is sufficient for analytics.",
        "Browser -> WebSocket -> in-memory Redis -> BI dashboard; Redis handles all analytical queries natively.",
      ],
      correctAnswer: 1,
      explanation: "The modern streaming analytics pipeline has distinct layers with clear responsibilities: (1) Collection — a lightweight HTTP endpoint or SDK batches events from the browser and writes to Kafka; (2) Kafka — a distributed commit log that durably buffers events and decouples high-volume producers from potentially slower consumers; (3) Flink/Spark Streaming — consumes from Kafka, handles deduplication (event IDs), enrichment (joining with user/session metadata), sessionization, and windowed aggregations; (4) OLAP store — ClickHouse or BigQuery stores processed events in a columnar format optimized for GROUP BY / COUNT / SUM queries over billions of rows. This architecture is used by Meta (Scuba/ODS), Airbnb (Minerva), Netflix (Druid), and LinkedIn (Pinot).",
      hints: [
        "Why is Kafka placed between the collection endpoint and the stream processing engine rather than writing directly to the OLAP store?",
        "What does 'columnar storage' enable that row-oriented storage (PostgreSQL) does not for analytical GROUP BY queries?",
      ],
    },
    {
      id: "q-sdi-soc-34",
      type: "multiple-choice",
      difficulty: "medium",
      question: "A social platform wants to compute the conversion funnel: page_view -> sign_up -> first_post -> day_7_retention. Each step can only be reached through the previous step, and events arrive out of order. What is the core challenge in computing funnel conversion rates in a streaming system?",
      options: [
        "Funnels cannot be computed in streaming systems and require batch processing.",
        "Funnel computation requires correlating multiple events for the same user across time. In a streaming system, events arrive out of order (network delays, mobile app buffering). The system must: (1) assign events to user sessions using a session window, (2) handle late arrivals within a watermark period, (3) join events by user_id across the funnel steps. State must be maintained per user across potentially days (sign_up to day_7_retention is a 7-day window), requiring persistent state backends (RocksDB in Flink) rather than purely in-memory state.",
        "Funnel analysis only requires counting events at each step independently, with no need to correlate events per user.",
        "Out-of-order events are not a problem because the analytics database re-sorts events by timestamp after ingestion.",
      ],
      correctAnswer: 1,
      explanation: "Funnel analysis is stateful: you need to know that user_id=123 performed step 1 (page_view) before counting their step 2 (sign_up) as a conversion, not just that sign_up events occurred. This requires per-user state across a time window. In a streaming system: event ordering is not guaranteed; mobile apps may buffer events and send them in batches minutes later; the 7-day retention window means state must be held per user for 7+ days. Flink addresses this with event-time processing, watermarks (a threshold after which late events are dropped or handled separately), and durable state backends (RocksDB) for large keyed state. Simpler approaches compute funnels in batch on the OLAP store after all events for a cohort day have landed.",
      hints: [
        "If a user signs up at 10:00 AM and the sign_up event arrives at the stream processor at 10:05 AM, how does the system know to credit this as following the page_view that arrived at 10:01 AM?",
        "Day 7 retention requires remembering which users signed up 7 days ago — how long must per-user state be held in the streaming job?",
      ],
    },
  ],
};

registerQuestions(questions);
